import type { LabRefItem } from './lab-types'

export const labRefSpecial: LabRefItem[] = [
  // ── 심장·염증·신장 바이오마커 ─────────────────────────────
  {
    id: 'crp',
    nameKo: 'C반응성단백',
    nameEn: 'CRP',
    unit: 'mg/L',
    section: ['special'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '체내 염증이 생기면 간에서 빠르게 만들어지는 단백질입니다. 감염·수술·자가면역 질환 여부를 조기에 감지하는 염증 지표입니다. 개에서 특히 민감하며, 고양이는 반응이 낮아 해석에 주의가 필요합니다.',
    defaultRefRange: { dog: '<10', cat: '검사 의의 제한적' },
    ranges: {
      common: [
        { min: null, max: 10.0,  resultText: 'Normal',             resultTextKo: '정상',        isAbnormal: false                       },
        { min: 10.0, max: 40.0,  resultText: 'Mild elevation',     resultTextKo: '경도 상승',   isAbnormal: true,  severity: 'mild'     },
        { min: 40.0, max: 100.0, resultText: 'Moderate elevation', resultTextKo: '중등도 상승', isAbnormal: true,  severity: 'moderate' },
        { min: 100.0, max: null, resultText: 'Severe elevation',   resultTextKo: '심한 상승',   isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '급성 염증, 감염, 수술 후, 면역매개성 질환, 종양. 개: 예민한 급성기 단백',
      decrease: '임상적 의의 낮음',
      normal: '고양이는 CRP 반응성이 낮아 검사 의의가 제한적',
    },
    aiExtractKeywords: ['CRP', 'C-Reactive Protein', 'C반응성단백'],
  },
  {
    id: 'sdma',
    nameKo: '대칭 디메틸아르기닌',
    nameEn: 'SDMA',
    unit: 'μg/dL',
    section: ['special', 'kidney'],
    testType: 'range',
    foldProfile: 'renal',
    descriptionKo: '신장이 혈액을 걸러내는 능력(사구체 여과율)을 조기에 감지하는 마커입니다. 일반 신장 수치(BUN·크레아티닌)보다 훨씬 일찍 — 신장 기능이 약 40% 감소한 시점부터 — 이상을 포착합니다.',
    defaultRefRange: { common: '<14' },
    ranges: {
      common: [
        { min: null, max: 14.0, resultText: 'Normal',                    resultTextKo: '정상',             isAbnormal: false                       },
        { min: 14.0, max: 18.0, resultText: 'Mildly elevated SDMA',      resultTextKo: '경도 SDMA 상승',   isAbnormal: true,  severity: 'mild'     },
        { min: 18.0, max: 25.0, resultText: 'Moderately elevated SDMA',  resultTextKo: '중등도 SDMA 상승', isAbnormal: true,  severity: 'moderate' },
        { min: 25.0, max: null, resultText: 'Severely elevated SDMA',    resultTextKo: '심한 SDMA 상승',   isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: 'GFR 40% 감소 시점부터 상승 (크레아티닌보다 조기 감지). CKD 조기 발견에 유용',
      decrease: '임상적 의의 낮음',
      normal: 'IDEXX SDMA 검사. IRIS 병기 기준 포함',
    },
    aiExtractKeywords: ['SDMA', 'Symmetric Dimethylarginine'],
  },
  {
    id: 'nt_probnp',
    nameKo: 'NT-proBNP (심장표지자)',
    nameEn: 'NT-proBNP',
    unit: 'pmol/L',
    section: ['special'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '심장 근육이 과부하를 받을 때 분비되는 호르몬 조각입니다. 심장 비대·판막 질환·심부전 등 심장에 이상이 생기면 수치가 올라가며, 증상이 나타나기 전 단계의 심장 문제를 조기 발견하는 데 사용합니다.',
    defaultRefRange: { dog: '<900', cat: '<100' },
    ranges: {
      dog: [
        { min: null,    max: 900.0,  resultText: 'Normal — cardiac disease unlikely',              resultTextKo: '정상 — 심장질환 가능성 낮음',        isAbnormal: false                    },
        { min: 900.0,  max: 1800.0, resultText: 'Mildly elevated — cardiac monitoring needed',    resultTextKo: '경도 상승 — 심장 모니터링 권장',     isAbnormal: true,  severity: 'mild' },
        { min: 1800.0, max: null,   resultText: 'Markedly elevated — significant cardiac disease', resultTextKo: '현저한 상승 — 심장질환 가능성 높음', isAbnormal: true,  severity: 'high' },
      ],
      cat: [
        { min: null,   max: 100.0,  resultText: 'Normal — cardiac disease unlikely',          resultTextKo: '정상 — 심장질환 가능성 낮음',       isAbnormal: false                        },
        { min: 100.0,  max: 270.0,  resultText: 'Equivocal — cardiac disease possible',       resultTextKo: '경계 — 심장질환 가능성',            isAbnormal: true,  severity: 'mild'     },
        { min: 270.0,  max: 536.0,  resultText: 'Elevated — heart disease likely',            resultTextKo: '상승 — 심장질환 가능성 높음',       isAbnormal: true,  severity: 'moderate' },
        { min: 536.0,  max: null,   resultText: 'Markedly elevated — CHF likely',             resultTextKo: '현저한 상승 — 울혈성심부전 가능성', isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '심근 스트레스 증가: 심비대·울혈성심부전(CHF)·심근병증·심낭삼출. 개 >1800 pmol/L: 심장초음파 강력 권장. 고양이 >270 pmol/L: 심장질환 시사. 호흡곤란 감별(심인성 vs 폐인성)에 활용',
      decrease: '임상적 의의 낮음',
      normal: '심장 기능 선별 바이오마커 (IDEXX Cardiopet® 기준). 기기·랩별 기준치 상이 — 보고서 참고범위 우선 적용',
    },
    aiExtractKeywords: [
      'NT-proBNP', 'NT proBNP', 'NTproBNP',
      'N-terminal proBNP', 'N-terminal pro-BNP',
      'proBNP', 'pro-BNP', 'ProBNP',
      'cProBNP', 'c-ProBNP', 'canine proBNP',
      'fProBNP', 'f-ProBNP', 'feline proBNP',
      'Cardiopet proBNP', 'Cardiopet NT-proBNP',
      'BNP', 'B-type Natriuretic Peptide',
    ],
  },

  // ── 간·소화기·췌장 특수검사 ──────────────────────────────
  {
    id: 'bile_acid',
    nameKo: '담즙산',
    nameEn: 'Bile Acid',
    unit: 'μmol/L',
    section: ['special', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '간이 음식을 소화하고 처리하는 능력을 직접 측정하는 검사입니다. 공복과 식사 후 두 번 채혈해서 간의 순환 기능을 평가합니다. 간질환이나 혈관 단락(PSS) 진단에 중요한 지표입니다.',
    defaultRefRange: { dog: '공복 <10 | 식후 <25', cat: '공복 <5 | 식후 <10' },
    ranges: {
      dog: [
        { min: null, max: 10.0,  resultText: 'Normal (fasting)',            resultTextKo: '정상 (공복)',              isAbnormal: false                        },
        { min: 10.0, max: 25.0,  resultText: 'Borderline — recheck postprandial', resultTextKo: '경계 — 식후 재검 권장', isAbnormal: true, severity: 'mild' },
        { min: 25.0, max: 50.0,  resultText: 'Elevated — hepatic dysfunction', resultTextKo: '상승 — 간기능 이상',    isAbnormal: true,  severity: 'moderate' },
        { min: 50.0, max: null,  resultText: 'Markedly elevated — PSS / liver failure', resultTextKo: '현저한 상승 — PSS / 간부전', isAbnormal: true, severity: 'high' },
      ],
      cat: [
        { min: null, max: 5.0,   resultText: 'Normal (fasting)',            resultTextKo: '정상 (공복)',              isAbnormal: false                        },
        { min: 5.0,  max: 10.0,  resultText: 'Borderline',                  resultTextKo: '경계',                     isAbnormal: true,  severity: 'mild'     },
        { min: 10.0, max: 30.0,  resultText: 'Elevated — hepatic dysfunction', resultTextKo: '상승 — 간기능 이상',    isAbnormal: true,  severity: 'moderate' },
        { min: 30.0, max: null,  resultText: 'Markedly elevated',           resultTextKo: '현저한 상승',              isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '간기능 저하, 문맥체순환단락(PSS), 간미세혈관이형성증',
      decrease: '임상적 의의 낮음',
      normal: '공복과 식후(2시간) 쌍 측정. 간의 순환 기능을 직접 반영',
    },
    aiExtractKeywords: ['Bile Acid', '담즙산', 'Pre/Post Prandial'],
  },
  {
    id: 'pli_dog',
    nameKo: '개 췌장 리파아제 면역반응성',
    nameEn: 'cPLI / Spec cPL',
    unit: 'μg/L',
    section: ['special', 'pancreas'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '췌장에서만 만들어지는 리파아제(지방 소화 효소)를 특이적으로 측정합니다. 일반 리파아제 검사보다 췌장염 진단 정확도가 훨씬 높으며, 개의 췌장염 진단을 위한 핵심 검사입니다.',
    defaultRefRange: { dog: '<200 (60–200: 경계)' },
    ranges: {
      dog: [
        { min: null, max: 60.0,  resultText: 'Normal',                       resultTextKo: '정상',                    isAbnormal: false                        },
        { min: 60.0, max: 200.0, resultText: 'Equivocal — pancreatitis possible', resultTextKo: '경계 — 췌장염 가능성', isAbnormal: true, severity: 'mild' },
        { min: 200.0, max: null, resultText: 'Pancreatitis likely',          resultTextKo: '췌장염 가능성 높음',       isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '췌장염. 200 μg/L 이상: 췌장염 가능성 높음. 60~200: 경계',
      decrease: '임상적 의의 낮음',
      normal: 'IDEXX Spec cPL. 일반 리파아제보다 췌장 특이도 높음',
    },
    aiExtractKeywords: ['cPLI', 'Spec cPL', 'PLI', 'Canine Pancreatic Lipase'],
  },
  {
    id: 'pli_cat',
    nameKo: '고양이 췌장 리파아제 면역반응성',
    nameEn: 'fPLI / Spec fPL',
    unit: 'μg/L',
    section: ['special', 'pancreas'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '고양이 췌장에서만 만들어지는 리파아제를 특이적으로 측정합니다. 고양이 췌장염은 구토·설사 같은 전형적인 증상이 없는 경우가 많아 이 검사가 진단에 특히 중요합니다.',
    defaultRefRange: { cat: '<3.5 (3.5–5.3: 경계)' },
    ranges: {
      cat: [
        { min: null, max: 3.5,  resultText: 'Normal',                        resultTextKo: '정상',                    isAbnormal: false                        },
        { min: 3.5,  max: 5.4,  resultText: 'Equivocal — pancreatitis possible', resultTextKo: '경계 — 췌장염 가능성', isAbnormal: true, severity: 'mild' },
        { min: 5.4,  max: null, resultText: 'Pancreatitis likely',           resultTextKo: '췌장염 가능성 높음',      isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '췌장염. 5.4 μg/L 이상: 췌장염 가능성 높음',
      decrease: '임상적 의의 낮음',
      normal: '고양이 췌장염은 임상 징후가 비특이적 — fPLI + 초음파 병용 권장',
    },
    aiExtractKeywords: ['fPLI', 'Spec fPL', 'Feline Pancreatic Lipase'],
  },
  {
    id: 'b12_cobalamin',
    nameKo: '코발라민 (비타민 B12)',
    nameEn: 'Cobalamin (B12)',
    unit: 'ng/L',
    section: ['special'],
    testType: 'range',
    foldProfile: 'renal',
    descriptionKo: '소장에서 흡수되는 비타민 B12로, 소화기 흡수 능력을 간접적으로 평가합니다. 수치가 낮으면 소장 질환(IBD, 외분비췌장기능부전 등)이나 신장 문제로 흡수가 안 되고 있음을 시사합니다.',
    defaultRefRange: { dog: '200–900', cat: '200–1500' },
    ranges: {
      dog: [
        { min: null, max: 200.0,  resultText: 'Deficiency',            resultTextKo: '결핍',              isAbnormal: true,  severity: 'high'     },
        { min: 200.0, max: 350.0, resultText: 'Low-normal',            resultTextKo: '낮은 정상',         isAbnormal: true,  severity: 'mild'     },
        { min: 350.0, max: 900.0, resultText: 'Normal',                resultTextKo: '정상',              isAbnormal: false                        },
        { min: 900.0, max: null,  resultText: 'Elevated',              resultTextKo: '상승',              isAbnormal: false                        },
      ],
      cat: [
        { min: null, max: 200.0,   resultText: 'Deficiency',           resultTextKo: '결핍',              isAbnormal: true,  severity: 'high'     },
        { min: 200.0, max: 350.0,  resultText: 'Low-normal',           resultTextKo: '낮은 정상',         isAbnormal: true,  severity: 'mild'     },
        { min: 350.0, max: 1500.0, resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                        },
        { min: 1500.0, max: null,  resultText: 'Elevated',             resultTextKo: '상승',              isAbnormal: false                        },
      ],
    },
    comment: {
      increase: '임상적 의의 낮음',
      decrease: '소장 흡수장애(EPI, IBD, 림프종), 신기능 저하. 신경학적 증상 유발 가능',
    },
    aiExtractKeywords: ['B12', 'Cobalamin', 'Vitamin B12', '코발라민'],
  },
  {
    id: 'folate',
    nameKo: '엽산',
    nameEn: 'Folate',
    unit: 'μg/L',
    section: ['special'],
    testType: 'range',
    foldProfile: 'renal',
    descriptionKo: '소장의 흡수 기능과 장내 세균 균형을 평가하는 검사입니다. 코발라민(B12)과 함께 측정하면 소화기 이상 위치를 파악하는 데 유용합니다. 낮으면 소화흡수 장애, 높으면 세균 과증식을 시사합니다.',
    defaultRefRange: { dog: '7.7–24.4', cat: '9.0–28.4' },
    ranges: {
      dog: [
        { min: null, max: 7.7,  resultText: 'Low — proximal SI malabsorption', resultTextKo: '낮음 — 근위 소장 흡수장애', isAbnormal: true, severity: 'moderate' },
        { min: 7.7,  max: 24.4, resultText: 'Normal',                           resultTextKo: '정상',                       isAbnormal: false                       },
        { min: 24.4, max: null, resultText: 'Elevated — SIBO possible',         resultTextKo: '상승 — 세균 과증식 가능성',  isAbnormal: true, severity: 'mild'    },
      ],
      cat: [
        { min: null, max: 9.0,  resultText: 'Low — proximal SI malabsorption', resultTextKo: '낮음 — 근위 소장 흡수장애', isAbnormal: true, severity: 'moderate' },
        { min: 9.0,  max: 28.4, resultText: 'Normal',                           resultTextKo: '정상',                       isAbnormal: false                       },
        { min: 28.4, max: null, resultText: 'Elevated — SIBO possible',         resultTextKo: '상승 — 세균 과증식 가능성',  isAbnormal: true, severity: 'mild'    },
      ],
    },
    comment: {
      increase: '세균과증식(SIBO) — 세균이 엽산 생성',
      decrease: '근위 소장 흡수장애(EPI, IBD 등)',
      normal: '코발라민과 함께 측정 시 소장 기능 평가에 유용',
    },
    aiExtractKeywords: ['Folate', '엽산'],
  },
  {
    id: 'tli',
    nameKo: '트립신 유사 면역반응성',
    nameEn: 'TLI',
    unit: 'μg/L',
    section: ['special', 'pancreas'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '췌장이 소화 효소(트립신)를 충분히 만들어내는지 평가하는 검사입니다. 수치가 매우 낮으면 외분비췌장기능부전(EPI)을 진단하는 데 사용되며, 만성 소화장애와 체중감소의 원인을 파악하는 데 중요합니다.',
    defaultRefRange: { dog: '5.7–45.2', cat: '17–49' },
    ranges: {
      dog: [
        { min: null, max: 2.5,  resultText: 'EPI confirmed',           resultTextKo: '외분비췌장기능부전(EPI) 확진', isAbnormal: true,  severity: 'high'     },
        { min: 2.5,  max: 5.7,  resultText: 'Borderline — EPI suspected', resultTextKo: '경계 — EPI 의심',          isAbnormal: true,  severity: 'moderate' },
        { min: 5.7,  max: 45.2, resultText: 'Normal',                   resultTextKo: '정상',                       isAbnormal: false                        },
        { min: 45.2, max: null, resultText: 'Elevated — pancreatitis',  resultTextKo: '상승 — 췌장염',              isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null, max: 8.0,  resultText: 'EPI suspected',           resultTextKo: 'EPI 의심',                   isAbnormal: true,  severity: 'high'     },
        { min: 8.0,  max: 17.0, resultText: 'Borderline low',          resultTextKo: '경계 저하',                  isAbnormal: true,  severity: 'mild'     },
        { min: 17.0, max: 49.0, resultText: 'Normal',                  resultTextKo: '정상',                       isAbnormal: false                        },
        { min: 49.0, max: null, resultText: 'Elevated — pancreatitis', resultTextKo: '상승 — 췌장염',              isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '췌장염',
      decrease: '외분비췌장기능부전(EPI) 확진 — 개: 2.5 μg/L 미만',
      normal: 'EPI 진단의 gold standard. 음식 제공 72시간 전 금식 권장',
    },
    aiExtractKeywords: ['TLI', 'Trypsin-like Immunoreactivity', 'TLI'],
  },
]
