import type { LabRefItem } from './lab-types'

export const labRefUrinalysis: LabRefItem[] = [
  // ── 물리적 특성 ──────────────────────────────────────────────
  {
    id: 'urine_sg',
    nameKo: '요비중',
    nameEn: 'Urine SG',
    unit: '',
    section: ['urinalysis'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '1.015–1.045', cat: '1.020–1.060' },
    ranges: {
      dog: [
        { min: null,   max: 1.008,  resultText: 'Isosthenuric — renal failure suspected', resultTextKo: '등장뇨 — 신부전 의심', isAbnormal: true,  severity: 'critical' },
        { min: 1.008,  max: 1.015,  resultText: 'Hyposthenuric / poor concentration',     resultTextKo: '농축 불량',            isAbnormal: true,  severity: 'moderate' },
        { min: 1.015,  max: 1.030,  resultText: 'Adequate but borderline (dog)',           resultTextKo: '적절하나 경계 (개)',    isAbnormal: true,  severity: 'mild'     },
        { min: 1.030,  max: 1.045,  resultText: 'Normal — adequate concentration',        resultTextKo: '정상 농축',            isAbnormal: false                        },
        { min: 1.045,  max: null,   resultText: 'High SG — dehydration possible',         resultTextKo: '고비중 — 탈수 가능',   isAbnormal: true,  severity: 'mild'     },
      ],
      cat: [
        { min: null,   max: 1.008,  resultText: 'Isosthenuric — renal failure suspected', resultTextKo: '등장뇨 — 신부전 의심', isAbnormal: true,  severity: 'critical' },
        { min: 1.008,  max: 1.020,  resultText: 'Poor concentration (cat)',               resultTextKo: '농축 불량 (고양이)',    isAbnormal: true,  severity: 'moderate' },
        { min: 1.020,  max: 1.035,  resultText: 'Adequate but borderline (cat)',          resultTextKo: '경계 (고양이)',         isAbnormal: true,  severity: 'mild'     },
        { min: 1.035,  max: 1.060,  resultText: 'Normal — adequate concentration',       resultTextKo: '정상 농축',            isAbnormal: false                        },
        { min: 1.060,  max: null,   resultText: 'High SG — dehydration possible',        resultTextKo: '고비중 — 탈수 가능',   isAbnormal: true,  severity: 'mild'     },
      ],
    },
    comment: {
      increase: '탈수, 신전성 질환(신장 농축 기능 정상)',
      decrease: '신부전(등장뇨 1.008~1.012), 당뇨, DI, 과다음수. 1.030 미만(개)/1.035 미만(고양이) 시 농축 불량',
      normal: '개: 1.015~1.045 / 고양이: 1.020~1.060. 신기능 평가의 핵심 지표',
    },
    aiExtractKeywords: ['SG', 'Specific Gravity', '요비중', 'USG'],
  },
  {
    id: 'urine_ph',
    nameKo: '요 pH',
    nameEn: 'Urine pH',
    unit: '',
    section: ['urinalysis'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { common: '5.5–7.5' },
    ranges: {
      common: [
        { min: null, max: 5.0,  resultText: 'Strongly acidic',   resultTextKo: '강산성',       isAbnormal: true,  severity: 'mild'    },
        { min: 5.0,  max: 5.5,  resultText: 'Acidic',            resultTextKo: '산성',          isAbnormal: false                       },
        { min: 5.5,  max: 7.5,  resultText: 'Normal',            resultTextKo: '정상',          isAbnormal: false                       },
        { min: 7.5,  max: 8.5,  resultText: 'Alkaline',          resultTextKo: '알칼리성',      isAbnormal: true,  severity: 'mild'    },
        { min: 8.5,  max: null, resultText: 'Strongly alkaline — UTI?', resultTextKo: '강알칼리 — 요로감염 의심', isAbnormal: true, severity: 'moderate' },
      ],
    },
    comment: {
      increase: '(알칼리성) 세균요로감염(요소분해균), 식이(채식), 대사성알칼리증',
      decrease: '(산성) 고단백식이, 대사성산증, 기아, 발열',
    },
    aiExtractKeywords: ['pH', 'Urine pH'],
  },
  {
    id: 'urine_color',
    nameKo: '요색',
    nameEn: 'Color',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '연황색–황색 (Yellow)' },
    options: [
      { value: '무색',         isAbnormal: true,  severity: 'mild',     labelKo: '무색 — 희석뇨/다뇨' },
      { value: '연황색',       isAbnormal: false,                        labelKo: '연황색 — 정상' },
      { value: '황색',         isAbnormal: false,                        labelKo: '황색 — 정상' },
      { value: '진황색',       isAbnormal: true,  severity: 'mild',     labelKo: '진황색 — 탈수/농뇨' },
      { value: '주황색',       isAbnormal: true,  severity: 'moderate', labelKo: '주황색 — 빌리루빈뇨' },
      { value: '적색/혈색',   isAbnormal: true,  severity: 'high',     labelKo: '적색 — 혈뇨/혈색소뇨' },
      { value: '갈색/암갈색', isAbnormal: true,  severity: 'high',     labelKo: '갈색 — 빌리루빈뇨/근색소뇨' },
      { value: '혼탁',         isAbnormal: true,  severity: 'moderate', labelKo: '혼탁 — 농뇨/결정뇨' },
    ],
    comment: {
      increase: '진한 황색/갈색: 탈수, 빌리루빈뇨. 적색/혈색: 혈뇨, 혈색소뇨, 근색소뇨',
      decrease: '무색/연한색: 희석뇨, 다음다뇨',
    },
    aiExtractKeywords: ['Color', '요색', 'Colour'],
  },

  // ── 화학적 검사 ──────────────────────────────────────────────
  {
    id: 'urine_protein',
    nameKo: '요단백',
    nameEn: 'Urine Protein',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '음성 (Negative)' },
    options: [
      { value: 'Negative', isAbnormal: false,                        labelKo: '음성 (정상)' },
      { value: 'Trace',    isAbnormal: true,  severity: 'mild',     labelKo: 'Trace — 경미한 단백뇨' },
      { value: '1+',       isAbnormal: true,  severity: 'mild',     labelKo: '1+ — 경도 단백뇨' },
      { value: '2+',       isAbnormal: true,  severity: 'moderate', labelKo: '2+ — 중등도 단백뇨' },
      { value: '3+',       isAbnormal: true,  severity: 'high',     labelKo: '3+ — 심한 단백뇨' },
      { value: '4+',       isAbnormal: true,  severity: 'critical', labelKo: '4+ — 극심한 단백뇨' },
    ],
    comment: {
      increase: '신장성(사구체신염, 단백소실신증), 신전성(Bence-Jones), 신후성(요로감염/출혈). UPC로 정량 필요',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Protein', 'PRO', '요단백'],
  },
  {
    id: 'upc',
    nameKo: '요단백:크레아티닌 비율',
    nameEn: 'UPC',
    unit: '',
    section: ['urinalysis'],
    testType: 'range',
    foldProfile: 'renal',
    defaultRefRange: { dog: '<0.5', cat: '<0.4' },
    ranges: {
      dog: [
        { min: null, max: 0.2,  resultText: 'Normal',                        resultTextKo: '정상',                   isAbnormal: false                        },
        { min: 0.2,  max: 0.5,  resultText: 'Borderline proteinuria (IRIS)', resultTextKo: '경계 단백뇨 (IRIS)',      isAbnormal: true,  severity: 'mild'     },
        { min: 0.5,  max: 2.0,  resultText: 'Proteinuria confirmed',         resultTextKo: '단백뇨 확진',            isAbnormal: true,  severity: 'moderate' },
        { min: 2.0,  max: null, resultText: 'Severe proteinuria — PLN',      resultTextKo: '심한 단백뇨 — 단백소실신증', isAbnormal: true, severity: 'high'   },
      ],
      cat: [
        { min: null, max: 0.2,  resultText: 'Normal',                        resultTextKo: '정상',                   isAbnormal: false                        },
        { min: 0.2,  max: 0.4,  resultText: 'Borderline proteinuria (IRIS)', resultTextKo: '경계 단백뇨 (IRIS)',      isAbnormal: true,  severity: 'mild'     },
        { min: 0.4,  max: 2.0,  resultText: 'Proteinuria confirmed',         resultTextKo: '단백뇨 확진',            isAbnormal: true,  severity: 'moderate' },
        { min: 2.0,  max: null, resultText: 'Severe proteinuria',            resultTextKo: '심한 단백뇨',            isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '0.5 이상(개)/0.4 이상(고양이): 단백뇨 확진. 신증, 사구체신염 모니터링',
      decrease: '임상적 의의 낮음',
      normal: 'IRIS 기준: 경계(0.2~0.5) / 단백뇨(>0.5). 24시간 소변 단백의 대안',
    },
    aiExtractKeywords: ['UPC', 'Urine Protein:Creatinine', '요단백크레아티닌비'],
  },
  {
    id: 'urine_glucose',
    nameKo: '요당',
    nameEn: 'Urine Glucose',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '음성 (Negative)' },
    options: [
      { value: 'Negative', isAbnormal: false,                        labelKo: '음성 (정상)' },
      { value: 'Trace',    isAbnormal: true,  severity: 'mild',     labelKo: 'Trace' },
      { value: '1+',       isAbnormal: true,  severity: 'moderate', labelKo: '1+ — 당뇨 의심' },
      { value: '2+',       isAbnormal: true,  severity: 'high',     labelKo: '2+' },
      { value: '3+',       isAbnormal: true,  severity: 'high',     labelKo: '3+' },
    ],
    comment: {
      increase: '고혈당(당뇨 신역치 초과), 신성 당뇨(신역치 저하), 스트레스(고양이 일시적)',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Glucose', 'GLU', '요당'],
  },
  {
    id: 'urine_ketone',
    nameKo: '요케톤',
    nameEn: 'Urine Ketone',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '음성 (Negative)' },
    options: [
      { value: 'Negative', isAbnormal: false,                        labelKo: '음성 (정상)' },
      { value: 'Trace',    isAbnormal: true,  severity: 'mild',     labelKo: 'Trace' },
      { value: '1+',       isAbnormal: true,  severity: 'moderate', labelKo: '1+' },
      { value: '2+',       isAbnormal: true,  severity: 'high',     labelKo: '2+ — DKA 위험' },
      { value: '3+',       isAbnormal: true,  severity: 'critical', labelKo: '3+ — DKA' },
    ],
    comment: {
      increase: '당뇨성케톤산증(DKA), 기아, 고지방식이',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Ketone', 'KET', '요케톤'],
  },
  {
    id: 'urine_blood',
    nameKo: '요잠혈',
    nameEn: 'Urine Blood',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '음성 (Negative)' },
    options: [
      { value: 'Negative', isAbnormal: false,                        labelKo: '음성 (정상)' },
      { value: 'Trace',    isAbnormal: true,  severity: 'mild',     labelKo: 'Trace' },
      { value: '1+',       isAbnormal: true,  severity: 'mild',     labelKo: '1+' },
      { value: '2+',       isAbnormal: true,  severity: 'moderate', labelKo: '2+ — 침전물 현미경 확인' },
      { value: '3+',       isAbnormal: true,  severity: 'high',     labelKo: '3+ — 육안적 혈뇨' },
    ],
    comment: {
      increase: '혈뇨(적혈구), 혈색소뇨(용혈), 근색소뇨(근육손상). 침전물 현미경으로 감별',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Blood', 'BLD', 'OB', '잠혈'],
  },
  {
    id: 'urine_bilirubin',
    nameKo: '요빌리루빈',
    nameEn: 'Urine Bilirubin',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { dog: '음성–1+', cat: '음성' },
    options: [
      { value: 'Negative', isAbnormal: false,                        labelKo: '음성' },
      { value: '1+',       isAbnormal: false,                        labelKo: '1+ (개: 정상 범주)' },
      { value: '2+',       isAbnormal: true,  severity: 'moderate', labelKo: '2+ — 간/담도 질환 의심' },
      { value: '3+',       isAbnormal: true,  severity: 'high',     labelKo: '3+ — 담즙정체 강력 시사' },
    ],
    comment: {
      increase: '간질환, 담즙정체. 개 소량(1+)은 정상 범주',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Bilirubin', 'BIL', '빌리루빈'],
  },

  // ── 침전물 현미경 ──────────────────────────────────────────
  {
    id: 'urine_rbc_hpf',
    nameKo: '요침전물 적혈구',
    nameEn: 'RBC/HPF',
    unit: '/HPF',
    section: ['urinalysis'],
    testType: 'range',
    foldProfile: 'cell',
    defaultRefRange: { common: '0–5 /HPF' },
    ranges: {
      common: [
        { min: null, max: 5.0,  resultText: 'Normal',                       resultTextKo: '정상',                  isAbnormal: false                        },
        { min: 5.0,  max: 20.0, resultText: 'Mild hematuria',               resultTextKo: '경도 혈뇨',             isAbnormal: true,  severity: 'mild'     },
        { min: 20.0, max: 50.0, resultText: 'Moderate hematuria',           resultTextKo: '중등도 혈뇨',           isAbnormal: true,  severity: 'moderate' },
        { min: 50.0, max: null, resultText: 'Marked hematuria',             resultTextKo: '심한 혈뇨',             isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '방광염, 요로결석, 신우신염, 종양, 외상. 5/HPF 이상: 혈뇨',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['RBC/HPF', 'Red Blood Cell/HPF'],
  },
  {
    id: 'urine_wbc_hpf',
    nameKo: '요침전물 백혈구',
    nameEn: 'WBC/HPF',
    unit: '/HPF',
    section: ['urinalysis'],
    testType: 'range',
    foldProfile: 'cell',
    defaultRefRange: { common: '0–5 /HPF' },
    ranges: {
      common: [
        { min: null, max: 5.0,  resultText: 'Normal',                       resultTextKo: '정상',                  isAbnormal: false                        },
        { min: 5.0,  max: 20.0, resultText: 'Mild pyuria',                  resultTextKo: '경도 농뇨',             isAbnormal: true,  severity: 'mild'     },
        { min: 20.0, max: 50.0, resultText: 'Moderate pyuria — UTI likely', resultTextKo: '중등도 농뇨 — 요로감염', isAbnormal: true,  severity: 'moderate' },
        { min: 50.0, max: null, resultText: 'Marked pyuria',                resultTextKo: '심한 농뇨',             isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '요로감염, 방광염, 신우신염, 전립선염. 5/HPF 이상: 농뇨',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['WBC/HPF', 'White Blood Cell/HPF'],
  },
  {
    id: 'urine_cast',
    nameKo: '요원주',
    nameEn: 'Cast',
    unit: '/LPF',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '초자원주 0–2 /LPF, 그 외 음성' },
    options: [
      { value: '없음',                   isAbnormal: false,                        labelKo: '없음 (정상)' },
      { value: '초자원주 (1-2)',         isAbnormal: false,                        labelKo: '초자원주 1-2/LPF (정상 범주)' },
      { value: '초자원주 (다수)',        isAbnormal: true,  severity: 'mild',     labelKo: '초자원주 다수 — 탈수/발열' },
      { value: '세립원주',               isAbnormal: true,  severity: 'high',     labelKo: '세립원주 — AKI/세뇨관 손상' },
      { value: '적혈구원주',             isAbnormal: true,  severity: 'high',     labelKo: '적혈구원주 — 사구체신염' },
      { value: '백혈구원주',             isAbnormal: true,  severity: 'high',     labelKo: '백혈구원주 — 신우신염' },
      { value: '상피세포원주',           isAbnormal: true,  severity: 'moderate', labelKo: '상피세포원주 — 세뇨관 손상' },
      { value: '납양원주 (waxy)',        isAbnormal: true,  severity: 'critical', labelKo: '납양원주 — 만성/심한 신부전' },
    ],
    comment: {
      increase: '세뇨관 손상. 초자원주(정상 소량), 세립원주(AKI), 적혈구원주(사구체신염), 백혈구원주(신우신염)',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Cast', '원주', 'Cylindrical cast'],
  },
  {
    id: 'urine_crystal',
    nameKo: '요결정',
    nameEn: 'Crystal',
    unit: '',
    section: ['urinalysis'],
    testType: 'multiselect',
    defaultRefRange: { common: '음성 (Negative)' },
    options: [
      { value: '없음',              isAbnormal: false,                        labelKo: '없음' },
      { value: 'Struvite',         isAbnormal: true,  severity: 'moderate', labelKo: 'Struvite — 요로감염 연관' },
      { value: 'Calcium oxalate',  isAbnormal: true,  severity: 'moderate', labelKo: 'Calcium oxalate — 특발성/고수산증' },
      { value: 'Urate',            isAbnormal: true,  severity: 'high',     labelKo: 'Urate — PSS/달마시안' },
      { value: 'Cystine',          isAbnormal: true,  severity: 'high',     labelKo: 'Cystine — 시스틴뇨' },
      { value: 'Calcium phosphate', isAbnormal: true, severity: 'mild',     labelKo: 'Calcium phosphate' },
      { value: 'Bilirubin',        isAbnormal: true,  severity: 'moderate', labelKo: 'Bilirubin 결정 — 간담도 질환' },
    ],
    comment: {
      increase: 'Struvite(요로감염 연관), Oxalate(고양이 특발성), Urate(PSS/달마시안), Cystine(시스틴뇨)',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Crystal', '결정', 'Crystalluria'],
  },
  {
    id: 'urine_bacteria',
    nameKo: '요세균',
    nameEn: 'Bacteria',
    unit: '',
    section: ['urinalysis'],
    testType: 'select',
    defaultRefRange: { common: '음성 (Negative)' },
    options: [
      { value: '없음',       isAbnormal: false,                        labelKo: '없음 (정상)' },
      { value: '소수',       isAbnormal: true,  severity: 'mild',     labelKo: '소수 — 오염 가능성' },
      { value: '중등도',     isAbnormal: true,  severity: 'moderate', labelKo: '중등도 — 배양 권장' },
      { value: '다수',       isAbnormal: true,  severity: 'high',     labelKo: '다수 — 요로감염 확률 높음' },
    ],
    comment: {
      increase: '요로감염. 중간뇨 vs 방광천자 채취 여부 고려. 배양 및 감수성 검사 권장',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['Bacteria', '세균'],
  },
]
