import type { LabRefItem } from './lab-types'

export const labRefChemistry: LabRefItem[] = [
  // ── 간 기능 ──────────────────────────────────────────────────
  {
    id: 'alt',
    nameKo: '알라닌 아미노전이효소',
    nameEn: 'ALT',
    unit: 'U/L',
    section: ['chemistry', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '간세포가 손상될 때 혈액으로 새어 나오는 효소입니다. 간 건강을 평가하는 가장 민감한 지표로, 수치가 높으면 간에 염증이나 손상이 생겼을 가능성을 확인합니다.',
    defaultRefRange: { dog: '10–88', cat: '10–100' },
    ranges: {
      dog: [
        { min: null,  max: 10.0,   resultText: 'Below reference',      resultTextKo: '참고범위 미만',     isAbnormal: true,  severity: 'mild'     },
        { min: 10.0,  max: 88.0,   resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 88.0,  max: 264.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',         isAbnormal: true,  severity: 'mild'     },
        { min: 264.0, max: 880.0,  resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',       isAbnormal: true,  severity: 'moderate' },
        { min: 880.0, max: null,   resultText: 'Severe elevation',     resultTextKo: '심한 상승',         isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 10.0,   resultText: 'Below reference',      resultTextKo: '참고범위 미만',     isAbnormal: true,  severity: 'mild'     },
        { min: 10.0,  max: 100.0,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 100.0, max: 300.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',         isAbnormal: true,  severity: 'mild'     },
        { min: 300.0, max: 1000.0, resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',       isAbnormal: true,  severity: 'moderate' },
        { min: 1000.0, max: null,  resultText: 'Severe elevation',     resultTextKo: '심한 상승',         isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '간세포 손상의 가장 민감한 지표. 간염, 지방간, 독소, 약물, 저산소증',
      decrease: '임상적 의의 낮음 (심한 간부전 말기)',
      normal: '개/고양이 모두 간특이적 효소. 고양이는 반감기가 짧아 지속 상승 시 더 의미 있음',
    },
    aiExtractKeywords: ['ALT', 'SGPT', 'Alanine Aminotransferase', '알라닌'],
  },
  {
    id: 'ast',
    nameKo: '아스파르테이트 아미노전이효소',
    nameEn: 'AST',
    unit: 'U/L',
    section: ['chemistry', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '간과 근육 세포가 손상될 때 혈액으로 나오는 효소입니다. ALT와 함께 간 건강을 평가하며, 수치가 높으면 간 또는 근육에 이상이 있는지 확인합니다.',
    defaultRefRange: { dog: '0–50', cat: '0–48' },
    ranges: {
      dog: [
        { min: null,  max: 50.0,   resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 50.0,  max: 150.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',         isAbnormal: true,  severity: 'mild'     },
        { min: 150.0, max: 500.0,  resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',       isAbnormal: true,  severity: 'moderate' },
        { min: 500.0, max: null,   resultText: 'Severe elevation',     resultTextKo: '심한 상승',         isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 48.0,   resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 48.0,  max: 144.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',         isAbnormal: true,  severity: 'mild'     },
        { min: 144.0, max: 480.0,  resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',       isAbnormal: true,  severity: 'moderate' },
        { min: 480.0, max: null,   resultText: 'Severe elevation',     resultTextKo: '심한 상승',         isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '간손상 + 근육손상(심근, 골격근). ALT와 함께 평가 필요',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['AST', 'SGOT', 'Aspartate Aminotransferase'],
  },
  {
    id: 'alp',
    nameKo: '알칼리 포스파타아제',
    nameEn: 'ALP',
    unit: 'U/L',
    section: ['chemistry', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '간과 담도, 뼈에서 만들어지는 효소입니다. 담즙 흐름 이상이나 간 문제를 평가합니다. 개에서는 스테로이드나 쿠싱증후군으로도 상승할 수 있어 다른 검사와 종합해서 판단합니다.',
    defaultRefRange: { dog: '10–150', cat: '14–111' },
    ranges: {
      dog: [
        { min: null,  max: 10.0,   resultText: 'Below reference',      resultTextKo: '참고범위 미만',     isAbnormal: true,  severity: 'mild'     },
        { min: 10.0,  max: 150.0,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 150.0, max: 450.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',         isAbnormal: true,  severity: 'mild'     },
        { min: 450.0, max: 1500.0, resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',       isAbnormal: true,  severity: 'moderate' },
        { min: 1500.0, max: null,  resultText: 'Severe elevation',     resultTextKo: '심한 상승',         isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 14.0,   resultText: 'Below reference',      resultTextKo: '참고범위 미만',     isAbnormal: true,  severity: 'mild'     },
        { min: 14.0,  max: 111.0,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 111.0, max: 333.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',         isAbnormal: true,  severity: 'mild'     },
        { min: 333.0, max: 1110.0, resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',       isAbnormal: true,  severity: 'moderate' },
        { min: 1110.0, max: null,  resultText: 'Severe elevation',     resultTextKo: '심한 상승',         isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '담즙정체, 쿠싱증후군(개), 스테로이드 투여, 골 성장/질환, 성장기',
      decrease: '임상적 의의 낮음',
      normal: '개: 스테로이드 유도 ALP 존재. 고양이: 상승 시 간담도 질환 강력 시사',
    },
    aiExtractKeywords: ['ALP', 'Alkaline Phosphatase', '알칼리포스파타아제'],
  },
  {
    id: 'ggt',
    nameKo: '감마글루타밀전이효소',
    nameEn: 'GGT',
    unit: 'U/L',
    section: ['chemistry', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    defaultRefRange: { dog: '0–11', cat: '0–8' },
    ranges: {
      dog: [
        { min: null, max: 11.0,  resultText: 'Normal',               resultTextKo: '정상',          isAbnormal: false                       },
        { min: 11.0, max: 33.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',     isAbnormal: true,  severity: 'mild'     },
        { min: 33.0, max: 110.0, resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',   isAbnormal: true,  severity: 'moderate' },
        { min: 110.0, max: null, resultText: 'Severe elevation',     resultTextKo: '심한 상승',     isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null, max: 8.0,   resultText: 'Normal',               resultTextKo: '정상',          isAbnormal: false                       },
        { min: 8.0,  max: 24.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',     isAbnormal: true,  severity: 'mild'     },
        { min: 24.0, max: 80.0,  resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',   isAbnormal: true,  severity: 'moderate' },
        { min: 80.0, max: null,  resultText: 'Severe elevation',     resultTextKo: '심한 상승',     isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '담즙정체, 간질환, 쿠싱증후군, 스테로이드',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['GGT', 'Gamma-GT', 'γ-GT', 'GGT'],
  },
  {
    id: 'tbil',
    nameKo: '총 빌리루빈',
    nameEn: 'T.Bil',
    unit: 'mg/dL',
    section: ['chemistry', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    defaultRefRange: { dog: '0–0.3', cat: '0–0.4' },
    ranges: {
      dog: [
        { min: null, max: 0.3,  resultText: 'Normal',               resultTextKo: '정상',               isAbnormal: false                       },
        { min: 0.3,  max: 1.0,  resultText: 'Mild hyperbilirubinemia', resultTextKo: '경도 고빌리루빈혈증', isAbnormal: true, severity: 'mild'  },
        { min: 1.0,  max: 3.0,  resultText: 'Moderate hyperbilirubinemia', resultTextKo: '중등도 고빌리루빈혈증', isAbnormal: true, severity: 'moderate' },
        { min: 3.0,  max: null, resultText: 'Severe hyperbilirubinemia / Jaundice', resultTextKo: '심한 고빌리루빈혈증/황달', isAbnormal: true, severity: 'high' },
      ],
      cat: [
        { min: null, max: 0.4,  resultText: 'Normal',               resultTextKo: '정상',               isAbnormal: false                       },
        { min: 0.4,  max: 1.0,  resultText: 'Mild hyperbilirubinemia', resultTextKo: '경도 고빌리루빈혈증', isAbnormal: true, severity: 'mild'  },
        { min: 1.0,  max: 3.0,  resultText: 'Moderate hyperbilirubinemia', resultTextKo: '중등도 고빌리루빈혈증', isAbnormal: true, severity: 'moderate' },
        { min: 3.0,  max: null, resultText: 'Severe hyperbilirubinemia / Jaundice', resultTextKo: '심한 고빌리루빈혈증/황달', isAbnormal: true, severity: 'high' },
      ],
    },
    comment: {
      increase: '황달 원인 감별 — 용혈전(용혈성빈혈), 간전(간부전), 간후(담즙정체/담도폐색)',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['T.Bil', 'Total Bilirubin', 'TBIL', '총빌리루빈'],
  },
  {
    id: 'dbil',
    nameKo: '직접 빌리루빈',
    nameEn: 'D.Bil',
    unit: 'mg/dL',
    section: ['chemistry', 'liver'],
    testType: 'range',
    foldProfile: 'enzyme',
    defaultRefRange: { common: '0–0.1' },
    ranges: {
      common: [
        { min: null, max: 0.1,  resultText: 'Normal',                       resultTextKo: '정상',               isAbnormal: false                       },
        { min: 0.1,  max: 0.5,  resultText: 'Mild elevation',               resultTextKo: '경도 상승',          isAbnormal: true,  severity: 'mild'     },
        { min: 0.5,  max: 2.0,  resultText: 'Moderate elevation',           resultTextKo: '중등도 상승',        isAbnormal: true,  severity: 'moderate' },
        { min: 2.0,  max: null, resultText: 'Severe elevation / Cholestasis', resultTextKo: '심한 상승/담즙정체', isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '담즙정체, 간내 또는 간외 담도 폐쇄',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['D.Bil', 'Direct Bilirubin', 'DBIL'],
  },

  // ── 신장 기능 ──────────────────────────────────────────────
  {
    id: 'bun',
    nameKo: '혈중 요소 질소',
    nameEn: 'BUN',
    unit: 'mg/dL',
    section: ['chemistry', 'kidney'],
    testType: 'range',
    foldProfile: 'renal',
    descriptionKo: '신장이 단백질 노폐물을 얼마나 잘 걸러내는지 보여주는 지표입니다. 수치가 높으면 신장 기능이 떨어졌거나 탈수가 있을 수 있습니다. 크레아티닌(CREA)과 함께 신장 건강을 평가합니다.',
    defaultRefRange: { dog: '7–27', cat: '14–36' },
    ranges: {
      dog: [
        { min: null, max: 7.0,   resultText: 'Low BUN',              resultTextKo: 'BUN 감소',          isAbnormal: true,  severity: 'mild'     },
        { min: 7.0,  max: 27.0,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 27.0, max: 50.0,  resultText: 'Mild azotemia',        resultTextKo: '경도 질소혈증',     isAbnormal: true,  severity: 'mild'     },
        { min: 50.0, max: 100.0, resultText: 'Moderate azotemia',    resultTextKo: '중등도 질소혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 100.0, max: null, resultText: 'Severe azotemia',      resultTextKo: '심한 질소혈증',     isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null, max: 14.0,  resultText: 'Low BUN',              resultTextKo: 'BUN 감소',          isAbnormal: true,  severity: 'mild'     },
        { min: 14.0, max: 36.0,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 36.0, max: 60.0,  resultText: 'Mild azotemia',        resultTextKo: '경도 질소혈증',     isAbnormal: true,  severity: 'mild'     },
        { min: 60.0, max: 120.0, resultText: 'Moderate azotemia',    resultTextKo: '중등도 질소혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 120.0, max: null, resultText: 'Severe azotemia',      resultTextKo: '심한 질소혈증',     isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '신전성(탈수, 저혈압, 출혈), 신성(CKD, AKI), 신후성(요로폐색), 고단백식이',
      decrease: '간부전, 문맥체순환단락(PSS), 저단백식이, 다음다뇨',
    },
    aiExtractKeywords: ['BUN', 'Blood Urea Nitrogen', 'UREA', '요소질소'],
  },
  {
    id: 'crea',
    nameKo: '크레아티닌',
    nameEn: 'CREA',
    unit: 'mg/dL',
    section: ['chemistry', 'kidney'],
    testType: 'range',
    foldProfile: 'renal',
    descriptionKo: '근육에서 생성된 노폐물로, 신장을 통해 소변으로 배출됩니다. 신장 기능이 떨어질수록 혈중 수치가 높아집니다. BUN과 함께 신장의 실제 여과 능력을 평가하는 핵심 지표입니다.',
    defaultRefRange: { dog: '0.5–1.8', cat: '0.8–2.4' },
    ranges: {
      dog: [
        { min: null, max: 0.5,  resultText: 'Low creatinine',        resultTextKo: '크레아티닌 감소',   isAbnormal: true,  severity: 'mild'     },
        { min: 0.5,  max: 1.8,  resultText: 'Normal',                resultTextKo: '정상',              isAbnormal: false                       },
        { min: 1.8,  max: 2.5,  resultText: 'IRIS CKD Stage 1–2',   resultTextKo: 'IRIS CKD 1–2단계', isAbnormal: true,  severity: 'mild'     },
        { min: 2.5,  max: 5.0,  resultText: 'IRIS CKD Stage 3',     resultTextKo: 'IRIS CKD 3단계',   isAbnormal: true,  severity: 'moderate' },
        { min: 5.0,  max: null, resultText: 'IRIS CKD Stage 4',     resultTextKo: 'IRIS CKD 4단계',   isAbnormal: true,  severity: 'critical' },
      ],
      cat: [
        { min: null, max: 0.8,  resultText: 'Low creatinine',        resultTextKo: '크레아티닌 감소',   isAbnormal: true,  severity: 'mild'     },
        { min: 0.8,  max: 2.4,  resultText: 'Normal',                resultTextKo: '정상',              isAbnormal: false                       },
        { min: 2.4,  max: 2.9,  resultText: 'IRIS CKD Stage 1–2',   resultTextKo: 'IRIS CKD 1–2단계', isAbnormal: true,  severity: 'mild'     },
        { min: 2.9,  max: 5.0,  resultText: 'IRIS CKD Stage 3',     resultTextKo: 'IRIS CKD 3단계',   isAbnormal: true,  severity: 'moderate' },
        { min: 5.0,  max: null, resultText: 'IRIS CKD Stage 4',     resultTextKo: 'IRIS CKD 4단계',   isAbnormal: true,  severity: 'critical' },
      ],
    },
    comment: {
      increase: '신기능 저하(GFR 감소). BUN과 함께 해석. 근육량 많을수록 기저치 높음',
      decrease: '근육량 감소, 악액질, 노령',
      normal: 'IRIS 분류에 따라 CKD 병기 결정에 사용',
    },
    aiExtractKeywords: ['CREA', 'Creatinine', 'CRE', '크레아티닌'],
  },
  // ── 췌장 ──────────────────────────────────────────────────
  {
    id: 'amy',
    nameKo: '아밀라아제',
    nameEn: 'AMY',
    unit: 'U/L',
    section: ['chemistry', 'pancreas'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '췌장과 침샘에서 분비되어 음식물 소화를 돕는 효소입니다. 췌장에 염증이 생기거나 기능에 이상이 있을 때 혈중 수치가 올라갈 수 있습니다.',
    defaultRefRange: { dog: '200–1200', cat: '100–1200' },
    ranges: {
      dog: [
        { min: null,   max: 200.0,  resultText: 'Below reference',    resultTextKo: '참고범위 미만',   isAbnormal: true,  severity: 'mild'     },
        { min: 200.0,  max: 1200.0, resultText: 'Normal',             resultTextKo: '정상',            isAbnormal: false                       },
        { min: 1200.0, max: 3600.0, resultText: 'Mild elevation',     resultTextKo: '경도 상승',       isAbnormal: true,  severity: 'mild'     },
        { min: 3600.0, max: null,   resultText: 'Marked elevation',   resultTextKo: '현저한 상승',     isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null,   max: 100.0,  resultText: 'Below reference',    resultTextKo: '참고범위 미만',   isAbnormal: true,  severity: 'mild'     },
        { min: 100.0,  max: 1200.0, resultText: 'Normal',             resultTextKo: '정상',            isAbnormal: false                       },
        { min: 1200.0, max: 3600.0, resultText: 'Mild elevation',     resultTextKo: '경도 상승',       isAbnormal: true,  severity: 'mild'     },
        { min: 3600.0, max: null,   resultText: 'Marked elevation',   resultTextKo: '현저한 상승',     isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '췌장염, 신부전(신장에서 배설), 장폐색. 비특이적',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['AMY', 'Amylase', '아밀라아제'],
  },
  {
    id: 'lipa',
    nameKo: '리파아제',
    nameEn: 'LIPA',
    unit: 'U/L',
    section: ['chemistry', 'pancreas'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '췌장에서 분비되어 지방 소화를 돕는 효소입니다. 췌장염 진단에 아밀라아제보다 특이도가 높아, 췌장 건강을 평가하는 데 중요하게 활용됩니다.',
    defaultRefRange: { dog: '0–200', cat: '0–100' },
    ranges: {
      dog: [
        { min: null,  max: 200.0,  resultText: 'Normal',               resultTextKo: '정상',          isAbnormal: false                       },
        { min: 200.0, max: 600.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',     isAbnormal: true,  severity: 'mild'     },
        { min: 600.0, max: 2000.0, resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',   isAbnormal: true,  severity: 'moderate' },
        { min: 2000.0, max: null,  resultText: 'Severe elevation',     resultTextKo: '심한 상승',     isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 100.0,  resultText: 'Normal',               resultTextKo: '정상',          isAbnormal: false                       },
        { min: 100.0, max: 300.0,  resultText: 'Mild elevation',       resultTextKo: '경도 상승',     isAbnormal: true,  severity: 'mild'     },
        { min: 300.0, max: 1000.0, resultText: 'Moderate elevation',   resultTextKo: '중등도 상승',   isAbnormal: true,  severity: 'moderate' },
        { min: 1000.0, max: null,  resultText: 'Severe elevation',     resultTextKo: '심한 상승',     isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '췌장염, 신부전. 아밀라아제보다 특이도 높음',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['LIPA', 'Lipase', '리파아제'],
  },

  // ── 단백질 ──────────────────────────────────────────────────
  {
    id: 'tp',
    nameKo: '총 단백',
    nameEn: 'TP',
    unit: 'g/dL',
    section: ['chemistry', 'protein'],
    testType: 'range',
    foldProfile: 'enzyme',
    defaultRefRange: { dog: '5.4–7.1', cat: '5.7–7.8' },
    ranges: {
      dog: [
        { min: null, max: 4.0,  resultText: 'Severe hypoproteinemia', resultTextKo: '심한 저단백혈증', isAbnormal: true,  severity: 'high'     },
        { min: 4.0,  max: 5.4,  resultText: 'Mild hypoproteinemia',   resultTextKo: '경도 저단백혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 5.4,  max: 7.1,  resultText: 'Normal',                 resultTextKo: '정상',            isAbnormal: false                       },
        { min: 7.1,  max: 8.5,  resultText: 'Mild hyperproteinemia',  resultTextKo: '경도 고단백혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 8.5,  max: null, resultText: 'Hyperproteinemia',       resultTextKo: '고단백혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null, max: 4.0,  resultText: 'Severe hypoproteinemia', resultTextKo: '심한 저단백혈증', isAbnormal: true,  severity: 'high'     },
        { min: 4.0,  max: 5.7,  resultText: 'Mild hypoproteinemia',   resultTextKo: '경도 저단백혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 5.7,  max: 7.8,  resultText: 'Normal',                 resultTextKo: '정상',            isAbnormal: false                       },
        { min: 7.8,  max: 9.0,  resultText: 'Mild hyperproteinemia',  resultTextKo: '경도 고단백혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 9.0,  max: null, resultText: 'Hyperproteinemia',       resultTextKo: '고단백혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '탈수, 만성염증(글로불린 상승), 다발성골수종',
      decrease: '영양불량, 단백손실(신증, 장병증), 간부전, 출혈',
    },
    aiExtractKeywords: ['TP', 'Total Protein', '총단백'],
  },
  {
    id: 'alb',
    nameKo: '알부민',
    nameEn: 'ALB',
    unit: 'g/dL',
    section: ['chemistry', 'protein'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '간에서 만들어지는 주요 혈중 단백질입니다. 영양 상태와 간 합성 능력을 반영하며, 수치가 낮으면 부종이나 복수가 생길 수 있습니다. 영양 상태·간·신장·장 건강을 종합적으로 평가합니다.',
    defaultRefRange: { dog: '2.3–3.1', cat: '2.2–3.5' },
    ranges: {
      dog: [
        { min: null, max: 1.5,  resultText: 'Severe hypoalbuminemia', resultTextKo: '심한 저알부민혈증', isAbnormal: true,  severity: 'critical' },
        { min: 1.5,  max: 2.3,  resultText: 'Mild hypoalbuminemia',   resultTextKo: '경도 저알부민혈증', isAbnormal: true,  severity: 'moderate' },
        { min: 2.3,  max: 3.1,  resultText: 'Normal',                 resultTextKo: '정상',              isAbnormal: false                       },
        { min: 3.1,  max: 4.0,  resultText: 'Mild hyperalbuminemia',  resultTextKo: '경도 고알부민혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 4.0,  max: null, resultText: 'Hyperalbuminemia',       resultTextKo: '고알부민혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null, max: 1.5,  resultText: 'Severe hypoalbuminemia', resultTextKo: '심한 저알부민혈증', isAbnormal: true,  severity: 'critical' },
        { min: 1.5,  max: 2.2,  resultText: 'Mild hypoalbuminemia',   resultTextKo: '경도 저알부민혈증', isAbnormal: true,  severity: 'moderate' },
        { min: 2.2,  max: 3.5,  resultText: 'Normal',                 resultTextKo: '정상',              isAbnormal: false                       },
        { min: 3.5,  max: 4.5,  resultText: 'Mild hyperalbuminemia',  resultTextKo: '경도 고알부민혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 4.5,  max: null, resultText: 'Hyperalbuminemia',       resultTextKo: '고알부민혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '탈수(상대적 상승)',
      decrease: '영양불량, 간부전(합성 저하), 신증(손실), 장병증(손실), 만성염증',
      normal: '교질삼투압 유지, 약물 운반체. 저알부민 시 부종/흉수/복수 위험',
    },
    aiExtractKeywords: ['ALB', 'Albumin', '알부민'],
  },
  {
    id: 'glob',
    nameKo: '글로불린',
    nameEn: 'GLOB',
    unit: 'g/dL',
    section: ['chemistry', 'protein'],
    testType: 'range',
    foldProfile: 'enzyme',
    defaultRefRange: { dog: '2.8–4.2', cat: '2.6–5.1' },
    ranges: {
      dog: [
        { min: null, max: 2.0,  resultText: 'Hypoglobulinemia',      resultTextKo: '저글로불린혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 2.0,  max: 2.8,  resultText: 'Mild hypoglobulinemia', resultTextKo: '경도 저글로불린혈증', isAbnormal: true, severity: 'mild'   },
        { min: 2.8,  max: 4.2,  resultText: 'Normal',                resultTextKo: '정상',             isAbnormal: false                       },
        { min: 4.2,  max: 6.0,  resultText: 'Mild hyperglobulinemia', resultTextKo: '경도 고글로불린혈증', isAbnormal: true, severity: 'mild'  },
        { min: 6.0,  max: null, resultText: 'Hyperglobulinemia',     resultTextKo: '고글로불린혈증',   isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null, max: 2.0,  resultText: 'Hypoglobulinemia',      resultTextKo: '저글로불린혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 2.0,  max: 2.6,  resultText: 'Mild hypoglobulinemia', resultTextKo: '경도 저글로불린혈증', isAbnormal: true, severity: 'mild'   },
        { min: 2.6,  max: 5.1,  resultText: 'Normal',                resultTextKo: '정상',             isAbnormal: false                       },
        { min: 5.1,  max: 7.0,  resultText: 'Mild hyperglobulinemia', resultTextKo: '경도 고글로불린혈증', isAbnormal: true, severity: 'mild'  },
        { min: 7.0,  max: null, resultText: 'Hyperglobulinemia',     resultTextKo: '고글로불린혈증',   isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '만성염증, 면역매개성 질환, 감염(FIP 등), 다발성골수종',
      decrease: '면역결핍, 신생아, 영양불량',
    },
    aiExtractKeywords: ['GLOB', 'Globulin', '글로불린'],
  },

  // ── 혈당 ──────────────────────────────────────────────────
  {
    id: 'glu',
    nameKo: '혈당',
    nameEn: 'GLU',
    descriptionKo: '혈액 속 포도당(혈당) 수치입니다. 당뇨병 여부를 확인하고 췌장의 인슐린 기능을 평가합니다. 스트레스나 식사 시간에 따라 일시적으로 변할 수 있어 다른 검사와 함께 해석합니다.',
    unit: 'mg/dL',
    section: ['chemistry', 'glucose'],
    testType: 'range',
    foldProfile: 'renal',
    defaultRefRange: { dog: '76–119', cat: '79–159' },
    ranges: {
      dog: [
        { min: null,  max: 45.0,  resultText: 'Severe hypoglycemia',   resultTextKo: '심한 저혈당',    isAbnormal: true,  severity: 'critical' },
        { min: 45.0,  max: 76.0,  resultText: 'Mild hypoglycemia',     resultTextKo: '경도 저혈당',    isAbnormal: true,  severity: 'moderate' },
        { min: 76.0,  max: 119.0, resultText: 'Normal',                resultTextKo: '정상',           isAbnormal: false                       },
        { min: 119.0, max: 200.0, resultText: 'Mild hyperglycemia',    resultTextKo: '경도 고혈당',    isAbnormal: true,  severity: 'mild'     },
        { min: 200.0, max: 400.0, resultText: 'Moderate hyperglycemia',resultTextKo: '중등도 고혈당',  isAbnormal: true,  severity: 'moderate' },
        { min: 400.0, max: null,  resultText: 'Severe hyperglycemia',  resultTextKo: '심한 고혈당',    isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 45.0,  resultText: 'Severe hypoglycemia',   resultTextKo: '심한 저혈당',    isAbnormal: true,  severity: 'critical' },
        { min: 45.0,  max: 79.0,  resultText: 'Mild hypoglycemia',     resultTextKo: '경도 저혈당',    isAbnormal: true,  severity: 'moderate' },
        { min: 79.0,  max: 159.0, resultText: 'Normal',                resultTextKo: '정상',           isAbnormal: false                       },
        { min: 159.0, max: 300.0, resultText: 'Mild hyperglycemia',    resultTextKo: '경도 고혈당',    isAbnormal: true,  severity: 'mild'     },
        { min: 300.0, max: 500.0, resultText: 'Moderate hyperglycemia',resultTextKo: '중등도 고혈당',  isAbnormal: true,  severity: 'moderate' },
        { min: 500.0, max: null,  resultText: 'Severe hyperglycemia',  resultTextKo: '심한 고혈당',    isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '당뇨병, 스트레스(특히 고양이), 쿠싱증후군, 글루카곤종, 약물(스테로이드)',
      decrease: '인슐린과다, 인슐린종, 간부전, 패혈증, 기아, 신생아저혈당',
    },
    aiExtractKeywords: ['GLU', 'Glucose', 'BG', '혈당'],
  },
  {
    id: 'fructosamine',
    nameKo: '과당아민',
    nameEn: 'Fructosamine',
    unit: 'μmol/L',
    section: ['chemistry', 'glucose'],
    testType: 'range',
    foldProfile: 'enzyme',
    defaultRefRange: { dog: '262–390', cat: '190–365' },
    ranges: {
      dog: [
        { min: null,  max: 200.0, resultText: 'Low fructosamine',              resultTextKo: '과당아민 감소',        isAbnormal: true,  severity: 'mild'     },
        { min: 200.0, max: 262.0, resultText: 'Below reference',               resultTextKo: '참고범위 미만',        isAbnormal: true,  severity: 'mild'     },
        { min: 262.0, max: 390.0, resultText: 'Normal (euglycemic 2–3 weeks)', resultTextKo: '정상 (최근 혈당 양호)', isAbnormal: false                       },
        { min: 390.0, max: 450.0, resultText: 'Acceptable glycemic control',   resultTextKo: '비교적 양호한 혈당 조절', isAbnormal: true, severity: 'mild'   },
        { min: 450.0, max: 550.0, resultText: 'Poor glycemic control',         resultTextKo: '혈당 조절 불량',        isAbnormal: true,  severity: 'moderate' },
        { min: 550.0, max: null,  resultText: 'Very poor glycemic control',    resultTextKo: '혈당 조절 매우 불량',   isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 150.0, resultText: 'Low fructosamine',              resultTextKo: '과당아민 감소',         isAbnormal: true,  severity: 'mild'     },
        { min: 150.0, max: 190.0, resultText: 'Below reference',               resultTextKo: '참고범위 미만',         isAbnormal: true,  severity: 'mild'     },
        { min: 190.0, max: 365.0, resultText: 'Normal (euglycemic 2–3 weeks)', resultTextKo: '정상 (최근 혈당 양호)', isAbnormal: false                       },
        { min: 365.0, max: 430.0, resultText: 'Acceptable glycemic control',   resultTextKo: '비교적 양호한 혈당 조절', isAbnormal: true, severity: 'mild'   },
        { min: 430.0, max: 530.0, resultText: 'Poor glycemic control',         resultTextKo: '혈당 조절 불량',        isAbnormal: true,  severity: 'moderate' },
        { min: 530.0, max: null,  resultText: 'Very poor glycemic control',    resultTextKo: '혈당 조절 매우 불량',   isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '최근 2~3주간 고혈당 지속 — 당뇨 모니터링 지표',
      decrease: '저알부민혈증(위음성 가능), 갑상선기능항진증(고양이)',
      normal: '혈당의 단기(2~3주) 평균 반영. 스트레스 혈당의 영향 없음',
    },
    aiExtractKeywords: ['Fructosamine', '과당아민'],
  },

  // ── 지질 ──────────────────────────────────────────────────
  {
    id: 'chol',
    nameKo: '콜레스테롤',
    nameEn: 'CHOL',
    unit: 'mg/dL',
    section: ['chemistry', 'lipid'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '혈액 속 지방 성분 중 하나입니다. 너무 높으면 갑상선 기능 저하, 쿠싱증후군, 당뇨, 담즙 문제 등을 의심합니다. 너무 낮으면 영양 불량이나 간 기능 저하를 평가합니다.',
    defaultRefRange: { dog: '130–370', cat: '95–260' },
    ranges: {
      dog: [
        { min: null,  max: 100.0, resultText: 'Hypocholesterolemia',      resultTextKo: '저콜레스테롤혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 100.0, max: 130.0, resultText: 'Mild hypocholesterolemia', resultTextKo: '경도 저콜레스테롤혈증', isAbnormal: true, severity: 'mild'   },
        { min: 130.0, max: 370.0, resultText: 'Normal',                   resultTextKo: '정상',               isAbnormal: false                       },
        { min: 370.0, max: 600.0, resultText: 'Mild hypercholesterolemia',resultTextKo: '경도 고콜레스테롤혈증', isAbnormal: true, severity: 'mild'   },
        { min: 600.0, max: null,  resultText: 'Hypercholesterolemia',     resultTextKo: '고콜레스테롤혈증',   isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null,  max: 75.0,  resultText: 'Hypocholesterolemia',      resultTextKo: '저콜레스테롤혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 75.0,  max: 95.0,  resultText: 'Mild hypocholesterolemia', resultTextKo: '경도 저콜레스테롤혈증', isAbnormal: true, severity: 'mild'   },
        { min: 95.0,  max: 260.0, resultText: 'Normal',                   resultTextKo: '정상',               isAbnormal: false                       },
        { min: 260.0, max: 400.0, resultText: 'Mild hypercholesterolemia',resultTextKo: '경도 고콜레스테롤혈증', isAbnormal: true, severity: 'mild'   },
        { min: 400.0, max: null,  resultText: 'Hypercholesterolemia',     resultTextKo: '고콜레스테롤혈증',   isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '갑상선기능저하증(개), 쿠싱증후군, 당뇨, 신증, 고지방식이, 담즙정체',
      decrease: '간부전, 영양불량, 부신기능저하증, 장병증',
    },
    aiExtractKeywords: ['CHOL', 'Cholesterol', 'TC', '콜레스테롤'],
  },
  {
    id: 'trig',
    nameKo: '중성지방',
    nameEn: 'TRIG',
    unit: 'mg/dL',
    section: ['chemistry', 'lipid'],
    testType: 'range',
    foldProfile: 'enzyme',
    descriptionKo: '혈액 속 중성지방(트리글리세라이드) 수치입니다. 높으면 비만, 당뇨, 갑상선 기능 저하 등을 의심하며, 심한 경우 췌장염 위험인자가 될 수 있습니다. 고지방 식이 후에도 일시적으로 상승할 수 있습니다.',
    defaultRefRange: { dog: '20–150', cat: '20–130' },
    ranges: {
      dog: [
        { min: null,  max: 20.0,  resultText: 'Below reference',       resultTextKo: '참고범위 미만',   isAbnormal: true,  severity: 'mild'     },
        { min: 20.0,  max: 150.0, resultText: 'Normal',                resultTextKo: '정상',            isAbnormal: false                       },
        { min: 150.0, max: 300.0, resultText: 'Mild hypertriglyceridemia', resultTextKo: '경도 고중성지방혈증', isAbnormal: true, severity: 'mild' },
        { min: 300.0, max: 500.0, resultText: 'Moderate hypertriglyceridemia', resultTextKo: '중등도 고중성지방혈증', isAbnormal: true, severity: 'moderate' },
        { min: 500.0, max: null,  resultText: 'Severe hypertriglyceridemia', resultTextKo: '심한 고중성지방혈증', isAbnormal: true, severity: 'high' },
      ],
      cat: [
        { min: null,  max: 20.0,  resultText: 'Below reference',       resultTextKo: '참고범위 미만',   isAbnormal: true,  severity: 'mild'     },
        { min: 20.0,  max: 130.0, resultText: 'Normal',                resultTextKo: '정상',            isAbnormal: false                       },
        { min: 130.0, max: 250.0, resultText: 'Mild hypertriglyceridemia', resultTextKo: '경도 고중성지방혈증', isAbnormal: true, severity: 'mild' },
        { min: 250.0, max: 500.0, resultText: 'Moderate hypertriglyceridemia', resultTextKo: '중등도 고중성지방혈증', isAbnormal: true, severity: 'moderate' },
        { min: 500.0, max: null,  resultText: 'Severe hypertriglyceridemia', resultTextKo: '심한 고중성지방혈증', isAbnormal: true, severity: 'high' },
      ],
    },
    comment: {
      increase: '고지방식이, 비만, 당뇨, 갑상선기능저하증, 쿠싱증후군, 췌장염 위험인자',
      decrease: '임상적 의의 낮음',
    },
    aiExtractKeywords: ['TRIG', 'Triglyceride', 'TG', '중성지방'],
  },

  // ── 전해질 ──────────────────────────────────────────────────
  {
    id: 'na',
    nameKo: '나트륨',
    nameEn: 'Na',
    unit: 'mEq/L',
    section: ['chemistry', 'electrolyte'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '140–154', cat: '149–163' },
    ranges: {
      dog: [
        { min: null,  max: 130.0, resultText: 'Severe hyponatremia',   resultTextKo: '심한 저나트륨혈증',   isAbnormal: true,  severity: 'critical' },
        { min: 130.0, max: 140.0, resultText: 'Mild hyponatremia',     resultTextKo: '경도 저나트륨혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 140.0, max: 154.0, resultText: 'Normal',                resultTextKo: '정상',                isAbnormal: false                       },
        { min: 154.0, max: 160.0, resultText: 'Mild hypernatremia',    resultTextKo: '경도 고나트륨혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 160.0, max: null,  resultText: 'Hypernatremia',         resultTextKo: '고나트륨혈증',        isAbnormal: true,  severity: 'high'     },
      ],
      cat: [
        { min: null,  max: 140.0, resultText: 'Severe hyponatremia',   resultTextKo: '심한 저나트륨혈증',   isAbnormal: true,  severity: 'critical' },
        { min: 140.0, max: 149.0, resultText: 'Mild hyponatremia',     resultTextKo: '경도 저나트륨혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 149.0, max: 163.0, resultText: 'Normal',                resultTextKo: '정상',                isAbnormal: false                       },
        { min: 163.0, max: 170.0, resultText: 'Mild hypernatremia',    resultTextKo: '경도 고나트륨혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 170.0, max: null,  resultText: 'Hypernatremia',         resultTextKo: '고나트륨혈증',        isAbnormal: true,  severity: 'high'     },
      ],
    },
    comment: {
      increase: '탈수(수분 손실 > 나트륨 손실), 과나트륨증, DI(요붕증)',
      decrease: '구토/설사, 부신기능저하증(Addison), SIADH, 울혈성심부전',
    },
    aiExtractKeywords: ['Na', 'Sodium', '나트륨'],
  },
  {
    id: 'k',
    nameKo: '칼륨',
    nameEn: 'K',
    unit: 'mEq/L',
    section: ['chemistry', 'electrolyte'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '3.7–5.8', cat: '3.5–5.1' },
    ranges: {
      dog: [
        { min: null, max: 2.5,  resultText: 'Severe hypokalemia',   resultTextKo: '심한 저칼륨혈증',   isAbnormal: true,  severity: 'critical' },
        { min: 2.5,  max: 3.7,  resultText: 'Mild hypokalemia',     resultTextKo: '경도 저칼륨혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 3.7,  max: 5.8,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 5.8,  max: 7.0,  resultText: 'Mild hyperkalemia',    resultTextKo: '경도 고칼륨혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 7.0,  max: null, resultText: 'Severe hyperkalemia',  resultTextKo: '심한 고칼륨혈증',   isAbnormal: true,  severity: 'critical' },
      ],
      cat: [
        { min: null, max: 2.5,  resultText: 'Severe hypokalemia',   resultTextKo: '심한 저칼륨혈증',   isAbnormal: true,  severity: 'critical' },
        { min: 2.5,  max: 3.5,  resultText: 'Mild hypokalemia',     resultTextKo: '경도 저칼륨혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 3.5,  max: 5.1,  resultText: 'Normal',               resultTextKo: '정상',              isAbnormal: false                       },
        { min: 5.1,  max: 6.5,  resultText: 'Mild hyperkalemia',    resultTextKo: '경도 고칼륨혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 6.5,  max: null, resultText: 'Severe hyperkalemia',  resultTextKo: '심한 고칼륨혈증',   isAbnormal: true,  severity: 'critical' },
      ],
    },
    comment: {
      increase: '부신기능저하증, 급성신부전, 요도폐색, 산증, ACE억제제',
      decrease: '구토/설사/이뇨, 인슐린, 알칼리증, 저칼륨혈증성다발성근병증(고양이)',
    },
    aiExtractKeywords: ['K', 'Potassium', '칼륨'],
  },
  {
    id: 'cl',
    nameKo: '염소',
    nameEn: 'Cl',
    unit: 'mEq/L',
    section: ['chemistry', 'electrolyte'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '102–120', cat: '111–125' },
    ranges: {
      dog: [
        { min: null,  max: 95.0,  resultText: 'Severe hypochloremia', resultTextKo: '심한 저염소혈증', isAbnormal: true,  severity: 'high'     },
        { min: 95.0,  max: 102.0, resultText: 'Mild hypochloremia',   resultTextKo: '경도 저염소혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 102.0, max: 120.0, resultText: 'Normal',               resultTextKo: '정상',            isAbnormal: false                       },
        { min: 120.0, max: 128.0, resultText: 'Mild hyperchloremia',  resultTextKo: '경도 고염소혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 128.0, max: null,  resultText: 'Hyperchloremia',       resultTextKo: '고염소혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null,  max: 105.0, resultText: 'Severe hypochloremia', resultTextKo: '심한 저염소혈증', isAbnormal: true,  severity: 'high'     },
        { min: 105.0, max: 111.0, resultText: 'Mild hypochloremia',   resultTextKo: '경도 저염소혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 111.0, max: 125.0, resultText: 'Normal',               resultTextKo: '정상',            isAbnormal: false                       },
        { min: 125.0, max: 132.0, resultText: 'Mild hyperchloremia',  resultTextKo: '경도 고염소혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 132.0, max: null,  resultText: 'Hyperchloremia',       resultTextKo: '고염소혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '과나트륨증과 동반, 대사성산증(음이온갭 정상형)',
      decrease: '위액소실(구토), 대사성알칼리증',
    },
    aiExtractKeywords: ['Cl', 'Chloride', '염소'],
  },
  {
    id: 'ca',
    nameKo: '칼슘',
    nameEn: 'Ca',
    unit: 'mg/dL',
    section: ['chemistry', 'electrolyte'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '9.3–11.8', cat: '9.0–11.5' },
    ranges: {
      dog: [
        { min: null,  max: 7.0,   resultText: 'Severe hypocalcemia',   resultTextKo: '심한 저칼슘혈증',   isAbnormal: true,  severity: 'critical' },
        { min: 7.0,   max: 9.3,   resultText: 'Mild hypocalcemia',     resultTextKo: '경도 저칼슘혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 9.3,   max: 11.8,  resultText: 'Normal',                resultTextKo: '정상',              isAbnormal: false                       },
        { min: 11.8,  max: 13.0,  resultText: 'Mild hypercalcemia',    resultTextKo: '경도 고칼슘혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 13.0,  max: 15.0,  resultText: 'Moderate hypercalcemia',resultTextKo: '중등도 고칼슘혈증', isAbnormal: true,  severity: 'moderate' },
        { min: 15.0,  max: null,  resultText: 'Severe hypercalcemia',  resultTextKo: '심한 고칼슘혈증',   isAbnormal: true,  severity: 'critical' },
      ],
      cat: [
        { min: null,  max: 7.0,   resultText: 'Severe hypocalcemia',   resultTextKo: '심한 저칼슘혈증',   isAbnormal: true,  severity: 'critical' },
        { min: 7.0,   max: 9.0,   resultText: 'Mild hypocalcemia',     resultTextKo: '경도 저칼슘혈증',   isAbnormal: true,  severity: 'moderate' },
        { min: 9.0,   max: 11.5,  resultText: 'Normal',                resultTextKo: '정상',              isAbnormal: false                       },
        { min: 11.5,  max: 13.0,  resultText: 'Mild hypercalcemia',    resultTextKo: '경도 고칼슘혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 13.0,  max: 15.0,  resultText: 'Moderate hypercalcemia',resultTextKo: '중등도 고칼슘혈증', isAbnormal: true,  severity: 'moderate' },
        { min: 15.0,  max: null,  resultText: 'Severe hypercalcemia',  resultTextKo: '심한 고칼슘혈증',   isAbnormal: true,  severity: 'critical' },
      ],
    },
    comment: {
      increase: '부갑상선기능항진증(원발/이차성), 악성종양(림프종, 항문낭선암), 비타민D독성, 육아종',
      decrease: '저알부민혈증(보정 필요), 부갑상선기능저하증(수술후), 수산화불소중독',
    },
    aiExtractKeywords: ['Ca', 'Calcium', '칼슘'],
  },
  {
    id: 'phos',
    nameKo: '인',
    nameEn: 'PHOS',
    unit: 'mg/dL',
    section: ['chemistry', 'electrolyte'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '2.5–6.0', cat: '3.4–8.5' },
    ranges: {
      dog: [
        { min: null, max: 1.5,  resultText: 'Severe hypophosphatemia',   resultTextKo: '심한 저인혈증',   isAbnormal: true,  severity: 'high'     },
        { min: 1.5,  max: 2.5,  resultText: 'Mild hypophosphatemia',     resultTextKo: '경도 저인혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 2.5,  max: 6.0,  resultText: 'Normal',                    resultTextKo: '정상',            isAbnormal: false                       },
        { min: 6.0,  max: 8.0,  resultText: 'Mild hyperphosphatemia',    resultTextKo: '경도 고인혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 8.0,  max: null, resultText: 'Hyperphosphatemia',         resultTextKo: '고인혈증',        isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null, max: 2.0,  resultText: 'Severe hypophosphatemia',   resultTextKo: '심한 저인혈증',   isAbnormal: true,  severity: 'high'     },
        { min: 2.0,  max: 3.4,  resultText: 'Mild hypophosphatemia',     resultTextKo: '경도 저인혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 3.4,  max: 8.5,  resultText: 'Normal',                    resultTextKo: '정상',            isAbnormal: false                       },
        { min: 8.5,  max: 11.0, resultText: 'Mild hyperphosphatemia',    resultTextKo: '경도 고인혈증',   isAbnormal: true,  severity: 'mild'     },
        { min: 11.0, max: null, resultText: 'Hyperphosphatemia',         resultTextKo: '고인혈증',        isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '신부전(배설 감소), 부갑상선기능저하증, 비타민D독성, 성장기',
      decrease: '부갑상선기능항진증, 당뇨 치료 중(인슐린), 영양불량, 재투식증후군',
    },
    aiExtractKeywords: ['PHOS', 'Phosphorus', 'P', '인'],
  },
  {
    id: 'mg',
    nameKo: '마그네슘',
    nameEn: 'Mg',
    unit: 'mg/dL',
    section: ['chemistry', 'electrolyte'],
    testType: 'range',
    foldProfile: 'electrolyte',
    defaultRefRange: { dog: '1.8–2.4', cat: '1.9–2.5' },
    ranges: {
      dog: [
        { min: null, max: 1.2,  resultText: 'Severe hypomagnesemia',   resultTextKo: '심한 저마그네슘혈증', isAbnormal: true,  severity: 'high'     },
        { min: 1.2,  max: 1.8,  resultText: 'Mild hypomagnesemia',     resultTextKo: '경도 저마그네슘혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 1.8,  max: 2.4,  resultText: 'Normal',                  resultTextKo: '정상',                isAbnormal: false                       },
        { min: 2.4,  max: 3.2,  resultText: 'Mild hypermagnesemia',    resultTextKo: '경도 고마그네슘혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 3.2,  max: null, resultText: 'Hypermagnesemia',         resultTextKo: '고마그네슘혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
      cat: [
        { min: null, max: 1.2,  resultText: 'Severe hypomagnesemia',   resultTextKo: '심한 저마그네슘혈증', isAbnormal: true,  severity: 'high'     },
        { min: 1.2,  max: 1.9,  resultText: 'Mild hypomagnesemia',     resultTextKo: '경도 저마그네슘혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 1.9,  max: 2.5,  resultText: 'Normal',                  resultTextKo: '정상',                isAbnormal: false                       },
        { min: 2.5,  max: 3.2,  resultText: 'Mild hypermagnesemia',    resultTextKo: '경도 고마그네슘혈증', isAbnormal: true,  severity: 'mild'     },
        { min: 3.2,  max: null, resultText: 'Hypermagnesemia',         resultTextKo: '고마그네슘혈증',      isAbnormal: true,  severity: 'moderate' },
      ],
    },
    comment: {
      increase: '신부전, 과보충',
      decrease: '만성설사, 이뇨제, 영양불량, 재투식증후군. 저칼슘/저칼륨 동반 가능',
    },
    aiExtractKeywords: ['Mg', 'Magnesium', '마그네슘'],
  },

]
