import { ImpressionRule } from './types';

export const impressionRules: ImpressionRule[] = [
  {
    ruleID: 'rule_hepatic_lipidosis',
    conditions: {
      liver_echogenicity: 'markedly_hyperechoic',
      liver_texture: 'fine',
    },
    impression: 'Diffuse hepatic lipidosis or vacuolar hepatopathy pattern',
    impressionKo: '미만성 간 지방증 또는 공포성 간증 패턴',
    differentials: ['Hepatic lipidosis', 'Steroid hepatopathy', 'Vacuolar hepatopathy', 'Hyperadrenocorticism'],
    differentialsKo: ['간 지방증', '스테로이드 간증', '공포성 간증', '부신피질 기능항진증'],
    recommendation: 'Hepatic cytology / biopsy; evaluate cortisol, bile acids, ALT, ALP',
    recommendationKo: '간 세포 검사 / 생검; 코르티솔, 담즙산, ALT, ALP 평가',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_chronic_hepatopathy',
    conditions: {
      liver_echogenicity: ['mildly_hyperechoic', 'mixed'],
      liver_texture: 'coarse',
      liver_margin: 'irregular',
    },
    impression: 'Chronic hepatopathy / hepatic fibrosis pattern',
    impressionKo: '만성 간질환 / 간 섬유화 패턴',
    differentials: ['Chronic hepatitis', 'Hepatic fibrosis', 'Cirrhosis', 'Chronic toxin exposure'],
    differentialsKo: ['만성 간염', '간 섬유화', '간경변', '만성 독소 노출'],
    recommendation: 'Hepatic biopsy, liver function tests (bile acids, albumin, coagulation panel)',
    recommendationKo: '간 생검, 간 기능 검사 (담즙산, 알부민, 응고 패널)',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_acute_pancreatitis',
    conditions: {
      pancreas_echogenicity: 'hypoechoic',
      peripancreatic_effusion: 'true',
    },
    impression: 'Acute pancreatitis pattern',
    impressionKo: '급성 췌장염 패턴',
    differentials: ['Acute pancreatitis', 'Pancreatic neoplasia with inflammation'],
    differentialsKo: ['급성 췌장염', '염증 동반 췌장 종양'],
    recommendation: 'cPLI/fPLI, supportive care; repeat ultrasound in 48-72h if severe',
    recommendationKo: 'cPLI/fPLI 검사, 지지 치료; 중증인 경우 48-72시간 후 재검',
    severity: 'severe',
  },
  {
    ruleID: 'rule_gallbladder_mucocele',
    conditions: {
      gb_mucocele_presence: 'present',
    },
    impression: 'Gallbladder mucocele',
    impressionKo: '담낭 점액낭종',
    differentials: ['Gallbladder mucocele', 'Inspissated bile / biliary sludge'],
    differentialsKo: ['담낭 점액낭종', '농축 담즙 / 담즙 슬러지'],
    recommendation: 'Surgical consultation; cholecystectomy often indicated; evaluate for rupture risk signs',
    recommendationKo: '외과적 상담; 담낭 절제술 고려 필요; 파열 위험 징후 평가',
    severity: 'severe',
  },
  {
    ruleID: 'rule_mucocele_rupture_risk',
    conditions: {
      gb_mucocele_presence: 'present',
      gb_rupture_risk: 'true',
    },
    impression: 'Gallbladder mucocele with rupture risk signs — emergency',
    impressionKo: '파열 위험 징후를 동반한 담낭 점액낭종 — 응급',
    differentials: ['Impending GB rupture', 'GB perforation with bile peritonitis'],
    differentialsKo: ['담낭 파열 임박', '담즙 복막염을 동반한 담낭 천공'],
    recommendation: 'Emergency surgical consultation; immediate cholecystectomy likely required; IV fluids, antibiotics',
    recommendationKo: '응급 외과 상담; 즉각적 담낭 절제술 가능성 높음; 정맥 수액, 항생제 투여',
    severity: 'critical',
  },
  {
    ruleID: 'rule_biliary_obstruction',
    conditions: {
      ihbd_dilation: ['mild', 'severe'],
    },
    impression: 'Biliary obstruction pattern — intrahepatic bile duct dilation',
    impressionKo: '담도 폐쇄 패턴 — 간내 담도 확장',
    differentials: [
      'Common bile duct obstruction (cholelith, mass, stricture)',
      'Cholangitis / Cholangiohepatitis',
      'Pancreatitis with periductal compression',
      'Biliary neoplasia',
    ],
    differentialsKo: [
      '총담관 폐쇄 (담석, 종괴, 협착)',
      '담관염 / 담관간염',
      '췌장 주위 압박을 동반한 췌장염',
      '담도 종양',
    ],
    recommendation: 'Liver enzymes (ALP, GGT, bilirubin), bile acids; abdominal CT or cholangiography; consider endoscopic or surgical biliary decompression',
    recommendationKo: '간 효소 (ALP, GGT, 빌리루빈), 담즙산; 복부 CT 또는 담도조영술; 내시경 또는 외과적 담도 감압 고려',
    severity: 'severe',
  },
  {
    ruleID: 'rule_biliary_obstruction_severe',
    conditions: {
      ihbd_dilation: 'severe',
      cbd_dilation_cause: ['cholelith_obstruction', 'mass_compression'],
    },
    impression: 'Severe biliary obstruction — IHBD dilation with marked CBD dilation',
    impressionKo: '중증 담도 폐쇄 — 간내 담도 + 총담관 현저 확장',
    differentials: [
      'Complete CBD obstruction (cholelith, neoplasia)',
      'Biliary neoplasia with ductal invasion',
    ],
    differentialsKo: [
      '완전 총담관 폐쇄 (담석, 종양)',
      '담도 침습을 동반한 담도 종양',
    ],
    recommendation: 'Urgent surgical or interventional biliary decompression; hepatic biopsy for concurrent hepatopathy; CBC, coagulation panel',
    recommendationKo: '긴급 외과 또는 중재적 담도 감압; 동반 간질환 평가를 위한 간 생검; CBC, 응고 패널',
    severity: 'critical',
  },
  {
    ruleID: 'rule_gb_mass_neoplasia',
    conditions: {
      gb_mass_presence: 'mass_present',
    },
    impression: 'Gallbladder mural/intraluminal mass — neoplasia suspected',
    impressionKo: '담낭 종괴 — 종양 의심',
    differentials: [
      'Gallbladder adenocarcinoma',
      'Gallbladder lymphoma',
      'Leiomyosarcoma',
      'Metastatic neoplasia',
      'Cholesterol polyp (benign)',
    ],
    differentialsKo: [
      '담낭 선암종',
      '담낭 림프종',
      '평활근육종',
      '전이성 종양',
      '콜레스테롤 폴립 (양성)',
    ],
    recommendation: 'Fine needle aspirate or biopsy; staging CT; surgical consultation',
    recommendationKo: '세침흡인 또는 생검; 병기 설정을 위한 CT; 외과적 상담',
    severity: 'severe',
  },
  {
    ruleID: 'rule_biliary_mass_neoplasia',
    conditions: {
      cbd_mass_presence: 'present',
    },
    impression: 'Biliary duct mass — cholangiocarcinoma or biliary neoplasia suspected',
    impressionKo: '담도 종괴 — 담관암 또는 담도 종양 의심',
    differentials: [
      'Cholangiocarcinoma (intrahepatic / hilar / distal)',
      'Biliary carcinoid',
      'Extrinsic mass compression (pancreatic, hepatic neoplasia)',
      'Biliary cystadenoma/cystadenocarcinoma',
    ],
    differentialsKo: [
      '담관암 (간내형 / 간문부형 / 원위부형)',
      '담도 카르시노이드',
      '외부 종괴 압박 (췌장, 간 종양)',
      '담도 낭선종/낭선암',
    ],
    recommendation: 'Hepatic cytology or biopsy; staging CT; biliary brush cytology if accessible; surgical consultation',
    recommendationKo: '간 세포 검사 또는 생검; 병기 설정 CT; 접근 가능 시 담도 솔질 세포검사; 외과적 상담',
    severity: 'severe',
  },
  {
    ruleID: 'rule_ckd_advanced',
    conditions: {
      kidney_cortex_echogenicity: 'markedly_increased',
      kidney_cmd: 'absent',
    },
    impression: 'Advanced chronic kidney disease pattern',
    impressionKo: '진행성 만성 신장 질환 패턴',
    differentials: ['Advanced CKD', 'End-stage renal disease'],
    differentialsKo: ['진행성 만성 신장 질환', '말기 신부전'],
    recommendation: 'IRIS staging, serum creatinine, SDMA, urine protein:creatinine ratio',
    recommendationKo: 'IRIS 단계 평가, 혈청 크레아티닌, SDMA, 단백뇨/크레아티닌 비율',
    severity: 'severe',
  },
  {
    ruleID: 'rule_haemoabdomen',
    conditions: {
      free_fluid_presence: 'true',
      free_fluid_echogenicity: 'echogenic',
      spleen_size: ['splenomegaly_mild', 'splenomegaly_marked'],
    },
    impression: 'Haemoabdomen with splenic lesion; haemangiosarcoma strongly suspected',
    impressionKo: '비장 병변을 동반한 혈복강; 혈관육종 강력 의심',
    differentials: ['Splenic haemangiosarcoma', 'Nodular hyperplasia with rupture', 'Traumatic haemorrhage'],
    differentialsKo: ['비장 혈관육종', '파열을 동반한 결절성 과증식', '외상성 출혈'],
    recommendation: 'Emergency evaluation; CBC, coagulation, surgical consultation',
    recommendationKo: '응급 평가; CBC, 응고 검사, 외과적 상담',
    severity: 'critical',
  },
  {
    ruleID: 'rule_hyperadrenocorticism',
    conditions: {
      adrenal_size: 'mild',
      adrenal_asymmetry: 'false',
      liver_echogenicity: 'markedly_hyperechoic',
    },
    impression: 'Pituitary-dependent hyperadrenocorticism (PDH) pattern',
    impressionKo: '뇌하수체 의존성 부신피질 기능항진증 패턴',
    differentials: ['PDH (Cushing\'s disease)', 'Iatrogenic hyperadrenocorticism'],
    differentialsKo: ['뇌하수체 의존성 부신피질 기능항진증', '의원성 부신피질 기능항진증'],
    recommendation: 'LDDS/HDDS test, ACTH stimulation test, urine cortisol:creatinine ratio',
    recommendationKo: '저용량/고용량 덱사메타손 억제 검사, ACTH 자극 검사, 소변 코르티솔:크레아티닌 비율',
    severity: 'moderate',
  },
  // ── Renal contour rules ──────────────────────────────────────────────
  {
    ruleID: 'rule_renal_infarction',
    conditions: {
      kidney_contour: ['cortical_indentation', 'focal_depression'],
    },
    impression: 'Renal infarction pattern (cortical scarring / focal notch)',
    impressionKo: '신장 경색 패턴 (피질 반흔 / 국소 노치)',
    differentials: [
      'Renal infarction (thromboembolic)',
      'Chronic pyelonephritis with scarring',
      'Post-traumatic cortical scar',
    ],
    differentialsKo: [
      '혈전색전성 신장 경색',
      '반흔을 동반한 만성 신우신염',
      '외상 후 피질 반흔',
    ],
    recommendation: 'Cardiac evaluation (echocardiography) — especially in cats; urinalysis, urine culture; assess blood pressure',
    recommendationKo: '심장 초음파 평가 (특히 고양이 HCM 배제); 요검사 및 소변 배양; 혈압 측정',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_renal_infarction_severe',
    conditions: {
      kidney_contour: 'focal_depression',
      kidney_cortex_echogenicity: ['mildly_increased', 'markedly_increased'],
    },
    impression: 'Renal infarction with parenchymal change strongly suspected',
    impressionKo: '실질 변화를 동반한 신장 경색 강력 의심',
    differentials: [
      'Acute-to-subacute renal infarction',
      'Chronic infarction with CKD progression',
    ],
    differentialsKo: [
      '급성~아급성 신장 경색',
      '만성 경색에 의한 CKD 진행',
    ],
    recommendation: 'Cardiac workup (echocardiography, NT-proBNP), blood pressure, renal panel (BUN/Cr/SDMA), urinalysis; consider anticoagulation therapy',
    recommendationKo: '심장 검사 (심초음파, NT-proBNP), 혈압, 신장 패널 (BUN/Cr/SDMA), 요검사; 항응고 치료 고려',
    severity: 'severe',
  },
  {
    ruleID: 'rule_bosselated_kidney',
    conditions: {
      kidney_contour: 'bosselated',
    },
    impression: 'Bosselated / nodular renal surface — polycystic kidney disease or multifocal neoplasia',
    impressionKo: '신장 표면 결절성 돌출 — 다낭성 신장 질환 또는 다초점 종양',
    differentials: [
      'Polycystic kidney disease (PKD — especially Persian cats)',
      'Multiple renal cysts',
      'Nodular hyperplasia',
      'Multifocal lymphoma',
      'Metastatic neoplasia',
    ],
    differentialsKo: [
      '다낭성 신장 질환 (PKD — 특히 페르시안 고양이)',
      '다발성 신장 낭종',
      '결절성 과형성',
      '다초점 림프종',
      '전이성 종양',
    ],
    recommendation: 'PKD genetic test (cats), fine needle aspirate of solid nodules; abdominal survey for primary neoplasia',
    recommendationKo: 'PKD 유전자 검사 (고양이), 고형 결절 세침흡인; 원발 종양 확인을 위한 복강 전반 평가',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_shrunken_kidney',
    conditions: {
      kidney_contour: 'shrunken',
    },
    impression: 'Shrunken / contracted kidney — end-stage CKD or chronic infarction',
    impressionKo: '신장 위축 / 수축 변형 — 말기 만성 신장 질환 또는 만성 경색',
    differentials: [
      'End-stage chronic kidney disease',
      'Renal hypoplasia / aplasia',
      'Chronic renal infarction with atrophy',
      'Post-inflammatory fibrosis',
    ],
    differentialsKo: [
      '말기 만성 신장 질환 (ESRD)',
      '신장 형성부전 / 무발생',
      '만성 경색에 의한 위축',
      '염증 후 섬유화',
    ],
    recommendation: 'IRIS CKD staging, BUN/Cr/SDMA/phosphorus/potassium, urine protein:creatinine ratio; blood pressure; contralateral kidney function evaluation',
    recommendationKo: 'IRIS CKD 단계 분류, BUN/Cr/SDMA/인/칼륨 측정, 단백뇨/크레아티닌 비율; 혈압; 반대측 신장 기능 평가',
    severity: 'severe',
  },
  {
    ruleID: 'rule_irregular_renal_contour',
    conditions: {
      kidney_contour: 'irregular_contour',
    },
    impression: 'Irregular renal contour — chronic nephropathy / fibrosis',
    impressionKo: '신장 윤곽 불규칙 — 만성 신장 질환 / 섬유화',
    differentials: [
      'Chronic kidney disease with fibrosis',
      'Chronic pyelonephritis',
      'Resolving renal infarction',
      'Infiltrative neoplasia (lymphoma)',
    ],
    differentialsKo: [
      '섬유화를 동반한 만성 신장 질환',
      '만성 신우신염',
      '회복 중인 신장 경색',
      '침윤성 종양 (림프종)',
    ],
    recommendation: 'Renal panel, urinalysis, urine culture; if neoplasia suspected, cytology or biopsy',
    recommendationKo: '신장 패널, 요검사, 소변 배양; 종양 의심 시 세포검사 또는 생검',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_lymphoma',
    conditions: {
      ln_enlargement: 'marked',
      ln_echogenicity: 'hypoechoic_rounded',
      si_wall_layering: 'obliterated',
    },
    impression: 'Multicentric or alimentary lymphoma pattern',
    impressionKo: '다발성 또는 소화기형 림프종 패턴',
    differentials: ['Alimentary lymphoma', 'Multicentric lymphoma', 'IBD with reactive lymphadenopathy'],
    differentialsKo: ['소화기형 림프종', '다발성 림프종', '반응성 림프절병증을 동반한 염증성 장질환'],
    recommendation: 'FNA of lymph node or GI wall, PARR, histopathology for classification',
    recommendationKo: '림프절 또는 위장관 벽 세침흡인, PARR, 분류를 위한 조직병리 검사',
    severity: 'severe',
  },
];
