import { ImpressionRule } from './types';

export const impressionRules: ImpressionRule[] = [
  {
    ruleID: 'rule_hepatic_lipidosis',
    conditions: {
      liver_echogenicity: 'markedly_hyperechoic',
      liver_texture: 'fine',
    },
    impression: 'Diffuse hepatic lipidosis or vacuolar hepatopathy pattern',
    impressionKo: '미만성 간 지방증 또는 공포성 간증 패턴',
    differentials: ['Hepatic lipidosis', 'Steroid hepatopathy', 'Vacuolar hepatopathy', 'Hyperadrenocorticism'],
    differentialsKo: ['간 지방증', '스테로이드 간증', '공포성 간증', '부신피질 기능항진증'],
    recommendation: 'Hepatic cytology / biopsy; evaluate cortisol, bile acids, ALT, ALP',
    recommendationKo: '간 세포 검사 / 생검; 코르티솔, 담즙산, ALT, ALP 평가',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_chronic_hepatopathy',
    conditions: {
      liver_echogenicity: ['mildly_hyperechoic', 'mixed'],
      liver_texture: 'coarse',
      liver_margin: 'irregular',
    },
    impression: 'Chronic hepatopathy / hepatic fibrosis pattern',
    impressionKo: '만성 간질환 / 간 섬유화 패턴',
    differentials: ['Chronic hepatitis', 'Hepatic fibrosis', 'Cirrhosis', 'Chronic toxin exposure'],
    differentialsKo: ['만성 간염', '간 섬유화', '간경변', '만성 독소 노출'],
    recommendation: 'Hepatic biopsy, liver function tests (bile acids, albumin, coagulation panel)',
    recommendationKo: '간 생검, 간 기능 검사 (담즙산, 알부민, 응고 패널)',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_acute_pancreatitis',
    conditions: {
      pancreas_echogenicity: 'hypoechoic',
      peripancreatic_effusion: 'true',
    },
    impression: 'Acute pancreatitis pattern',
    impressionKo: '급성 췌장염 패턴',
    differentials: ['Acute pancreatitis', 'Pancreatic neoplasia with inflammation'],
    differentialsKo: ['급성 췌장염', '염증 동반 췌장 종양'],
    recommendation: 'cPLI/fPLI, supportive care; repeat ultrasound in 48-72h if severe',
    recommendationKo: 'cPLI/fPLI 검사, 지지 치료; 중증인 경우 48-72시간 후 재검',
    severity: 'severe',
  },
  {
    ruleID: 'rule_gallbladder_mucocele',
    conditions: {
      gb_content: 'mucocele',
    },
    impression: 'Gallbladder mucocele',
    impressionKo: '담낭 점액낭종',
    differentials: ['Gallbladder mucocele', 'Inspissated bile'],
    differentialsKo: ['담낭 점액낭종', '농축 담즙'],
    recommendation: 'Surgical consultation; cholecystectomy often indicated',
    recommendationKo: '외과적 상담; 담낭 절제술 고려 필요',
    severity: 'severe',
  },
  {
    ruleID: 'rule_ckd_advanced',
    conditions: {
      kidney_cortex_echogenicity: 'markedly_increased',
      kidney_cmd: 'absent',
    },
    impression: 'Advanced chronic kidney disease pattern',
    impressionKo: '진행성 만성 신장 질환 패턴',
    differentials: ['Advanced CKD', 'End-stage renal disease'],
    differentialsKo: ['진행성 만성 신장 질환', '말기 신부전'],
    recommendation: 'IRIS staging, serum creatinine, SDMA, urine protein:creatinine ratio',
    recommendationKo: 'IRIS 단계 평가, 혈청 크레아티닌, SDMA, 단백뇨/크레아티닌 비율',
    severity: 'severe',
  },
  {
    ruleID: 'rule_haemoabdomen',
    conditions: {
      free_fluid_presence: 'true',
      free_fluid_echogenicity: 'echogenic',
      spleen_size: ['splenomegaly_mild', 'splenomegaly_marked'],
    },
    impression: 'Haemoabdomen with splenic lesion; haemangiosarcoma strongly suspected',
    impressionKo: '비장 병변을 동반한 혈복강; 혈관육종 강력 의심',
    differentials: ['Splenic haemangiosarcoma', 'Nodular hyperplasia with rupture', 'Traumatic haemorrhage'],
    differentialsKo: ['비장 혈관육종', '파열을 동반한 결절성 과증식', '외상성 출혈'],
    recommendation: 'Emergency evaluation; CBC, coagulation, surgical consultation',
    recommendationKo: '응급 평가; CBC, 응고 검사, 외과적 상담',
    severity: 'critical',
  },
  {
    ruleID: 'rule_hyperadrenocorticism',
    conditions: {
      adrenal_size: 'mild',
      adrenal_asymmetry: 'false',
      liver_echogenicity: 'markedly_hyperechoic',
    },
    impression: 'Pituitary-dependent hyperadrenocorticism (PDH) pattern',
    impressionKo: '뇌하수체 의존성 부신피질 기능항진증 패턴',
    differentials: ['PDH (Cushing\'s disease)', 'Iatrogenic hyperadrenocorticism'],
    differentialsKo: ['뇌하수체 의존성 부신피질 기능항진증', '의원성 부신피질 기능항진증'],
    recommendation: 'LDDS/HDDS test, ACTH stimulation test, urine cortisol:creatinine ratio',
    recommendationKo: '저용량/고용량 덱사메타손 억제 검사, ACTH 자극 검사, 소변 코르티솔:크레아티닌 비율',
    severity: 'moderate',
  },
  {
    ruleID: 'rule_lymphoma',
    conditions: {
      ln_enlargement: 'marked',
      ln_echogenicity: 'hypoechoic_rounded',
      si_wall_layering: 'obliterated',
    },
    impression: 'Multicentric or alimentary lymphoma pattern',
    impressionKo: '다발성 또는 소화기형 림프종 패턴',
    differentials: ['Alimentary lymphoma', 'Multicentric lymphoma', 'IBD with reactive lymphadenopathy'],
    differentialsKo: ['소화기형 림프종', '다발성 림프종', '반응성 림프절병증을 동반한 염증성 장질환'],
    recommendation: 'FNA of lymph node or GI wall, PARR, histopathology for classification',
    recommendationKo: '림프절 또는 위장관 벽 세침흡인, PARR, 분류를 위한 조직병리 검사',
    severity: 'severe',
  },
];
