import { UltrasoundTestItem } from '../types';

export const adrenalTests: UltrasoundTestItem[] = [
  {
    testID: 'organ_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'adrenal',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'surgical_removal', label: 'Surgical removal', labelKo: '수술적 적출', resultText: 'Previously removed surgically', resultTextKo: '기존 수술을 통해 적출됨', isAbnormal: true },
      { value: 'congenital_absence', label: 'Congenital absence / Agenesis', labelKo: '선천적 결손', resultText: 'Congenital absence / agenesis', resultTextKo: '선천적 결손/미발달', isAbnormal: true },
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
      { value: 'ectopic', label: 'Ectopic location', labelKo: '이소성 위치', resultText: 'Ectopic location suspected', resultTextKo: '이소성 위치 의심', isAbnormal: true },
    ],
  },
  {
    testID: 'adrenal_size',
    testName: 'Adrenal Gland Thickness (Width)',
    testNameKo: '부신 두께',
    organ: 'adrenal',
    partOfOrgan: 'bilateral',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Measure the width (pole-to-pole). Dog: <7.4mm. Cat: <4.3mm.',
    normalRange: {
      dog: { max: 7.4 },
      cat: { max: 4.3 },
    },
    ranges: [
      {
        min: 0,
        max: 7.4,
        resultText: 'Adrenal gland size within normal limits',
        resultTextKo: '부신 크기 정상 범위',
        ownerResultTextKo: '부신의 크기가 정상 범위 내에 있습니다.',
        isAbnormal: false,
      },
      {
        min: 7.4,
        max: 15,
        resultText: 'Adrenal gland enlargement; hyperadrenocorticism (pituitary-dependent) or early neoplasia suspected',
        resultTextKo: '부신 비대; 뇌하수체 의존성 부신피질 기능항진증 또는 초기 종양 의심',
        ownerResultTextKo: '부신이 커져 있습니다. 부신피질 기능항진증(쿠싱)이나 초기 종양 가능성이 있어 관련 검사가 필요할 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 15,
        max: null,
        resultText: 'Marked adrenal enlargement (>15mm); adrenal tumour (adenoma/carcinoma) suspected',
        resultTextKo: '현저한 부신 비대(>15mm); 부신 종양 (선종/암종) 의심',
        ownerResultTextKo: '부신이 매우 심하게 커져 있습니다. 부신 종양(혹) 가능성이 매우 높습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'adrenal_shape',
    testName: 'Adrenal Gland Shape',
    testNameKo: '부신 형태',
    organ: 'adrenal',
    partOfOrgan: 'bilateral',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      {
        value: 'normal_bilobed',
        label: 'Normal peanut/bilobed shape',
        labelKo: '정상 땅콩/이엽 형태',
        resultText: 'Adrenal gland morphology normal (peanut-shaped)',
        resultTextKo: '부신 형태 정상 (땅콩 모양)',
        ownerResultTextKo: '부신이 정상적인 땅콩 모양을 유지하고 있습니다.',
        isAbnormal: false,
      },
      {
        value: 'rounded',
        label: 'Rounded / Spherical',
        labelKo: '둥근/구형',
        resultText: 'Rounded adrenal gland; neoplasia suspected',
        resultTextKo: '둥근 형태의 부신; 종양 의심',
        ownerResultTextKo: '부신이 둥글게 변해 있습니다. 종양성 변화에 대한 주의가 필요합니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'irregular_mass',
        label: 'Irregular mass',
        labelKo: '불규칙한 종괴',
        resultText: 'Irregular adrenal mass; adrenocortical carcinoma or phaeochromocytoma suspected',
        resultTextKo: '불규칙한 부신 종괴; 부신피질암종 또는 갈색세포종 의심',
        ownerResultTextKo: '부신에 불규칙한 혹(종괴)이 관찰됩니다. 악성 종양 가능성을 확인해야 합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'adrenal_asymmetry',
    testName: 'Adrenal Asymmetry',
    testNameKo: '부신 비대칭',
    organ: 'adrenal',
    partOfOrgan: 'bilateral',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    positiveResultText: 'Unilateral adrenal enlargement (asymmetry); adrenal-dependent hyperadrenocorticism or unilateral adrenal neoplasia suspected',
    positiveResultTextKo: '일측성 부신 비대 (비대칭); 부신 의존성 부신피질 기능항진증 또는 일측성 부신 종양 의심',
    positiveOwnerResultTextKo: '양쪽 부신의 크기가 다릅니다. 한쪽 부신에 종양이나 기능 이상이 있을 가능성이 있습니다.',
    negativeResultText: 'Bilateral adrenal glands symmetrical',
    negativeResultTextKo: '양측 부신 대칭',
    negativeOwnerResultTextKo: '양쪽 부신의 크기가 대칭적이고 정상입니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'adrenal_mass_size',
    testName: 'Adrenal Mass Size',
    testNameKo: '부신 종괴 크기',
    organ: 'adrenal',
    partOfOrgan: 'bilateral',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'adrenal_shape', triggerValues: ['rounded', 'irregular_mass'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 20,
        resultText: 'Adrenal mass <20mm; adenoma or pheochromocytoma possible; endocrine evaluation recommended',
        resultTextKo: '20mm 미만 부신 종괴; 선종 또는 갈색세포종 가능; 내분비 평가 권장',
        ownerResultTextKo: '부신에 2cm 미만의 작은 혹(종괴)이 관찰됩니다. 양성 선종이나 기능성 종양 가능성이 있어 추가적인 호르몬 검사가 권장됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 20, max: 40,
        resultText: 'Adrenal mass 20–40mm; adrenocortical carcinoma or pheochromocytoma suspected',
        resultTextKo: '20-40mm 부신 종괴; 부신피질암종 또는 갈색세포종 의심',
        ownerResultTextKo: '부신에 2~4cm 크기의 혹이 관찰됩니다. 악성 종양 가능성이 있어 정밀한 평가가 필요합니다.',
        isAbnormal: true, severity: 'severe',
      },
      {
        min: 40, max: null,
        resultText: 'Large adrenal mass >40mm; malignant adrenal neoplasia; vascular invasion evaluation required',
        resultTextKo: '40mm 초과 대형 부신 종괴; 악성 부신 종양; 혈관 침습 평가 필요',
        ownerResultTextKo: '부신에 4cm 이상의 큰 혹이 관찰됩니다. 악성 종양 가능성이 매우 높으며 주변 혈관 침습 여부에 대한 추가 검사가 반드시 필요합니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'adrenal_mass_echogenicity',
    testName: 'Adrenal Mass Echogenicity',
    testNameKo: '부신 종괴 에코 음영',
    organ: 'adrenal',
    partOfOrgan: 'bilateral',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'adrenal_shape', triggerValues: ['rounded', 'irregular_mass'] },
    options: [
      {
        value: 'homogeneous_hypo',
        label: 'Homogeneous hypoechoic',
        labelKo: '균질 저에코',
        resultText: 'Homogeneous hypoechoic adrenal mass; adenoma suspected',
        resultTextKo: '균질 저에코 부신 종괴; 선종 의심',
        ownerResultTextKo: '부신의 혹이 내부적으로 균일하고 어둡게 보입니다. 비교적 얌전한 선종일 가능성이 있습니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'heterogeneous',
        label: 'Heterogeneous / Mixed',
        labelKo: '불균질/혼합',
        resultText: 'Heterogeneous adrenal mass; pheochromocytoma or carcinoma suspected',
        resultTextKo: '불균질 부신 종괴; 갈색세포종 또는 암종 의심',
        ownerResultTextKo: '부신의 혹 내부가 불규칙하고 지저분하게 보입니다. 공격적인 종양일 가능성을 고려해야 합니다.',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'mineralised',
        label: 'Mineralised (with shadowing)',
        labelKo: '석회화 동반',
        resultText: 'Mineralised adrenal mass with acoustic shadowing; chronic haematoma or carcinoma suspected',
        resultTextKo: '음향 음영을 동반한 석회화 부신 종괴; 만성 혈종 또는 암종 의심',
        ownerResultTextKo: '부신의 혹 내부에 딱딱한 석회 성분이 관찰됩니다. 오래된 혈종이거나 종양성 변화일 수 있습니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'adrenal_vascular_invasion',
    testName: 'Adrenal Mass — Vascular Invasion',
    testNameKo: '부신 종괴 혈관 침습',
    organ: 'adrenal',
    partOfOrgan: 'bilateral',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'adrenal_shape', triggerValues: ['rounded', 'irregular_mass'] },
    note: 'Check for caudal vena cava (CVC) invasion — increases surgical risk significantly',
    positiveResultText: 'Vascular invasion (CVC or aorta) identified; surgical risk high; CT/MRI recommended',
    positiveResultTextKo: '혈관 침습(후대정맥 또는 대동맥) 관찰; 수술 위험도 높음; CT/MRI 권장',
    positiveOwnerResultTextKo: '부신의 혹이 주변의 큰 혈관(대정맥 등)을 파고든 것이 관찰됩니다. 수술 위험도가 매우 높으며 CT 등의 정밀 검사가 필요합니다.',
    negativeResultText: 'No vascular invasion identified',
    negativeResultTextKo: '혈관 침습 없음',
    negativeOwnerResultTextKo: '부신의 혹이 주변 큰 혈관을 침습한 흔적은 아직 보이지 않습니다.',
    positiveIsAbnormal: true,
  },
];
