import { UltrasoundTestItem } from '../types';

export const colonTests: UltrasoundTestItem[] = [
  {
    testID: 'colon_wall_thickness',
    testName: 'Colon Wall Thickness',
    testNameKo: '결장 벽 두께',
    organ: 'colon',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Normal: <2.0-3.0mm. Usually very thin.',
    normalRange: { dog: { max: 3 }, cat: { max: 3 } },
    ranges: [
      { min: 0, max: 3, resultText: 'Colonic wall thickness within normal limits', resultTextKo: '결장 벽 두께 정상 범위', isAbnormal: false },
      { min: 3, max: null, resultText: 'Colonic wall thickening; colitis suspected', resultTextKo: '결장 벽 비후; 결장염 의심', isAbnormal: true, severity: 'mild' },
    ],
    dogRanges: [
      { min: 0, max: 3, resultText: 'Colonic wall thickness within normal limits', resultTextKo: '결장 벽 두께 정상 범위 (개: ≤3mm)', isAbnormal: false },
      { min: 3, max: null, resultText: 'Colonic wall thickening; colitis suspected', resultTextKo: '결장 벽 비후(>3mm); 결장염 의심', isAbnormal: true, severity: 'mild' },
    ],
    catRanges: [
      { min: 0, max: 2.5, resultText: 'Colonic wall thickness within normal limits', resultTextKo: '결장 벽 두께 정상 범위 (고양이: ≤2.5mm)', isAbnormal: false },
      { min: 2.5, max: null, resultText: 'Colonic wall thickening; colitis suspected', resultTextKo: '결장 벽 비후(>2.5mm); 결장염 의심', isAbnormal: true, severity: 'mild' },
    ],
  },
  {
    testID: 'colon_content',
    testName: 'Colon Content',
    testNameKo: '결장 내강물',
    organ: 'colon',
    partOfOrgan: 'lumen',
    testType: 'select',
    clinicalSignificance: 'low',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      { value: 'feces', label: 'Feces (normal)', labelKo: '변 (정상)', resultText: 'Colonic content consists of normal feces', resultTextKo: '결장 내 정상 변 관찰됨', isAbnormal: false },
      { value: 'gas', label: 'Gas', labelKo: '가스', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'empty', label: 'Empty', labelKo: '비어있음', resultText: '', resultTextKo: '', isAbnormal: false },
    ],
  },
  {
    testID: 'colon_muscularis_severity',
    testName: 'Muscularis Propria Hypertrophy',
    testNameKo: '결장 근육층(muscularis propria) 비후',
    organ: 'colon',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '근육층 비후는 IBD, 림프종, 만성 결장염 등에서 관찰됩니다.',
    options: [
      { value: 'normal', label: 'Normal muscularis', labelKo: '근육층 정상', resultText: 'Colonic muscularis propria normal thickness', resultTextKo: '결장 근육층 두께 정상', isAbnormal: false },
      { value: 'mild', label: 'Mild hypertrophy', labelKo: '경도 비후', resultText: 'Mild colonic muscularis hypertrophy; IBD or chronic colitis suspected', resultTextKo: '경도 결장 근육층 비후; IBD 또는 만성 결장염 의심', isAbnormal: true, severity: 'mild' },
      { value: 'moderate', label: 'Moderate hypertrophy', labelKo: '중등도 비후', resultText: 'Moderate colonic muscularis hypertrophy; IBD or lymphoma suspected', resultTextKo: '중등도 결장 근육층 비후; IBD 또는 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'severe', label: 'Severe hypertrophy', labelKo: '심한 비후', resultText: 'Severe colonic muscularis hypertrophy; lymphoma or infiltrative neoplasia strongly suspected', resultTextKo: '심한 결장 근육층 비후; 림프종 또는 침윤성 종양 강력 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'colon_layer_predominance',
    testName: 'Wall Layer Predominance',
    testNameKo: '결장 비후 우세층',
    organ: 'colon',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'colon_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '점막·점막하층 우세 → IBD/결장염, 근육층 우세 → 소세포 림프종, 전층 균등 → 대세포 림프종/선암종',
    options: [
      { value: 'mucosal_submucosal', label: 'Mucosal / submucosal predominance', labelKo: '점막·점막하층 우세', resultText: 'Colonic wall thickening predominantly mucosal/submucosal; IBD or colitis pattern', resultTextKo: '결장 점막·점막하층 우세 비후; IBD 또는 결장염 패턴', isAbnormal: true, severity: 'mild' },
      { value: 'muscularis', label: 'Muscularis predominance', labelKo: '근육층 우세', resultText: 'Colonic wall thickening predominantly muscularis; small cell lymphoma suspected', resultTextKo: '결장 근육층 우세 비후; 소세포 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'transmural', label: 'Transmural / uniform', labelKo: '전층 균등 비후', resultText: 'Colonic transmural uniform thickening; large cell lymphoma or adenocarcinoma suspected', resultTextKo: '결장 전층 균등 비후; 대세포 림프종 또는 선암종 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'colon_muscularis_thickness',
    testName: 'Muscularis Propria Thickness (measured)',
    testNameKo: '결장 근육층 두께 (측정값)',
    organ: 'colon',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'colon_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '선택 입력. 근육층만 분리 측정 시 기록 (정상 <2mm).',
    normalRange: { dog: { max: 2 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 2, resultText: 'Colonic muscularis thickness within normal limits', resultTextKo: '결장 근육층 두께 정상 범위', isAbnormal: false },
      { min: 2, max: null, resultText: 'Colonic muscularis thickening >2mm', resultTextKo: '결장 근육층 비후 >2mm', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'colon_mucosal_striations',
    testName: 'Hyperechoic Mucosal Striations',
    testNameKo: '고에코 점막 선조 (Hyperechoic mucosal striations)',
    organ: 'colon',
    partOfOrgan: 'wall',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '결장 점막층의 밝은 흰색 선조. IBD·림프관확장증·단백소실성장병증(PLE)에서 관찰되며, 소장에 비해 빈도는 낮습니다.',
    positiveResultText: 'Hyperechoic mucosal striations present in colon; lacteal dilation — IBD or lymphangiectasia suspected',
    positiveResultTextKo: '결장 고에코 점막 선조 관찰; 유미관 확장 — IBD 또는 림프관확장증 감별 필요',
    positiveOwnerResultTextKo: '결장 점막에서 밝은 흰 줄 무늬가 관찰됩니다. 장 점막의 염증 또는 림프관 확장과 관련될 수 있습니다.',
    negativeResultText: 'No hyperechoic mucosal striations in colon',
    negativeResultTextKo: '결장 고에코 점막 선조 없음',
    negativeOwnerResultTextKo: '결장 점막에서 특별한 이상 줄무늬는 관찰되지 않습니다.',
    positiveIsAbnormal: true,
  },
];
