import { UltrasoundTestItem } from '../types';

export const duodenumTests: UltrasoundTestItem[] = [
  {
    testID: 'duodenum_wall_thickness',
    testName: 'Duodenum Wall Thickness',
    testNameKo: '십이지장 벽 두께',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Dog: 3.0-6.0mm, Cat: 2.0-2.5mm. Thickest part of small intestine.',
    normalRange: { dog: { max: 6 }, cat: { max: 2.5 } },
    ranges: [
      { min: 0, max: 6, resultText: 'Duodenal wall thickness within normal limits', resultTextKo: '십이지장 벽 두께 정상 범위', isAbnormal: false },
      { min: 6, max: 8, resultText: 'Mild duodenal wall thickening; enteritis suspected', resultTextKo: '경미한 십이지장 벽 비후; 장염 의심', isAbnormal: true, severity: 'mild' },
      { min: 8, max: null, resultText: 'Marked duodenal wall thickening; infiltrative disease suspected', resultTextKo: '현저한 십이지장 벽 비후; 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'duodenum_wall_layering',
    testName: 'Duodenum Wall Layering',
    testNameKo: '십이지장 벽 층구조',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      { value: 'preserved', label: 'Normal 5-layer preserved', labelKo: '정상 5층 구조 보존', resultText: 'Duodenal wall 5-layer structure preserved', resultTextKo: '십이지장 벽 5층 구조 보존', isAbnormal: false },
      { value: 'indistinct', label: 'Indistinct layers', labelKo: '층구조 불명확', resultText: 'Duodenal wall layering indistinct; severe enteritis suspected', resultTextKo: '십이지장 벽 층구조 불명확; 중증 장염 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'duodenum_special_findings',
    testName: 'Special Findings',
    testNameKo: '특이 사항',
    organ: 'duodenum',
    partOfOrgan: 'general',
    testType: 'multiselect',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'Duodenal findings: {values}',
    resultTemplateKo: '십이지장 특이 소견: {values}',
    options: [
      { value: 'peyers_patches', label: 'Peyer\'s patches (normal)', labelKo: '파이어판 (정상)', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'corrugation', label: 'Corrugation (folding)', labelKo: '주름 형성 (Corrugation)', resultText: 'Duodenal corrugation observed; peritonitis or pancreatitis suspected', resultTextKo: '십이지장 주름 형성(Corrugation) 관찰됨; 복막염 또는 췌장염 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'foreign_body', label: 'Foreign body suspected', labelKo: '이물 의심', resultText: 'Possible foreign body in duodenum', resultTextKo: '십이지장 내 이물 가능성', isAbnormal: true, severity: 'severe' },
    ],
  },
];
