import { UltrasoundTestItem } from '../types';

export const duodenumTests: UltrasoundTestItem[] = [
  {
    testID: 'duodenum_wall_thickness',
    testName: 'Duodenum Wall Thickness',
    testNameKo: '십이지장 벽 두께',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Dog: 3.0-6.0mm, Cat: 2.0-2.5mm. Thickest part of small intestine.',
    normalRange: { dog: { max: 6 }, cat: { max: 2.5 } },
    ranges: [
      { min: 0, max: 6, resultText: 'Duodenal wall thickness within normal limits', resultTextKo: '십이지장 벽 두께 정상 범위', isAbnormal: false },
      { min: 6, max: 8, resultText: 'Mild duodenal wall thickening; enteritis suspected', resultTextKo: '경미한 십이지장 벽 비후; 장염 의심', isAbnormal: true, severity: 'mild' },
      { min: 8, max: null, resultText: 'Marked duodenal wall thickening; infiltrative disease suspected', resultTextKo: '현저한 십이지장 벽 비후; 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
    dogRanges: [
      { min: 0, max: 6, resultText: 'Duodenal wall thickness within normal limits', resultTextKo: '십이지장 벽 두께 정상 범위 (개: ≤6mm)', isAbnormal: false },
      { min: 6, max: 8, resultText: 'Mild duodenal wall thickening; enteritis suspected', resultTextKo: '경미한 십이지장 벽 비후; 장염 의심', isAbnormal: true, severity: 'mild' },
      { min: 8, max: null, resultText: 'Marked duodenal wall thickening; infiltrative disease suspected', resultTextKo: '현저한 십이지장 벽 비후; 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
    catRanges: [
      { min: 0, max: 2.5, resultText: 'Duodenal wall thickness within normal limits', resultTextKo: '십이지장 벽 두께 정상 범위 (고양이: ≤2.5mm)', isAbnormal: false },
      { min: 2.5, max: 4, resultText: 'Mild duodenal wall thickening; enteritis suspected', resultTextKo: '경미한 십이지장 벽 비후(>2.5mm); 장염 의심', isAbnormal: true, severity: 'mild' },
      { min: 4, max: null, resultText: 'Marked duodenal wall thickening; infiltrative disease suspected', resultTextKo: '현저한 십이지장 벽 비후(>4mm); 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'duodenum_wall_layering',
    testName: 'Duodenum Wall Layering',
    testNameKo: '십이지장 벽 층구조',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      { value: 'preserved', label: 'Normal 5-layer preserved', labelKo: '정상 5층 구조 보존', resultText: 'Duodenal wall 5-layer structure preserved', resultTextKo: '십이지장 벽 5층 구조 보존', isAbnormal: false },
      { value: 'indistinct', label: 'Indistinct layers', labelKo: '층구조 불명확', resultText: 'Duodenal wall layering indistinct; severe enteritis suspected', resultTextKo: '십이지장 벽 층구조 불명확; 중증 장염 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'duodenum_special_findings',
    testName: 'Special Findings',
    testNameKo: '특이 사항',
    organ: 'duodenum',
    partOfOrgan: 'general',
    testType: 'multiselect',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'Duodenal findings: {values}',
    resultTemplateKo: '십이지장 특이 소견: {values}',
    options: [
      { value: 'peyers_patches', label: 'Peyer\'s patches (normal)', labelKo: '파이어판 (정상)', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'corrugation', label: 'Corrugation (folding)', labelKo: '주름 형성 (Corrugation)', resultText: 'Duodenal corrugation observed; peritonitis or pancreatitis suspected', resultTextKo: '십이지장 주름 형성(Corrugation) 관찰됨; 복막염 또는 췌장염 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'foreign_body', label: 'Foreign body suspected', labelKo: '이물 의심', resultText: 'Possible foreign body in duodenum', resultTextKo: '십이지장 내 이물 가능성', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'duodenum_muscularis_severity',
    testName: 'Muscularis Propria Hypertrophy',
    testNameKo: '십이지장 근육층(muscularis propria) 비후',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '근육층 비후는 IBD, 소세포 림프종, 만성 장염 등에서 관찰됩니다.',
    options: [
      { value: 'normal', label: 'Normal muscularis', labelKo: '근육층 정상', resultText: 'Muscularis propria normal thickness', resultTextKo: '십이지장 근육층 두께 정상', isAbnormal: false },
      { value: 'mild', label: 'Mild hypertrophy', labelKo: '경도 비후', resultText: 'Mild duodenal muscularis hypertrophy; IBD or chronic enteritis suspected', resultTextKo: '경도 십이지장 근육층 비후; IBD 또는 만성 장염 의심', isAbnormal: true, severity: 'mild' },
      { value: 'moderate', label: 'Moderate hypertrophy', labelKo: '중등도 비후', resultText: 'Moderate duodenal muscularis hypertrophy; IBD or lymphoma suspected', resultTextKo: '중등도 십이지장 근육층 비후; IBD 또는 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'severe', label: 'Severe hypertrophy', labelKo: '심한 비후', resultText: 'Severe duodenal muscularis hypertrophy; lymphoma or infiltrative neoplasia strongly suspected', resultTextKo: '심한 십이지장 근육층 비후; 림프종 또는 침윤성 종양 강력 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'duodenum_layer_predominance',
    testName: 'Wall Layer Predominance',
    testNameKo: '십이지장 비후 우세층',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'duodenum_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '점막·점막하층 우세 → IBD, 근육층 우세 → 소세포 림프종, 전층 균등 → 대세포 림프종/선암종',
    options: [
      { value: 'mucosal_submucosal', label: 'Mucosal / submucosal predominance', labelKo: '점막·점막하층 우세', resultText: 'Duodenal wall thickening predominantly mucosal/submucosal; IBD pattern', resultTextKo: '십이지장 점막·점막하층 우세 비후; IBD 패턴', isAbnormal: true, severity: 'mild' },
      { value: 'muscularis', label: 'Muscularis predominance', labelKo: '근육층 우세', resultText: 'Duodenal wall thickening predominantly muscularis; small cell lymphoma suspected', resultTextKo: '십이지장 근육층 우세 비후; 소세포 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'transmural', label: 'Transmural / uniform', labelKo: '전층 균등 비후', resultText: 'Duodenal transmural uniform thickening; large cell lymphoma or adenocarcinoma suspected', resultTextKo: '십이지장 전층 균등 비후; 대세포 림프종 또는 선암종 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'duodenum_muscularis_thickness',
    testName: 'Muscularis Propria Thickness (measured)',
    testNameKo: '십이지장 근육층 두께 (측정값)',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'duodenum_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '선택 입력. 근육층만 분리 측정 시 기록 (정상 <2mm).',
    normalRange: { dog: { max: 2 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 2, resultText: 'Muscularis thickness within normal limits', resultTextKo: '십이지장 근육층 두께 정상 범위', isAbnormal: false },
      { min: 2, max: null, resultText: 'Duodenal muscularis thickening >2mm', resultTextKo: '십이지장 근육층 비후 >2mm', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'duodenum_mucosal_striations',
    testName: 'Hyperechoic Mucosal Striations',
    testNameKo: '고에코 점막 선조 (Hyperechoic mucosal striations)',
    organ: 'duodenum',
    partOfOrgan: 'wall',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '점막층의 밝은 흰색 선조. 유미관(lacteal) 확장을 의미하며 IBD·림프관확장증·PLE에서 관찰됩니다.',
    positiveResultText: 'Hyperechoic mucosal striations present in duodenum; lacteal dilation — IBD, lymphangiectasia, or PLE suspected',
    positiveResultTextKo: '십이지장 고에코 점막 선조 관찰; 유미관 확장 — IBD, 림프관확장증, 단백소실성장병증(PLE) 감별 필요',
    positiveOwnerResultTextKo: '십이지장 점막에서 밝은 흰 줄 무늬가 관찰됩니다. 장 점막의 림프관 확장 또는 염증성 장 질환과 관련될 수 있습니다.',
    negativeResultText: 'No hyperechoic mucosal striations in duodenum',
    negativeResultTextKo: '십이지장 고에코 점막 선조 없음',
    negativeOwnerResultTextKo: '특별한 이상 줄무늬는 관찰되지 않습니다.',
    positiveIsAbnormal: true,
  },
];
