import { UltrasoundTestItem } from '../types';

export const freeFluidTests: UltrasoundTestItem[] = [
  {
    testID: 'free_fluid_presence',
    testName: 'Abdominal Free Fluid',
    testNameKo: '복강 내 유리액',
    organ: 'free_fluid',
    partOfOrgan: 'general',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['free_fluid_amount', 'free_fluid_echogenicity', 'free_fluid_location'],
    positiveResultText: 'Abdominal free fluid identified',
    positiveResultTextKo: '복강 내 유리액 관찰',
    positiveOwnerResultTextKo: '복강 내부에 비정상적인 물(복수 등)이 고여 있는 것이 확인됩니다.',
    negativeResultText: 'No abdominal free fluid',
    negativeResultTextKo: '복강 내 유리액 없음',
    negativeOwnerResultTextKo: '복강 내부에 고인 물(복수)은 관찰되지 않습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'free_fluid_amount',
    testName: 'Free Fluid Amount',
    testNameKo: '유리액 양',
    organ: 'free_fluid',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      {
        value: 'trace',
        label: 'Trace (focal pocket)',
        labelKo: '미량 (국소적)',
        resultText: 'Trace amount of abdominal free fluid',
        resultTextKo: '소량의 복강 내 유리액 관찰',
        ownerResultTextKo: '아주 적은 양의 물이 특정 부위에 고여 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'mild',
        label: 'Mild',
        labelKo: '경미',
        resultText: 'Mild abdominal free fluid',
        resultTextKo: '경미한 복강 내 유리액',
        ownerResultTextKo: '약간의 복수가 관찰됩니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'moderate',
        label: 'Moderate',
        labelKo: '중등도',
        resultText: 'Moderate abdominal free fluid (ascites)',
        resultTextKo: '중등도의 복강 내 유리액 (복수)',
        ownerResultTextKo: '복수가 어느 정도 고여 있어 원인 파악이 필요합니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'marked',
        label: 'Markedly enlarged',
        labelKo: '다량',
        resultText: 'Marked abdominal free fluid; portal hypertension, right-sided heart failure, hypoalbuminemia, or haemoabdomen suspected',
        resultTextKo: '다량의 복강 내 유리액; 문맥 고혈압, 우심부전, 저알부민혈증 또는 혈복강 의심',
        ownerResultTextKo: '매우 많은 양의 복수가 차 있습니다. 심장병, 간질환 또는 출혈 등 심각한 원인을 찾아야 합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'free_fluid_echogenicity',
    testName: 'Free Fluid Echogenicity',
    testNameKo: '유리액 에코 음영',
    organ: 'free_fluid',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      {
        value: 'anechoic',
        label: 'Anechoic (transudate)',
        labelKo: '무에코 (여출액)',
        resultText: 'Anechoic abdominal free fluid consistent with transudate; hypoalbuminemia or portal hypertension suspected',
        resultTextKo: '무에코 복강 내 유리액; 여출액에 합당; 저알부민혈증 또는 문맥 고혈압 의심',
        ownerResultTextKo: '고여 있는 물이 깨끗하고 맑게 보입니다. 단백질 부족이나 순환 장애일 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'echogenic',
        label: 'Echogenic (exudate/haemorrhage)',
        labelKo: '에코성 (삼출액/출혈)',
        resultText: 'Echogenic abdominal free fluid consistent with exudate or haemorrhage; haemoabdomen or septic peritonitis suspected',
        resultTextKo: '에코성 복강 내 유리액; 삼출액 또는 출혈에 합당; 혈복강 또는 패혈성 복막염 의심',
        ownerResultTextKo: '고여 있는 물이 탁하거나 입자가 보입니다. 염증(삼출액)이나 피(출혈)가 섞여 있을 가능성이 큽니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'mixed',
        label: 'Mixed / Fibrinous',
        labelKo: '혼합/섬유소성',
        resultText: 'Mixed echogenic abdominal free fluid with fibrin strands; septic peritonitis or chylous effusion suspected',
        resultTextKo: '섬유소 가닥을 동반한 혼합 에코성 복강 내 유리액; 패혈성 복막염 또는 유미성 삼출 의심',
        ownerResultTextKo: '고여 있는 물 내부에 찌꺼기가 섞여 있습니다. 심한 염증이나 감염성 복막염 등이 의심됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
];
