import { UltrasoundTestItem } from '../types';

export const gallbladderTests: UltrasoundTestItem[] = [
  {
    testID: 'organ_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'surgical_removal', label: 'Surgical removal', labelKo: '수술적 적출', resultText: 'Previously removed surgically', resultTextKo: '기존 수술을 통해 적출됨', isAbnormal: true },
      { value: 'congenital_absence', label: 'Congenital absence / Agenesis', labelKo: '선천적 결손', resultText: 'Congenital absence / agenesis', resultTextKo: '선천적 결손/미발달', isAbnormal: true },
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
      { value: 'ectopic', label: 'Ectopic location', labelKo: '이소성 위치', resultText: 'Ectopic location suspected', resultTextKo: '이소성 위치 의심', isAbnormal: true },
      { value: 'contracted_gb', label: 'Contracted GB (chronic cholecystitis,fibrosis, post-prandial)', labelKo: '담낭 위축 (만성 담낭염, 섬유화, 식후 등)', resultText: 'Contracted gallbladder', resultTextKo: '위축된 담낭', isAbnormal: true },
    ],
  },
  {
    testID: 'gb_wall_thickness',
    testName: 'Gallbladder Wall Thickness',
    testNameKo: '담낭벽 두께',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['gb_content'],
    normalRange: {
      dog: { max: 3 },
      cat: { max: 1 },
    },
    ranges: [
      {
        min: 0,
        max: 3,
        resultText: 'Gallbladder wall thickness within normal limits',
        resultTextKo: '담낭벽 두께 정상 범위',
        ownerResultTextKo: '담낭 벽의 두께가 정상입니다.',
        isAbnormal: false,
      },
      {
        min: 3,
        max: 5,
        resultText: 'Mild gallbladder wall thickening; cholecystitis or hypoalbuminemia suspected',
        resultTextKo: '경미한 담낭벽 비후; 담낭염 또는 저알부민혈증 의심',
        ownerResultTextKo: '담낭 벽이 약간 두꺼워져 있습니다. 담낭염이나 혈액 내 단백질 부족이 원인일 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 5,
        max: null,
        resultText: 'Marked gallbladder wall thickening (>5mm); cholecystitis, neoplasia, or oedema suspected',
        resultTextKo: '현저한 담낭벽 비후(>5mm); 담낭염, 종양 또는 부종 의심',
        ownerResultTextKo: '담낭 벽이 매우 두껍게 부어 있습니다. 심한 담낭염이나 부종 등이 의심됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'gb_content',
    testName: 'Gallbladder Contents',
    testNameKo: '담낭 내용물',
    organ: 'gallbladder',
    partOfOrgan: 'lumen',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    resultTemplate: 'Gallbladder contents: {values}',
    resultTemplateKo: '담낭 내용물: {values}',
    resultTemplateOwnerKo: '담낭(쓸개) 내부에 다음 내용물들이 관찰됩니다: {values}',
    options: [
      {
        value: 'anechoic',
        label: 'Anechoic (normal bile)',
        labelKo: '무에코 (정상 담즙)',
        resultText: 'anechoic bile (normal)',
        resultTextKo: '무에코 담즙 (정상)',
        ownerResultTextKo: '깨끗한 담즙 (정상)',
        isAbnormal: false,
      },
      {
        value: 'sludge',
        label: 'Biliary sludge',
        labelKo: '담즙 슬러지',
        resultText: 'biliary sludge',
        resultTextKo: '담즙 슬러지',
        ownerResultTextKo: '담즙 찌꺼기(슬러지)',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'cholelith',
        label: 'Cholelith (gallstone)',
        labelKo: '담석',
        resultText: 'cholelith with acoustic shadowing',
        resultTextKo: '음향 음영을 동반한 담석',
        ownerResultTextKo: '담석(쓸개 돌)',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'mucocele',
        label: 'Mucocele (stellate/kiwi pattern)',
        labelKo: '담낭 점액낭종 (별모양/키위 패턴)',
        resultText: 'gallbladder mucocele with stellate echogenic content',
        resultTextKo: '별모양의 고에코 내용물을 동반한 담낭 점액낭종',
        ownerResultTextKo: '담낭 점액낭종(담즙이 끈적하게 굳는 질환)',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'mass',
        label: 'Intraluminal mass',
        labelKo: '내강 내 종괴',
        resultText: 'intraluminal gallbladder mass; neoplasia suspected',
        resultTextKo: '담낭 내강 내 종괴; 종양 의심',
        ownerResultTextKo: '담낭 내 혹(덩어리)',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'gb_rupture_risk',
    testName: 'Gallbladder Rupture Risk Signs',
    testNameKo: '담낭 파열 위험 징후',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: 'Striated wall, pericholecystic fluid, or wall discontinuity suggest impending rupture',
    positiveResultText: 'Gallbladder rupture risk signs present (striated wall / pericholecystic fluid); emergency evaluation required',
    positiveResultTextKo: '담낭 파열 위험 징후 관찰 (줄무늬 담낭벽 / 담낭 주변 삼출); 응급 평가 필요',
    positiveOwnerResultTextKo: '담낭 파열 위험 징후(담낭벽 변화 또는 주변 삼출액)가 관찰됩니다. 즉각적인 응급 처치가 필요합니다.',
    negativeResultText: 'No gallbladder rupture risk signs',
    negativeResultTextKo: '담낭 파열 위험 징후 없음',
    negativeOwnerResultTextKo: '담낭 파열을 시사하는 위험 징후는 없습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'cbd_diameter',
    testName: 'Common Bile Duct Diameter',
    testNameKo: '총담관 직경',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'gallbladder_status', triggerValues: ['abnormal', 'absent'] },
    normalRange: {
      dog: { max: 3 },
      cat: { max: 4 },
    },
    ranges: [
      {
        min: 0,
        max: 3,
        resultText: 'Common bile duct within normal limits',
        resultTextKo: '총담관 직경 정상',
        ownerResultTextKo: '담즙이 내려가는 통로의 크기가 정상입니다.',
        isAbnormal: false,
      },
      {
        min: 3,
        max: 5,
        resultText: 'Mild common bile duct dilation; biliary obstruction or cholangitis suspected',
        resultTextKo: '경미한 총담관 확장; 담도 폐쇄 또는 담관염 의심',
        ownerResultTextKo: '담즙이 내려가는 통로가 약간 넓어져 있습니다. 담관염이나 경미한 폐쇄 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 5,
        max: null,
        resultText: 'Marked common bile duct dilation (>5mm); biliary obstruction suspected',
        resultTextKo: '현저한 총담관 확장(>5mm); 담도 폐쇄 의심',
        ownerResultTextKo: '담즙이 내려가는 주요 통로가 막혀서 확장되어 있습니다. 즉각적인 처치가 필요할 수 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
];
