import { UltrasoundTestItem } from '../types';

export const gallbladderTests: UltrasoundTestItem[] = [
  // ── Absence reason ───────────────────────────────────────────────────
  {
    testID: 'organ_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'surgical_removal', label: 'Surgical removal', labelKo: '수술적 적출', resultText: 'Previously removed surgically', resultTextKo: '기존 수술을 통해 적출됨', isAbnormal: true },
      { value: 'congenital_absence', label: 'Congenital absence / Agenesis', labelKo: '선천적 결손', resultText: 'Congenital absence / agenesis', resultTextKo: '선천적 결손/미발달', isAbnormal: true },
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
      { value: 'ectopic', label: 'Ectopic location', labelKo: '이소성 위치', resultText: 'Ectopic location suspected', resultTextKo: '이소성 위치 의심', isAbnormal: true },
      { value: 'contracted_gb', label: 'Contracted GB (chronic cholecystitis, fibrosis, post-prandial)', labelKo: '담낭 위축 (만성 담낭염, 섬유화, 식후 등)', resultText: 'Contracted gallbladder', resultTextKo: '위축된 담낭', isAbnormal: true },
    ],
  },

  // ── Gallbladder wall ──────────────────────────────────────────────────
  {
    testID: 'gb_wall_thickness',
    testName: 'Gallbladder Wall Thickness',
    testNameKo: '담낭벽 두께',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['gb_content'],
    normalRange: { dog: { max: 3 }, cat: { max: 1 } },
    ranges: [
      {
        min: 0, max: 3,
        resultText: 'Gallbladder wall thickness within normal limits',
        resultTextKo: '담낭벽 두께 정상 범위',
        ownerResultTextKo: '담낭 벽의 두께가 정상입니다.',
        isAbnormal: false,
      },
      {
        min: 3, max: 5,
        resultText: 'Mild gallbladder wall thickening; cholecystitis or hypoalbuminemia suspected',
        resultTextKo: '경미한 담낭벽 비후; 담낭염 또는 저알부민혈증 의심',
        ownerResultTextKo: '담낭 벽이 약간 두꺼워져 있습니다. 담낭염이나 혈액 내 단백질 부족이 원인일 수 있습니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 5, max: null,
        resultText: 'Marked gallbladder wall thickening (>5mm); cholecystitis, neoplasia, or oedema suspected',
        resultTextKo: '현저한 담낭벽 비후(>5mm); 담낭염, 종양 또는 부종 의심',
        ownerResultTextKo: '담낭 벽이 매우 두껍게 부어 있습니다. 심한 담낭염이나 부종 등이 의심됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
    ],
    dogRanges: [
      { min: 0, max: 3, resultText: 'Gallbladder wall thickness within normal limits', resultTextKo: '담낭벽 두께 정상 범위 (개: ≤3mm)', isAbnormal: false },
      { min: 3, max: 5, resultText: 'Mild gallbladder wall thickening; cholecystitis or hypoalbuminemia suspected', resultTextKo: '경미한 담낭벽 비후(>3mm); 담낭염 또는 저알부민혈증 의심', isAbnormal: true, severity: 'mild' },
      { min: 5, max: null, resultText: 'Marked gallbladder wall thickening (>5mm)', resultTextKo: '현저한 담낭벽 비후(>5mm); 담낭염, 종양 또는 부종 의심', isAbnormal: true, severity: 'moderate' },
    ],
    catRanges: [
      { min: 0, max: 1, resultText: 'Gallbladder wall thickness within normal limits', resultTextKo: '담낭벽 두께 정상 범위 (고양이: ≤1mm)', isAbnormal: false },
      { min: 1, max: 3, resultText: 'Mild gallbladder wall thickening; cholecystitis suspected', resultTextKo: '경미한 담낭벽 비후(>1mm); 담낭염 의심', isAbnormal: true, severity: 'mild' },
      { min: 3, max: null, resultText: 'Marked gallbladder wall thickening (>3mm); cholecystitis or neoplasia suspected', resultTextKo: '현저한 담낭벽 비후(>3mm); 담낭염 또는 종양 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },

  // ── Gallbladder contents (sludge / stones only) ───────────────────────
  {
    testID: 'gb_content',
    testName: 'Gallbladder Contents',
    testNameKo: '담낭 내용물',
    organ: 'gallbladder',
    partOfOrgan: 'lumen',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: '점액낭종(Mucocele) 및 종괴(Mass)는 아래 전용 항목에서 별도 평가합니다.',
    resultTemplate: 'Gallbladder contents: {values}',
    resultTemplateKo: '담낭 내용물: {values}',
    resultTemplateOwnerKo: '담낭 내부에 다음이 관찰됩니다: {values}',
    options: [
      {
        value: 'anechoic',
        label: 'Anechoic (normal bile)',
        labelKo: '무에코 (정상 담즙)',
        resultText: 'anechoic bile (normal)',
        resultTextKo: '무에코 담즙 (정상)',
        ownerResultTextKo: '깨끗한 담즙 (정상)',
        isAbnormal: false,
      },
      {
        value: 'sludge',
        label: 'Biliary sludge',
        labelKo: '담즙 슬러지',
        resultText: 'biliary sludge',
        resultTextKo: '담즙 슬러지',
        ownerResultTextKo: '담즙 찌꺼기(슬러지)',
        isAbnormal: true, severity: 'mild',
      },
      {
        value: 'cholelith',
        label: 'Cholelith (gallstone)',
        labelKo: '담석',
        resultText: 'cholelith with acoustic shadowing',
        resultTextKo: '음향 음영을 동반한 담석',
        ownerResultTextKo: '담석(쓸개 돌)',
        isAbnormal: true, severity: 'moderate',
      },
    ],
  },

  // ── GB Mucocele ────────────────────────────────────────────────────────
  {
    testID: 'gb_mucocele_presence',
    testName: 'Gallbladder Mucocele',
    testNameKo: '담낭 점액낭종 (Mucocele)',
    organ: 'gallbladder',
    partOfOrgan: 'lumen',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '담낭 내 점액 과분비로 담즙이 끈적하게 굳는 질환. 개에서 호발. 파열 위험 있음.',
    options: [
      {
        value: 'absent',
        label: 'No mucocele',
        labelKo: '점액낭종 없음',
        resultText: 'No gallbladder mucocele',
        resultTextKo: '담낭 점액낭종 관찰되지 않음',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Mucocele present',
        labelKo: '점액낭종 있음',
        resultText: 'Gallbladder mucocele identified; surgical evaluation recommended',
        resultTextKo: '담낭 점액낭종 확인됨; 외과적 평가 권장',
        ownerResultTextKo: '담낭 점액낭종(담즙이 끈적하게 굳는 질환)이 관찰됩니다. 수술적 처치가 필요할 수 있습니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'gb_mucocele_type',
    testName: 'Mucocele Type / Pattern',
    testNameKo: '점액낭종 유형',
    organ: 'gallbladder',
    partOfOrgan: 'lumen',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gb_mucocele_presence', triggerValues: ['present'] },
    note: 'Type I(초기/중력 의존성) → 파열 위험 낮음. Type II(전형 별모양) → 수술 권장. Type III(완전 충전) → 파열 위험 높음. 파열 여부는 아래 파열 징후 항목에서 평가.',
    options: [
      {
        value: 'type_I_gravity',
        label: 'Type I — Gravity-dependent (mobile, layering)',
        labelKo: 'Type I — 중력 의존성 (이동성, 층 형성)',
        resultText: 'Developing mucocele (Type I) — gravity-dependent echogenic bile; mobile with position change; monitor closely',
        resultTextKo: '초기 점액낭종 (Type I) — 중력 의존성 고에코 담즙; 체위 변경 시 이동성; 면밀한 추적 필요',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'type_II_stellate',
        label: 'Type II — Stellate / Kiwi pattern (immobile, non-gravity-dependent)',
        labelKo: 'Type II — 별모양 / 키위 패턴 (고정, 중력 비의존성)',
        resultText: 'Classic mucocele (Type II) — immobile stellate (kiwi) echogenic pattern; surgical evaluation recommended',
        resultTextKo: '전형적 점액낭종 (Type II) — 고정된 별모양(키위 패턴) 고에코 내용물; 외과적 평가 권장',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'type_III_complete',
        label: 'Type III — Complete filling (no anechoic bile visible)',
        labelKo: 'Type III — 완전 충전 (무에코 담즙 소실)',
        resultText: 'Advanced mucocele (Type III) — complete GB filling with echogenic material; high rupture risk; emergency surgical evaluation',
        resultTextKo: '진행성 점액낭종 (Type III) — 전체 담낭 고에코 충전; 파열 위험 높음; 응급 외과 평가',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },

  // ── GB Mass / Tumor ────────────────────────────────────────────────────
  {
    testID: 'gb_mass_presence',
    testName: 'Gallbladder Mass / Neoplasia',
    testNameKo: '담낭 종괴 / 종양',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '폴립, 선암종, 점액낭선암종, 평활근육종 등 포함. 담석과의 감별: 담석은 위치 이동, 음향 음영을 동반.',
    options: [
      {
        value: 'absent',
        label: 'No gallbladder mass',
        labelKo: '담낭 종괴 없음',
        resultText: 'No gallbladder mass or neoplasia identified',
        resultTextKo: '담낭 내 종괴/종양 관찰되지 않음',
        isAbnormal: false,
      },
      {
        value: 'polyp',
        label: 'Polyp (pedunculated, ≤10mm)',
        labelKo: '폴립 (유경성, ≤10mm)',
        resultText: 'Gallbladder polyp identified; likely benign; monitoring recommended',
        resultTextKo: '담낭 폴립 관찰; 양성 가능성 높음; 추적 관찰 권장',
        ownerResultTextKo: '담낭에 작은 폴립(혹)이 관찰됩니다. 대부분 양성이지만 정기적인 추적 관찰이 필요합니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        value: 'mass_present',
        label: 'Mural / intraluminal mass (>10mm or suspicious)',
        labelKo: '벽 내 / 내강 종괴 (>10mm 또는 의심)',
        resultText: 'Gallbladder mural or intraluminal mass; neoplasia suspected; see details',
        resultTextKo: '담낭 벽 내 또는 내강 종괴; 종양 의심; 세부 항목 참조',
        ownerResultTextKo: '담낭에서 종괴(혹)가 관찰됩니다. 종양 가능성을 배제하기 위한 추가 검사가 필요합니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'gb_mass_location',
    testName: 'Gallbladder Mass Location',
    testNameKo: '담낭 종괴 위치',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gb_mass_presence', triggerValues: ['polyp', 'mass_present'] },
    resultTemplate: 'Gallbladder mass location: {values}',
    resultTemplateKo: '담낭 종괴 위치: {values}',
    options: [
      { value: 'fundus', label: 'Fundus', labelKo: '담낭 저부', resultText: '', resultTextKo: '', isAbnormal: true, severity: 'moderate' },
      { value: 'body', label: 'Body', labelKo: '담낭 체부', resultText: '', resultTextKo: '', isAbnormal: true, severity: 'moderate' },
      { value: 'neck_cystic_duct', label: 'Neck / Cystic duct', labelKo: '담낭경 / 담낭관', resultText: '', resultTextKo: '', isAbnormal: true, severity: 'severe' },
      { value: 'mural_infiltrative', label: 'Mural infiltrative (transmural)', labelKo: '벽 침윤성 (전층)', resultText: '', resultTextKo: '', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'gb_mass_size',
    testName: 'Gallbladder Mass Size',
    testNameKo: '담낭 종괴 크기',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gb_mass_presence', triggerValues: ['polyp', 'mass_present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      { min: 0, max: 10, resultText: 'Small gallbladder lesion <10mm; likely benign polyp; monitor every 3–6 months', resultTextKo: '10mm 미만 담낭 병변; 양성 폴립 가능성; 3-6개월마다 추적 권장', isAbnormal: true, severity: 'mild' },
      { min: 10, max: 20, resultText: 'Gallbladder mass 10–20mm; neoplasia suspected; cytology or biopsy recommended', resultTextKo: '10-20mm 담낭 종괴; 종양 의심; 세포검사 또는 생검 권장', isAbnormal: true, severity: 'moderate' },
      { min: 20, max: null, resultText: 'Large gallbladder mass >20mm; malignant neoplasia likely; surgical evaluation required', resultTextKo: '20mm 초과 담낭 종괴; 악성 종양 가능성 높음; 외과적 평가 필요', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'gb_mass_echogenicity',
    testName: 'Gallbladder Mass Echogenicity',
    testNameKo: '담낭 종괴 에코 음영',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gb_mass_presence', triggerValues: ['polyp', 'mass_present'] },
    options: [
      { value: 'hyperechoic', label: 'Hyperechoic', labelKo: '고에코', resultText: 'Hyperechoic GB mass; cholesterol polyp or adenoma suspected', resultTextKo: '고에코 담낭 종괴; 콜레스테롤 폴립 또는 선종 의심', isAbnormal: true, severity: 'mild' },
      { value: 'hypoechoic', label: 'Hypoechoic', labelKo: '저에코', resultText: 'Hypoechoic GB mass; carcinoma or lymphoma suspected', resultTextKo: '저에코 담낭 종괴; 담낭암 또는 림프종 의심', isAbnormal: true, severity: 'severe' },
      { value: 'mixed', label: 'Mixed / Heterogeneous', labelKo: '혼합/불균질', resultText: 'Mixed echogenicity GB mass; malignant neoplasia suspected', resultTextKo: '혼합 에코 담낭 종괴; 악성 종양 의심', isAbnormal: true, severity: 'severe' },
    ],
  },

  // ── Rupture risk ──────────────────────────────────────────────────────
  {
    testID: 'gb_rupture_risk',
    testName: 'Gallbladder Rupture Risk Signs',
    testNameKo: '담낭 파열 위험 징후',
    organ: 'gallbladder',
    partOfOrgan: 'wall',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '줄무늬 담낭벽(striated wall), 담낭 주변 삼출(pericholecystic fluid), 벽 불연속(discontinuity) → 파열 임박 가능성',
    positiveResultText: 'Gallbladder rupture risk signs present (striated wall / pericholecystic fluid); emergency evaluation required',
    positiveResultTextKo: '담낭 파열 위험 징후 관찰 (줄무늬 담낭벽 / 담낭 주변 삼출); 응급 평가 필요',
    positiveOwnerResultTextKo: '담낭 파열 위험 징후가 관찰됩니다. 즉각적인 응급 처치가 필요합니다.',
    negativeResultText: 'No gallbladder rupture risk signs',
    negativeResultTextKo: '담낭 파열 위험 징후 없음',
    negativeOwnerResultTextKo: '담낭 파열을 시사하는 위험 징후는 없습니다.',
    positiveIsAbnormal: true,
  },

  // ── Biliary tract — dilation ──────────────────────────────────────────
  {
    testID: 'ihbd_dilation',
    testName: 'Intrahepatic Bile Duct Dilation',
    testNameKo: '간내 담도 확장 (IHBD)',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '간내 담도 확장은 간문부/총담관 폐쇄의 중요 지표. 정상에서는 혈관과 나란한 작은 관은 보이지 않음.',
    options: [
      {
        value: 'absent',
        label: 'None',
        labelKo: '없음',
        resultText: 'No intrahepatic bile duct dilation',
        resultTextKo: '간내 담도 확장 없음',
        isAbnormal: false,
      },
      {
        value: 'mild',
        label: 'Mild — tortuous tubular structures visible',
        labelKo: '경도 — 사행성 관상 구조 관찰',
        resultText: 'Mild intrahepatic bile duct dilation; biliary obstruction or cholangitis suspected',
        resultTextKo: '경도 간내 담도 확장; 담도 폐쇄 또는 담관염 의심',
        ownerResultTextKo: '간 내부의 담즙 통로가 약간 늘어나 있습니다. 담도 폐쇄 가능성이 있습니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'severe',
        label: 'Severe — prominent tortuous dilation ("too many tubes")',
        labelKo: '중증 — 현저한 사행성 확장 ("Too many tubes" sign)',
        resultText: 'Severe intrahepatic bile duct dilation ("too many tubes"); significant biliary obstruction suspected',
        resultTextKo: '중증 간내 담도 확장 ("Too many tubes" sign); 심각한 담도 폐쇄 의심',
        ownerResultTextKo: '간 내부 담즙 통로가 심하게 늘어나 있습니다. 담관이 막혀 있을 가능성이 높습니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'cbd_diameter',
    testName: 'Common Bile Duct (CBD) Diameter',
    testNameKo: '총담관 직경',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '정상범위 — 개: ≤3mm, 고양이: ≤4mm. 담낭 절제 후에는 약간 확장될 수 있음.',
    normalRange: { dog: { max: 3 }, cat: { max: 4 } },
    ranges: [
      { min: 0, max: 4, resultText: 'Common bile duct within normal limits', resultTextKo: '총담관 직경 정상', ownerResultTextKo: '담즙 통로의 크기가 정상입니다.', isAbnormal: false },
      { min: 4, max: 6, resultText: 'Mild CBD dilation; biliary obstruction or cholangitis suspected', resultTextKo: '경미한 총담관 확장; 담도 폐쇄 또는 담관염 의심', ownerResultTextKo: '담즙 통로가 약간 넓어져 있습니다. 담관염이나 경미한 폐쇄 가능성이 있습니다.', isAbnormal: true, severity: 'mild' },
      { min: 6, max: null, resultText: 'Marked CBD dilation (>6mm); significant biliary obstruction suspected', resultTextKo: '현저한 총담관 확장(>6mm); 심각한 담도 폐쇄 의심', ownerResultTextKo: '담즙 통로가 크게 막혀 확장되어 있습니다. 즉각적인 처치가 필요할 수 있습니다.', isAbnormal: true, severity: 'severe' },
    ],
    dogRanges: [
      { min: 0, max: 3, resultText: 'CBD within normal limits', resultTextKo: '총담관 직경 정상 (개: ≤3mm)', isAbnormal: false },
      { min: 3, max: 5, resultText: 'Mild CBD dilation (3–5mm); biliary obstruction or cholangitis suspected', resultTextKo: '경미한 총담관 확장 (3-5mm); 담도 폐쇄 또는 담관염 의심', isAbnormal: true, severity: 'mild' },
      { min: 5, max: null, resultText: 'Marked CBD dilation (>5mm); significant biliary obstruction suspected', resultTextKo: '현저한 총담관 확장 (>5mm); 심각한 담도 폐쇄 의심', isAbnormal: true, severity: 'severe' },
    ],
    catRanges: [
      { min: 0, max: 4, resultText: 'CBD within normal limits', resultTextKo: '총담관 직경 정상 (고양이: ≤4mm)', isAbnormal: false },
      { min: 4, max: 6, resultText: 'Mild CBD dilation (4–6mm); biliary obstruction or cholangitis suspected', resultTextKo: '경미한 총담관 확장 (4-6mm); 담도 폐쇄 또는 담관염 의심', isAbnormal: true, severity: 'mild' },
      { min: 6, max: null, resultText: 'Marked CBD dilation (>6mm); significant biliary obstruction suspected', resultTextKo: '현저한 총담관 확장 (>6mm); 심각한 담도 폐쇄 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'cbd_dilation_cause',
    testName: 'CBD Dilation — Suspected Cause',
    testNameKo: '총담관 확장 — 원인 추정',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOnAny: [
      { testID: 'ihbd_dilation', triggerValues: ['mild', 'severe'] },
      { testID: 'cbd_diameter', triggerValues: [] },
    ],
    note: '담도 확장의 원인을 초음파 소견 기반으로 추정. 최종 진단은 추가 검사(CT, 내시경) 필요.',
    options: [
      { value: 'cholelith_obstruction', label: 'Cholelith obstruction', labelKo: '담석에 의한 폐쇄', resultText: 'CBD dilation — cholelith obstruction suspected', resultTextKo: '총담관 확장 — 담석 폐쇄 의심', isAbnormal: true, severity: 'severe' },
      { value: 'mass_compression', label: 'Mass / neoplasia compression', labelKo: '종괴/종양에 의한 압박', resultText: 'CBD dilation — mass or neoplasia compression suspected', resultTextKo: '총담관 확장 — 종괴 또는 종양 압박 의심', isAbnormal: true, severity: 'severe' },
      { value: 'pancreatitis', label: 'Pancreatitis (peripancreatic compression)', labelKo: '췌장염에 의한 압박', resultText: 'CBD dilation — pancreatitis-related periductal compression suspected', resultTextKo: '총담관 확장 — 췌장염에 의한 주위 압박 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'cholangitis', label: 'Cholangitis / Cholangiohepatitis', labelKo: '담관염 / 담관간염', resultText: 'CBD dilation — cholangitis or cholangiohepatitis suspected', resultTextKo: '총담관 확장 — 담관염 또는 담관간염 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'post_surgical', label: 'Post-cholecystectomy (physiological)', labelKo: '담낭 절제 후 (생리적 확장)', resultText: 'CBD dilation — post-cholecystectomy physiological dilation', resultTextKo: '총담관 확장 — 담낭 절제 후 생리적 확장', isAbnormal: false },
    ],
  },

  // ── Biliary tract — mass / tumor ──────────────────────────────────────
  {
    testID: 'cbd_mass_presence',
    testName: 'Biliary Duct Mass / Cholangiocarcinoma',
    testNameKo: '담도 종괴 / 담관종양',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '담관암(Cholangiocarcinoma), 담도 폴립, 담도 압박 종괴 등을 평가합니다.',
    options: [
      {
        value: 'absent',
        label: 'No biliary duct mass',
        labelKo: '담도 종괴 없음',
        resultText: 'No biliary duct mass or neoplasia identified',
        resultTextKo: '담도 내 종괴/종양 관찰되지 않음',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Biliary duct mass present',
        labelKo: '담도 종괴 있음',
        resultText: 'Biliary duct mass identified; cholangiocarcinoma or biliary neoplasia suspected; see details',
        resultTextKo: '담도 종괴 관찰됨; 담관암 또는 담도 종양 의심; 세부 항목 참조',
        ownerResultTextKo: '담즙 통로(담도)에서 종괴(혹)가 관찰됩니다. 종양 가능성을 확인하기 위한 정밀 검사가 필요합니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'cbd_mass_location',
    testName: 'Biliary Mass Location',
    testNameKo: '담도 종괴 위치',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'cbd_mass_presence', triggerValues: ['present'] },
    options: [
      { value: 'intrahepatic', label: 'Intrahepatic bile duct', labelKo: '간내 담도', resultText: 'Intrahepatic biliary mass; intrahepatic cholangiocarcinoma suspected', resultTextKo: '간내 담도 종괴; 간내 담관암 의심', isAbnormal: true, severity: 'severe' },
      { value: 'hepatic_hilum', label: 'Hepatic hilum (porta hepatis)', labelKo: '간문부', resultText: 'Perihilar biliary mass; hilar cholangiocarcinoma (Klatskin tumour) suspected', resultTextKo: '간문부 담도 종괴; 간문부 담관암(Klatskin 종양) 의심', isAbnormal: true, severity: 'severe' },
      { value: 'cbd', label: 'Common bile duct (extrahepatic)', labelKo: '간외 총담관', resultText: 'Extrahepatic CBD mass; distal cholangiocarcinoma or extrinsic compression suspected', resultTextKo: '간외 총담관 종괴; 원위부 담관암 또는 외부 압박 의심', isAbnormal: true, severity: 'severe' },
      { value: 'cystic_duct', label: 'Cystic duct', labelKo: '담낭관', resultText: 'Cystic duct mass; obstruction and secondary cholecystitis suspected', resultTextKo: '담낭관 종괴; 폐쇄 및 이차성 담낭염 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'cbd_mass_size',
    testName: 'Biliary Mass Size',
    testNameKo: '담도 종괴 크기',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'cbd_mass_presence', triggerValues: ['present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      { min: 0, max: 1, resultText: 'Small biliary mass <1cm; biopsy recommended', resultTextKo: '1cm 미만 소형 담도 종괴; 생검 권장', isAbnormal: true, severity: 'moderate' },
      { min: 1, max: 3, resultText: 'Biliary mass 1–3cm; malignant neoplasia suspected; cytology/biopsy required', resultTextKo: '1-3cm 담도 종괴; 악성 종양 의심; 세포검사/생검 필요', isAbnormal: true, severity: 'severe' },
      { min: 3, max: null, resultText: 'Large biliary mass >3cm; cholangiocarcinoma likely; surgical evaluation required', resultTextKo: '3cm 초과 담도 종괴; 담관암 가능성 높음; 외과적 평가 필요', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'cbd_mass_echogenicity',
    testName: 'Biliary Mass Echogenicity',
    testNameKo: '담도 종괴 에코 음영',
    organ: 'gallbladder',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'cbd_mass_presence', triggerValues: ['present'] },
    options: [
      { value: 'hyperechoic', label: 'Hyperechoic', labelKo: '고에코', resultText: 'Hyperechoic biliary mass; biliary adenoma or inspissated material suspected', resultTextKo: '고에코 담도 종괴; 담도 선종 또는 농축 물질 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'hypoechoic', label: 'Hypoechoic', labelKo: '저에코', resultText: 'Hypoechoic biliary mass; cholangiocarcinoma strongly suspected', resultTextKo: '저에코 담도 종괴; 담관암 강력 의심', isAbnormal: true, severity: 'severe' },
      { value: 'mixed', label: 'Mixed / Heterogeneous', labelKo: '혼합/불균질', resultText: 'Mixed echogenicity biliary mass; malignant neoplasia suspected', resultTextKo: '혼합 에코 담도 종괴; 악성 종양 의심', isAbnormal: true, severity: 'severe' },
      { value: 'isoechoic', label: 'Isoechoic (subtle)', labelKo: '등에코 (경계 불명확)', resultText: 'Isoechoic biliary mass — subtle finding; CT or MRCP recommended for confirmation', resultTextKo: '등에코 담도 종괴 — 미세 소견; CT 또는 MRCP 확진 권장', isAbnormal: true, severity: 'severe' },
    ],
  },
];
