import { UltrasoundTestItem } from '../types';

export const giTractTests: UltrasoundTestItem[] = [
  {
    testID: 'gi_tract_general_notes',
    testName: 'General GI Notes',
    testNameKo: '위장관 전반 특이사항',
    organ: 'gi_tract',
    partOfOrgan: 'general',
    testType: 'multiselect',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'GI general findings: {values}',
    resultTemplateKo: '위장관 전반 소견: {values}',
    options: [
      { value: 'no_specific', label: 'No specific findings', labelKo: '특이 소견 없음', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'free_fluid', label: 'Peritoneal fluid (localized)', labelKo: '국소적 복강 유리액', resultText: 'Localized peritoneal fluid around GI segments', resultTextKo: '위장관 주변 국소적 복강 유리액', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'gi_foreign_body',
    testName: 'GI Foreign Body / Obstruction',
    testNameKo: '위장관 이물/폐쇄',
    organ: 'gi_tract',
    partOfOrgan: 'lumen',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    positiveResultText: 'Intraluminal foreign body or mechanical obstruction identified; corrugation pattern or proximal dilation present',
    positiveResultTextKo: '위장관 내강 이물 또는 기계적 폐쇄 관찰; 주름 패턴 또는 근위부 확장 동반',
    positiveOwnerResultTextKo: '위장관 내부에서 이물질(먹어서는 안 되는 물건)이나 장이 막힌 소견이 관찰됩니다.',
    negativeResultText: 'No GI foreign body or obstruction identified',
    negativeResultTextKo: '위장관 이물/폐쇄 없음',
    negativeOwnerResultTextKo: '위장관 내부에서 특별한 이물질이나 막힌 곳은 보이지 않습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'gi_fb_location',
    testName: 'GI Foreign Body Location',
    testNameKo: '위장관 이물 위치',
    organ: 'gi_tract',
    partOfOrgan: 'lumen',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gi_foreign_body', triggerValues: ['true'] },
    resultTemplate: 'GI foreign body location(s): {values}',
    resultTemplateKo: '위장관 이물 위치: {values}',
    resultTemplateOwnerKo: '다음 부위에서 이물질이 확인됩니다: {values}',
    options: [
      {
        value: 'stomach',
        label: 'Stomach',
        labelKo: '위',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'duodenum',
        label: 'Duodenum',
        labelKo: '십이지장',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'jejunum_ileum',
        label: 'Jejunum / Ileum',
        labelKo: '공장/회장',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'colon',
        label: 'Colon',
        labelKo: '결장',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'moderate',
      },
    ],
  },
  {
    testID: 'gi_fb_echogenicity',
    testName: 'GI Foreign Body Acoustic Character',
    testNameKo: '위장관 이물 음향 특성',
    organ: 'gi_tract',
    partOfOrgan: 'lumen',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gi_foreign_body', triggerValues: ['true'] },
    options: [
      {
        value: 'shadowing',
        label: 'Hyperechoic with acoustic shadowing (mineral/bone/metal)',
        labelKo: '고에코 + 음향 음영 (광물/뼈/금속)',
        resultText: 'Hyperechoic foreign body with acoustic shadowing; mineral, bone, or metal suspected',
        resultTextKo: '음향 음영을 동반한 고에코 이물; 광물, 뼈 또는 금속 의심',
        ownerResultTextKo: '뼈, 금속, 돌 같은 단단한 물체가 관찰됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'reverberation',
        label: 'Reverberation artefact (gas-producing / linear)',
        labelKo: '반향 허상 (가스 발생/선형 이물)',
        resultText: 'Foreign body with reverberation artefact; linear or gas-producing material suspected',
        resultTextKo: '반향 허상을 동반한 이물; 선형 이물 또는 가스 발생 이물 의심',
        ownerResultTextKo: '끈이나 가스를 포함한 이물질이 의심됩니다. 선형 이물의 경우 장 꼬임 위험이 큽니다.',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'soft_tissue',
        label: 'Soft tissue / Mixed (fabric/food)',
        labelKo: '연조직/혼합 (섬유/음식물)',
        resultText: 'Soft tissue density foreign body; fabric, food material, or bezoar suspected',
        resultTextKo: '연조직 밀도 이물; 섬유, 음식물 또는 모구 의심',
        ownerResultTextKo: '헝겊, 음식물 덩어리, 털뭉치(모구) 같은 이물이 의심됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
    ],
  },
  {
    testID: 'gi_mass_presence',
    testName: 'GI Mural / Intraluminal Mass Presence',
    testNameKo: '위장관 벽 내/내강 종괴 유무',
    organ: 'gi_tract',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: 'Distinct from diffuse wall thickening; focal mural or intraluminal lesion',
    options: [
      {
        value: 'absent',
        label: 'No focal GI mass',
        labelKo: '위장관 종괴 없음',
        resultText: 'No focal GI mural or intraluminal mass identified',
        resultTextKo: '위장관 내 국소 종괴 관찰되지 않음',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Focal mass present',
        labelKo: '국소 종괴 있음',
        resultText: 'Focal GI mural or intraluminal mass identified; see details below',
        resultTextKo: '위장관 내 국소 종괴 관찰; 세부 항목 참조',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'gi_mass_location',
    testName: 'GI Mass Location',
    testNameKo: '위장관 종괴 위치',
    organ: 'gi_tract',
    partOfOrgan: 'wall',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gi_mass_presence', triggerValues: ['present'] },
    resultTemplate: 'GI mass location(s): {values}',
    resultTemplateKo: '위장관 종괴 위치: {values}',
    resultTemplateOwnerKo: '다음 부위에서 종괴(혹)가 관찰됩니다: {values}',
    options: [
      {
        value: 'stomach',
        label: 'Stomach',
        labelKo: '위',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'small_intestine',
        label: 'Small intestine',
        labelKo: '소장',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'large_intestine',
        label: 'Large intestine',
        labelKo: '대장',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'gi_mass_size',
    testName: 'GI Mass Size',
    testNameKo: '위장관 종괴 크기',
    organ: 'gi_tract',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'gi_mass_presence', triggerValues: ['present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 2,
        resultText: 'Small GI mass <2 cm; biopsy recommended for definitive diagnosis',
        resultTextKo: '2cm 미만 소형 위장관 종괴; 확진을 위한 생검 권장',
        ownerResultTextKo: '2cm 미만의 작은 혹이 위장관에서 관찰됩니다. 정밀 검사가 필요합니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 2, max: null,
        resultText: 'GI mass ≥2 cm; malignant neoplasia likely; surgical evaluation and biopsy recommended',
        resultTextKo: '2cm 이상 위장관 종괴; 악성 종양 가능성 높음; 외과적 평가 및 생검 권장',
        ownerResultTextKo: '2cm 이상의 큰 종괴가 관찰됩니다. 악성 종양 가능성을 배제할 수 없어 적극적인 치료가 권장됩니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
];
