import { UltrasoundTestItem } from '../types';

export const kidneyTests: UltrasoundTestItem[] = [
  {
    testID: 'organ_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'kidney',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'surgical_removal', label: 'Surgical removal', labelKo: '수술적 적출', resultText: 'Previously removed surgically', resultTextKo: '기존 수술을 통해 적출됨', isAbnormal: true },
      { value: 'congenital_absence', label: 'Congenital absence / Agenesis', labelKo: '선천적 결손', resultText: 'Congenital absence / agenesis', resultTextKo: '선천적 결손/미발달', isAbnormal: true },
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
      { value: 'ectopic', label: 'Ectopic location', labelKo: '이소성 위치', resultText: 'Ectopic location suspected', resultTextKo: '이소성 위치 의심', isAbnormal: true },
    ],
  },
  {
    testID: 'kidney_cortex_echogenicity',
    testName: 'Renal Cortical Echogenicity',
    testNameKo: '신피질 에코 음영',
    organ: 'kidney',
    partOfOrgan: ['bilateral', 'cortex'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['kidney_cmd', 'kidney_size'],
    note: 'Normal: cortex isoechoic or slightly hypoechoic to liver/spleen',
    options: [
      {
        value: 'normal',
        label: 'Normal cortical echogenicity',
        labelKo: '정상 신피질 에코',
        resultText: 'Renal cortical echogenicity within normal limits',
        resultTextKo: '신피질 에코 음영 정상 범위',
        ownerResultTextKo: '신장의 밝기가 정상적입니다.',
        isAbnormal: false,
      },
      {
        value: 'mildly_increased',
        label: 'Mildly increased (=liver)',
        labelKo: '경미하게 증가 (=간)',
        resultText: 'Mildly increased renal cortical echogenicity (isoechoic to liver); early chronic kidney disease suspected',
        resultTextKo: '신피질 에코 음영 경미한 증가 (간과 동등); 초기 만성 신장 질환 의심',
        ownerResultTextKo: '신장의 밝기가 약간 밝아져 있습니다. 초기 신장 기능 저하가 의심될 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'markedly_increased',
        label: 'Markedly increased (>liver, =spleen or brighter)',
        labelKo: '현저하게 증가 (>간, ≥비장)',
        resultText: 'Markedly increased renal cortical echogenicity; chronic kidney disease, glomerulonephritis, or nephrocalcinosis suspected',
        resultTextKo: '신피질 에코 음영 현저한 증가; 만성 신장 질환, 사구체신염 또는 신장 석회화 의심',
        ownerResultTextKo: '신장의 밝기가 매우 밝습니다. 만성 신부전이나 신장 조직의 손상이 상당히 진행되었을 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'decreased',
        label: 'Decreased',
        labelKo: '감소',
        resultText: 'Decreased renal cortical echogenicity; acute nephritis or lymphoma suspected',
        resultTextKo: '신피질 에코 음영 감소; 급성 신염 또는 림프종 의심',
        ownerResultTextKo: '신장의 밝기가 어둡게 보입니다. 급성 염증이나 종양성 변화 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'kidney_cmd',
    testName: 'Corticomedullary Distinction (CMD)',
    testNameKo: '피수질 구분',
    organ: 'kidney',
    partOfOrgan: ['bilateral', 'cortex', 'medulla'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      {
        value: 'distinct',
        label: 'Distinct',
        labelKo: '명확',
        resultText: 'Corticomedullary distinction clear',
        resultTextKo: '피수질 구분 명확',
        ownerResultTextKo: '신장의 겉부분과 속부분이 아주 뚜렷하게 잘 구분됩니다. 건강한 상태입니다.',
        isAbnormal: false,
      },
      {
        value: 'reduced',
        label: 'Reduced',
        labelKo: '감소',
        resultText: 'Reduced corticomedullary distinction; chronic kidney disease suspected',
        resultTextKo: '피수질 구분 감소; 만성 신장 질환 의심',
        ownerResultTextKo: '신장의 내부 구조 경계가 흐릿해져 있습니다. 만성 신부전 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'absent',
        label: 'Absent',
        labelKo: '소실',
        resultText: 'Corticomedullary distinction absent; advanced chronic kidney disease suspected',
        resultTextKo: '피수질 구분 소실; 진행성 만성 신장 질환 의심',
        ownerResultTextKo: '신장의 내부 구조가 거의 구분되지 않습니다. 신장 기능이 상당히 저하된 상태로 보입니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_medullary_rim_sign',
    testName: 'Medullary Rim Sign',
    testNameKo: '피수질 경계 고에코 라인 (Medullary rim sign)',
    organ: 'kidney',
    partOfOrgan: ['bilateral', 'medulla'],
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      {
        value: 'absent',
        label: 'Absent',
        labelKo: '없음',
        resultText: 'Medullary rim sign absent',
        resultTextKo: '피수질 경계 고에코 라인 관찰되지 않음',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Present',
        labelKo: '있음',
        resultText: 'Medullary rim sign observed; consider underlying kidney disease or non-specific finding',
        resultTextKo: '피수질 경계 고에코 라인(Medullary rim sign) 관찰됨; 신장 질환 또는 비특이적 소견 고려',
        ownerResultTextKo: '신장 내부에 비정상적인 밝은 선이 보입니다. 신장 질환의 신호일 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
    ],
  },
  {
    testID: 'kidney_nephrocalcinosis',
    testName: 'Nephrocalcinosis',
    testNameKo: '신석회증 (Nephrocalcinosis)',
    organ: 'kidney',
    partOfOrgan: ['bilateral', 'parenchyma'],
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      {
        value: 'none',
        label: 'None',
        labelKo: '없음',
        resultText: 'No evidence of nephrocalcinosis',
        resultTextKo: '신석회증 관찰되지 않음',
        isAbnormal: false,
      },
      {
        value: 'mild',
        label: 'Mild',
        labelKo: '경미',
        resultText: 'Mild nephrocalcinosis observed; small hyperechoic foci without shadowing',
        resultTextKo: '경미한 신석회증 관찰됨 (음영 없는 미세한 고에코 입자)',
        ownerResultTextKo: '신장 조직 내부에 아주 미세한 석회화(딱딱한 침착물)가 보입니다. 현재로서는 큰 이상은 없으나 정기적인 관찰이 필요합니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'moderate_to_severe',
        label: 'Moderate to Severe',
        labelKo: '중등도 이상',
        resultText: 'Significant nephrocalcinosis observed; multiple hyperechoic foci with acoustic shadowing',
        resultTextKo: '중등도 이상의 신석회증 관찰됨 (음영을 동반한 다수의 고에코 입자)',
        ownerResultTextKo: '신장 내부에 뚜렷한 석회화가 진행되어 있습니다. 이는 신장 기능 저하나 대사 이상과 관련이 있을 수 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'kidney_size_length',
    testName: 'Renal Length',
    testNameKo: '신장 길이',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Measure longest axis. Dog: ~2.5–4.4 cm (varies with body weight). Cat: 3.0–4.3 cm.',
    normalRange: {
      dog: { min: 2.5, max: 6.5 },
      cat: { min: 3.0, max: 4.3 },
    },
    ranges: [
      {
        min: 0,
        max: 2.5,
        resultText: 'Small kidney; renal hypoplasia or end-stage chronic kidney disease suspected',
        resultTextKo: '신장 길이 감소; 신장 형성부전 또는 말기 만성 신장 질환 의심',
        ownerResultTextKo: '신장의 크기가 정상보다 매우 작습니다. 선천적인 원인이나 만성 신부전 말기 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        min: 2.5,
        max: 6.5,
        resultText: 'Renal size within normal limits',
        resultTextKo: '신장 크기 정상 범위',
        ownerResultTextKo: '신장의 크기가 정상입니다.',
        isAbnormal: false,
      },
      {
        min: 6.5,
        max: null,
        resultText: 'Renomegaly; hydronephrosis, neoplasia, or acute nephritis suspected',
        resultTextKo: '신장 비대; 수신증, 종양 또는 급성 신염 의심',
        ownerResultTextKo: '신장이 정상보다 커져 있습니다. 부종이나 염증, 종양 혹은 소변 정체 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'kidney_contour',
    testName: 'Renal Contour / Shape',
    testNameKo: '신장 윤곽 및 형태 이상',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '복수 선택 가능. 신장 외곽선 및 형태 이상 소견을 모두 선택하세요.',
    resultTemplate: 'Renal contour abnormality: {values}',
    resultTemplateKo: '신장 윤곽 이상 소견: {values}',
    options: [
      {
        value: 'irregular_contour',
        label: 'Irregular renal contour',
        labelKo: '신장 윤곽 불규칙',
        resultText: 'Irregular renal contour; chronic kidney disease or fibrosis suspected',
        resultTextKo: '신장 윤곽 불규칙; 만성 신장 질환 또는 섬유화 의심',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'cortical_indentation',
        label: 'Cortical indentation / Cortical scarring',
        labelKo: '피질 함몰 / 반흔 (Cortical scarring)',
        resultText: 'Cortical indentation or scarring; renal infarction or chronic pyelonephritis suspected',
        resultTextKo: '신피질 함몰 또는 반흔; 신장 경색 또는 만성 신우신염 의심',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'focal_depression',
        label: 'Focal cortical depression / notch',
        labelKo: '국소 피질 함몰 / V형 노치 (Notch)',
        resultText: 'Focal cortical depression (V-shaped notch); renal infarction strongly suspected',
        resultTextKo: '국소 신피질 함몰 (V형 노치); 신장 경색 강력 의심',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'bosselated',
        label: 'Bosselated / Nodular surface',
        labelKo: '표면 결절성 / 울퉁불퉁 (Bosselated)',
        resultText: 'Bosselated or nodular renal surface; polycystic kidney disease or multifocal lesions suspected',
        resultTextKo: '신장 표면 결절성 돌출; 다낭성 신장 질환 또는 다초점 병변 의심',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'shrunken',
        label: 'Shrunken / Contracted kidney',
        labelKo: '신장 위축 / 수축 변형 (Shrunken)',
        resultText: 'Shrunken or contracted kidney; end-stage CKD or chronic infarction suspected',
        resultTextKo: '신장 위축 또는 수축 변형; 말기 만성 신장 질환 또는 만성 경색 의심',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_pelvis_dilation',
    testName: 'Renal Pelvis Dilation',
    testNameKo: '신우 확장',
    organ: 'kidney',
    partOfOrgan: 'pelvis',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['kidney_ureter_dilation'],
    normalRange: {
      dog: { max: 3 },
      cat: { max: 3 },
    },
    ranges: [
      {
        min: 0,
        max: 3,
        resultText: 'Renal pelvis within normal limits',
        resultTextKo: '신우 확장 없음, 정상 범위',
        ownerResultTextKo: '신장 내부 소변이 모이는 곳에 확장이 없습니다. 정상입니다.',
        isAbnormal: false,
      },
      {
        min: 3,
        max: 8,
        resultText: 'Mild renal pelvic dilation; mild hydronephrosis; urinary obstruction or pyelonephritis suspected',
        resultTextKo: '경미한 신우 확장; 경미한 수신증; 요로 폐쇄 또는 신우신염 의심',
        ownerResultTextKo: '신장 내부 소변 주머니가 약간 늘어나 있습니다. 소변 정체나 신장 염증이 의심됩니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 8,
        max: null,
        resultText: 'Marked renal pelvic dilation; moderate-to-severe hydronephrosis; urinary obstruction suspected',
        resultTextKo: '현저한 신우 확장; 중등도-중증 수신증; 요로 폐쇄 의심',
        ownerResultTextKo: '신장 내부 소변 주머니가 아주 많이 늘어나 있습니다. 하부 요로가 막혔을 가능성이 높습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_stone',
    testName: 'Nephrolithiasis',
    testNameKo: '신결석',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    positiveResultText: 'Renal calculus/calculi identified with acoustic shadowing',
    positiveResultTextKo: '음향 음영을 동반한 신결석 관찰',
    positiveOwnerResultTextKo: '신장 내부에 결석(돌)이 관찰됩니다.',
    negativeResultText: 'No renal calculi identified',
    negativeResultTextKo: '신결석 없음',
    negativeOwnerResultTextKo: '신장에 결석은 보이지 않습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'kidney_stone_size',
    testName: 'Nephrolithiasis Size (largest)',
    testNameKo: '신결석 크기 (최대)',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'kidney_stone', triggerValues: ['true'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 5,
        resultText: 'Small nephrolithiasis (<5mm); may pass spontaneously',
        resultTextKo: '소형 신결석(<5mm); 자연 배출 가능',
        ownerResultTextKo: '5mm 미만의 작은 신장 결석입니다. 자연적으로 배출될 가능성이 있습니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 5, max: 10,
        resultText: 'Moderate nephrolithiasis (5–10mm); monitoring or intervention required',
        resultTextKo: '중간 크기 신결석(5-10mm); 모니터링 또는 중재 필요',
        ownerResultTextKo: '5~10mm 크기의 결석입니다. 정기적인 확인이나 치료가 필요할 수 있습니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 10, max: null,
        resultText: 'Large nephrolithiasis (>10mm); obstruction risk high; surgical or lithotripsy evaluation recommended',
        resultTextKo: '대형 신결석(>10mm); 폐쇄 위험 높음; 수술 또는 쇄석술 평가 권장',
        ownerResultTextKo: '10mm 이상의 큰 결석입니다. 요관을 막을 위험이 있어 수술적 처치가 고려됩니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_stone_location',
    testName: 'Nephrolithiasis Location',
    testNameKo: '신결석 위치',
    organ: 'kidney',
    partOfOrgan: ['pelvis', 'cortex'],
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'kidney_stone', triggerValues: ['true'] },
    resultTemplate: 'Nephrolithiasis location(s): {values}',
    resultTemplateKo: '신결석 위치: {values}',
    resultTemplateOwnerKo: '다음 부위에서 신장 결석이 관찰됩니다: {values}',
    options: [
      {
        value: 'pelvis',
        label: 'Renal pelvis',
        labelKo: '신우',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'parenchyma',
        label: 'Renal parenchyma (nephrocalcinosis)',
        labelKo: '신실질 (신장 석회화)',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'bilateral',
        label: 'Bilateral',
        labelKo: '양측성',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_cyst',
    testName: 'Renal Cyst',
    testNameKo: '신장 낭종',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'boolean',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    positiveResultText: 'Renal cyst(s) identified; polycystic kidney disease vs simple cyst',
    positiveResultTextKo: '신장 낭종 관찰; 다낭성 신장 질환 vs 단순 낭종 감별 필요',
    positiveOwnerResultTextKo: '신장에 물주머니(낭종)가 관찰됩니다.',
    negativeResultText: 'No renal cysts identified',
    negativeResultTextKo: '신장 낭종 없음',
    negativeOwnerResultTextKo: '신장에 물주머니는 보이지 않습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'kidney_cyst_number',
    testName: 'Renal Cyst Number',
    testNameKo: '신장 낭종 개수',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'kidney_cyst', triggerValues: ['true'] },
    options: [
      {
        value: 'single',
        label: 'Single',
        labelKo: '단발성 (1개)',
        resultText: 'Single renal cyst; simple renal cyst',
        resultTextKo: '단발성 신장 낭종; 단순 낭종',
        ownerResultTextKo: '한 개의 물주머니가 관찰됩니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        value: 'few',
        label: 'Few (2–3)',
        labelKo: '소수 (2-3개)',
        resultText: 'Few renal cysts (2–3)',
        resultTextKo: '소수의 신장 낭종 (2-3개)',
        ownerResultTextKo: '적은 수의 물주머니가 관찰됩니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        value: 'multiple_polycystic',
        label: 'Multiple / Polycystic',
        labelKo: '다발성 / 다낭성',
        resultText: 'Multiple renal cysts; polycystic kidney disease suspected',
        resultTextKo: '다발성 신장 낭종; 다낭성 신장 질환 의심',
        ownerResultTextKo: '매우 많은 수의 물주머니가 관찰됩니다. 유전성 다낭성 신장 질환 가능성이 있습니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_cyst_size',
    testName: 'Renal Cyst Size (largest)',
    testNameKo: '신장 낭종 크기 (최대)',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'kidney_cyst', triggerValues: ['true'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 1,
        resultText: 'Small renal cyst(s) <1 cm; routine monitoring recommended',
        resultTextKo: '1cm 미만 소형 신장 낭종; 정기적 모니터링 권장',
        ownerResultTextKo: '1cm 미만의 작은 물주머니입니다. 정기적인 확인만으로 충분할 수 있습니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 1, max: 3,
        resultText: 'Renal cyst(s) 1–3 cm; follow-up ultrasound recommended',
        resultTextKo: '1-3cm 신장 낭종; 추적 초음파 검사 권장',
        ownerResultTextKo: '1~3cm 크기의 물주머니가 보입니다. 주기적인 초음파 검사가 필요합니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 3, max: null,
        resultText: 'Large renal cyst(s) >3 cm; compression of adjacent parenchyma possible',
        resultTextKo: '3cm 초과 대형 신장 낭종; 인접 실질 압박 가능성',
        ownerResultTextKo: '3cm가 넘는 큰 물주머니가 있습니다. 신장 조직을 압박할 수 있어 주의가 필요합니다.',
        isAbnormal: true, severity: 'moderate',
      },
    ],
  },
  {
    testID: 'kidney_focal_lesion_presence',
    testName: 'Focal Renal Lesion (non-cystic)',
    testNameKo: '신장 국소 병변 (비낭성)',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: 'Solid or mixed renal mass excluding simple cysts and calculi',
    options: [
      {
        value: 'absent',
        label: 'No focal solid lesion',
        labelKo: '국소 고형 병변 없음',
        resultText: 'No focal solid renal lesion identified',
        resultTextKo: '신장 내 국소 고형 병변 관찰되지 않음',
        ownerResultTextKo: '신장 내부에 단단한 혹이나 덩어리는 보이지 않습니다.',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Focal solid lesion present',
        labelKo: '국소 고형 병변 있음',
        resultText: 'Focal solid renal lesion identified; see details below',
        resultTextKo: '신장 내 국소 고형 병변 관찰; 세부 항목 참조',
        ownerResultTextKo: '신장 내부에서 혹이나 덩어리 같은 변화가 관찰됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
    ],
  },
  {
    testID: 'kidney_focal_size',
    testName: 'Focal Renal Lesion Size',
    testNameKo: '신장 국소 병변 크기',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'kidney_focal_lesion_presence', triggerValues: ['present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 1,
        resultText: 'Small focal renal lesion <1 cm; cytology or follow-up recommended',
        resultTextKo: '1cm 미만 소형 신장 국소 병변; 세포검사 또는 추적 검사 권장',
        ownerResultTextKo: '신장에 1cm 미만의 작은 혹이 보입니다. 정기적인 추적 관찰이 권장됩니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 1, max: 3,
        resultText: 'Focal renal lesion 1–3 cm; neoplasia suspected; cytology recommended',
        resultTextKo: '1-3cm 신장 국소 병변; 종양 의심; 세포검사 권장',
        ownerResultTextKo: '1~3cm 크기의 혹이 보입니다. 종양 가능성을 배제하기 위해 추가 검사가 권장됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 3, max: null,
        resultText: 'Large focal renal mass >3 cm; renal carcinoma or lymphoma suspected',
        resultTextKo: '3cm 초과 신장 종괴; 신세포암종 또는 림프종 의심',
        ownerResultTextKo: '3cm 이상의 큰 종괴가 관찰됩니다. 정밀 검사와 적극적인 치료가 필요할 수 있습니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'kidney_focal_echogenicity',
    testName: 'Focal Renal Lesion Echogenicity',
    testNameKo: '신장 국소 병변 에코 음영',
    organ: 'kidney',
    partOfOrgan: 'bilateral',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'kidney_focal_lesion_presence', triggerValues: ['present'] },
    options: [
      {
        value: 'hyperechoic',
        label: 'Hyperechoic',
        labelKo: '고에코',
        resultText: 'Hyperechoic focal renal lesion; lipoma or angiomyolipoma suspected',
        resultTextKo: '고에코 신장 국소 병변; 지방종 또는 혈관근지방종 의심',
        ownerResultTextKo: '주변보다 밝게 보이는 혹이 관찰됩니다. 지방종 등 양성 병변일 수 있습니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        value: 'hypoechoic',
        label: 'Hypoechoic',
        labelKo: '저에코',
        resultText: 'Hypoechoic focal renal lesion; lymphoma or renal carcinoma suspected',
        resultTextKo: '저에코 신장 국소 병변; 림프종 또는 신세포암종 의심',
        ownerResultTextKo: '주변보다 어둡게 보이는 혹이 관찰됩니다. 종양성 변화에 대한 주의가 필요합니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'mixed',
        label: 'Mixed / Heterogeneous',
        labelKo: '혼합/불균질',
        resultText: 'Mixed echogenicity focal renal lesion; malignant neoplasia suspected',
        resultTextKo: '혼합 에코 신장 국소 병변; 악성 종양 의심',
        ownerResultTextKo: '밝고 어두운 부분이 섞인 복잡한 형태의 혹이 보입니다. 악성 가능성을 고려해야 합니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
];
