import { UltrasoundTestItem } from '../types';

export const liverTests: UltrasoundTestItem[] = [
  {
    testID: 'liver_echogenicity',
    testName: 'Hepatic Echogenicity',
    testNameKo: '간 에코 음영',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['liver_texture', 'liver_size'],
    options: [
      {
        value: 'normal',
        label: 'Normal (isoechoic to spleen/cortex)',
        labelKo: '정상',
        resultText: 'Hepatic echogenicity within normal limits',
        resultTextKo: '간 에코 음영 정상 범위',
        ownerResultTextKo: '간의 밝기가 정상입니다.',
        isAbnormal: false,
      },
      {
        value: 'mildly_hyperechoic',
        label: 'Mildly hyperechoic',
        labelKo: '경미하게 고에코',
        resultText: 'Mildly increased hepatic echogenicity observed',
        resultTextKo: '간 에코 음영 경미한 증가 소견',
        ownerResultTextKo: '간의 밝기가 조금 밝아져 있습니다. 지방간 등이 의심될 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'markedly_hyperechoic',
        label: 'Markedly hyperechoic',
        labelKo: '현저하게 고에코',
        resultText: 'Markedly increased hepatic echogenicity; fat infiltration or vacuolar hepatopathy suspected',
        resultTextKo: '간 에코 음영 현저한 증가; 지방 침윤 또는 공포성 간증 의심',
        ownerResultTextKo: '간의 밝기가 매우 밝습니다. 심한 지방간이나 간 수치와 관련된 변화가 의심됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'hypoechoic',
        label: 'Hypoechoic',
        labelKo: '저에코',
        resultText: 'Decreased hepatic echogenicity; congestion, hepatitis, or lymphoma suspected',
        resultTextKo: '간 에코 음영 감소; 울혈성 간, 간염 또는 림프종 의심',
        ownerResultTextKo: '간의 밝기가 어둡게 보입니다. 간의 혈액 순환 장애나 염증 등이 의심될 수 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'mixed',
        label: 'Mixed / Heterogeneous',
        labelKo: '혼합/불균질',
        resultText: 'Heterogeneous hepatic echogenicity; multifocal lesions suspected',
        resultTextKo: '간 에코 음영 불균질; 다발성 병변 의심',
        ownerResultTextKo: '간의 밝기가 일정하지 않고 얼룩덜룩하게 보입니다. 여러 군데에 변화가 생긴 상태일 수 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'liver_texture',
    testName: 'Hepatic Parenchymal Texture',
    testNameKo: '간 실질 텍스처',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['liver_echogenicity'],
    options: [
      {
        value: 'fine',
        label: 'Fine and homogeneous',
        labelKo: '미세 균질',
        resultText: 'Hepatic parenchymal texture fine and homogeneous',
        resultTextKo: '간 실질 텍스처 미세 균질',
        ownerResultTextKo: '간 내부 조직이 아주 고르고 깨끗하게 보입니다.',
        isAbnormal: false,
      },
      {
        value: 'coarse',
        label: 'Coarse / Nodular',
        labelKo: '조대/결절성',
        resultText: 'Coarse hepatic parenchymal texture; chronic hepatopathy or cirrhosis suspected',
        resultTextKo: '간 실질 텍스처 조대; 만성 간질환 또는 간경변 의심',
        ownerResultTextKo: '간 조직이 거칠게 보입니다. 만성적인 간 손상이나 간경화 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'target_pattern',
        label: 'Target pattern (halo sign)',
        labelKo: '표적 패턴 (halo sign)',
        resultText: 'Target pattern lesion(s) identified; neoplasia or abscess suspected',
        resultTextKo: '표적 패턴 병변 관찰; 종양 또는 농양 의심',
        ownerResultTextKo: '과녁 모양의 특수한 병변이 보입니다. 종양이나 농양 같은 덩어리가 의심됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_size',
    testName: 'Hepatic Size',
    testNameKo: '간 크기',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      {
        value: 'normal',
        label: 'Normal size',
        labelKo: '정상',
        resultText: 'Liver size within normal limits',
        resultTextKo: '간 크기 정상 범위',
        ownerResultTextKo: '간의 크기가 정상 범위 내에 있습니다.',
        isAbnormal: false,
      },
      {
        value: 'hepatomegaly_mild',
        label: 'Mild hepatomegaly',
        labelKo: '경미한 간비대',
        resultText: 'Mild hepatomegaly noted',
        resultTextKo: '경미한 간비대 소견',
        ownerResultTextKo: '간이 평소보다 약간 부어 있는 상태입니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'hepatomegaly_marked',
        label: 'Marked hepatomegaly',
        labelKo: '현저한 간비대',
        resultText: 'Marked hepatomegaly; neoplasia, congestion, or hepatocellular disease suspected',
        resultTextKo: '현저한 간비대; 종양, 울혈 또는 간세포 질환 의심',
        ownerResultTextKo: '간이 상당히 부어 있습니다. 혈액 순환 장애나 간 질환, 혹은 종양 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'microhepatica',
        label: 'Microhepatica',
        labelKo: '간 위축',
        resultText: 'Microhepatica noted; portosystemic shunt or end-stage liver disease suspected',
        resultTextKo: '간 위축 소견; 문맥체순환 단락 또는 말기 간질환 의심',
        ownerResultTextKo: '간이 정상보다 작아져 있습니다. 선천적인 혈관 이상이나 만성적인 간 위축이 의심됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_margin',
    testName: 'Hepatic Margin',
    testNameKo: '간 경계',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      {
        value: 'smooth',
        label: 'Smooth and sharp',
        labelKo: '매끈하고 명확',
        resultText: 'Hepatic margins smooth and well-defined',
        resultTextKo: '간 경계 매끈하고 명확',
        ownerResultTextKo: '간의 테두리가 매끄럽고 건강해 보입니다.',
        isAbnormal: false,
      },
      {
        value: 'irregular',
        label: 'Irregular / Lobulated',
        labelKo: '불규칙/엽상',
        resultText: 'Irregular hepatic margin; chronic fibrosis or nodular hyperplasia suspected',
        resultTextKo: '간 경계 불규칙; 만성 섬유화 또는 결절성 과증식 의심',
        ownerResultTextKo: '간의 테두리가 울퉁불퉁합니다. 만성적인 변화나 조직의 변성이 의심됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'rounded',
        label: 'Rounded (blunted edges)',
        labelKo: '둥근 경계 (뭉툭한 끝)',
        resultText: 'Rounded hepatic margins; hepatomegaly or diffuse infiltration suspected',
        resultTextKo: '간 경계 둥글게 뭉툭; 간비대 또는 미만성 침윤 의심',
        ownerResultTextKo: '간의 끝부분이 뾰족하지 않고 둥글게 부어 있습니다. 간 비대가 의심됩니다.',
        isAbnormal: true,
        severity: 'mild',
      },
    ],
  },
  {
    testID: 'liver_vascularity',
    testName: 'Hepatic Vascular Pattern',
    testNameKo: '간 혈관 패턴',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    relatedTests: ['liver_size'],
    note: 'Portal vein diameter >13mm (dog) suggests portal hypertension',
    options: [
      {
        value: 'normal',
        label: 'Normal vascular pattern',
        labelKo: '정상 혈관 패턴',
        resultText: 'Normal hepatic vascular pattern',
        resultTextKo: '간 혈관 패턴 정상',
        ownerResultTextKo: '간 내부의 혈관 흐름이 정상적입니다.',
        isAbnormal: false,
      },
      {
        value: 'portal_dilation',
        label: 'Portal vein dilation',
        labelKo: '문맥 확장',
        resultText: 'Portal vein dilation noted; portal hypertension suspected',
        resultTextKo: '문맥 확장 소견; 문맥 고혈압 의심',
        ownerResultTextKo: '간으로 들어가는 주요 혈관이 확장되어 있습니다. 혈압이 높거나 혈류 정체가 의심됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'hepatic_vein_dilation',
        label: 'Hepatic vein dilation',
        labelKo: '간정맥 확장',
        resultText: 'Hepatic vein dilation; right-sided heart failure or hepatic venous obstruction suspected',
        resultTextKo: '간정맥 확장; 우심부전 또는 간정맥 폐쇄 의심',
        ownerResultTextKo: '간에서 나가는 혈관이 넓어져 있습니다. 심장 기능 저하나 혈액 배출 장애가 의심됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'tortuous_vessel',
        label: 'Tortuous / Anomalous vessel',
        labelKo: '사행/이상 혈관',
        resultText: 'Anomalous or tortuous hepatic vessel(s) observed; portosystemic shunt suspected',
        resultTextKo: '사행 또는 이상 혈관 관찰; 문맥체순환 단락 의심',
        ownerResultTextKo: '간 주변 혈관이 꼬여있거나 비정상적인 경로로 흐릅니다. 선천적인 혈관 기형 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_nodule_presence',
    testName: 'Hepatic Nodule / Mass Presence',
    testNameKo: '간 결절/종괴 유무',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'If present, complete all Level 2 nodule sub-items below',
    options: [
      {
        value: 'absent',
        label: 'No nodule / mass',
        labelKo: '결절/종괴 없음',
        resultText: 'No focal hepatic lesion identified',
        resultTextKo: '간 내 국소 병변 관찰되지 않음',
        ownerResultTextKo: '간 내부에 특별한 혹이나 덩어리가 보이지 않습니다.',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Nodule / Mass present',
        labelKo: '결절/종괴 있음',
        resultText: 'Focal hepatic lesion(s) identified; see details below',
        resultTextKo: '간 내 국소 병변 관찰; 세부 항목 참조',
        ownerResultTextKo: '간 내부에서 혹이나 덩어리 같은 변화가 관찰됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'liver_nodule_number',
    testName: 'Hepatic Nodule Number',
    testNameKo: '간 결절 개수',
    organ: 'liver',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: {
      testID: 'liver_nodule_presence',
      triggerValues: ['present'],
    },
    relatedTests: ['liver_nodule_size', 'liver_nodule_echogenicity', 'liver_nodule_location'],
    options: [
      {
        value: 'solitary',
        label: 'Solitary (single)',
        labelKo: '단발성 (1개)',
        resultText: 'Single hepatic focal lesion',
        resultTextKo: '단발성 간 국소 병변',
        ownerResultTextKo: '한 개의 혹이 발견되었습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'few',
        label: 'Few (2–3)',
        labelKo: '소수 (2-3개)',
        resultText: 'Few (2–3) hepatic focal lesions',
        resultTextKo: '소수(2-3개) 간 국소 병변',
        ownerResultTextKo: '2~3개 정도의 적은 수의 혹이 보입니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'multiple',
        label: 'Multiple (≥4)',
        labelKo: '다발성 (4개 이상)',
        resultText: 'Multiple (≥4) hepatic focal lesions; multifocal neoplasia or nodular hyperplasia suspected',
        resultTextKo: '다발성(4개 이상) 간 국소 병변; 다발성 종양 또는 결절성 과증식 의심',
        ownerResultTextKo: '여러 군데에 혹들이 퍼져 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'innumerable',
        label: 'Innumerable / Diffuse',
        labelKo: '셀 수 없이 많음 / 미만성',
        resultText: 'Innumerable / diffusely distributed hepatic lesions; diffuse neoplastic infiltration suspected',
        resultTextKo: '셀 수 없이 많은/미만성 간 병변; 미만성 종양 침윤 의심',
        ownerResultTextKo: '간 전체에 셀 수 없을 정도로 많은 혹이나 변화가 퍼져 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_nodule_size',
    testName: 'Hepatic Nodule / Mass Size (largest)',
    testNameKo: '간 결절/종괴 크기 (최대 병변)',
    organ: 'liver',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: {
      testID: 'liver_nodule_presence',
      triggerValues: ['present'],
    },
    relatedTests: ['liver_nodule_echogenicity', 'liver_nodule_number', 'liver_nodule_location'],
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0,
        max: 1,
        resultText: 'Hepatic nodule(s) <1 cm; nodular hyperplasia vs neoplasia, follow-up recommended',
        resultTextKo: '1cm 미만 간 결절 관찰; 결절성 과증식 vs 종양성 병변 감별 필요, 추적 검사 권장',
        ownerResultTextKo: '1cm 미만의 작은 혹이 보입니다. 단순 노화 현상일 수 있지만 정기적인 관찰이 필요합니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 1,
        max: 3,
        resultText: 'Hepatic nodule(s) 1–3 cm; fine needle aspiration recommended',
        resultTextKo: '1-3cm 간 결절 관찰; 세침흡인 검사 권장',
        ownerResultTextKo: '1~3cm 크기의 혹이 보입니다. 정확한 성상을 알기 위해 세포 검사가 권장될 수 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        min: 3,
        max: null,
        resultText: 'Hepatic mass >3 cm; hepatocellular carcinoma or other neoplasia suspected; further evaluation recommended',
        resultTextKo: '3cm 초과 간 종괴 관찰; 간세포암종 또는 기타 종양 의심; 정밀 평가 권장',
        ownerResultTextKo: '3cm가 넘는 큰 덩어리(혹)가 관찰됩니다. 정밀 검사나 수술적 처치가 필요할 수 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_nodule_echogenicity',
    testName: 'Hepatic Nodule Echogenicity',
    testNameKo: '간 결절 에코 음영',
    organ: 'liver',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: {
      testID: 'liver_nodule_presence',
      triggerValues: ['present'],
    },
    relatedTests: ['liver_nodule_size', 'liver_nodule_number', 'liver_nodule_location'],
    options: [
      {
        value: 'hyperechoic_nodule',
        label: 'Hyperechoic',
        labelKo: '고에코',
        resultText: 'Hyperechoic hepatic nodule; hepatocellular carcinoma, nodular hyperplasia, or lipoma suspected',
        resultTextKo: '고에코 간 결절; 간세포암종, 결절성 과증식 또는 지방종 의심',
        ownerResultTextKo: '주변보다 밝게 보이는 혹이 관찰됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'hypoechoic_nodule',
        label: 'Hypoechoic',
        labelKo: '저에코',
        resultText: 'Hypoechoic hepatic nodule; lymphoma, mast cell tumor, or abscess suspected',
        resultTextKo: '저에코 간 결절; 림프종, 비만세포종양 또는 농양 의심',
        ownerResultTextKo: '주변보다 어둡게 보이는 혹이 관찰됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'anechoic_nodule',
        label: 'Anechoic (cyst)',
        labelKo: '무에코 (낭종)',
        resultText: 'Anechoic hepatic lesion with posterior acoustic enhancement; cyst suspected',
        resultTextKo: '후방음향증강을 동반한 무에코 간 병변; 낭종 의심',
        ownerResultTextKo: '간 내부에 물주머니(낭종)가 관찰됩니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'mixed_nodule',
        label: 'Mixed / Heterogeneous',
        labelKo: '혼합/불균질',
        resultText: 'Mixed echogenicity hepatic nodule; malignant neoplasia or abscess suspected',
        resultTextKo: '혼합 에코 간 결절; 악성 종양 또는 농양 의심',
        ownerResultTextKo: '밝고 어두운 부분이 섞여 있는 복잡한 형태의 혹이 관찰됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'target_nodule',
        label: 'Target pattern (halo sign)',
        labelKo: '표적 패턴 (halo sign)',
        resultText: 'Target pattern hepatic nodule; malignant neoplasia or abscess strongly suspected',
        resultTextKo: '표적 패턴 간 결절; 악성 종양 또는 농양 강력 의심',
        ownerResultTextKo: '과녁 모양의 종괴가 보입니다. 종양일 가능성이 높아 정밀 검사가 필요합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_nodule_location',
    testName: 'Hepatic Nodule Location',
    testNameKo: '간 결절 위치',
    organ: 'liver',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'multiselect',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: {
      testID: 'liver_nodule_presence',
      triggerValues: ['present'],
    },
    relatedTests: ['liver_nodule_size', 'liver_nodule_number', 'liver_nodule_echogenicity'],
    resultTemplate: 'Hepatic nodule location(s): {values}',
    resultTemplateKo: '간 결절 위치: {values}',
    resultTemplateOwnerKo: '간의 다음 부위에서 결절(혹)이 관찰됩니다: {values}',
    options: [
      { value: 'left_lobe', label: 'Left lobe', labelKo: '좌엽', resultText: '', resultTextKo: '', isAbnormal: true },
      { value: 'right_lobe', label: 'Right lobe', labelKo: '우엽', resultText: '', resultTextKo: '', isAbnormal: true },
      { value: 'quadrate_lobe', label: 'Quadrate lobe', labelKo: '방형엽', resultText: '', resultTextKo: '', isAbnormal: true },
      { value: 'caudate_lobe', label: 'Caudate lobe', labelKo: '미상엽', resultText: '', resultTextKo: '', isAbnormal: true },
      { value: 'diffuse', label: 'Throughout all lobes', labelKo: '전체 간에 걸쳐', resultText: '', resultTextKo: '', isAbnormal: true },
    ],
  },
  {
    testID: 'liver_nodule_margin',
    testName: 'Hepatic Nodule Margin',
    testNameKo: '간 결절 경계',
    organ: 'liver',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: {
      testID: 'liver_nodule_presence',
      triggerValues: ['present'],
    },
    options: [
      {
        value: 'well_defined',
        label: 'Well-defined / Smooth margin',
        labelKo: '경계 명확/매끈',
        resultText: 'Hepatic lesion with well-defined smooth margin; benign lesion more likely',
        resultTextKo: '경계 명확하고 매끈한 간 병변; 양성 병변 가능성 높음',
        ownerResultTextKo: '혹의 테두리가 매끈하고 명확합니다. 상대적으로 얌전한 혹일 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'ill_defined',
        label: 'Ill-defined / Irregular margin',
        labelKo: '경계 불명확/불규칙',
        resultText: 'Hepatic lesion with ill-defined or irregular margin; malignant neoplasia suspected',
        resultTextKo: '경계 불명확하거나 불규칙한 간 병변; 악성 종양 의심',
        ownerResultTextKo: '혹의 테두리가 울퉁불퉁하거나 흐릿합니다. 주변 조직으로 침범하는 나쁜 혹일 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'liver_biliary_dilation',
    testName: 'Intrahepatic Biliary Dilation',
    testNameKo: '간내 담도 확장',
    organ: 'liver',
    partOfOrgan: 'diffuse',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    positiveResultText: 'Intrahepatic biliary dilation noted; biliary obstruction suspected',
    positiveResultTextKo: '간내 담도 확장 소견; 담도 폐쇄 의심',
    positiveOwnerResultTextKo: '간 내부의 담즙이 흐르는 길이 확장되어 있습니다. 담즙 배출이 원활하지 않을 수 있습니다.',
    negativeResultText: 'No intrahepatic biliary dilation',
    negativeResultTextKo: '간내 담도 확장 없음',
    negativeOwnerResultTextKo: '간 내부 담즙 통로에 특별한 이상이 없습니다.',
    positiveIsAbnormal: true,
  },
];
