import { UltrasoundTestItem } from '../types';

export const lymphNodeTests: UltrasoundTestItem[] = [
  {
    testID: 'ln_location',
    testName: 'Target Lymph Nodes',
    testNameKo: '대상 림프절 위치',
    organ: 'lymph_node',
    partOfOrgan: 'general',
    testType: 'multiselect',
    clinicalSignificance: 'medium',
    species: 'both',
    required: true,
    displayLevel: 1,
    resultTemplate: 'Observed Lymph Nodes: {values}',
    resultTemplateKo: '대상 림프절 위치: {values}',
    resultTemplateOwnerKo: '다음 위치의 림프절들을 확인했습니다: {values}',
    options: [
      { value: 'jejunal', label: 'Jejunal', labelKo: '공장', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'medial_iliac', label: 'Medial Iliac', labelKo: '내장골', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'hypogastric', label: 'Hypogastric', labelKo: '하복부', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'colic', label: 'Colic', labelKo: '결장', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'portal', label: 'Portal', labelKo: '간문', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'splenic', label: 'Splenic', labelKo: '비장', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'gastric', label: 'Gastric', labelKo: '위', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'pancreaticoduodenal', label: 'Pancreaticoduodenal', labelKo: '췌십이지장', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'renal', label: 'Renal', labelKo: '신장', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'aortic', label: 'Aortic', labelKo: '대동맥', resultText: '', resultTextKo: '', isAbnormal: false },
    ],
  },
  {
    testID: 'ln_enlargement',
    testName: 'Abdominal Lymph Node Enlargement',
    testNameKo: '복강 림프절 비대',
    organ: 'lymph_node',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['ln_echogenicity', 'ln_shape'],
    options: [
      {
        value: 'not_visible',
        label: 'Not visible / Normal size',
        labelKo: '관찰되지 않음 / 정상 크기',
        resultText: 'No significant abdominal lymph node enlargement',
        resultTextKo: '복강 림프절 유의미한 비대 없음',
        ownerResultTextKo: '복강 내 림프절이 붓지 않고 정상적인 크기입니다.',
        isAbnormal: false,
      },
      {
        value: 'mild',
        label: 'Mildly enlarged',
        labelKo: '경미한 비대',
        resultText: 'Mildly enlarged abdominal lymph node(s); reactive lymphadenopathy suspected',
        resultTextKo: '복강 림프절 경미한 비대; 반응성 림프절병증 의심',
        ownerResultTextKo: '복강 내 림프절이 약간 커져 있습니다. 염증 등에 의한 단순 반응일 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'marked',
        label: 'Markedly enlarged',
        labelKo: '현저한 비대',
        resultText: 'Markedly enlarged abdominal lymph node(s); lymphoma or metastatic neoplasia suspected',
        resultTextKo: '복강 림프절 현저한 비대; 림프종 또는 전이성 종양 의심',
        ownerResultTextKo: '복강 내 림프절이 매우 크게 부어 있습니다. 종양(림프종 등)이나 다른 곳에서 암이 전이되었을 가능성이 높습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'ln_echogenicity',
    testName: 'Lymph Node Echogenicity',
    testNameKo: '림프절 에코 음영',
    organ: 'lymph_node',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      {
        value: 'normal_hypoechoic',
        label: 'Normal (homogeneous, mildly hypoechoic)',
        labelKo: '정상 (균질, 경미하게 저에코)',
        resultText: 'Lymph node echogenicity normal',
        resultTextKo: '림프절 에코 음영 정상',
        ownerResultTextKo: '림프절 내부의 음영이 정상적입니다.',
        isAbnormal: false,
      },
      {
        value: 'hypoechoic_rounded',
        label: 'Hypoechoic and rounded',
        labelKo: '저에코 및 둥근 형태',
        resultText: 'Hypoechoic rounded lymph node; lymphoma suspected',
        resultTextKo: '저에코 둥근 림프절; 림프종 의심',
        ownerResultTextKo: '림프절이 매우 어둡게 보이고 동그랗게 부어 있습니다. 림프종 같은 종양성 변화가 강력히 의심됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'hyperechoic_heterogeneous',
        label: 'Hyperechoic / Heterogeneous',
        labelKo: '고에코/불균질',
        resultText: 'Heterogeneous lymph node; metastatic neoplasia or abscess suspected',
        resultTextKo: '불균질 림프절; 전이성 종양 또는 농양 의심',
        ownerResultTextKo: '림프절 내부가 얼룩덜룩하고 지저분하게 보입니다. 전이성 종양이나 농양(고름집) 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'ln_shape',
    testName: 'Lymph Node Shape',
    testNameKo: '림프절 형태',
    organ: 'lymph_node',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      {
        value: 'elongated_normal',
        label: 'Elongated (normal L:W >2)',
        labelKo: '타원형 (정상 L:W >2)',
        resultText: 'Lymph node shape normal (elongated)',
        resultTextKo: '림프절 형태 정상 (타원형)',
        ownerResultTextKo: '림프절이 정상적인 길쭉한 타원형 모양을 유지하고 있습니다.',
        isAbnormal: false,
      },
      {
        value: 'rounded_abnormal',
        label: 'Rounded (L:W <2)',
        labelKo: '둥근 형태 (L:W <2)',
        resultText: 'Rounded lymph node shape (L:W ratio <2); neoplastic infiltration suspected',
        resultTextKo: '둥근 림프절 형태 (L:W 비 <2); 종양성 침윤 의심',
        ownerResultTextKo: '림프절이 정상적인 타원형을 잃고 동그랗게 변했습니다. 종양 세포의 침투 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
];
