import { UltrasoundTestItem } from '../types';

export const pancreasTests: UltrasoundTestItem[] = [
  {
    testID: 'pancreas_echogenicity',
    testName: 'Pancreatic Echogenicity',
    testNameKo: '췌장 에코 음영',
    organ: 'pancreas',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['pancreas_size', 'peripancreatic_effusion'],
    options: [
      {
        value: 'normal',
        label: 'Normal (isoechoic to mesentery)',
        labelKo: '정상 (장간막과 동등)',
        resultText: 'Pancreatic echogenicity within normal limits',
        resultTextKo: '췌장 에코 음영 정상 범위',
        ownerResultTextKo: '췌장의 밝기가 정상입니다.',
        isAbnormal: false,
      },
      {
        value: 'hypoechoic',
        label: 'Hypoechoic',
        labelKo: '저에코',
        resultText: 'Hypoechoic pancreas; acute pancreatitis suspected',
        resultTextKo: '저에코 췌장; 급성 췌장염 의심',
        ownerResultTextKo: '췌장이 어둡게 부어 있습니다. 급성 췌장염이 의심됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'hyperechoic',
        label: 'Hyperechoic',
        labelKo: '고에코',
        resultText: 'Hyperechoic pancreas; chronic pancreatitis or fibrosis suspected',
        resultTextKo: '고에코 췌장; 만성 췌장염 또는 섬유화 의심',
        ownerResultTextKo: '췌장이 밝게 변해 있습니다. 만성적인 염증이나 조직의 변성이 의심됩니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'mixed',
        label: 'Mixed / Heterogeneous',
        labelKo: '혼합/불균질',
        resultText: 'Heterogeneous pancreatic echogenicity; neoplasia or severe pancreatitis suspected',
        resultTextKo: '불균질 췌장 에코 음영; 종양 또는 중증 췌장염 의심',
        ownerResultTextKo: '췌장의 밝기가 일정하지 않고 불규칙합니다. 심한 염증이나 종양성 변화 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'pancreas_size',
    testName: 'Pancreatic Thickness',
    testNameKo: '췌장 두께',
    organ: 'pancreas',
    partOfOrgan: 'body',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: 'Pancreatic body thickness. Dog: <10mm. Cat: <10mm at body.',
    normalRange: {
      dog: { max: 10 },
      cat: { max: 10 },
    },
    ranges: [
      {
        min: 0,
        max: 10,
        resultText: 'Pancreatic thickness within normal limits',
        resultTextKo: '췌장 두께 정상 범위',
        ownerResultTextKo: '췌장의 두께가 정상 범위 내에 있습니다.',
        isAbnormal: false,
      },
      {
        min: 10,
        max: 15,
        resultText: 'Mildly enlarged pancreas; early pancreatitis suspected',
        resultTextKo: '경미한 췌장 비대; 초기 췌장염 의심',
        ownerResultTextKo: '췌장이 약간 부어 있습니다. 췌장염 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 15,
        max: null,
        resultText: 'Marked pancreatic enlargement; severe pancreatitis or neoplasia suspected',
        resultTextKo: '현저한 췌장 비대; 중증 췌장염 또는 종양 의심',
        ownerResultTextKo: '췌장이 매우 심하게 부어 있습니다. 심각한 췌장염이나 종양 확인이 필요합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'peripancreatic_effusion',
    testName: 'Peripancreatic Effusion / Hyperechoic Mesentery',
    testNameKo: '췌장 주변 삼출 / 장간막 고에코',
    organ: 'pancreas',
    partOfOrgan: 'general',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    positiveResultText: 'Peripancreatic free fluid and/or hyperechoic mesentery identified; pancreatitis strongly suspected',
    positiveResultTextKo: '췌장 주변 삼출액 및/또는 고에코 장간막 관찰; 췌장염 강력 의심',
    positiveOwnerResultTextKo: '췌장 주변에 물이 차 있거나 주변 지방 조직의 염증 반응이 관찰됩니다. 췌장염일 가능성이 매우 높습니다.',
    negativeResultText: 'No peripancreatic effusion',
    negativeResultTextKo: '췌장 주변 삼출액 없음',
    negativeOwnerResultTextKo: '췌장 주변에 특별한 액체 저류나 염증 소견이 보이지 않습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'pancreatic_duct_dilation',
    testName: 'Pancreatic Duct Dilation',
    testNameKo: '췌관 확장',
    organ: 'pancreas',
    partOfOrgan: 'body',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    positiveResultText: 'Pancreatic duct dilation noted; chronic pancreatitis or pancreatic mass suspected',
    positiveResultTextKo: '췌관 확장 소견; 만성 췌장염 또는 췌장 종괴 의심',
    positiveOwnerResultTextKo: '췌장 내부의 관이 확장되어 있습니다. 만성적인 췌장염이나 혹에 의한 폐쇄 가능성이 있습니다.',
    negativeResultText: 'No pancreatic duct dilation',
    negativeResultTextKo: '췌관 확장 없음',
    negativeOwnerResultTextKo: '췌장 내부 관의 크기가 정상입니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'pancreas_mass_presence',
    testName: 'Pancreatic Mass Presence',
    testNameKo: '췌장 종괴 유무',
    organ: 'pancreas',
    partOfOrgan: ['body', 'neck', 'tail'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: 'Distinct from diffuse enlargement; look for focal hypo/hyperechoic lesion',
    options: [
      {
        value: 'absent',
        label: 'No focal pancreatic mass',
        labelKo: '췌장 종괴 없음',
        resultText: 'No focal pancreatic mass identified',
        resultTextKo: '췌장 내 국소 종괴 관찰되지 않음',
        ownerResultTextKo: '췌장 내부에 혹이나 덩어리는 보이지 않습니다.',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Focal mass present',
        labelKo: '국소 종괴 있음',
        resultText: 'Focal pancreatic mass identified; see details below',
        resultTextKo: '췌장 내 국소 종괴 관찰; 세부 항목 참조',
        ownerResultTextKo: '췌장 내부에서 혹이나 덩어리 같은 변화가 관찰됩니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'pancreas_mass_location',
    testName: 'Pancreatic Mass Location',
    testNameKo: '췌장 종괴 위치',
    organ: 'pancreas',
    partOfOrgan: ['neck', 'body', 'tail'],
    testType: 'multiselect',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'pancreas_mass_presence', triggerValues: ['present'] },
    resultTemplate: 'Pancreatic mass location(s): {values}',
    resultTemplateKo: '췌장 종괴 위치: {values}',
    resultTemplateOwnerKo: '다음 부위에서 췌장 종괴(혹)가 확인됩니다: {values}',
    options: [
      {
        value: 'right_lobe',
        label: 'Right lobe / duodenal limb',
        labelKo: '우엽 / 십이지장 분지',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'body',
        label: 'Body',
        labelKo: '체부',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'left_lobe',
        label: 'Left lobe / splenic limb',
        labelKo: '좌엽 / 비장 분지',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'pancreas_mass_size',
    testName: 'Pancreatic Mass Size',
    testNameKo: '췌장 종괴 크기',
    organ: 'pancreas',
    partOfOrgan: ['body', 'neck', 'tail'],
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'pancreas_mass_presence', triggerValues: ['present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 2,
        resultText: 'Small pancreatic mass <2 cm; insulinoma or focal pancreatitis suspected',
        resultTextKo: '2cm 미만 소형 췌장 종괴; 인슐린종 또는 국소 췌장염 의심',
        ownerResultTextKo: '2cm 미만의 작은 혹이 췌장에서 발견되었습니다. 인슐린종이나 부분적인 염증일 수 있습니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 2, max: null,
        resultText: 'Pancreatic mass ≥2 cm; exocrine pancreatic adenocarcinoma suspected; CT/biopsy recommended',
        resultTextKo: '2cm 이상 췌장 종괴; 외분비 췌장 선암종 의심; CT/생검 권장',
        ownerResultTextKo: '2cm 이상의 혹이 관찰됩니다. 악성 종양 가능성이 있어 정밀 검사가 강력히 권장됩니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'pancreas_mass_echogenicity',
    testName: 'Pancreatic Mass Echogenicity',
    testNameKo: '췌장 종괴 에코 음영',
    organ: 'pancreas',
    partOfOrgan: ['body', 'neck', 'tail'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'pancreas_mass_presence', triggerValues: ['present'] },
    options: [
      {
        value: 'hypoechoic',
        label: 'Hypoechoic',
        labelKo: '저에코',
        resultText: 'Hypoechoic pancreatic mass; exocrine adenocarcinoma or insulinoma suspected',
        resultTextKo: '저에코 췌장 종괴; 외분비 선암종 또는 인슐린종 의심',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'mixed',
        label: 'Mixed / Cavitating',
        labelKo: '혼합/공동형성',
        resultText: 'Mixed or cavitating pancreatic mass; abscess or necrotic neoplasia suspected',
        resultTextKo: '혼합 또는 공동형성 췌장 종괴; 농양 또는 괴사성 종양 의심',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
];
