import { UltrasoundTestItem } from '../types';

export const smallIntestineTests: UltrasoundTestItem[] = [
  {
    testID: 'si_wall_thickness',
    testName: 'Small Intestine Wall Thickness',
    testNameKo: '소장(공장/회장) 벽 두께',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Dog: 2.0-4.0mm, Cat: ~2.0mm. Ileum up to 3.2mm in cats.',
    normalRange: { dog: { max: 4 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 4, resultText: 'Small intestinal wall thickness within normal limits', resultTextKo: '소장 벽 두께 정상 범위', isAbnormal: false },
      { min: 4, max: 7, resultText: 'Mild small intestinal wall thickening; enteritis or IBD suspected', resultTextKo: '경미한 소장 벽 비후; 장염 또는 IBD 의심', isAbnormal: true, severity: 'mild' },
      { min: 7, max: null, resultText: 'Marked small intestinal wall thickening; neoplasia or severe infiltrative disease suspected', resultTextKo: '현저한 소장 벽 비후; 종양 또는 중증 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
    dogRanges: [
      { min: 0, max: 4, resultText: 'Small intestinal wall thickness within normal limits', resultTextKo: '소장 벽 두께 정상 범위 (개: ≤4mm)', isAbnormal: false },
      { min: 4, max: 7, resultText: 'Mild small intestinal wall thickening; enteritis or IBD suspected', resultTextKo: '경미한 소장 벽 비후; 장염 또는 IBD 의심', isAbnormal: true, severity: 'mild' },
      { min: 7, max: null, resultText: 'Marked small intestinal wall thickening; neoplasia or severe infiltrative disease suspected', resultTextKo: '현저한 소장 벽 비후; 종양 또는 중증 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
    catRanges: [
      { min: 0, max: 2, resultText: 'Small intestinal wall thickness within normal limits', resultTextKo: '소장 벽 두께 정상 범위 (고양이: ≤2mm)', isAbnormal: false },
      { min: 2, max: 3.5, resultText: 'Mild small intestinal wall thickening; enteritis or IBD suspected', resultTextKo: '경미한 소장 벽 비후(>2mm); 장염 또는 IBD 의심', isAbnormal: true, severity: 'mild' },
      { min: 3.5, max: null, resultText: 'Marked small intestinal wall thickening; neoplasia or severe infiltrative disease suspected', resultTextKo: '현저한 소장 벽 비후(>3.5mm); 종양 또는 중증 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_wall_layering',
    testName: 'Small Intestine Wall Layering',
    testNameKo: '소장 벽 층구조',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      { value: 'preserved', label: 'Normal 5-layer preserved', labelKo: '정상 5층 구조 보존', resultText: 'Small intestinal wall 5-layer structure preserved', resultTextKo: '소장 벽 5층 구조 보존', isAbnormal: false },
      { value: 'muscularis_thickening', label: 'Muscularis layer thickening (Cat)', labelKo: '근육층 비후 (고양이)', resultText: 'Muscularis layer thickening relative to submucosa; IBD or low-grade lymphoma suspected', resultTextKo: '점막하층 대비 근육층 비후; IBD 또는 저등급 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'obliterated', label: 'Obliterated (loss of layering)', labelKo: '층구조 소실', resultText: 'Small intestinal wall layering obliterated; neoplasia suspected', resultTextKo: '소장 벽 층구조 소실; 종양 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_motility',
    testName: 'Small Intestine Motility',
    testNameKo: '소장 운동성',
    organ: 'small_intestine',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      { value: 'normal', label: 'Normal peristalsis', labelKo: '정상 연동운동', resultText: 'Small intestinal motility normal', resultTextKo: '소장 운동성 정상', isAbnormal: false },
      { value: 'hypomotility', label: 'Hypomotility / Ileus', labelKo: '저운동성/장폐색', resultText: 'Small intestinal hypomotility or ileus; obstruction suspected', resultTextKo: '소장 저운동성 또는 마비성 장폐색; 폐색 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'si_special_findings',
    testName: 'Special Findings',
    testNameKo: '특이 사항',
    organ: 'small_intestine',
    partOfOrgan: 'general',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'Small intestinal findings: {values}',
    resultTemplateKo: '소장 특이 소견: {values}',
    options: [
      { value: 'intussusception', label: 'Intussusception (Target sign)', labelKo: '장중첩 (Target sign)', resultText: 'Intussusception identified with characteristic target sign', resultTextKo: '장중첩 관찰됨 (특징적인 Target sign)', isAbnormal: true, severity: 'severe' },
      { value: 'foreign_body', label: 'Foreign body suspected', labelKo: '이물 의심', resultText: 'Possible foreign body in small intestine', resultTextKo: '소장 내 이물 가능성', isAbnormal: true, severity: 'severe' },
      { value: 'plication', label: 'Plication (Linear FB)', labelKo: '장분절 주름 형성 (선형 이물)', resultText: 'Intestinal plication observed; linear foreign body suspected', resultTextKo: '장분절 주름 형성 관찰됨; 선형 이물 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_muscularis_severity',
    testName: 'Muscularis Propria Hypertrophy',
    testNameKo: '소장 근육층(muscularis propria) 비후',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '근육층 비후는 IBD, 소세포 림프종, 만성 장염 등에서 관찰됩니다. 고양이에서 특히 중요한 소견입니다.',
    options: [
      { value: 'normal', label: 'Normal muscularis', labelKo: '근육층 정상', resultText: 'Small intestinal muscularis propria normal thickness', resultTextKo: '소장 근육층 두께 정상', isAbnormal: false },
      { value: 'mild', label: 'Mild hypertrophy', labelKo: '경도 비후', resultText: 'Mild small intestinal muscularis hypertrophy; IBD or chronic enteritis suspected', resultTextKo: '경도 소장 근육층 비후; IBD 또는 만성 장염 의심', isAbnormal: true, severity: 'mild' },
      { value: 'moderate', label: 'Moderate hypertrophy', labelKo: '중등도 비후', resultText: 'Moderate small intestinal muscularis hypertrophy; IBD or lymphoma suspected', resultTextKo: '중등도 소장 근육층 비후; IBD 또는 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'severe', label: 'Severe hypertrophy', labelKo: '심한 비후', resultText: 'Severe small intestinal muscularis hypertrophy; lymphoma or infiltrative neoplasia strongly suspected', resultTextKo: '심한 소장 근육층 비후; 림프종 또는 침윤성 종양 강력 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_layer_predominance',
    testName: 'Wall Layer Predominance',
    testNameKo: '소장 비후 우세층',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'si_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '점막·점막하층 우세 → IBD, 근육층 우세 → 소세포 림프종(고양이), 전층 균등 → 대세포 림프종/선암종',
    options: [
      { value: 'mucosal_submucosal', label: 'Mucosal / submucosal predominance', labelKo: '점막·점막하층 우세', resultText: 'Small intestinal wall thickening predominantly mucosal/submucosal; IBD pattern', resultTextKo: '소장 점막·점막하층 우세 비후; IBD 패턴', isAbnormal: true, severity: 'mild' },
      { value: 'muscularis', label: 'Muscularis predominance', labelKo: '근육층 우세', resultText: 'Small intestinal wall thickening predominantly muscularis; small cell lymphoma suspected', resultTextKo: '소장 근육층 우세 비후; 소세포 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'transmural', label: 'Transmural / uniform', labelKo: '전층 균등 비후', resultText: 'Small intestinal transmural uniform thickening; large cell lymphoma or adenocarcinoma suspected', resultTextKo: '소장 전층 균등 비후; 대세포 림프종 또는 선암종 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_muscularis_thickness',
    testName: 'Muscularis Propria Thickness (measured)',
    testNameKo: '소장 근육층 두께 (측정값)',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'si_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '선택 입력. 근육층만 분리 측정 시 기록 (정상 <2mm).',
    normalRange: { dog: { max: 2 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 2, resultText: 'Small intestinal muscularis thickness within normal limits', resultTextKo: '소장 근육층 두께 정상 범위', isAbnormal: false },
      { min: 2, max: null, resultText: 'Small intestinal muscularis thickening >2mm', resultTextKo: '소장 근육층 비후 >2mm', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'si_mucosal_striations',
    testName: 'Hyperechoic Mucosal Striations',
    testNameKo: '고에코 점막 선조 (Hyperechoic mucosal striations)',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '점막층에서 관찰되는 밝은 흰색 선조. 유미관(lacteal) 확장을 의미하며 IBD·림프관확장증·단백소실성장병증(PLE)에서 관찰됩니다. 고양이 소세포 림프종에서도 흔히 관찰됩니다.',
    positiveResultText: 'Hyperechoic mucosal striations present in small intestine; lacteal dilation — IBD, lymphangiectasia, or PLE suspected',
    positiveResultTextKo: '소장 고에코 점막 선조 관찰; 유미관 확장 — IBD, 림프관확장증, 단백소실성장병증(PLE) 감별 필요',
    positiveOwnerResultTextKo: '소장 점막에서 밝은 흰 줄 무늬가 관찰됩니다. 장 점막의 림프관 확장 또는 염증성 장 질환과 관련될 수 있습니다.',
    negativeResultText: 'No hyperechoic mucosal striations in small intestine',
    negativeResultTextKo: '소장 고에코 점막 선조 없음',
    negativeOwnerResultTextKo: '소장 점막에서 특별한 이상 줄무늬는 관찰되지 않습니다.',
    positiveIsAbnormal: true,
  },
];
