import { UltrasoundTestItem } from '../types';

export const smallIntestineTests: UltrasoundTestItem[] = [
  {
    testID: 'si_wall_thickness',
    testName: 'Small Intestine Wall Thickness',
    testNameKo: '소장(공장/회장) 벽 두께',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Dog: 2.0-4.0mm, Cat: ~2.0mm. Ileum up to 3.2mm in cats.',
    normalRange: { dog: { max: 4 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 4, resultText: 'Small intestinal wall thickness within normal limits', resultTextKo: '소장 벽 두께 정상 범위', isAbnormal: false },
      { min: 4, max: 7, resultText: 'Mild small intestinal wall thickening; enteritis or IBD suspected', resultTextKo: '경미한 소장 벽 비후; 장염 또는 IBD 의심', isAbnormal: true, severity: 'mild' },
      { min: 7, max: null, resultText: 'Marked small intestinal wall thickening; neoplasia or severe infiltrative disease suspected', resultTextKo: '현저한 소장 벽 비후; 종양 또는 중증 침윤성 질환 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_wall_layering',
    testName: 'Small Intestine Wall Layering',
    testNameKo: '소장 벽 층구조',
    organ: 'small_intestine',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      { value: 'preserved', label: 'Normal 5-layer preserved', labelKo: '정상 5층 구조 보존', resultText: 'Small intestinal wall 5-layer structure preserved', resultTextKo: '소장 벽 5층 구조 보존', isAbnormal: false },
      { value: 'muscularis_thickening', label: 'Muscularis layer thickening (Cat)', labelKo: '근육층 비후 (고양이)', resultText: 'Muscularis layer thickening relative to submucosa; IBD or low-grade lymphoma suspected', resultTextKo: '점막하층 대비 근육층 비후; IBD 또는 저등급 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'obliterated', label: 'Obliterated (loss of layering)', labelKo: '층구조 소실', resultText: 'Small intestinal wall layering obliterated; neoplasia suspected', resultTextKo: '소장 벽 층구조 소실; 종양 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'si_motility',
    testName: 'Small Intestine Motility',
    testNameKo: '소장 운동성',
    organ: 'small_intestine',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      { value: 'normal', label: 'Normal peristalsis', labelKo: '정상 연동운동', resultText: 'Small intestinal motility normal', resultTextKo: '소장 운동성 정상', isAbnormal: false },
      { value: 'hypomotility', label: 'Hypomotility / Ileus', labelKo: '저운동성/장폐색', resultText: 'Small intestinal hypomotility or ileus; obstruction suspected', resultTextKo: '소장 저운동성 또는 마비성 장폐색; 폐색 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'si_special_findings',
    testName: 'Special Findings',
    testNameKo: '특이 사항',
    organ: 'small_intestine',
    partOfOrgan: 'general',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'Small intestinal findings: {values}',
    resultTemplateKo: '소장 특이 소견: {values}',
    options: [
      { value: 'intussusception', label: 'Intussusception (Target sign)', labelKo: '장중첩 (Target sign)', resultText: 'Intussusception identified with characteristic target sign', resultTextKo: '장중첩 관찰됨 (특징적인 Target sign)', isAbnormal: true, severity: 'severe' },
      { value: 'foreign_body', label: 'Foreign body suspected', labelKo: '이물 의심', resultText: 'Possible foreign body in small intestine', resultTextKo: '소장 내 이물 가능성', isAbnormal: true, severity: 'severe' },
      { value: 'plication', label: 'Plication (Linear FB)', labelKo: '장분절 주름 형성 (선형 이물)', resultText: 'Intestinal plication observed; linear foreign body suspected', resultTextKo: '장분절 주름 형성 관찰됨; 선형 이물 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
];
