import { UltrasoundTestItem } from '../types';

export const spleenTests: UltrasoundTestItem[] = [
  {
    testID: 'organ_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'spleen',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'surgical_removal', label: 'Surgical removal', labelKo: '수술적 적출', resultText: 'Previously removed surgically', resultTextKo: '기존 수술을 통해 적출됨', isAbnormal: true },
      { value: 'congenital_absence', label: 'Congenital absence / Agenesis', labelKo: '선천적 결손', resultText: 'Congenital absence / agenesis', resultTextKo: '선천적 결손/미발달', isAbnormal: true },
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
      { value: 'ectopic', label: 'Ectopic location', labelKo: '이소성 위치', resultText: 'Ectopic location suspected', resultTextKo: '이소성 위치 의심', isAbnormal: true },
    ],
  },
  {
    testID: 'spleen_echogenicity',
    testName: 'Splenic Echogenicity',
    testNameKo: '비장 에코 음영',
    organ: 'spleen',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    relatedTests: ['spleen_size', 'spleen_texture'],
    options: [
      {
        value: 'normal',
        label: 'Normal (homogeneous, mildly hyperechoic to liver)',
        labelKo: '정상 (균질, 간보다 약간 고에코)',
        resultText: 'Splenic echogenicity within normal limits',
        resultTextKo: '비장 에코 음영 정상 범위',
        ownerResultTextKo: '비장의 밝기가 정상입니다.',
        isAbnormal: false,
      },
      {
        value: 'hyperechoic',
        label: 'Hyperechoic / Heterogeneous',
        labelKo: '고에코/불균질',
        resultText: 'Increased or heterogeneous splenic echogenicity; diffuse infiltration or neoplasia suspected',
        resultTextKo: '비장 에코 음영 증가 또는 불균질; 미만성 침윤 또는 종양 의심',
        ownerResultTextKo: '비장의 밝기가 평소보다 밝거나 균일하지 않습니다. 만성적인 변화가 의심됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'hypoechoic',
        label: 'Hypoechoic',
        labelKo: '저에코',
        resultText: 'Decreased splenic echogenicity; congestion or lymphoma suspected',
        resultTextKo: '비장 에코 음영 감소; 울혈 또는 림프종 의심',
        ownerResultTextKo: '비장의 밝기가 어둡게 보입니다. 혈액 정체나 종양성 변화 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'spleen_size',
    testName: 'Splenic Size',
    testNameKo: '비장 크기',
    organ: 'spleen',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      {
        value: 'normal',
        label: 'Normal',
        labelKo: '정상',
        resultText: 'Spleen size within normal limits',
        resultTextKo: '비장 크기 정상',
        ownerResultTextKo: '비장의 크기가 정상입니다.',
        isAbnormal: false,
      },
      {
        value: 'splenomegaly_mild',
        label: 'Mild splenomegaly',
        labelKo: '경미한 비장 비대',
        resultText: 'Mild splenomegaly noted',
        resultTextKo: '경미한 비장 비대 소견',
        ownerResultTextKo: '비장이 약간 커져 있습니다. 가벼운 염증 등이 원인일 수 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'splenomegaly_marked',
        label: 'Marked splenomegaly',
        labelKo: '현저한 비장 비대',
        resultText: 'Marked splenomegaly; neoplasia, congestion, or haematopoietic disease suspected',
        resultTextKo: '현저한 비장 비대; 종양, 울혈 또는 조혈계 질환 의심',
        ownerResultTextKo: '비장이 상당히 커져 있습니다. 종양이나 혈액 질환 등의 정밀 검사가 필요합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'spleen_nodule_presence',
    testName: 'Splenic Nodule / Mass Presence',
    testNameKo: '비장 결절/종괴 유무',
    organ: 'spleen',
    partOfOrgan: 'diffuse',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Haemangiosarcoma risk is high in GSDs and Golden Retrievers',
    options: [
      {
        value: 'absent',
        label: 'No nodule / mass',
        labelKo: '결절/종괴 없음',
        resultText: 'No focal splenic lesion identified',
        resultTextKo: '비장 내 국소 병변 관찰되지 않음',
        ownerResultTextKo: '비장 내 이상 병변은 보이지 않습니다.',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Nodule / Mass present',
        labelKo: '결절/종괴 있음',
        resultText: 'Focal splenic lesion(s) identified; see details below',
        resultTextKo: '비장 내 국소 병변 관찰; 세부 항목 참조',
        ownerResultTextKo: '비장 내에 혹(결절/종괴)이 관찰됩니다. 성상 확인을 위한 추가 검사가 필요할 수 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'spleen_nodule_number',
    testName: 'Splenic Nodule Number',
    testNameKo: '비장 결절 개수',
    organ: 'spleen',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'spleen_nodule_presence', triggerValues: ['present'] },
    options: [
      {
        value: 'solitary',
        label: 'Solitary (single)',
        labelKo: '단발성 (1개)',
        resultText: 'Single splenic focal lesion',
        resultTextKo: '단발성 비장 국소 병변',
        ownerResultTextKo: '비장에 한 개의 혹이 관찰됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'few',
        label: 'Few (2–3)',
        labelKo: '소수 (2-3개)',
        resultText: 'Few (2–3) splenic focal lesions',
        resultTextKo: '소수(2-3개) 비장 국소 병변',
        ownerResultTextKo: '비장에 몇 개의 혹이 관찰됩니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'multiple',
        label: 'Multiple (≥4)',
        labelKo: '다발성 (4개 이상)',
        resultText: 'Multiple (≥4) splenic focal lesions; multifocal haemangiosarcoma or nodular hyperplasia suspected',
        resultTextKo: '다발성(4개 이상) 비장 국소 병변; 다발성 혈관육종 또는 결절성 과증식 의심',
        ownerResultTextKo: '비장에 다수의 혹이 퍼져 있습니다. 종양성 변화에 대한 정밀 검사가 강력히 권장됩니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'spleen_nodule_size',
    testName: 'Splenic Nodule / Mass Size (largest)',
    testNameKo: '비장 결절/종괴 크기 (최대 병변)',
    organ: 'spleen',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'spleen_nodule_presence', triggerValues: ['present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0,
        max: 1,
        resultText: 'Splenic nodule <1 cm; nodular hyperplasia vs neoplasia, monitoring recommended',
        resultTextKo: '1cm 미만 비장 결절; 결절성 과증식 vs 종양성 감별, 모니터링 권장',
        ownerResultTextKo: '1cm 미만의 작은 결절이 보입니다. 정기적인 추적 관찰이 필요합니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 1,
        max: 3,
        resultText: 'Splenic nodule/mass 1–3 cm; haemangiosarcoma or nodular hyperplasia suspected; cytology recommended',
        resultTextKo: '1-3cm 비장 결절/종괴; 혈관육종 또는 결절성 과증식 의심; 세포 검사 권장',
        ownerResultTextKo: '1~3cm 크기의 종괴가 보입니다. 세포 검사 등을 통해 성상을 확인하는 것이 좋습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        min: 3,
        max: null,
        resultText: 'Splenic mass >3 cm; haemangiosarcoma suspected; surgical evaluation recommended',
        resultTextKo: '3cm 초과 비장 종괴; 혈관육종 의심; 외과적 평가 권장',
        ownerResultTextKo: '3cm가 넘는 큰 종괴가 관찰됩니다. 수술적 처치나 정밀 검사가 즉시 필요할 수 있습니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'spleen_nodule_echogenicity',
    testName: 'Splenic Nodule Echogenicity',
    testNameKo: '비장 결절 에코 음영',
    organ: 'spleen',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'spleen_nodule_presence', triggerValues: ['present'] },
    options: [
      {
        value: 'hyperechoic_nodule',
        label: 'Hyperechoic',
        labelKo: '고에코',
        resultText: 'Hyperechoic splenic nodule; myelolipoma or nodular hyperplasia suspected',
        resultTextKo: '고에코 비장 결절; 골수지방종 또는 결절성 과증식 의심',
        ownerResultTextKo: '밝게 보이는 혹이 관찰됩니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'hypoechoic_nodule',
        label: 'Hypoechoic / Anechoic',
        labelKo: '저에코/무에코',
        resultText: 'Hypoechoic/anechoic splenic nodule; haemangiosarcoma, haematoma, or cyst suspected',
        resultTextKo: '저에코/무에코 비장 결절; 혈관육종, 혈종 또는 낭종 의심',
        ownerResultTextKo: '어둡거나 비어 보이는 혹이 관찰됩니다. 혈종이나 종양의 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'mixed_nodule',
        label: 'Mixed / Heterogeneous',
        labelKo: '혼합/불균질',
        resultText: 'Mixed echogenicity splenic lesion; malignant neoplasia suspected',
        resultTextKo: '혼합 에코 비장 병변; 악성 종양 의심',
        ownerResultTextKo: '밝고 어두운 부분이 섞여 있는 복잡한 혹이 관찰됩니다. 주의 깊은 평가가 필요합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
  {
    testID: 'spleen_nodule_margin',
    testName: 'Splenic Nodule Margin',
    testNameKo: '비장 결절 경계',
    organ: 'spleen',
    partOfOrgan: ['solitary', 'multiple'],
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'spleen_nodule_presence', triggerValues: ['present'] },
    options: [
      {
        value: 'well_defined',
        label: 'Well-defined / Smooth',
        labelKo: '경계 명확/매끈',
        resultText: 'Splenic lesion with well-defined smooth margin; benign lesion more likely',
        resultTextKo: '경계 명확하고 매끈한 비장 병변; 양성 병변 가능성 높음',
        ownerResultTextKo: '혹의 경계가 매끈하고 명확합니다. 양성일 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'ill_defined',
        label: 'Ill-defined / Irregular',
        labelKo: '경계 불명확/불규칙',
        resultText: 'Splenic lesion with ill-defined or irregular margin; malignant neoplasia suspected',
        resultTextKo: '경계 불명확하거나 불규칙한 비장 병변; 악성 종양 의심',
        ownerResultTextKo: '혹의 경계가 불규칙하거나 흐릿합니다. 악성 종양 가능성을 고려해야 합니다.',
        isAbnormal: true,
        severity: 'severe',
      },
    ],
  },
];
