import { UltrasoundTestItem } from '../types';

export const stomachTests: UltrasoundTestItem[] = [
  {
    testID: 'stomach_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'stomach',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
    ],
  },
  {
    testID: 'stomach_wall_thickness',
    testName: 'Stomach Wall Thickness',
    testNameKo: '위 벽 두께',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Dog: 3.0-5.0mm, Cat: <2.0mm. Measured between rugal folds.',
    normalRange: { dog: { max: 5 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 5, resultText: 'Stomach wall thickness within normal limits', resultTextKo: '위 벽 두께 정상 범위', isAbnormal: false },
      { min: 5, max: 8, resultText: 'Mild stomach wall thickening; gastritis or early neoplasia suspected', resultTextKo: '경미한 위 벽 비후; 위염 또는 초기 종양 의심', isAbnormal: true, severity: 'mild' },
      { min: 8, max: null, resultText: 'Marked stomach wall thickening (>8mm); neoplasia (lymphoma, adenocarcinoma) suspected', resultTextKo: '현저한 위 벽 비후(>8mm); 종양 (림프종, 선암종) 의심', isAbnormal: true, severity: 'severe' },
    ],
    dogRanges: [
      { min: 0, max: 5, resultText: 'Stomach wall thickness within normal limits', resultTextKo: '위 벽 두께 정상 범위 (개: ≤5mm)', isAbnormal: false },
      { min: 5, max: 8, resultText: 'Mild stomach wall thickening', resultTextKo: '경미한 위 벽 비후; 위염 또는 초기 종양 의심', isAbnormal: true, severity: 'mild' },
      { min: 8, max: null, resultText: 'Marked stomach wall thickening (>8mm)', resultTextKo: '현저한 위 벽 비후(>8mm); 종양 (림프종, 선암종) 의심', isAbnormal: true, severity: 'severe' },
    ],
    catRanges: [
      { min: 0, max: 2, resultText: 'Stomach wall thickness within normal limits', resultTextKo: '위 벽 두께 정상 범위 (고양이: ≤2mm)', isAbnormal: false },
      { min: 2, max: 4, resultText: 'Mild stomach wall thickening; gastritis or early neoplasia suspected', resultTextKo: '경미한 위 벽 비후(>2mm); 위염 또는 초기 종양 의심', isAbnormal: true, severity: 'mild' },
      { min: 4, max: null, resultText: 'Marked stomach wall thickening (>4mm); neoplasia (lymphoma) suspected', resultTextKo: '현저한 위 벽 비후(>4mm); 종양 (림프종) 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'stomach_wall_layering',
    testName: 'Stomach Wall Layering',
    testNameKo: '위 벽 층구조',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      { value: 'preserved', label: 'Normal 5-layer preserved', labelKo: '정상 5층 구조 보존', resultText: 'Stomach wall 5-layer structure preserved', resultTextKo: '위 벽 5층 구조 보존', isAbnormal: false },
      { value: 'indistinct', label: 'Indistinct layers', labelKo: '층구조 불명확', resultText: 'Stomach wall layering indistinct; infiltrative gastritis or lymphoma suspected', resultTextKo: '위 벽 층구조 불명확; 침윤성 위염 또는 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'obliterated', label: 'Obliterated (loss of layering)', labelKo: '층구조 소실', resultText: 'Stomach wall layering obliterated; neoplasia strongly suspected', resultTextKo: '위 벽 층구조 소실; 종양 강력 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'stomach_motility',
    testName: 'Stomach Motility',
    testNameKo: '위 운동성',
    organ: 'stomach',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      { value: 'normal', label: 'Normal peristalsis', labelKo: '정상 연동운동', resultText: 'Stomach motility normal', resultTextKo: '위 운동성 정상', isAbnormal: false },
      { value: 'hypomotility', label: 'Hypomotility', labelKo: '저운동성', resultText: 'Stomach hypomotility; functional or mechanical outflow obstruction suspected', resultTextKo: '위 저운동성; 기능적 또는 기계적 배출 폐쇄 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'stomach_content',
    testName: 'Stomach Content',
    testNameKo: '위 내강물',
    organ: 'stomach',
    partOfOrgan: 'lumen',
    testType: 'multiselect',
    clinicalSignificance: 'low',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'Stomach contents: {values}',
    resultTemplateKo: '위 내강물: {values}',
    options: [
      { value: 'empty', label: 'Empty', labelKo: '비어있음', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'food', label: 'Food material', labelKo: '음식물', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'gas', label: 'Gas', labelKo: '가스', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'fluid', label: 'Fluid', labelKo: '액체', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'foreign_body', label: 'Foreign body suspected', labelKo: '이물 의심', resultText: 'Possible foreign body in stomach', resultTextKo: '위 내 이물 가능성', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'stomach_muscularis_severity',
    testName: 'Muscularis Propria Hypertrophy',
    testNameKo: '위 근육층(muscularis propria) 비후',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '근육층 비후는 소세포 림프종(small cell lymphoma), IBD, 만성 위염 등에서 관찰됩니다.',
    options: [
      { value: 'normal', label: 'Normal muscularis', labelKo: '근육층 정상', resultText: 'Muscularis propria normal thickness', resultTextKo: '위 근육층 두께 정상', isAbnormal: false },
      { value: 'mild', label: 'Mild hypertrophy', labelKo: '경도 비후', resultText: 'Mild muscularis hypertrophy; IBD or chronic gastritis suspected', resultTextKo: '경도 위 근육층 비후; IBD 또는 만성 위염 의심', isAbnormal: true, severity: 'mild' },
      { value: 'moderate', label: 'Moderate hypertrophy', labelKo: '중등도 비후', resultText: 'Moderate muscularis hypertrophy; IBD or lymphoma suspected', resultTextKo: '중등도 위 근육층 비후; IBD 또는 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'severe', label: 'Severe hypertrophy', labelKo: '심한 비후', resultText: 'Severe muscularis hypertrophy; lymphoma or infiltrative neoplasia strongly suspected', resultTextKo: '심한 위 근육층 비후; 림프종 또는 침윤성 종양 강력 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'stomach_layer_predominance',
    testName: 'Wall Layer Predominance',
    testNameKo: '위 비후 우세층',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'stomach_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '점막·점막하층 우세 → IBD, 근육층 우세 → 소세포 림프종(cats), 전층 균등 → 대세포 림프종/선암종',
    options: [
      { value: 'mucosal_submucosal', label: 'Mucosal / submucosal predominance', labelKo: '점막·점막하층 우세', resultText: 'Wall thickening predominantly mucosal/submucosal; IBD pattern', resultTextKo: '점막·점막하층 우세 비후; IBD 패턴', isAbnormal: true, severity: 'mild' },
      { value: 'muscularis', label: 'Muscularis predominance', labelKo: '근육층 우세', resultText: 'Wall thickening predominantly muscularis; small cell lymphoma suspected (esp. cats)', resultTextKo: '근육층 우세 비후; 소세포 림프종 의심 (특히 고양이)', isAbnormal: true, severity: 'moderate' },
      { value: 'transmural', label: 'Transmural / uniform', labelKo: '전층 균등 비후', resultText: 'Transmural uniform wall thickening; large cell lymphoma or adenocarcinoma suspected', resultTextKo: '전층 균등 비후; 대세포 림프종 또는 선암종 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'stomach_muscularis_thickness',
    testName: 'Muscularis Propria Thickness (measured)',
    testNameKo: '위 근육층 두께 (측정값)',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'stomach_muscularis_severity', triggerValues: ['mild', 'moderate', 'severe'] },
    note: '선택 입력. 근육층만 분리 측정 시 기록 (일반적으로 정상 <2mm).',
    normalRange: { dog: { max: 2 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 2, resultText: 'Muscularis thickness within normal limits', resultTextKo: '위 근육층 두께 정상 범위', isAbnormal: false },
      { min: 2, max: null, resultText: 'Muscularis thickening >2mm', resultTextKo: '위 근육층 비후 >2mm', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'stomach_mucosal_striations',
    testName: 'Hyperechoic Mucosal Striations',
    testNameKo: '고에코 점막 선조 (Hyperechoic mucosal striations)',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    note: '점막층에서 관찰되는 밝은 흰색 선조. 확장된 유미관(lacteal) 또는 림프관을 의미하며, IBD·림프관확장증·단백소실성장병증(PLE)에서 관찰됩니다.',
    positiveResultText: 'Hyperechoic mucosal striations present; lacteal dilation suspected — IBD, lymphangiectasia, or PLE',
    positiveResultTextKo: '고에코 점막 선조 관찰; 유미관(lacteal) 확장 의심 — IBD, 림프관확장증, 단백소실성장병증(PLE) 감별 필요',
    positiveOwnerResultTextKo: '위 점막에서 밝은 흰 줄 무늬가 관찰됩니다. 장 점막의 림프관 확장 또는 염증성 장 질환과 관련될 수 있습니다.',
    negativeResultText: 'No hyperechoic mucosal striations',
    negativeResultTextKo: '고에코 점막 선조 없음',
    negativeOwnerResultTextKo: '점막에서 특별한 이상 줄무늬는 관찰되지 않습니다.',
    positiveIsAbnormal: true,
  },
];
