import { UltrasoundTestItem } from '../types';

export const stomachTests: UltrasoundTestItem[] = [
  {
    testID: 'stomach_absent_reason',
    testName: 'Reason for Absence',
    testNameKo: '장기 결손/적출 사유',
    organ: 'stomach',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    dependsOn: { testID: 'organ_status', triggerValues: ['absent'] },
    options: [
      { value: 'not_identified', label: 'Not identified (Gas, etc.)', labelKo: '관찰 불가 (가스 등)', resultText: 'Not identified on ultrasound', resultTextKo: '초음파상 관찰되지 않음', isAbnormal: true },
    ],
  },
  {
    testID: 'stomach_wall_thickness',
    testName: 'Stomach Wall Thickness',
    testNameKo: '위 벽 두께',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Dog: 3.0-5.0mm, Cat: <2.0mm. Measured between rugal folds.',
    normalRange: { dog: { max: 5 }, cat: { max: 2 } },
    ranges: [
      { min: 0, max: 5, resultText: 'Stomach wall thickness within normal limits', resultTextKo: '위 벽 두께 정상 범위', isAbnormal: false },
      { min: 5, max: 8, resultText: 'Mild stomach wall thickening; gastritis or early neoplasia suspected', resultTextKo: '경미한 위 벽 비후; 위염 또는 초기 종양 의심', isAbnormal: true, severity: 'mild' },
      { min: 8, max: null, resultText: 'Marked stomach wall thickening (>8mm); neoplasia (lymphoma, adenocarcinoma) suspected', resultTextKo: '현저한 위 벽 비후(>8mm); 종양 (림프종, 선암종) 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'stomach_wall_layering',
    testName: 'Stomach Wall Layering',
    testNameKo: '위 벽 층구조',
    organ: 'stomach',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    options: [
      { value: 'preserved', label: 'Normal 5-layer preserved', labelKo: '정상 5층 구조 보존', resultText: 'Stomach wall 5-layer structure preserved', resultTextKo: '위 벽 5층 구조 보존', isAbnormal: false },
      { value: 'indistinct', label: 'Indistinct layers', labelKo: '층구조 불명확', resultText: 'Stomach wall layering indistinct; infiltrative gastritis or lymphoma suspected', resultTextKo: '위 벽 층구조 불명확; 침윤성 위염 또는 림프종 의심', isAbnormal: true, severity: 'moderate' },
      { value: 'obliterated', label: 'Obliterated (loss of layering)', labelKo: '층구조 소실', resultText: 'Stomach wall layering obliterated; neoplasia strongly suspected', resultTextKo: '위 벽 층구조 소실; 종양 강력 의심', isAbnormal: true, severity: 'severe' },
    ],
  },
  {
    testID: 'stomach_motility',
    testName: 'Stomach Motility',
    testNameKo: '위 운동성',
    organ: 'stomach',
    partOfOrgan: 'general',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 1,
    options: [
      { value: 'normal', label: 'Normal peristalsis', labelKo: '정상 연동운동', resultText: 'Stomach motility normal', resultTextKo: '위 운동성 정상', isAbnormal: false },
      { value: 'hypomotility', label: 'Hypomotility', labelKo: '저운동성', resultText: 'Stomach hypomotility; functional or mechanical outflow obstruction suspected', resultTextKo: '위 저운동성; 기능적 또는 기계적 배출 폐쇄 의심', isAbnormal: true, severity: 'moderate' },
    ],
  },
  {
    testID: 'stomach_content',
    testName: 'Stomach Content',
    testNameKo: '위 내강물',
    organ: 'stomach',
    partOfOrgan: 'lumen',
    testType: 'multiselect',
    clinicalSignificance: 'low',
    species: 'both',
    required: false,
    displayLevel: 1,
    resultTemplate: 'Stomach contents: {values}',
    resultTemplateKo: '위 내강물: {values}',
    options: [
      { value: 'empty', label: 'Empty', labelKo: '비어있음', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'food', label: 'Food material', labelKo: '음식물', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'gas', label: 'Gas', labelKo: '가스', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'fluid', label: 'Fluid', labelKo: '액체', resultText: '', resultTextKo: '', isAbnormal: false },
      { value: 'foreign_body', label: 'Foreign body suspected', labelKo: '이물 의심', resultText: 'Possible foreign body in stomach', resultTextKo: '위 내 이물 가능성', isAbnormal: true, severity: 'moderate' },
    ],
  },
];
