import { UltrasoundTestItem } from '../types';

export const urinaryBladderTests: UltrasoundTestItem[] = [
  {
    testID: 'ub_wall_thickness',
    testName: 'Urinary Bladder Wall Thickness',
    testNameKo: '방광벽 두께',
    organ: 'urinary_bladder',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Measure when moderately distended. Empty bladder has physiologically thicker wall.',
    normalRange: {
      dog: { max: 2 },
      cat: { max: 1.5 },
    },
    ranges: [
      {
        min: 0,
        max: 2,
        resultText: 'Urinary bladder wall within normal limits',
        resultTextKo: '방광벽 두께 정상 범위',
        ownerResultTextKo: '방광 벽의 두께가 정상입니다.',
        isAbnormal: false,
      },
      {
        min: 2,
        max: 4,
        resultText: 'Mild urinary bladder wall thickening; cystitis suspected',
        resultTextKo: '경미한 방광벽 비후; 방광염 의심',
        ownerResultTextKo: '방광 벽이 약간 두꺼워져 있습니다. 방광염 가능성이 있습니다.',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        min: 4,
        max: null,
        resultText: 'Marked urinary bladder wall thickening; neoplasia, chronic cystitis, or polypoid cystitis suspected',
        resultTextKo: '현저한 방광벽 비후; 종양, 만성 방광염 또는 폴립성 방광염 의심',
        ownerResultTextKo: '방광 벽이 매우 두껍게 부어 있습니다. 만성적인 염증이나 종양 확인이 필요합니다.',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'ub_content',
    testName: 'Urinary Bladder Contents',
    testNameKo: '방광 내용물',
    organ: 'urinary_bladder',
    partOfOrgan: 'lumen',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    resultTemplate: 'Urinary bladder contents: {values}',
    resultTemplateKo: '방광 내용물: {values}',
    resultTemplateOwnerKo: '방광 내부에 다음 내용물들이 관찰됩니다: {values}',
    options: [
      {
        value: 'anechoic',
        label: 'Anechoic (normal urine)',
        labelKo: '무에코 (정상 소변)',
        resultText: 'anechoic urine (normal)',
        resultTextKo: '무에코 소변 (정상)',
        ownerResultTextKo: '깨끗한 소변 (정상)',
        isAbnormal: false,
      },
      {
        value: 'sediment',
        label: 'Echogenic sediment',
        labelKo: '에코성 침전물',
        resultText: 'echogenic sediment (crystalluria/pyuria)',
        resultTextKo: '에코성 침전물 (결정뇨/농뇨)',
        ownerResultTextKo: '소변 찌꺼기(슬러지)',
        isAbnormal: true,
        severity: 'mild',
      },
      {
        value: 'cystic_calculi',
        label: 'Cystic calculi',
        labelKo: '방광결석',
        resultText: 'cystic calculi with acoustic shadowing',
        resultTextKo: '음향 음영을 동반한 방광결석',
        ownerResultTextKo: '방광결석(돌)',
        isAbnormal: true,
        severity: 'moderate',
      },
      {
        value: 'mass',
        label: 'Intraluminal mass',
        labelKo: '방광 내강 내 종괴',
        resultText: 'intraluminal bladder mass; transitional cell carcinoma suspected',
        resultTextKo: '방광 내강 내 종괴; 이행상피세포암 의심',
        ownerResultTextKo: '방광 내 혹(덩어리)',
        isAbnormal: true,
        severity: 'severe',
      },
      {
        value: 'blood_clot',
        label: 'Blood clot',
        labelKo: '혈액 응괴',
        resultText: 'echogenic non-shadowing intraluminal material consistent with blood clot',
        resultTextKo: '음향 음영 없는 에코성 내강 내 물질; 혈액 응괴에 합당',
        ownerResultTextKo: '피떡(혈괴)',
        isAbnormal: true,
        severity: 'moderate',
      },
    ],
  },
  {
    testID: 'ub_mass_presence',
    testName: 'Bladder Mass / Mural Lesion Presence',
    testNameKo: '방광 종괴/벽 내 병변 유무',
    organ: 'urinary_bladder',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'high',
    species: 'both',
    required: true,
    displayLevel: 1,
    note: 'Trigone-based mass in dogs is highly suspicious for TCC/urothelial carcinoma',
    options: [
      {
        value: 'absent',
        label: 'No intraluminal or mural mass',
        labelKo: '방광 내강/벽 내 종괴 없음',
        resultText: 'No bladder mass or mural lesion identified',
        resultTextKo: '방광 종괴 또는 벽 내 병변 관찰되지 않음',
        ownerResultTextKo: '방광 내부나 벽에 혹 또는 덩어리는 보이지 않습니다.',
        isAbnormal: false,
      },
      {
        value: 'present',
        label: 'Mass / Mural lesion present',
        labelKo: '종괴/벽 내 병변 있음',
        resultText: 'Bladder mass or mural lesion identified; see details below',
        resultTextKo: '방광 종괴 또는 벽 내 병변 관찰; 세부 항목 참조',
        ownerResultTextKo: '방광 내부나 벽에서 혹 같은 변화가 관찰됩니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'ub_mass_location',
    testName: 'Bladder Mass Location',
    testNameKo: '방광 종괴 위치',
    organ: 'urinary_bladder',
    partOfOrgan: 'wall',
    testType: 'multiselect',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'ub_mass_presence', triggerValues: ['present'] },
    resultTemplate: 'Bladder mass location(s): {values}',
    resultTemplateKo: '방광 종괴 위치: {values}',
    resultTemplateOwnerKo: '다음 부위에서 방광 종괴(혹)가 확인됩니다: {values}',
    note: 'Trigone location highly suspicious for TCC',
    options: [
      {
        value: 'trigone',
        label: 'Trigone',
        labelKo: '삼각부',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
      {
        value: 'cranial',
        label: 'Cranial / Apex',
        labelKo: '전방/첨부',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'lateral_wall',
        label: 'Lateral wall',
        labelKo: '측벽',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'diffuse',
        label: 'Diffuse / Circumferential',
        labelKo: '미만성/전주',
        resultText: '',
        resultTextKo: '',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'ub_mass_size',
    testName: 'Bladder Mass Size',
    testNameKo: '방광 종괴 크기',
    organ: 'urinary_bladder',
    partOfOrgan: 'wall',
    testType: 'range',
    unit: 'cm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'ub_mass_presence', triggerValues: ['present'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 1,
        resultText: 'Small bladder mass <1 cm; polyp or early neoplasia suspected',
        resultTextKo: '1cm 미만 소형 방광 종괴; 폴립 또는 초기 종양 의심',
        ownerResultTextKo: '방광에 1cm 미만의 작은 혹이 보입니다. 폴립(양성)이나 초기 종양일 수 있습니다.',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 1, max: 3,
        resultText: 'Bladder mass 1–3 cm; transitional cell carcinoma suspected; cystoscopy or biopsy recommended',
        resultTextKo: '1-3cm 방광 종괴; 이행상피세포암 의심; 방광경 검사 또는 생검 권장',
        ownerResultTextKo: '1~3cm 크기의 혹이 관찰됩니다. 악성 종양 여부를 확인하기 위해 정밀 검사가 권장됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 3, max: null,
        resultText: 'Large bladder mass >3 cm; advanced transitional cell carcinoma suspected',
        resultTextKo: '3cm 초과 대형 방광 종괴; 진행성 이행상피세포암 의심',
        ownerResultTextKo: '3cm 이상의 큰 종괴가 관찰됩니다. 진행된 상태의 암종일 가능성이 높습니다.',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'ub_mass_echogenicity',
    testName: 'Bladder Mass Echogenicity',
    testNameKo: '방광 종괴 에코 음영',
    organ: 'urinary_bladder',
    partOfOrgan: 'wall',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'ub_mass_presence', triggerValues: ['present'] },
    options: [
      {
        value: 'hyperechoic',
        label: 'Hyperechoic (polypoid)',
        labelKo: '고에코 (폴립성)',
        resultText: 'Hyperechoic bladder mass consistent with polypoid cystitis or benign polyp',
        resultTextKo: '고에코 방광 종괴; 폴립성 방광염 또는 양성 폴립에 합당',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'hypoechoic',
        label: 'Hypoechoic / Mixed',
        labelKo: '저에코/혼합',
        resultText: 'Hypoechoic or mixed bladder mass; transitional cell carcinoma suspected',
        resultTextKo: '저에코 또는 혼합 에코 방광 종괴; 이행상피세포암 의심',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
  {
    testID: 'ub_calculi_presence',
    testName: 'Cystic Calculi Presence',
    testNameKo: '방광결석 유무',
    organ: 'urinary_bladder',
    partOfOrgan: 'lumen',
    testType: 'boolean',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 1,
    positiveResultText: 'Cystic calculi identified with acoustic shadowing',
    positiveResultTextKo: '음향 음영을 동반한 방광결석 관찰',
    positiveOwnerResultTextKo: '방광 내부에 결석(돌)이 관찰됩니다.',
    negativeResultText: 'No cystic calculi identified',
    negativeResultTextKo: '방광결석 없음',
    negativeOwnerResultTextKo: '방광 내부에 결석은 보이지 않습니다.',
    positiveIsAbnormal: true,
  },
  {
    testID: 'ub_calculi_number',
    testName: 'Cystic Calculi Number / Amount',
    testNameKo: '방광결석 개수/양',
    organ: 'urinary_bladder',
    partOfOrgan: 'lumen',
    testType: 'select',
    clinicalSignificance: 'medium',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'ub_calculi_presence', triggerValues: ['true'] },
    options: [
      {
        value: 'single',
        label: 'Single',
        labelKo: '단발성 (1개)',
        resultText: 'Single cystic calculus identified',
        resultTextKo: '단발성 방광결석 관찰',
        ownerResultTextKo: '한 개의 결석이 발견되었습니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'few',
        label: 'Few (2–5)',
        labelKo: '소수 (2-5개)',
        resultText: 'Few cystic calculi (2–5) identified',
        resultTextKo: '소수(2-5개) 방광결석 관찰',
        ownerResultTextKo: '몇 개의 결석이 관찰됩니다.',
        isAbnormal: true, severity: 'moderate',
      },
      {
        value: 'multiple',
        label: 'Multiple / Gravel',
        labelKo: '다수/자갈형',
        resultText: 'Multiple cystic calculi / urinary gravel identified',
        resultTextKo: '다수의 방광결석/요석 자갈 관찰',
        ownerResultTextKo: '다수의 결석이나 모래 같은 자갈형 요석들이 많이 깔려 있습니다.',
        isAbnormal: true, severity: 'moderate',
      },
    ],
  },
  {
    testID: 'ub_calculi_size',
    testName: 'Cystic Calculi Size (largest)',
    testNameKo: '방광결석 크기 (최대)',
    organ: 'urinary_bladder',
    partOfOrgan: 'lumen',
    testType: 'range',
    unit: 'mm',
    clinicalSignificance: 'high',
    species: 'both',
    required: false,
    displayLevel: 2,
    dependsOn: { testID: 'ub_calculi_presence', triggerValues: ['true'] },
    normalRange: { dog: { max: 0 }, cat: { max: 0 } },
    ranges: [
      {
        min: 0, max: 5,
        resultText: 'Small cystic calculus (<5mm); may pass through urethra',
        resultTextKo: '소형 방광결석(<5mm); 요도 통과 가능',
        isAbnormal: true, severity: 'mild',
      },
      {
        min: 5, max: 15,
        resultText: 'Moderate cystic calculus (5–15mm); urethral obstruction risk in cats/small dogs',
        resultTextKo: '중간 크기 방광결석(5-15mm); 고양이/소형견 요도 폐쇄 위험',
        isAbnormal: true, severity: 'moderate',
      },
      {
        min: 15, max: null,
        resultText: 'Large cystic calculus (>15mm); surgical removal recommended',
        resultTextKo: '대형 방광결석(>15mm); 외과적 제거 권장',
        isAbnormal: true, severity: 'severe',
      },
    ],
  },
];
