import type { Species } from '../../register/signalments'

export type Diet = {
  diet_id: number
  name: string
  company: string
  unit: string
  mass_vol: number
  species: Species | 'both'
}

export const DIETS: Diet[] = [
  {
    diet_id: 1,
    name: 'renal pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.182,
    species: 'feline',
  },
  {
    diet_id: 2,
    name: 'gastrointestinal biome cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.831,
    species: 'feline',
  },
  {
    diet_id: 3,
    name: 'adult oral+ dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.397,
    species: 'canine',
  },
  {
    diet_id: 4,
    name: 'i/d low fat loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.944,
    species: 'canine',
  },
  {
    diet_id: 5,
    name: 'sensitivity control(chicken & rice) dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.22,
    species: 'canine',
  },
  {
    diet_id: 6,
    name: 'hepatic dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.91,
    species: 'canine',
  },
  {
    diet_id: 7,
    name: 'h/d loaf dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.304,
    species: 'canine',
  },
  {
    diet_id: 8,
    name: 'anallergenic cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.9,
    species: 'feline',
  },
  {
    diet_id: 9,
    name: 'renal with tuna pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.943,
    species: 'feline',
  },
  {
    diet_id: 10,
    name: 'g/d dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.535,
    species: 'canine',
  },
  {
    diet_id: 11,
    name: 'hepatic dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.38,
    species: 'canine',
  },
  {
    diet_id: 12,
    name: 'adult stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.85,
    species: 'canine',
  },
  {
    diet_id: 13,
    name: 'c/d multicare dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.775,
    species: 'canine',
  },
  {
    diet_id: 14,
    name: 'satiety small dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 2.662,
    species: 'canine',
  },
  {
    diet_id: 15,
    name: '로우펫 유동식',
    company: '메디비아',
    unit: 'ml',
    mass_vol: 1,
    species: 'both',
  },
  {
    diet_id: 16,
    name: 'urinary s/o moderate calorie cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.505,
    species: 'feline',
  },
  {
    diet_id: 17,
    name: 'renal cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.924,
    species: 'feline',
  },
  {
    diet_id: 18,
    name: 't/d cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.52,
    species: 'feline',
  },
  {
    diet_id: 19,
    name: 'convalescence support pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.15,
    species: 'feline',
  },
  {
    diet_id: 20,
    name: 'hypoallergenic dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4,
    species: 'canine',
  },
  {
    diet_id: 21,
    name: '파워 리커버리 유동식',
    company: '메디비아',
    unit: 'ml',
    mass_vol: 1.2,
    species: 'both',
  },
  {
    diet_id: 22,
    name: 'puppy 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.928,
    species: 'canine',
  },
  {
    diet_id: 23,
    name: 'k/d + mobility dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.068,
    species: 'canine',
  },
  {
    diet_id: 24,
    name: 'd/d(potato & venison) dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.636,
    species: 'canine',
  },
  {
    diet_id: 25,
    name: 'hypoallergenic small dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.84,
    species: 'canine',
  },
  {
    diet_id: 26,
    name: 'metabolic stew(chicken & vegetable) cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.784,
    species: 'feline',
  },
  {
    diet_id: 27,
    name: 'gastrointestinal biome dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.456,
    species: 'canine',
  },
  {
    diet_id: 28,
    name: 'i/d dog dry 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.615,
    species: 'canine',
  },
  {
    diet_id: 29,
    name: 'cardiac dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.143,
    species: 'canine',
  },
  {
    diet_id: 30,
    name: 'z/d food sensitivities small bite  dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.556,
    species: 'canine',
  },
  {
    diet_id: 31,
    name: 'i/d stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.747,
    species: 'canine',
  },
  {
    diet_id: 32,
    name: 'd/d(potato & salmon) dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.643,
    species: 'canine',
  },
  {
    diet_id: 33,
    name: 'urinary s/o moderate calorie dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.31,
    species: 'canine',
  },
  {
    diet_id: 34,
    name: 'early renal cat pouch 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.978,
    species: 'feline',
  },
  {
    diet_id: 35,
    name: 'kitten cat 건',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.139,
    species: 'feline',
  },
  {
    diet_id: 36,
    name: 'hypoallergenic cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.1,
    species: 'feline',
  },
  {
    diet_id: 37,
    name: 'z/d food sensitivities dog\b습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.95,
    species: 'canine',
  },
  {
    diet_id: 38,
    name: 'metabolic cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.381,
    species: 'feline',
  },
  {
    diet_id: 39,
    name: 'k/d stew(chicken & vegetable) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.01,
    species: 'canine',
  },
  {
    diet_id: 40,
    name: 'mature adult 7+ dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.594,
    species: 'canine',
  },
  {
    diet_id: 41,
    name: 'renal with beef pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.992,
    species: 'feline',
  },
  {
    diet_id: 42,
    name: 'i/d stress stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.809,
    species: 'canine',
  },
  {
    diet_id: 43,
    name: 'metabolic loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.861,
    species: 'canine',
  },
  {
    diet_id: 44,
    name: 'urinary s/o cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.97,
    species: 'feline',
  },
  {
    diet_id: 45,
    name: 'early renal cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.808,
    species: 'feline',
  },
  {
    diet_id: 46,
    name: 'derm complete loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.211,
    species: 'canine',
  },
  {
    diet_id: 47,
    name: 'i/d low fat dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.36,
    species: 'canine',
  },
  {
    diet_id: 48,
    name: 'urinary s/o low purine dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.83,
    species: 'canine',
  },
  {
    diet_id: 49,
    name: 'diabetic cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.87,
    species: 'feline',
  },
  {
    diet_id: 50,
    name: 'renal dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.584,
    species: 'canine',
  },
  {
    diet_id: 51,
    name: 'renal special cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.932,
    species: 'feline',
  },
  {
    diet_id: 52,
    name: 'mobility dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.574,
    species: 'canine',
  },
  {
    diet_id: 53,
    name: 'a/a appetite aid',
    company: '시그니처바이',
    unit: 'g',
    mass_vol: 0.933,
    species: 'both',
  },
  {
    diet_id: 54,
    name: 'gastrointestinal biome cat stew 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.822,
    species: 'feline',
  },
  {
    diet_id: 55,
    name: 'gastrointestinal biome dog stew 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.808,
    species: 'canine',
  },
  {
    diet_id: 56,
    name: 'adult oral+ 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.12,
    species: 'feline',
  },
  {
    diet_id: 57,
    name: 'metabolic + mobility dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.21,
    species: 'canine',
  },
  {
    diet_id: 58,
    name: 'w/d multibenefit cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.82,
    species: 'feline',
  },
  {
    diet_id: 59,
    name: 'a/d canned(with chicken) 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.175,
    species: 'both',
  },
  {
    diet_id: 60,
    name: 'obesity pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.644,
    species: 'feline',
  },
  {
    diet_id: 61,
    name: 'satiety pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.607,
    species: 'feline',
  },
  {
    diet_id: 62,
    name: 'urinary s/o moderate calorie pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.76,
    species: 'feline',
  },
  {
    diet_id: 63,
    name: 'c/d multicare(with chicken) stress cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.891,
    species: 'feline',
  },
  {
    diet_id: 64,
    name: 'adult stew cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.034,
    species: 'feline',
  },
  {
    diet_id: 65,
    name: 'z/d food sensitivities original  dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.569,
    species: 'canine',
  },
  {
    diet_id: 66,
    name: 'metabolic(with chiken) dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.157,
    species: 'canine',
  },
  {
    diet_id: 67,
    name: 'k/d loaf(with chicken) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.141,
    species: 'canine',
  },
  {
    diet_id: 68,
    name: 'urinary s/o dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.87,
    species: 'canine',
  },
  {
    diet_id: 69,
    name: 'gastrointestinal pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.931,
    species: 'feline',
  },
  {
    diet_id: 70,
    name: 'renal cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.062,
    species: 'feline',
  },
  {
    diet_id: 71,
    name: 'renal dog pouch 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.952,
    species: 'canine',
  },
  {
    diet_id: 72,
    name: 'metabolic + mobility stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.615,
    species: 'canine',
  },
  {
    diet_id: 73,
    name: 'calm dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.875,
    species: 'canine',
  },
  {
    diet_id: 74,
    name: 'cardiac dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.24,
    species: 'canine',
  },
  {
    diet_id: 75,
    name: 'k/d minced(chicken) cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.135,
    species: 'feline',
  },
  {
    diet_id: 76,
    name: 'c/d multicare+metabolic dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.17,
    species: 'canine',
  },
  {
    diet_id: 77,
    name: 'u/d dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.015,
    species: 'canine',
  },
  {
    diet_id: 78,
    name: '레날 플러스 유동식',
    company: '메디비아',
    unit: 'ml',
    mass_vol: 2,
    species: 'both',
  },
  {
    diet_id: 79,
    name: 'sensitivity pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.962,
    species: 'feline',
  },
  {
    diet_id: 80,
    name: 'obesity cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.559,
    species: 'feline',
  },
  {
    diet_id: 81,
    name: 'k/d cat(with chicken) 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.239,
    species: 'feline',
  },
  {
    diet_id: 82,
    name: 's/d loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.266,
    species: 'canine',
  },
  {
    diet_id: 83,
    name: 'w/d cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.162,
    species: 'feline',
  },
  {
    diet_id: 84,
    name: 'k/d stew(beef & vegetable) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.932,
    species: 'canine',
  },
  {
    diet_id: 85,
    name: 'r/d loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.854,
    species: 'canine',
  },
  {
    diet_id: 86,
    name: 'c/d multicare stress stew cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.839,
    species: 'feline',
  },
  {
    diet_id: 87,
    name: 'gastrointestinal dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.09,
    species: 'canine',
  },
  {
    diet_id: 88,
    name: 'gastrointestinal moderate calorie cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.719,
    species: 'feline',
  },
  {
    diet_id: 89,
    name: 'gastrointestinal dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.07,
    species: 'canine',
  },
  {
    diet_id: 90,
    name: 'metabolic stew(vegetable & tuna) cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.773,
    species: 'feline',
  },
  {
    diet_id: 91,
    name: 'i/d minced cat 156g 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.072,
    species: 'feline',
  },
  {
    diet_id: 92,
    name: 'sensitivity cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.52,
    species: 'feline',
  },
  {
    diet_id: 93,
    name: 'i/d stew cat 82g 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.946,
    species: 'feline',
  },
  {
    diet_id: 94,
    name: 'j/d loaf dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.27,
    species: 'canine',
  },
  {
    diet_id: 95,
    name: 'k/d(chicken) dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.05,
    species: 'canine',
  },
  {
    diet_id: 96,
    name: 'dental special 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.723,
    species: 'canine',
  },
  {
    diet_id: 97,
    name: 'urinary s/o pouch(beef) cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.967,
    species: 'feline',
  },
  {
    diet_id: 98,
    name: 'fibre response cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.886,
    species: 'feline',
  },
  {
    diet_id: 99,
    name: 'dental dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.852,
    species: 'canine',
  },
  {
    diet_id: 100,
    name: 'dental cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.809,
    species: 'feline',
  },
  {
    diet_id: 101,
    name: 'satiety cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.075,
    species: 'feline',
  },
  {
    diet_id: 102,
    name: 'k/d(with lamb) dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.048,
    species: 'canine',
  },
  {
    diet_id: 103,
    name: 'z/d cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.688,
    species: 'feline',
  },
  {
    diet_id: 104,
    name: 'recovery liquid dog & cat 유동식',
    company: '로얄캐닌',
    unit: 'ml',
    mass_vol: 1.04,
    species: 'both',
  },
  {
    diet_id: 105,
    name: 'metabolic minced cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.873,
    species: 'feline',
  },
  {
    diet_id: 106,
    name: 'renal select dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.964,
    species: 'canine',
  },
  {
    diet_id: 107,
    name: 'k/d stew(chicken & vegetable) cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.85,
    species: 'feline',
  },
  {
    diet_id: 108,
    name: 'adult 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.117,
    species: 'feline',
  },
  {
    diet_id: 109,
    name: 'diabetic dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.45,
    species: 'canine',
  },
  {
    diet_id: 110,
    name: 'j/d small bite dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.868,
    species: 'canine',
  },
  {
    diet_id: 111,
    name: 'c/d loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.25,
    species: 'canine',
  },
  {
    diet_id: 112,
    name: 'sensitivity control dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.34,
    species: 'canine',
  },
  {
    diet_id: 113,
    name: 'puppy large breed 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.679,
    species: 'canine',
  },
  {
    diet_id: 114,
    name: 'mobility cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.86,
    species: 'feline',
  },
  {
    diet_id: 115,
    name: 'GI low fat liquid dog 유동식',
    company: '로얄캐닌',
    unit: 'ml',
    mass_vol: 1.04,
    species: 'canine',
  },
  {
    diet_id: 116,
    name: 'i/d loaf can(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.016,
    species: 'canine',
  },
  {
    diet_id: 117,
    name: 'urinary s/o dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.28,
    species: 'canine',
  },
  {
    diet_id: 118,
    name: 'metabolic stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.7,
    species: 'canine',
  },
  {
    diet_id: 119,
    name: 'diabetic pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.71,
    species: 'feline',
  },
  {
    diet_id: 120,
    name: 'w/d dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.1,
    species: 'canine',
  },
  {
    diet_id: 121,
    name: 'mother and babycat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.912,
    species: 'feline',
  },
  {
    diet_id: 122,
    name: 'satiety weight management dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 2.678,
    species: 'canine',
  },
  {
    diet_id: 123,
    name: 'u/d loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.348,
    species: 'canine',
  },
  {
    diet_id: 124,
    name: 'gastrointestinal low fat dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.456,
    species: 'canine',
  },
  {
    diet_id: 125,
    name: 'b/d dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.639,
    species: 'canine',
  },
  {
    diet_id: 126,
    name: 'ONC care cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.939,
    species: 'feline',
  },
  {
    diet_id: 127,
    name: 'GI high energy liquid dog 유동식',
    company: '로얄캐닌',
    unit: 'ml',
    mass_vol: 1.47,
    species: 'canine',
  },
  {
    diet_id: 128,
    name: 'urinary s/o pouch(chicken) cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.984,
    species: 'feline',
  },
  {
    diet_id: 129,
    name: 'y/d cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.147,
    species: 'feline',
  },
  {
    diet_id: 130,
    name: 'hypoallergenic moderate calorie dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.7,
    species: 'canine',
  },
  {
    diet_id: 131,
    name: 'gastrointestinal moderate calorie pouch cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.708,
    species: 'feline',
  },
  {
    diet_id: 132,
    name: 'hepatic cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.11,
    species: 'feline',
  },
  {
    diet_id: 133,
    name: 'obesity management dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.116,
    species: 'canine',
  },
  {
    diet_id: 134,
    name: 'renal special dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.587,
    species: 'canine',
  },
  {
    diet_id: 135,
    name: 'c/d stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.752,
    species: 'canine',
  },
  {
    diet_id: 136,
    name: 'i/d stress dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.318,
    species: 'canine',
  },
  {
    diet_id: 137,
    name: 'w/d minced cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.821,
    species: 'feline',
  },
  {
    diet_id: 138,
    name: 'urinary s/o small dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.86,
    species: 'canine',
  },
  {
    diet_id: 139,
    name: 'g/d loaf dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.049,
    species: 'canine',
  },
  {
    diet_id: 140,
    name: 'skin care junior small dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.05,
    species: 'canine',
  },
  {
    diet_id: 141,
    name: 'r/d dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 2.982,
    species: 'canine',
  },
  {
    diet_id: 142,
    name: 'puppy stew',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.89,
    species: 'canine',
  },
  {
    diet_id: 143,
    name: 'h/d dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.129,
    species: 'canine',
  },
  {
    diet_id: 144,
    name: 'hypoallergenic dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.95,
    species: 'canine',
  },
  {
    diet_id: 145,
    name: 'mother and babycat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.437,
    species: 'feline',
  },
  {
    diet_id: 146,
    name: 'k/d early stage cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.203,
    species: 'feline',
  },
  {
    diet_id: 147,
    name: 'fibre response dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.169,
    species: 'canine',
  },
  {
    diet_id: 148,
    name: 'd/d loaf(with duck) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.046,
    species: 'canine',
  },
  {
    diet_id: 149,
    name: 'urinary s/o dog pouch 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.918,
    species: 'canine',
  },
  {
    diet_id: 150,
    name: 'renal special dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.886,
    species: 'canine',
  },
  {
    diet_id: 151,
    name: 'kitten stew 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.11,
    species: 'feline',
  },
  {
    diet_id: 152,
    name: 'i/d cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.074,
    species: 'feline',
  },
  {
    diet_id: 153,
    name: 'gastrointestinal low fat dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.92,
    species: 'canine',
  },
  {
    diet_id: 154,
    name: 'renal liquid dog 유동식',
    company: '로얄캐닌',
    unit: 'ml',
    mass_vol: 1.5,
    species: 'canine',
  },
  {
    diet_id: 155,
    name: 'obesity dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.563,
    species: 'canine',
  },
  {
    diet_id: 156,
    name: 'renal select cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.112,
    species: 'feline',
  },
  {
    diet_id: 157,
    name: 'satiety dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.602,
    species: 'canine',
  },
  {
    diet_id: 158,
    name: 'urinary s/o cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1,
    species: 'feline',
  },
  {
    diet_id: 159,
    name: 'w/d loaf(original) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.83,
    species: 'canine',
  },
  {
    diet_id: 160,
    name: 'gastrointestinal junior dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.224,
    species: 'canine',
  },
  {
    diet_id: 161,
    name: 'gastrointestinal cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 4.076,
    species: 'feline',
  },
  {
    diet_id: 162,
    name: 'c/d multicare(with chicken) cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.826,
    species: 'feline',
  },
  {
    diet_id: 163,
    name: 'z/d minced cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.114,
    species: 'feline',
  },
  {
    diet_id: 164,
    name: 'renal dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.988,
    species: 'canine',
  },
  {
    diet_id: 165,
    name: 'calm cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.687,
    species: 'feline',
  },
  {
    diet_id: 166,
    name: 'd/d(potato & duck) dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.651,
    species: 'canine',
  },
  {
    diet_id: 167,
    name: 'renal liquid cat 유동식',
    company: '로얄캐닌',
    unit: 'ml',
    mass_vol: 1.08,
    species: 'feline',
  },
  {
    diet_id: 168,
    name: 'k/d loaf(with lamb) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.137,
    species: 'canine',
  },
  {
    diet_id: 169,
    name: 'k/d stew(vegetable & tuna) cat 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.849,
    species: 'feline',
  },
  {
    diet_id: 170,
    name: 'skin care dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.9,
    species: 'canine',
  },
  {
    diet_id: 171,
    name: 'urinary s/o high dilution cat 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.859,
    species: 'feline',
  },
  {
    diet_id: 172,
    name: 'derm complete dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.799,
    species: 'canine',
  },
  {
    diet_id: 173,
    name: 'c/d multicare + metabolic cat 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.255,
    species: 'feline',
  },
  {
    diet_id: 174,
    name: 'diabetic dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 0.727,
    species: 'canine',
  },
  {
    diet_id: 175,
    name: 'sensitivity control(duck & rice) dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.46,
    species: 'canine',
  },
  {
    diet_id: 176,
    name: 'k/d cat(ocean fish) 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 4.235,
    species: 'feline',
  },
  {
    diet_id: 177,
    name: 'i/d low fat stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.815,
    species: 'canine',
  },
  {
    diet_id: 178,
    name: 'k/d + mobility stew(chicken & vegetable) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.995,
    species: 'canine',
  },
  {
    diet_id: 179,
    name: 'gastrointestinal moderate calorie dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.611,
    species: 'canine',
  },
  {
    diet_id: 180,
    name: 'recovery dog & cat 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1.16,
    species: 'both',
  },
  {
    diet_id: 181,
    name: 'w/d stew dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 0.569,
    species: 'canine',
  },
  {
    diet_id: 182,
    name: 'd/d loaf(with salmon) dog 습식사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 1.094,
    species: 'canine',
  },
  {
    diet_id: 183,
    name: 'adult dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.698,
    species: 'canine',
  },
  {
    diet_id: 184,
    name: 'mobility dog 습식사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 1,
    species: 'canine',
  },
  {
    diet_id: 185,
    name: 'anallergenic dog 건사료',
    company: '로얄캐닌',
    unit: 'g',
    mass_vol: 3.88,
    species: 'canine',
  },
  {
    diet_id: 186,
    name: 'metabolic(lamb meal & rice)  dog 건사료',
    company: '힐스',
    unit: 'g',
    mass_vol: 3.116,
    species: 'canine',
  },
]
