// ============================================================
// AVDC Abbreviations for use in Case Logs
// Source: American Veterinary Dental College
// Type: 'anatomy' | 'dx' | 'tx'
//   - anatomy : Anatomical items (black font in original)
//   - dx      : Conditions & diagnostic procedures (blue font)
//   - tx      : Treatment procedures & related items (red font)
// ============================================================

export type AvdcAbbrevType = 'anatomy' | 'dx' | 'tx';

export interface AvdcAbbrev {
  abbr: string;
  definition: string;
  type: AvdcAbbrevType;
  parent?: string; // 상위 약어 (하위 항목인 경우)
}

export const AVDC_ABBREVIATIONS: AvdcAbbrev[] = [
  // ── A ──────────────────────────────────────────────────────
  { abbr: 'A',           definition: 'Alveolus',                                          type: 'anatomy' },
  { abbr: 'AB',          definition: 'Abrasion',                                          type: 'dx' },
  { abbr: 'ABE',         definition: 'Alveolar bone expansion',                           type: 'tx' },
  { abbr: 'ALV',         definition: 'Alveolectomy / alveoloplasty',                      type: 'tx' },
  { abbr: 'ANO',         definition: 'Anodontia',                                         type: 'dx' },
  { abbr: 'AOS',         definition: 'Alveolar osteitis',                                 type: 'dx' },
  { abbr: 'AP',          definition: 'Apex',                                              type: 'anatomy' },
  { abbr: 'AP/X',        definition: 'Apicoectomy',                                       type: 'tx' },
  { abbr: 'APN',         definition: 'Apexification',                                     type: 'tx' },
  { abbr: 'AT',          definition: 'Attrition',                                         type: 'dx' },
  { abbr: 'ATE',         definition: 'Abnormal tooth extrusion',                          type: 'dx' },

  // ── B ──────────────────────────────────────────────────────
  { abbr: 'B',           definition: 'Biopsy',                                            type: 'tx' },
  { abbr: 'B/B',         definition: 'Bite biopsy',                                       type: 'tx',  parent: 'B' },
  { abbr: 'B/CN',        definition: 'Core needle biopsy',                                type: 'tx',  parent: 'B' },
  { abbr: 'B/E',         definition: 'Excisional biopsy',                                 type: 'tx',  parent: 'B' },
  { abbr: 'B/I',         definition: 'Incisional biopsy',                                 type: 'tx',  parent: 'B' },
  { abbr: 'B/NA',        definition: 'Needle aspiration',                                 type: 'tx',  parent: 'B' },
  { abbr: 'B/NB',        definition: 'Needle biopsy',                                     type: 'tx',  parent: 'B' },
  { abbr: 'B/P',         definition: 'Punch biopsy',                                      type: 'tx',  parent: 'B' },
  { abbr: 'B/S',         definition: 'Surface biopsy',                                    type: 'tx',  parent: 'B' },
  { abbr: 'BR',          definition: 'Bite registration',                                 type: 'tx' },
  { abbr: 'BRI',         definition: 'Bridge',                                            type: 'tx' },
  { abbr: 'BTH',         definition: 'Ball therapy',                                      type: 'tx' },
  { abbr: 'BUC',         definition: 'Buccotomy',                                         type: 'tx' },
  { abbr: 'BUP',         definition: 'Bullous pemphigoid',                                type: 'dx' },

  // ── C ──────────────────────────────────────────────────────
  { abbr: 'C',           definition: 'Canine',                                            type: 'anatomy' },
  { abbr: 'CA',          definition: 'Caries',                                            type: 'dx' },
  { abbr: 'CA/INF',      definition: 'Infundibular caries (equines)',                     type: 'dx',  parent: 'CA' },
  { abbr: 'CA/INF/D',    definition: 'Distal infundibular caries',                        type: 'dx',  parent: 'CA/INF' },
  { abbr: 'CA/INF/M',    definition: 'Mesial infundibular caries',                        type: 'dx',  parent: 'CA/INF' },
  { abbr: 'CA/PER',      definition: 'Peripheral caries (equines)',                       type: 'dx',  parent: 'CA' },
  { abbr: 'CB',          definition: 'Crossbite',                                         type: 'dx' },
  { abbr: 'CB/C',        definition: 'Caudal crossbite',                                  type: 'dx',  parent: 'CB' },
  { abbr: 'CB/R',        definition: 'Rostral crossbite',                                 type: 'dx',  parent: 'CB' },
  { abbr: 'CC',          definition: 'Calcinosis circumscripta',                          type: 'dx' },
  { abbr: 'CEJ',         definition: 'Cementoenamel junction',                            type: 'anatomy' },
  { abbr: 'CFL',         definition: 'Cleft lip',                                         type: 'dx' },
  { abbr: 'CFL/R',       definition: 'Cleft lip repair',                                  type: 'tx',  parent: 'CFL' },
  { abbr: 'CFP',         definition: 'Cleft palate',                                      type: 'dx' },
  { abbr: 'CFP/R',       definition: 'Cleft palate repair',                               type: 'tx',  parent: 'CFP' },
  { abbr: 'CFS',         definition: 'Cleft soft palate',                                 type: 'dx' },
  { abbr: 'CFS/R',       definition: 'Cleft soft palate repair',                          type: 'tx',  parent: 'CFS' },
  { abbr: 'CFSH',        definition: 'Soft palate hypoplasia',                            type: 'dx' },
  { abbr: 'CFSH/R',      definition: 'Soft palate hypoplasia repair',                     type: 'tx',  parent: 'CFSH' },
  { abbr: 'CFSU',        definition: 'Unilateral cleft soft palate',                      type: 'dx' },
  { abbr: 'CFSU/R',      definition: 'Unilateral cleft soft palate repair',               type: 'tx',  parent: 'CFSU' },
  { abbr: 'CFT',         definition: 'Traumatic cleft palate',                            type: 'dx' },
  { abbr: 'CFT/R',       definition: 'Traumatic cleft palate repair',                     type: 'tx',  parent: 'CFT' },
  { abbr: 'CHO',         definition: 'Calvarial hyperostosis',                            type: 'dx' },
  { abbr: 'CL',          definition: 'Chewing lesion',                                    type: 'dx' },
  { abbr: 'CL/B',        definition: 'Chewing lesion (buccal mucosa / cheek)',            type: 'dx',  parent: 'CL' },
  { abbr: 'CL/L',        definition: 'Chewing lesion (labial mucosa / lip)',              type: 'dx',  parent: 'CL' },
  { abbr: 'CL/P',        definition: 'Chewing lesion (palatal mucosa / palate)',          type: 'dx',  parent: 'CL' },
  { abbr: 'CL/T',        definition: 'Chewing lesion (lingual / sublingual mucosa / tongue)', type: 'dx', parent: 'CL' },
  { abbr: 'CMO',         definition: 'Craniomandibular osteopathy',                       type: 'dx' },
  { abbr: 'COM',         definition: 'Commissurotomy',                                    type: 'tx' },
  { abbr: 'CON',         definition: 'Condylar process of the mandible',                  type: 'anatomy' },
  { abbr: 'CON/X',       definition: 'Condylectomy',                                      type: 'tx',  parent: 'CON' },
  { abbr: 'COO',         definition: 'Condensing osteitis',                               type: 'dx' },
  { abbr: 'COR',         definition: 'Coronoid process of the mandible',                  type: 'anatomy' },
  { abbr: 'COR/X',       definition: 'Coronoidectomy',                                    type: 'tx',  parent: 'COR' },
  { abbr: 'CPL',         definition: 'Cheiloplasty / commissuroplasty',                   type: 'tx' },
  { abbr: 'CR',          definition: 'Crown',                                             type: 'anatomy' },
  { abbr: 'CR/A',        definition: 'Crown amputation',                                  type: 'tx',  parent: 'CR' },
  { abbr: 'CR/AC',       definition: 'Anatomical crown',                                  type: 'anatomy', parent: 'CR' },
  { abbr: 'CR/C',        definition: 'Ceramic crown (full)',                              type: 'tx',  parent: 'CR' },
  { abbr: 'CR/C/P',      definition: 'Ceramic crown (partial)',                           type: 'tx',  parent: 'CR' },
  { abbr: 'CR/CC',       definition: 'Clinical crown',                                    type: 'anatomy', parent: 'CR' },
  { abbr: 'CR/E',        definition: 'Crown extension',                                   type: 'tx',  parent: 'CR' },
  { abbr: 'CR/L',        definition: 'Crown lengthening',                                 type: 'tx',  parent: 'CR' },
  { abbr: 'CR/M',        definition: 'Metal crown (full)',                                type: 'tx',  parent: 'CR' },
  { abbr: 'CR/M/P',      definition: 'Metal crown (partial)',                             type: 'tx',  parent: 'CR' },
  { abbr: 'CR/P',        definition: 'Crown preparation',                                 type: 'tx',  parent: 'CR' },
  { abbr: 'CR/PFM',      definition: 'Porcelain fused to metal crown (full)',             type: 'tx',  parent: 'CR' },
  { abbr: 'CR/PFM/P',    definition: 'Porcelain fused to metal crown (partial)',          type: 'tx',  parent: 'CR' },
  { abbr: 'CR/R',        definition: 'Resin crown (full)',                                type: 'tx',  parent: 'CR' },
  { abbr: 'CR/R/P',      definition: 'Resin crown (partial)',                             type: 'tx',  parent: 'CR' },
  { abbr: 'CR/RC',       definition: 'Reserve crown',                                     type: 'anatomy', parent: 'CR' },
  { abbr: 'CR/T',        definition: 'Temporary crown',                                   type: 'tx',  parent: 'CR' },
  { abbr: 'CR/XP',       definition: 'Crown reduction',                                   type: 'tx',  parent: 'CR' },
  { abbr: 'CS',          definition: 'Culture / sensitivity',                             type: 'dx' },
  { abbr: 'CT',          definition: 'Computed tomography',                               type: 'dx' },
  { abbr: 'CT/CB',       definition: 'Cone-beam CT',                                      type: 'dx',  parent: 'CT' },
  { abbr: 'CTH',         definition: 'Chemotherapy',                                      type: 'tx' },
  { abbr: 'CU',          definition: 'Contact mucositis or contact mucosal ulceration',   type: 'dx' },
  { abbr: 'CUS',         definition: 'Contact ulcerative stomatitis',                     type: 'dx' },

  // ── D ──────────────────────────────────────────────────────
  { abbr: 'D',           definition: 'Diastema',                                          type: 'dx' },
  { abbr: 'D/O',         definition: 'Open diastema',                                     type: 'dx',  parent: 'D' },
  { abbr: 'D/ODY',       definition: 'Diastema odontoplasty (or widening)',               type: 'tx',  parent: 'D' },
  { abbr: 'D/V',         definition: 'Valve diastema',                                    type: 'dx',  parent: 'D' },
  { abbr: 'DC',          definition: 'Diagnostic cast',                                   type: 'dx' },
  { abbr: 'DC/D',        definition: 'Die',                                               type: 'dx',  parent: 'DC' },
  { abbr: 'DC/SM',       definition: 'Stone model',                                       type: 'dx',  parent: 'DC' },
  { abbr: 'DI',          definition: 'Discharge',                                         type: 'dx' },
  { abbr: 'DI/ND',       definition: 'Right nasal discharge',                             type: 'dx',  parent: 'DI' },
  { abbr: 'DI/NS',       definition: 'Left nasal discharge',                              type: 'dx',  parent: 'DI' },
  { abbr: 'DI/NU',       definition: 'Bilateral nasal discharge',                         type: 'dx',  parent: 'DI' },
  { abbr: 'DI/OD',       definition: 'Right ocular discharge',                            type: 'dx',  parent: 'DI' },
  { abbr: 'DI/OS',       definition: 'Left ocular discharge',                             type: 'dx',  parent: 'DI' },
  { abbr: 'DI/OU',       definition: 'Bilateral ocular discharge',                        type: 'dx',  parent: 'DI' },
  { abbr: 'DMO',         definition: 'Decreased mouth opening',                           type: 'dx' },
  { abbr: 'DP',          definition: 'Defect preparation (prior to filling a dental defect)', type: 'tx' },
  { abbr: 'DT',          definition: 'Deciduous tooth',                                   type: 'anatomy' },
  { abbr: 'DT/P',        definition: 'Persistent deciduous tooth',                        type: 'dx',  parent: 'DT' },
  { abbr: 'DTC',         definition: 'Dentigerous cyst',                                  type: 'dx' },
  { abbr: 'DTC/R',       definition: 'Dentigerous cyst removal',                          type: 'tx',  parent: 'DTC' },

  // ── E ──────────────────────────────────────────────────────
  { abbr: 'E',           definition: 'Enamel',                                            type: 'anatomy' },
  { abbr: 'E/D',         definition: 'Enamel defect',                                     type: 'dx',  parent: 'E' },
  { abbr: 'E/H',         definition: 'Enamel hypoplasia',                                 type: 'dx',  parent: 'E' },
  { abbr: 'E/HM',        definition: 'Enamel hypomineralization',                         type: 'dx',  parent: 'E' },
  { abbr: 'E/P',         definition: 'Enamel pearl',                                      type: 'dx',  parent: 'E' },
  { abbr: 'EM',          definition: 'Erythema multiforme',                               type: 'dx' },
  { abbr: 'ENO',         definition: 'Enophthalmos',                                      type: 'dx' },
  { abbr: 'EOG',         definition: 'Eosinophilic granuloma',                            type: 'dx' },
  { abbr: 'EOG/L',       definition: 'Eosinophilic granuloma (lip)',                       type: 'dx',  parent: 'EOG' },
  { abbr: 'EOG/P',       definition: 'Eosinophilic granuloma (palate)',                    type: 'dx',  parent: 'EOG' },
  { abbr: 'EOG/T',       definition: 'Eosinophilic granuloma (tongue)',                    type: 'dx',  parent: 'EOG' },
  { abbr: 'ER',          definition: 'Erosion',                                           type: 'dx' },
  { abbr: 'ESP',         definition: 'Elongated soft palate',                             type: 'dx' },
  { abbr: 'ESP/R',       definition: 'Elongated soft palate reduction',                   type: 'tx',  parent: 'ESP' },
  { abbr: 'EXO',         definition: 'Exophthalmos',                                      type: 'dx' },

  // ── F ──────────────────────────────────────────────────────
  { abbr: 'F',           definition: 'Flap',                                              type: 'tx' },
  { abbr: 'F/AD',        definition: 'Advancement flap',                                  type: 'tx',  parent: 'F' },
  { abbr: 'F/AP',        definition: 'Apically positioned flap',                          type: 'tx',  parent: 'F' },
  { abbr: 'F/CO',        definition: 'Coronally positioned flap',                         type: 'tx',  parent: 'F' },
  { abbr: 'F/EN',        definition: 'Envelope flap',                                     type: 'tx',  parent: 'F' },
  { abbr: 'F/HI',        definition: 'Hinged (overlapping) flap',                         type: 'tx',  parent: 'F' },
  { abbr: 'F/IS',        definition: 'Island flap',                                       type: 'tx',  parent: 'F' },
  { abbr: 'F/LA',        definition: 'Laterally positioned flap',                         type: 'tx',  parent: 'F' },
  { abbr: 'F/RO',        definition: 'Rotation flap',                                     type: 'tx',  parent: 'F' },
  { abbr: 'F/TR',        definition: 'Transposition flap',                                type: 'tx',  parent: 'F' },
  { abbr: 'FB',          definition: 'Foreign body',                                      type: 'dx' },
  { abbr: 'FB/R',        definition: 'Foreign body removal',                              type: 'tx',  parent: 'FB' },
  { abbr: 'FOD',         definition: 'Fibrous osteodystrophy',                            type: 'dx' },
  { abbr: 'FOL',         definition: 'Folliculitis',                                      type: 'dx' },
  { abbr: 'FRE',         definition: 'Frenuloplasty (frenulotomy, frenulectomy)',          type: 'tx' },
  { abbr: 'FT',          definition: 'Fiberotomy',                                        type: 'tx' },
  { abbr: 'FX',          definition: 'Fracture (tooth or jaw)',                           type: 'dx' },
  { abbr: 'FX/R',        definition: 'Repair of jaw fracture',                            type: 'tx',  parent: 'FX' },
  { abbr: 'FX/R/EXF',    definition: 'External skeletal fixation',                        type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/IAS',    definition: 'Interarch splinting',                               type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/IDS',    definition: 'Interdental splinting',                             type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/IQS',    definition: 'Interquadrant splinting',                           type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/MMF',    definition: 'Maxillomandibular fixation',                        type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/MZ',     definition: 'Muzzling',                                          type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/PL',     definition: 'Bone plating',                                      type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/WIR/C',  definition: 'Wire cerclage',                                     type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/WIR/OS', definition: 'Intraosseous wiring',                               type: 'tx',  parent: 'FX/R' },

  // ── G ──────────────────────────────────────────────────────
  { abbr: 'GC',          definition: 'Gingival curettage',                                type: 'tx' },
  { abbr: 'GE',          definition: 'Gingival enlargement',                              type: 'dx' },
  { abbr: 'GF',          definition: 'Graft',                                             type: 'tx' },
  { abbr: 'GF/B',        definition: 'Bone graft',                                        type: 'tx',  parent: 'GF' },
  { abbr: 'GF/C',        definition: 'Cartilage graft',                                   type: 'tx',  parent: 'GF' },
  { abbr: 'GF/CT',       definition: 'Connective tissue graft',                           type: 'tx',  parent: 'GF' },
  { abbr: 'GF/F',        definition: 'Fat graft',                                         type: 'tx',  parent: 'GF' },
  { abbr: 'GF/G',        definition: 'Gingival graft',                                    type: 'tx',  parent: 'GF' },
  { abbr: 'GF/M',        definition: 'Mucosal graft',                                     type: 'tx',  parent: 'GF' },
  { abbr: 'GF/N',        definition: 'Nerve graft',                                       type: 'tx',  parent: 'GF' },
  { abbr: 'GF/S',        definition: 'Skin graft',                                        type: 'tx',  parent: 'GF' },
  { abbr: 'GF/V',        definition: 'Venous graft',                                      type: 'tx',  parent: 'GF' },
  { abbr: 'GH',          definition: 'Gingival hyperplasia',                              type: 'dx' },
  { abbr: 'GR',          definition: 'Gingival recession',                                type: 'dx' },
  { abbr: 'GTR',         definition: 'Guided tissue regeneration',                        type: 'tx' },
  { abbr: 'GV',          definition: 'Gingivectomy / gingivoplasty',                      type: 'tx' },

  // ── H ──────────────────────────────────────────────────────
  { abbr: 'HC',          definition: 'Hypercementosis',                                   type: 'dx' },
  { abbr: 'HS',          definition: 'Hemisection',                                       type: 'tx' },
  { abbr: 'HYP',         definition: 'Hypodontia',                                        type: 'dx' },

  // ── I ──────────────────────────────────────────────────────
  { abbr: 'I1,2,3',      definition: 'Incisor',                                           type: 'anatomy' },
  { abbr: 'IM',          definition: 'Detailed imprint of hard and/or soft tissues',      type: 'dx' },
  { abbr: 'IM/F',        definition: 'Full-mouth impression',                             type: 'dx',  parent: 'IM' },
  { abbr: 'IMP',         definition: 'Implant',                                           type: 'tx' },
  { abbr: 'INF',         definition: 'Infundibulum',                                      type: 'anatomy' },
  { abbr: 'IOF',         definition: 'Intraoral fistula',                                 type: 'dx' },
  { abbr: 'IOF/R',       definition: 'Intraoral fistula repair',                          type: 'tx',  parent: 'IOF' },
  { abbr: 'IP',          definition: 'Inclined plane',                                    type: 'tx' },
  { abbr: 'IP/AC',       definition: 'Acrylic inclined plane',                            type: 'tx',  parent: 'IP' },
  { abbr: 'IP/C',        definition: 'Composite inclined plane',                          type: 'tx',  parent: 'IP' },
  { abbr: 'IP/M',        definition: 'Metal (lab-produced) inclined plane',               type: 'tx',  parent: 'IP' },
  { abbr: 'ITH',         definition: 'Immunotherapy',                                     type: 'tx' },

  // ── L ──────────────────────────────────────────────────────
  { abbr: 'LAC',         definition: 'Laceration',                                        type: 'dx' },
  { abbr: 'LAC/B',       definition: 'Laceration (cheek skin / buccal mucosa)',           type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/G',       definition: 'Laceration (gingiva / alveolar mucosa)',            type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/L',       definition: 'Laceration (lip skin / labial mucosa)',             type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/O',       definition: 'Laceration (palatine tonsil / oropharyngeal mucosa)', type: 'dx', parent: 'LAC' },
  { abbr: 'LAC/P',       definition: 'Laceration (palatal mucosa)',                       type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/R',       definition: 'Laceration repair',                                 type: 'tx',  parent: 'LAC' },
  { abbr: 'LAC/T',       definition: 'Laceration (lingual / sublingual mucosa)',          type: 'dx',  parent: 'LAC' },
  { abbr: 'LE',          definition: 'Lupus erythematosus',                               type: 'dx' },
  { abbr: 'LIN',         definition: 'Tongue',                                            type: 'anatomy' },
  { abbr: 'LIN/X',       definition: 'Tongue resection',                                  type: 'tx',  parent: 'LIN' },
  { abbr: 'LIP',         definition: 'Lip / cheek',                                       type: 'anatomy' },
  { abbr: 'LIP/A/R',     definition: 'Lip avulsion repair',                               type: 'tx',  parent: 'LIP' },
  { abbr: 'LIP/X',       definition: 'Lip / cheek resection',                             type: 'tx',  parent: 'LIP' },
  { abbr: 'LN',          definition: 'Lymph node (regional)',                             type: 'anatomy' },
  { abbr: 'LN/E',        definition: 'Lymph node enlargement',                            type: 'dx',  parent: 'LN' },
  { abbr: 'LN/X',        definition: 'Lymph node resection',                              type: 'tx',  parent: 'LN' },

  // ── M ──────────────────────────────────────────────────────
  { abbr: 'M1,2,3',      definition: 'Molar',                                             type: 'anatomy' },
  { abbr: 'MAL',         definition: 'Malocclusion',                                      type: 'dx' },
  { abbr: 'MAL1',        definition: 'Class 1 malocclusion (neutroclusion)',              type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL1/BV',     definition: 'Buccoversion',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/DV',     definition: 'Distoversion',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/LABV',   definition: 'Labioversion',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/LV',     definition: 'Linguoversion',                                     type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/MV',     definition: 'Mesioversion',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/PV',     definition: 'Palatoversion',                                     type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL2',        definition: 'Class 2 malocclusion (mandibular distoclusion)',    type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL3',        definition: 'Class 3 malocclusion (mandibular mesioclusion)',    type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL4',        definition: 'Class 4 malocclusion (asymmetrical skeletal)',      type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL4/DV',     definition: 'Asymmetrical skeletal malocclusion (dorsoventral)', type: 'dx',  parent: 'MAL4' },
  { abbr: 'MAL4/RC',     definition: 'Asymmetrical skeletal malocclusion (rostrocaudal)', type: 'dx',  parent: 'MAL4' },
  { abbr: 'MAL4/STS',    definition: 'Asymmetrical skeletal malocclusion (side-to-side)', type: 'dx',  parent: 'MAL4' },
  { abbr: 'MAR',         definition: 'Marsupialization',                                  type: 'tx' },
  { abbr: 'MET',         definition: 'Metastasis',                                        type: 'dx' },
  { abbr: 'MET/D',       definition: 'Distant metastasis',                                type: 'dx',  parent: 'MET' },
  { abbr: 'MET/R',       definition: 'Regional metastasis',                               type: 'dx',  parent: 'MET' },
  { abbr: 'MMM',         definition: 'Masticatory muscle myositis',                       type: 'dx' },
  { abbr: 'MN',          definition: 'Mandible / mandibular',                             type: 'anatomy' },
  { abbr: 'MN/FX',       definition: 'Mandibular fracture',                               type: 'dx',  parent: 'MN' },
  { abbr: 'MRI',         definition: 'Magnetic resonance imaging',                        type: 'dx' },
  { abbr: 'MX',          definition: 'Maxilla / maxillary',                               type: 'anatomy' },
  { abbr: 'MX/FX',       definition: 'Maxillary fracture',                                type: 'dx',  parent: 'MX' },

  // ── N ──────────────────────────────────────────────────────
  { abbr: 'N',           definition: 'Nose / nasal / nasopharyngeal',                     type: 'anatomy' },
  { abbr: 'N/EN',        definition: 'Rhinoscopy',                                        type: 'dx',  parent: 'N' },
  { abbr: 'N/LAV',       definition: 'Nasal lavage',                                      type: 'tx',  parent: 'N' },
  { abbr: 'N/NS',        definition: 'Naris stenosis',                                    type: 'dx',  parent: 'N' },
  { abbr: 'N/NS/R',      definition: 'Naroplasty',                                        type: 'tx',  parent: 'N/NS' },
  { abbr: 'N/NPS',       definition: 'Nasopharyngeal stenosis',                           type: 'dx',  parent: 'N' },
  { abbr: 'N/NPS/R',     definition: 'Nasopharyngeal stenosis repair',                    type: 'tx',  parent: 'N/NPS' },
  { abbr: 'N/POL',       definition: 'Nasopharyngeal polyp',                              type: 'dx',  parent: 'N' },
  { abbr: 'N/SCC',       definition: 'Nasal SCC',                                         type: 'dx',  parent: 'N' },

  // ── O ──────────────────────────────────────────────────────
  { abbr: 'OA',          definition: 'Orthodontic appliance',                             type: 'tx' },
  { abbr: 'OA/A',        definition: 'Orthodontic appliance adjustment',                  type: 'tx',  parent: 'OA' },
  { abbr: 'OA/AR',       definition: 'Arch bar',                                          type: 'tx',  parent: 'OA' },
  { abbr: 'OA/BKT',      definition: 'Bracket, button or hook',                           type: 'tx',  parent: 'OA' },
  { abbr: 'OA/CMB',      definition: 'Custom-made OA/BKT',                                type: 'tx',  parent: 'OA' },
  { abbr: 'OA/EC',       definition: 'Elastic chain, tube or thread',                     type: 'tx',  parent: 'OA' },
  { abbr: 'OA/I',        definition: 'Orthodontic appliance installment',                 type: 'tx',  parent: 'OA' },
  { abbr: 'OA/R',        definition: 'Orthodontic appliance removal',                     type: 'tx',  parent: 'OA' },
  { abbr: 'OA/WIR',      definition: 'Orthodontic wire',                                  type: 'tx',  parent: 'OA' },
  { abbr: 'OAF',         definition: 'Oroantral fistula',                                 type: 'dx' },
  { abbr: 'OAF/R',       definition: 'Oroantral fistula repair',                          type: 'tx',  parent: 'OAF' },
  { abbr: 'OC',          definition: 'Orthodontic counseling',                            type: 'tx' },
  { abbr: 'ODY',         definition: 'Odontoplasty',                                      type: 'tx' },
  { abbr: 'OFF',         definition: 'Orofacial fistula',                                 type: 'dx' },
  { abbr: 'OFF/R',       definition: 'Orofacial fistula repair',                          type: 'tx',  parent: 'OFF' },
  { abbr: 'OLI',         definition: 'Oligodontia',                                       type: 'dx' },
  { abbr: 'OM',          definition: 'Oral / maxillofacial mass',                         type: 'dx' },
  { abbr: 'OM/AA',       definition: 'Acanthomatous ameloblastoma',                       type: 'dx',  parent: 'OM' },
  { abbr: 'OM/AD',       definition: 'Adenoma',                                           type: 'dx',  parent: 'OM' },
  { abbr: 'OM/ADC',      definition: 'Adenocarcinoma',                                    type: 'dx',  parent: 'OM' },
  { abbr: 'OM/APN',      definition: 'Anaplastic neoplasm',                               type: 'dx',  parent: 'OM' },
  { abbr: 'OM/APO',      definition: 'Amyloid-producing odontogenic tumor',               type: 'dx',  parent: 'OM' },
  { abbr: 'OM/CE',       definition: 'Cementoma',                                         type: 'dx',  parent: 'OM' },
  { abbr: 'OM/FIO',      definition: 'Feline inductive odontogenic tumor',                type: 'dx',  parent: 'OM' },
  { abbr: 'OM/FS',       definition: 'Fibrosarcoma',                                      type: 'dx',  parent: 'OM' },
  { abbr: 'OM/GCG',      definition: 'Giant cell granuloma',                              type: 'dx',  parent: 'OM' },
  { abbr: 'OM/GCT',      definition: 'Granular cell tumor',                               type: 'dx',  parent: 'OM' },
  { abbr: 'OM/HS',       definition: 'Hemangiosarcoma',                                   type: 'dx',  parent: 'OM' },
  { abbr: 'OM/LI',       definition: 'Lipoma',                                            type: 'dx',  parent: 'OM' },
  { abbr: 'OM/LS',       definition: 'Lymphosarcoma',                                     type: 'dx',  parent: 'OM' },
  { abbr: 'OM/MCT',      definition: 'Mast cell tumor',                                   type: 'dx',  parent: 'OM' },
  { abbr: 'OM/MM',       definition: 'Malignant melanoma',                                type: 'dx',  parent: 'OM' },
  { abbr: 'OM/MTB',      definition: 'Multilobular tumor of bone',                        type: 'dx',  parent: 'OM' },
  { abbr: 'OM/OO',       definition: 'Osteoma',                                           type: 'dx',  parent: 'OM' },
  { abbr: 'OM/OS',       definition: 'Osteosarcoma',                                      type: 'dx',  parent: 'OM' },
  { abbr: 'OM/PAP',      definition: 'Papilloma',                                         type: 'dx',  parent: 'OM' },
  { abbr: 'OM/PCT',      definition: 'Plasma cell tumor',                                 type: 'dx',  parent: 'OM' },
  { abbr: 'OM/PNT',      definition: 'Peripheral nerve sheath tumor',                     type: 'dx',  parent: 'OM' },
  { abbr: 'OM/POF',      definition: 'Peripheral odontogenic fibroma',                    type: 'dx',  parent: 'OM' },
  { abbr: 'OM/RBM',      definition: 'Rhabdomyosarcoma',                                  type: 'dx',  parent: 'OM' },
  { abbr: 'OM/SCC',      definition: 'Squamous cell carcinoma',                           type: 'dx',  parent: 'OM' },
  { abbr: 'OM/UDN',      definition: 'Undifferentiated neoplasm',                         type: 'dx',  parent: 'OM' },
  { abbr: 'OMJL',        definition: 'Open-mouth jaw locking',                            type: 'dx' },
  { abbr: 'OMJL/R',      definition: 'Open-mouth jaw locking reduction',                  type: 'tx',  parent: 'OMJL' },
  { abbr: 'ONF',         definition: 'Oronasal fistula',                                  type: 'dx' },
  { abbr: 'ONF/R',       definition: 'Oronasal fistula repair',                           type: 'tx',  parent: 'ONF' },
  { abbr: 'OP',          definition: 'Operculectomy',                                     type: 'tx' },
  { abbr: 'OR',          definition: 'Orthodontic recheck',                               type: 'tx' },
  { abbr: 'OS',          definition: 'Orthognathic surgery',                              type: 'tx' },
  { abbr: 'OSN',         definition: 'Osteonecrosis',                                     type: 'dx' },
  { abbr: 'OSS',         definition: 'Osteosclerosis',                                    type: 'dx' },
  { abbr: 'OST',         definition: 'Osteomyelitis',                                     type: 'dx' },

  // ── P ──────────────────────────────────────────────────────
  { abbr: 'PA',          definition: 'Periapical',                                        type: 'anatomy' },
  { abbr: 'PA/A',        definition: 'Periapical abscess',                                type: 'dx',  parent: 'PA' },
  { abbr: 'PA/C',        definition: 'Periapical cyst',                                   type: 'dx',  parent: 'PA' },
  { abbr: 'PA/G',        definition: 'Periapical granuloma',                              type: 'dx',  parent: 'PA' },
  { abbr: 'PA/P',        definition: 'Periapical pathology',                              type: 'dx',  parent: 'PA' },
  { abbr: 'PCB',         definition: 'Post-and-core build-up',                            type: 'tx' },
  { abbr: 'PCD',         definition: 'Direct pulp capping',                               type: 'tx' },
  { abbr: 'PCI',         definition: 'Indirect pulp capping',                             type: 'tx' },
  { abbr: 'PD',          definition: 'Periodontal disease',                               type: 'dx' },
  { abbr: 'PD0',         definition: 'Clinically normal',                                 type: 'dx',  parent: 'PD' },
  { abbr: 'PD1',         definition: 'Gingivitis only (without attachment loss)',          type: 'dx',  parent: 'PD' },
  { abbr: 'PD2',         definition: 'Early periodontitis (<25% attachment loss)',        type: 'dx',  parent: 'PD' },
  { abbr: 'PD3',         definition: 'Moderate periodontitis (25–50% attachment loss)',   type: 'dx',  parent: 'PD' },
  { abbr: 'PD4',         definition: 'Advanced periodontitis (>50% attachment loss)',     type: 'dx',  parent: 'PD' },
  { abbr: 'PDE',         definition: 'Acquired palate defect',                            type: 'dx' },
  { abbr: 'PDE/R',       definition: 'Acquired palate defect repair',                     type: 'tx',  parent: 'PDE' },
  { abbr: 'PEC',         definition: 'Pericoronitis',                                     type: 'dx' },
  { abbr: 'PEO',         definition: 'Periostitis ossificans',                            type: 'dx' },
  { abbr: 'PH',          definition: 'Pulp horn (equines, du Toit system)',               type: 'anatomy' },
  { abbr: 'PH/D',        definition: 'Pulp horn defect',                                  type: 'dx',  parent: 'PH' },
  { abbr: 'PHA',         definition: 'Pharynx',                                           type: 'anatomy' },
  { abbr: 'PHA/IN',      definition: 'Pharyngitis',                                       type: 'dx',  parent: 'PHA' },
  { abbr: 'PM1-4',       definition: 'Premolar',                                          type: 'anatomy' },
  { abbr: 'POB',         definition: 'Palatal obturator',                                 type: 'tx' },
  { abbr: 'PRO',         definition: 'Professional dental cleaning (scaling, polishing, irrigation)', type: 'tx' },
  { abbr: 'PTY',         definition: 'Ptyalism',                                          type: 'dx' },
  { abbr: 'PU',          definition: 'Pulp',                                              type: 'anatomy' },
  { abbr: 'PU/M',        definition: 'Mineralization of pulp',                            type: 'dx',  parent: 'PU' },
  { abbr: 'PU/S',        definition: 'Pulp stone',                                        type: 'dx',  parent: 'PU' },
  { abbr: 'PV',          definition: 'Pemphigus vulgaris',                                type: 'dx' },
  { abbr: 'PYO',         definition: 'Pyogenic granuloma',                                type: 'dx' },

  // ── R ──────────────────────────────────────────────────────
  { abbr: 'R',           definition: 'Restoration (filling of a dental defect)',          type: 'tx' },
  { abbr: 'R/A',         definition: 'Filling made of amalgam',                           type: 'tx',  parent: 'R' },
  { abbr: 'R/C',         definition: 'Filling made of composite',                         type: 'tx',  parent: 'R' },
  { abbr: 'R/CP',        definition: 'Filling made of compomer',                          type: 'tx',  parent: 'R' },
  { abbr: 'R/I',         definition: 'Filling made of glass ionomer',                     type: 'tx',  parent: 'R' },
  { abbr: 'RAD',         definition: 'Radiography',                                       type: 'dx' },
  { abbr: 'RAD/SG',      definition: 'Sialography',                                       type: 'dx',  parent: 'RAD' },
  { abbr: 'RBA',         definition: 'Retrobulbar abscess',                               type: 'dx' },
  { abbr: 'RCR',         definition: 'Retained crown-root or clinical crown-reserve crown', type: 'dx' },
  { abbr: 'RCT',         definition: 'Standard root canal therapy',                       type: 'tx' },
  { abbr: 'RCT/S',       definition: 'Surgical root canal therapy',                       type: 'tx',  parent: 'RCT' },
  { abbr: 'RO',          definition: 'Root',                                              type: 'anatomy' },
  { abbr: 'RO/AC',       definition: 'Anatomical root',                                   type: 'anatomy', parent: 'RO' },
  { abbr: 'RO/CR',       definition: 'Clinical root',                                     type: 'anatomy', parent: 'RO' },
  { abbr: 'RO/X',        definition: 'Root resection / amputation',                       type: 'tx',  parent: 'RO' },
  { abbr: 'RP',          definition: 'Root planing',                                      type: 'tx' },
  { abbr: 'RP/C',        definition: 'Closed root planing',                               type: 'tx',  parent: 'RP' },
  { abbr: 'RP/O',        definition: 'Open root planing',                                 type: 'tx',  parent: 'RP' },
  { abbr: 'RPA',         definition: 'Retropharyngeal abscess',                           type: 'dx' },
  { abbr: 'RR',          definition: 'Internal resorption',                               type: 'dx' },
  { abbr: 'RTH',         definition: 'Radiotherapy',                                      type: 'tx' },
  { abbr: 'RTR',         definition: 'Retained root or reserve crown',                    type: 'dx' },

  // ── S ──────────────────────────────────────────────────────
  { abbr: 'S',           definition: 'Surgery',                                           type: 'tx' },
  { abbr: 'S/M',         definition: 'Partial mandibulectomy',                            type: 'tx',  parent: 'S' },
  { abbr: 'S/MB',        definition: 'Bilateral partial mandibulectomy',                  type: 'tx',  parent: 'S' },
  { abbr: 'S/MD',        definition: 'Dorsal marginal mandibulectomy',                    type: 'tx',  parent: 'S' },
  { abbr: 'S/MS',        definition: 'Segmental mandibulectomy',                          type: 'tx',  parent: 'S' },
  { abbr: 'S/MT',        definition: 'Total mandibulectomy',                              type: 'tx',  parent: 'S' },
  { abbr: 'S/P',         definition: 'Partial palatectomy',                               type: 'tx',  parent: 'S' },
  { abbr: 'S/X',         definition: 'Partial maxillectomy',                              type: 'tx',  parent: 'S' },
  { abbr: 'S/XB',        definition: 'Bilateral partial maxillectomy',                    type: 'tx',  parent: 'S' },
  { abbr: 'SCI',         definition: 'Scintigraphy',                                      type: 'dx' },
  { abbr: 'SG',          definition: 'Salivary gland',                                    type: 'anatomy' },
  { abbr: 'SG/ADC',      definition: 'Salivary gland adenocarcinoma',                     type: 'dx',  parent: 'SG' },
  { abbr: 'SG/ADS',      definition: 'Sialadenosis',                                      type: 'dx',  parent: 'SG' },
  { abbr: 'SG/IN',       definition: 'Sialadenitis',                                      type: 'dx',  parent: 'SG' },
  { abbr: 'SG/MAR',      definition: 'Marsupialization',                                  type: 'tx',  parent: 'SG' },
  { abbr: 'SG/MUC/C',    definition: 'Cervical sialocele',                                type: 'dx',  parent: 'SG' },
  { abbr: 'SG/MUC/P',    definition: 'Pharyngeal sialocele',                              type: 'dx',  parent: 'SG' },
  { abbr: 'SG/MUC/S',    definition: 'Sublingual sialocele',                              type: 'dx',  parent: 'SG' },
  { abbr: 'SG/NEC',      definition: 'Necrotizing sialometaplasia',                       type: 'dx',  parent: 'SG' },
  { abbr: 'SG/RC',       definition: 'Mucous retention cyst',                             type: 'dx',  parent: 'SG' },
  { abbr: 'SG/SI',       definition: 'Sialolith',                                         type: 'dx',  parent: 'SG' },
  { abbr: 'SG/X',        definition: 'Salivary gland resection',                          type: 'tx',  parent: 'SG' },
  { abbr: 'SHE',         definition: 'Shear mouth (equines)',                             type: 'dx' },
  { abbr: 'SIN',         definition: 'Sinus',                                             type: 'anatomy' },
  { abbr: 'SIN/CF',      definition: 'Conchofrontal sinus',                               type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/CF/F',    definition: 'Conchofrontal sinus flap',                          type: 'tx',  parent: 'SIN/CF' },
  { abbr: 'SIN/CMX',     definition: 'Caudal maxillary sinus',                            type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/EN',      definition: 'Sinoscopy',                                         type: 'dx',  parent: 'SIN' },
  { abbr: 'SIN/F',       definition: 'Sinus flap',                                        type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/IN',      definition: 'Sinusitis',                                         type: 'dx',  parent: 'SIN' },
  { abbr: 'SIN/LAV',     definition: 'Sinus lavage',                                      type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/MX/F',    definition: 'Maxillary sinus flap',                              type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/RMX',     definition: 'Rostral maxillary sinus',                           type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/SP',      definition: 'Sphenopalatine sinus',                              type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/TRP',     definition: 'Sinus trephination',                                type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/VC',      definition: 'Ventral conchal sinus',                             type: 'anatomy', parent: 'SIN' },
  { abbr: 'SR',          definition: 'Surgical repositioning',                            type: 'tx' },
  { abbr: 'ST',          definition: 'Stomatitis',                                        type: 'dx' },
  { abbr: 'ST/CS',       definition: 'Caudal stomatitis',                                 type: 'dx',  parent: 'ST' },
  { abbr: 'SYM',         definition: 'Mandibular symphysis',                              type: 'anatomy' },
  { abbr: 'SYM/R',       definition: 'Mandibular symphysis repair',                       type: 'tx',  parent: 'SYM' },
  { abbr: 'SYM/S',       definition: 'Mandibular symphysis separation',                   type: 'dx',  parent: 'SYM' },

  // ── T ──────────────────────────────────────────────────────
  { abbr: 'T',           definition: 'Tooth',                                             type: 'anatomy' },
  { abbr: 'T/A',         definition: 'Avulsed tooth',                                     type: 'dx',  parent: 'T' },
  { abbr: 'T/CCR',       definition: 'Concrescence',                                      type: 'dx',  parent: 'T' },
  { abbr: 'T/DEN',       definition: 'Dens invaginatus',                                  type: 'dx',  parent: 'T' },
  { abbr: 'T/DIL',       definition: 'Dilaceration',                                      type: 'dx',  parent: 'T' },
  { abbr: 'T/E',         definition: 'Embedded tooth',                                    type: 'dx',  parent: 'T' },
  { abbr: 'T/EL',        definition: 'Tooth elongation',                                  type: 'dx',  parent: 'T' },
  { abbr: 'T/FDR',       definition: 'Fused roots',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/FUS',       definition: 'Fusion',                                            type: 'dx',  parent: 'T' },
  { abbr: 'T/FX',        definition: 'Fractured tooth',                                   type: 'dx',  parent: 'T' },
  { abbr: 'T/FX/EI',     definition: 'Enamel infraction',                                 type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/FX/EF',     definition: 'Enamel fracture',                                   type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/FX/UCF',    definition: 'Uncomplicated crown fracture',                      type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/FX/CCF',    definition: 'Complicated crown fracture',                        type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/FX/UCRF',   definition: 'Uncomplicated crown-root fracture',                 type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/FX/CCRF',   definition: 'Complicated crown-root fracture',                   type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/FX/RF',     definition: 'Root fracture',                                     type: 'dx',  parent: 'T/FX' },
  { abbr: 'T/GEM',       definition: 'Gemination',                                        type: 'dx',  parent: 'T' },
  { abbr: 'T/I',         definition: 'Impacted tooth',                                    type: 'dx',  parent: 'T' },
  { abbr: 'T/LUX',       definition: 'Luxated tooth',                                     type: 'dx',  parent: 'T' },
  { abbr: 'T/MAC',       definition: 'Macrodontia',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/MIC',       definition: 'Microdontia',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/NE',        definition: 'Near pulp exposure',                                type: 'dx',  parent: 'T' },
  { abbr: 'T/NV',        definition: 'Non-vital tooth',                                   type: 'dx',  parent: 'T' },
  { abbr: 'T/PE',        definition: 'Pulp exposure',                                     type: 'dx',  parent: 'T' },
  { abbr: 'T/RI',        definition: 'Tooth reimplantation (for an avulsed tooth)',        type: 'tx',  parent: 'T' },
  { abbr: 'T/RP',        definition: 'Tooth repositioning (for a luxated tooth)',          type: 'tx',  parent: 'T' },
  { abbr: 'T/SN',        definition: 'Supernumerary tooth',                               type: 'dx',  parent: 'T' },
  { abbr: 'T/SR',        definition: 'Supernumerary root',                                type: 'dx',  parent: 'T' },
  { abbr: 'T/TRA',       definition: 'Transposition',                                     type: 'dx',  parent: 'T' },
  { abbr: 'T/U',         definition: 'Unerupted tooth',                                   type: 'dx',  parent: 'T' },
  { abbr: 'T/V',         definition: 'Vital tooth',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/XP',        definition: 'Partial tooth resection',                           type: 'tx',  parent: 'T' },
  { abbr: 'TMA',         definition: 'Trauma',                                            type: 'dx' },
  { abbr: 'TMA/B',       definition: 'Ballistic trauma',                                  type: 'dx',  parent: 'TMA' },
  { abbr: 'TMA/BRN',     definition: 'Burn trauma',                                       type: 'dx',  parent: 'TMA' },
  { abbr: 'TMA/E',       definition: 'Electric trauma',                                   type: 'dx',  parent: 'TMA' },
  { abbr: 'TMA/R',       definition: 'Trauma repair',                                     type: 'tx',  parent: 'TMA' },
  { abbr: 'TMJ',         definition: 'Temporomandibular joint',                           type: 'anatomy' },
  { abbr: 'TMJ/A',       definition: 'TMJ ankylosis (true or false)',                      type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/A/R',     definition: 'TMJ ankylosis repair',                              type: 'tx',  parent: 'TMJ/A' },
  { abbr: 'TMJ/D',       definition: 'TMJ dysplasia',                                     type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/FX',      definition: 'TMJ fracture',                                      type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/FX/R',    definition: 'TMJ fracture repair',                               type: 'tx',  parent: 'TMJ/FX' },
  { abbr: 'TMJ/LUX',     definition: 'TMJ luxation',                                      type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/LUX/R',   definition: 'TMJ luxation reduction',                            type: 'tx',  parent: 'TMJ/LUX' },
  { abbr: 'TON',         definition: 'Palatine tonsil',                                   type: 'anatomy' },
  { abbr: 'TON/IN',      definition: 'Tonsillitis',                                       type: 'dx',  parent: 'TON' },
  { abbr: 'TON/X',       definition: 'Tonsillectomy',                                     type: 'tx',  parent: 'TON' },
  { abbr: 'TP',          definition: 'Treatment plan',                                    type: 'tx' },
  { abbr: 'TR',          definition: 'Tooth resorption',                                  type: 'dx' },
  { abbr: 'TRP',         definition: 'Trephination',                                      type: 'tx' },
  { abbr: 'TS',          definition: 'Trisection',                                        type: 'tx' },
  { abbr: 'TT',          definition: 'Temporal teratoma',                                 type: 'dx' },

  // ── U ──────────────────────────────────────────────────────
  { abbr: 'US',          definition: 'Ultrasonography',                                   type: 'dx' },

  // ── V ──────────────────────────────────────────────────────
  { abbr: 'VPT',         definition: 'Vital pulp therapy',                                type: 'tx' },

  // ── X ──────────────────────────────────────────────────────
  { abbr: 'X',           definition: 'Closed extraction of a tooth (without sectioning)', type: 'tx' },
  { abbr: 'XS',          definition: 'Closed extraction of a tooth (with sectioning)',    type: 'tx' },
  { abbr: 'XS/ODY',      definition: 'Removal of interproximal crown tissue to facilitate transoral extraction', type: 'tx', parent: 'XS' },
  { abbr: 'XSS',         definition: 'Open extraction of a tooth',                        type: 'tx' },
  { abbr: 'XSS/APX/RPL', definition: 'Extraction after apicoectomy and repulsion',        type: 'tx',  parent: 'XSS' },
  { abbr: 'XSS/BUC',     definition: 'Transbuccal extraction after buccotomy',            type: 'tx',  parent: 'XSS' },
  { abbr: 'XSS/BUC/ALV', definition: 'Transbuccal extraction after buccotomy and alveolectomy', type: 'tx', parent: 'XSS/BUC' },
  { abbr: 'XSS/COM',     definition: 'Transbuccal extraction after commissurotomy',       type: 'tx',  parent: 'XSS' },
  { abbr: 'XSS/COM/ALV', definition: 'Transbuccal extraction after commissurotomy and alveolectomy', type: 'tx', parent: 'XSS/COM' },
  { abbr: 'XSS/MIB',     definition: 'Extraction via minimally invasive buccotomy',       type: 'tx',  parent: 'XSS' },
  { abbr: 'XSS/RPL',     definition: 'Extraction after repulsion',                        type: 'tx',  parent: 'XSS' },

  // ── Z ──────────────────────────────────────────────────────
  { abbr: 'ZYG',         definition: 'Zygoma (zygomatic arch)',                           type: 'anatomy' },
  { abbr: 'ZYG/X',       definition: 'Zygomectomy',                                       type: 'tx',  parent: 'ZYG' },
];

// ── 유틸리티 함수 ─────────────────────────────────────────────

/** 타입별 필터 */
export function getByType(type: AvdcAbbrevType): AvdcAbbrev[] {
  return AVDC_ABBREVIATIONS.filter((a) => a.type === type);
}

/** 약어로 단일 검색 */
export function getByAbbr(abbr: string): AvdcAbbrev | undefined {
  return AVDC_ABBREVIATIONS.find(
    (a) => a.abbr.toLowerCase() === abbr.toLowerCase()
  );
}

/** 약어 또는 정의에서 텍스트 검색 */
export function searchAbbreviations(query: string): AvdcAbbrev[] {
  const q = query.toLowerCase();
  return AVDC_ABBREVIATIONS.filter(
    (a) =>
      a.abbr.toLowerCase().includes(q) ||
      a.definition.toLowerCase().includes(q)
  );
}

/** 상위 약어의 하위 항목 조회 */
export function getChildren(parentAbbr: string): AvdcAbbrev[] {
  return AVDC_ABBREVIATIONS.filter((a) => a.parent === parentAbbr);
}

/** 타입별 한글 레이블 */
export const TYPE_LABELS: Record<AvdcAbbrevType, string> = {
  anatomy: '해부 (Anatomy)',
  dx:      '진단 (Diagnosis)',
  tx:      '치료 (Treatment)',
};

/** 타입별 색상 (Tailwind 클래스) */
export const TYPE_COLORS: Record<AvdcAbbrevType, { bg: string; text: string; border: string }> = {
  anatomy: { bg: 'bg-gray-100',   text: 'text-gray-700',  border: 'border-gray-300'  },
  dx:      { bg: 'bg-blue-50',    text: 'text-blue-700',  border: 'border-blue-300'  },
  tx:      { bg: 'bg-red-50',     text: 'text-red-700',   border: 'border-red-300'   },
};
