// ============================================================
// AVDC Abbreviations for use in Case Logs
// Source: American Veterinary Dental College
// Type: 'anatomy' | 'dx' | 'tx'
//   - anatomy : Anatomical items (black font in original)
//   - dx      : Conditions & diagnostic procedures (blue font)
//   - tx      : Treatment procedures & related items (red font)
// ============================================================

export type AvdcAbbrevType = 'anatomy' | 'dx' | 'tx';

export interface AvdcAbbrev {
  abbr: string;
  definition: string;
  definition_kr?: string;
  generalComment?: string; // 보호자에게 설명할 용어/설명
  type: AvdcAbbrevType;
  parent?: string; // 상위 약어 (하위 항목인 경우)
}

export const AVDC_ABBREVIATIONS: AvdcAbbrev[] = [
  // ── Anatomical Surfaces & Directions (해부학적 표면/방향) ────
  { abbr: 'M',           definition: 'Mesial',            definition_kr: '앞쪽 / 근심면',                 type: 'anatomy' },
  { abbr: 'D',           definition: 'Distal',            definition_kr: '뒤쪽 / 원심면',                 type: 'anatomy' },
  { abbr: 'B',           definition: 'Buccal',            definition_kr: '볼쪽 / 협면',                   type: 'anatomy' },
  { abbr: 'L',           definition: 'Lingual',           definition_kr: '혀쪽 / 설면',                   type: 'anatomy' },
  { abbr: 'P',           definition: 'Palatal',           definition_kr: '입천장쪽 / 구개면',               type: 'anatomy' },
  { abbr: 'O',           definition: 'Occlusal',          definition_kr: '씹는면 / 교합면',                 type: 'anatomy' },
  { abbr: 'I',           definition: 'Incisal',           definition_kr: '절단연 / 앞니면',                 type: 'anatomy' },
  { abbr: 'La',          definition: 'Labial',            definition_kr: '입술쪽 / 순면',                   type: 'anatomy' },
  { abbr: 'V',           definition: 'Vestibular',        definition_kr: '전정면 - 볼/입술쪽 통합',           type: 'anatomy' },
  { abbr: 'Rostral',     definition: 'Rostral',           definition_kr: '코쪽 / 앞쪽 방향',                type: 'anatomy' },
  { abbr: 'Caudal',      definition: 'Caudal',            definition_kr: '꼬리쪽 / 뒤쪽 방향',               type: 'anatomy' },
  { abbr: 'Coronal',     definition: 'Coronal',           definition_kr: '치관쪽 / 머리 방향',               type: 'anatomy' },
  { abbr: 'Apical',      definition: 'Apical',            definition_kr: '치근단쪽 / 뿌리 방향',              type: 'anatomy' },

  // ── A ──────────────────────────────────────────────────────
  { abbr: 'A',           definition: 'Alveolus',  definition_kr: '치조 (이틀)',                                          type: 'anatomy' },
  { abbr: 'AB',          definition: 'Abrasion',  definition_kr: '마찰 (마모)',                                          type: 'dx',  generalComment: '치아 표면이 딱딱한 물체나 반복적인 마찰로 인해 닳아있는 상태입니다.' },
  { abbr: 'ABE',         definition: 'Alveolar bone expansion',  definition_kr: '치조골 팽창',                           type: 'tx',  generalComment: '치아를 지지하는 뼈(잇몸뼈)를 치료 목적으로 확장하는 시술입니다.' },
  { abbr: 'ALV',         definition: 'Alveolectomy / alveoloplasty',  definition_kr: '치조 절제술/성형술',                      type: 'tx',  generalComment: '발치 후 치아가 있던 잇몸뼈를 매끄럽게 다듬는 처치를 시행하였습니다.' },
  { abbr: 'ANO',         definition: 'Anodontia',  definition_kr: '무치증',                                         type: 'dx',  generalComment: '선천적으로 치아가 나지 않는 상태입니다.' },
  { abbr: 'AOS',         definition: 'Alveolar osteitis',  definition_kr: '치조골염',                                 type: 'dx',  generalComment: '발치한 자리의 뼈에 염증이 생긴 상태(건성치조염)입니다.' },
  { abbr: 'AP',          definition: 'Apex',  definition_kr: '치근단',                                              type: 'anatomy' },
  { abbr: 'AP/X',        definition: 'Apicoectomy',  definition_kr: '치근단 절제술',                                       type: 'tx',  generalComment: '치아 뿌리 끝 부분의 염증 조직을 제거하는 수술을 시행하였습니다.' },
  { abbr: 'APN',         definition: 'Apexification',  definition_kr: '치근단 형성술',                                     type: 'tx',  generalComment: '치아 뿌리 끝이 완전히 형성될 수 있도록 돕는 치료를 시행하였습니다.' },
  { abbr: 'AT',          definition: 'Attrition',  definition_kr: '교모 (마찰)',                                         type: 'dx',  generalComment: '치아끼리 맞닿아 씹는 과정에서 치아 표면이 닳아있는 상태입니다.' },
  { abbr: 'ATE',         definition: 'Abnormal tooth extrusion',  definition_kr: '비정상적 치아 정출',                          type: 'dx',  generalComment: '치아가 정상보다 잇몸 밖으로 더 많이 돌출되어 있는 상태입니다.' },

  // ── B ──────────────────────────────────────────────────────
  { abbr: 'B',           definition: 'Biopsy',  definition_kr: '생검 (조직검사)',                                            type: 'tx',  generalComment: '이상이 의심되는 조직의 일부를 채취하여 정밀 검사를 진행하였습니다.' },
  { abbr: 'B/B',         definition: 'Bite biopsy',  definition_kr: '교합 생검',                                       type: 'tx',  parent: 'B',  generalComment: '교합(씹는 동작)으로 접근할 수 있는 부위의 조직을 채취하여 검사하였습니다.' },
  { abbr: 'B/CN',        definition: 'Core needle biopsy',  definition_kr: '중심부 바늘 생검',                                type: 'tx',  parent: 'B',  generalComment: '가는 바늘을 이용해 조직을 채취하여 검사하였습니다.' },
  { abbr: 'B/E',         definition: 'Excisional biopsy',  definition_kr: '절제 생검',                                 type: 'tx',  parent: 'B',  generalComment: '이상 조직을 절제하는 동시에 병리 검사를 진행하였습니다.' },
  { abbr: 'B/I',         definition: 'Incisional biopsy',  definition_kr: '절개 생검',                                 type: 'tx',  parent: 'B',  generalComment: '이상 조직의 일부를 절개하여 병리 검사를 진행하였습니다.' },
  { abbr: 'B/NA',        definition: 'Needle aspiration',  definition_kr: '바늘 흡인',                                 type: 'tx',  parent: 'B',  generalComment: '가는 바늘로 세포나 액체를 흡입하여 검사하였습니다.' },
  { abbr: 'B/NB',        definition: 'Needle biopsy',  definition_kr: '바늘 생검',                                     type: 'tx',  parent: 'B',  generalComment: '바늘을 이용해 조직을 채취하여 검사하였습니다.' },
  { abbr: 'B/P',         definition: 'Punch biopsy',  definition_kr: '펀치 생검',                                      type: 'tx',  parent: 'B',  generalComment: '원형 도구로 소량의 조직을 채취하여 검사하였습니다.' },
  { abbr: 'B/S',         definition: 'Surface biopsy',  definition_kr: '표면 생검',                                    type: 'tx',  parent: 'B',  generalComment: '조직 표면을 살짝 긁어 채취하여 검사하였습니다.' },
  { abbr: 'BR',          definition: 'Bite registration',  definition_kr: '교합 채득',                                 type: 'tx',  generalComment: '위아래 치아가 어떻게 맞물리는지 기록하였습니다.' },
  { abbr: 'BRI',         definition: 'Bridge',  definition_kr: '브릿지 (가공의치)',                                            type: 'tx',  generalComment: '빠진 치아 자리를 주변 치아에 연결하는 보철물을 장착하였습니다.' },
  { abbr: 'BTH',         definition: 'Ball therapy',  definition_kr: '볼 테라피',                                      type: 'tx',  generalComment: '볼(공) 물기를 이용한 구강 재활/교정 치료를 시행하였습니다.' },
  { abbr: 'BUC',         definition: 'Buccotomy',  definition_kr: '볼 점막 절개술 (협부절개)',                                         type: 'tx',  generalComment: '치료 접근을 위해 볼쪽 점막을 절개하는 처치를 시행하였습니다.' },
  { abbr: 'BUP',         definition: 'Bullous pemphigoid',  definition_kr: '수포성 유천포창',                                type: 'dx',  generalComment: '구강 내 물집이 생기는 면역 관련 질환이 확인되었습니다.' },

  // ── C ──────────────────────────────────────────────────────
  { abbr: 'C',           definition: 'Canine',  definition_kr: '송곳니 (견치)',                                            type: 'anatomy' },
  { abbr: 'CA',          definition: 'Caries',  definition_kr: '우식(충치)',                                            type: 'dx',  generalComment: '치아에 충치(우식)가 발생한 상태입니다. 세균에 의해 치아가 녹아 구멍이 생깁니다.' },
  { abbr: 'CA/INF',      definition: 'Infundibular caries (equines)',  definition_kr: '원뿔(누두부) 우식',                     type: 'dx',  parent: 'CA' },
  { abbr: 'CA/INF/D',    definition: 'Distal infundibular caries',  definition_kr: '원심성 원뿔 우식',                        type: 'dx',  parent: 'CA/INF' },
  { abbr: 'CA/INF/M',    definition: 'Mesial infundibular caries',  definition_kr: '근심성 원뿔 우식',                        type: 'dx',  parent: 'CA/INF' },
  { abbr: 'CA/PER',      definition: 'Peripheral caries (equines)',  definition_kr: '말초 우식',                       type: 'dx',  parent: 'CA' },
  { abbr: 'CB',          definition: 'Crossbite',  definition_kr: '반대교합',                                         type: 'dx',  generalComment: '위아래 치아가 정상과 반대로 맞물리는 상태(반대교합)입니다.' },
  { abbr: 'CB/C',        definition: 'Caudal crossbite',  definition_kr: '꼬리쪽(후방) 반대교합',                                  type: 'dx',  parent: 'CB' },
  { abbr: 'CB/R',        definition: 'Rostral crossbite',  definition_kr: '코쪽(전방) 반대교합',                                 type: 'dx',  parent: 'CB' },
  { abbr: 'CC',          definition: 'Calcinosis circumscripta',  definition_kr: '국소 칼슘침착증',                          type: 'dx' },
  { abbr: 'CEJ',         definition: 'Cementoenamel junction',  definition_kr: '백악법랑경계 (CEJ)',                            type: 'anatomy' },
  { abbr: 'CFL',         definition: 'Cleft lip',  definition_kr: '구순열 (토순)',                                         type: 'dx' },
  { abbr: 'CFL/R',       definition: 'Cleft lip repair',  definition_kr: '구순열 복원술',                                  type: 'tx',  parent: 'CFL' },
  { abbr: 'CFP',         definition: 'Cleft palate',  definition_kr: '구개열 (입천장갈림증)',                                      type: 'dx' },
  { abbr: 'CFP/R',       definition: 'Cleft palate repair',  definition_kr: '구개열 복원술',                               type: 'tx',  parent: 'CFP' },
  { abbr: 'CFS',         definition: 'Cleft soft palate',  definition_kr: '연구개열',                                 type: 'dx' },
  { abbr: 'CFS/R',       definition: 'Cleft soft palate repair',  definition_kr: '연구개열 복원술',                          type: 'tx',  parent: 'CFS' },
  { abbr: 'CFSH',        definition: 'Soft palate hypoplasia',  definition_kr: '연구개 형성부전',                            type: 'dx' },
  { abbr: 'CFSH/R',      definition: 'Soft palate hypoplasia repair',  definition_kr: '연구개 형성부전 복원술',                     type: 'tx',  parent: 'CFSH' },
  { abbr: 'CFSU',        definition: 'Unilateral cleft soft palate',  definition_kr: '편측 연구개열',                      type: 'dx' },
  { abbr: 'CFSU/R',      definition: 'Unilateral cleft soft palate repair',  definition_kr: '편측 연구개열 복원술',               type: 'tx',  parent: 'CFSU' },
  { abbr: 'CFT',         definition: 'Traumatic cleft palate',  definition_kr: '외상성 구개열',                            type: 'dx' },
  { abbr: 'CFT/R',       definition: 'Traumatic cleft palate repair',  definition_kr: '외상성 구개열 복원술',                     type: 'tx',  parent: 'CFT' },
  { abbr: 'CHO',         definition: 'Calvarial hyperostosis',  definition_kr: '두개관 골비후증',                            type: 'dx' },
  { abbr: 'CL',          definition: 'Chewing lesion',  definition_kr: '저작(씹기) 병변',                                    type: 'dx' },
  { abbr: 'CL/B',        definition: 'Chewing lesion (buccal mucosa / cheek)',  definition_kr: '저작 병변 (볼점막)',            type: 'dx',  parent: 'CL' },
  { abbr: 'CL/L',        definition: 'Chewing lesion (labial mucosa / lip)',  definition_kr: '저작 병변 (입술점막)',              type: 'dx',  parent: 'CL' },
  { abbr: 'CL/P',        definition: 'Chewing lesion (palatal mucosa / palate)',  definition_kr: '저작 병변 (구개점막)',          type: 'dx',  parent: 'CL' },
  { abbr: 'CL/T',        definition: 'Chewing lesion (lingual / sublingual mucosa / tongue)',  definition_kr: '저작 병변 (혀점막)', type: 'dx', parent: 'CL' },
  { abbr: 'CMO',         definition: 'Craniomandibular osteopathy',  definition_kr: '두개하악 골병증',                       type: 'dx' },
  { abbr: 'COM',         definition: 'Commissurotomy',  definition_kr: '구각절개술',                                    type: 'tx' },
  { abbr: 'CON',         definition: 'Condylar process of the mandible',  definition_kr: '하악 관절돌기',                  type: 'anatomy' },
  { abbr: 'CON/X',       definition: 'Condylectomy',  definition_kr: '관절돌기 절제술',                                      type: 'tx',  parent: 'CON' },
  { abbr: 'COO',         definition: 'Condensing osteitis',  definition_kr: '경화성 골염',                               type: 'dx' },
  { abbr: 'COR',         definition: 'Coronoid process of the mandible',  definition_kr: '하악 근돌기',                  type: 'anatomy' },
  { abbr: 'COR/X',       definition: 'Coronoidectomy',  definition_kr: '근돌기 절제술',                                    type: 'tx',  parent: 'COR' },
  { abbr: 'CPL',         definition: 'Cheiloplasty / commissuroplasty',  definition_kr: '구순/구각 성형술',                   type: 'tx' },
  { abbr: 'CR',          definition: 'Crown',  definition_kr: '치관 (크라운)',                                             type: 'anatomy' },
  { abbr: 'CR/A',        definition: 'Crown amputation',  definition_kr: '치관 절단술',                                  type: 'tx',  parent: 'CR',  generalComment: '치아 머리 부분(치관)을 절단하는 처치를 시행하였습니다.' },
  { abbr: 'CR/AC',       definition: 'Anatomical crown',  definition_kr: '해부학적 치관',                                  type: 'anatomy', parent: 'CR' },
  { abbr: 'CR/C',        definition: 'Ceramic crown (full)',  definition_kr: '세라믹 크라운 (전체)',                              type: 'tx',  parent: 'CR',  generalComment: '손상된 치아를 보호하기 위해 세라믹(도자기) 재질의 인공 치관을 씌웠습니다.' },
  { abbr: 'CR/C/P',      definition: 'Ceramic crown (partial)',  definition_kr: '세라믹 크라운 (부분)',                           type: 'tx',  parent: 'CR' },
  { abbr: 'CR/CC',       definition: 'Clinical crown',  definition_kr: '임상적 치관',                                    type: 'anatomy', parent: 'CR' },
  { abbr: 'CR/E',        definition: 'Crown extension',  definition_kr: '치관 연장',                                   type: 'tx',  parent: 'CR' },
  { abbr: 'CR/L',        definition: 'Crown lengthening',  definition_kr: '치관 연장술',                                 type: 'tx',  parent: 'CR' },
  { abbr: 'CR/M',        definition: 'Metal crown (full)',  definition_kr: '금속 크라운 (전체)',                                type: 'tx',  parent: 'CR',  generalComment: '손상된 치아를 보호하기 위해 금속 재질의 인공 치관을 씌웠습니다. 내구성이 매우 강합니다.' },
  { abbr: 'CR/M/P',      definition: 'Metal crown (partial)',  definition_kr: '금속 크라운 (부분)',                             type: 'tx',  parent: 'CR' },
  { abbr: 'CR/P',        definition: 'Crown preparation',  definition_kr: '치관 형성',                                 type: 'tx',  parent: 'CR' },
  { abbr: 'CR/PFM',      definition: 'Porcelain fused to metal crown (full)',  definition_kr: '금속도재관 (PFM, 전체)',             type: 'tx',  parent: 'CR' },
  { abbr: 'CR/PFM/P',    definition: 'Porcelain fused to metal crown (partial)',  definition_kr: '금속도재관 (PFM, 부분)',          type: 'tx',  parent: 'CR' },
  { abbr: 'CR/R',        definition: 'Resin crown (full)',  definition_kr: '레진 크라운 (전체)',                                type: 'tx',  parent: 'CR' },
  { abbr: 'CR/R/P',      definition: 'Resin crown (partial)',  definition_kr: '레진 크라운 (부분)',                             type: 'tx',  parent: 'CR' },
  { abbr: 'CR/RC',       definition: 'Reserve crown',  definition_kr: '예비(여분) 치관',                                     type: 'anatomy', parent: 'CR' },
  { abbr: 'CR/T',        definition: 'Temporary crown',  definition_kr: '임시 크라운',                                   type: 'tx',  parent: 'CR' },
  { abbr: 'CR/XP',       definition: 'Crown reduction',  definition_kr: '치관 축소',                                   type: 'tx',  parent: 'CR',  generalComment: '치아가 너무 길거나 마찰을 유발하는 경우, 치아 높이를 줄이는 처치를 시행하였습니다.' },
  { abbr: 'CS',          definition: 'Culture / sensitivity',  definition_kr: '배양 및 감수성 검사',                             type: 'dx' },
  { abbr: 'CT',          definition: 'Computed tomography',  definition_kr: '컴퓨터 단층촬영 (CT)',                               type: 'dx' },
  { abbr: 'CT/CB',       definition: 'Cone-beam CT',  definition_kr: '콘빔 CT (CBCT)',                                      type: 'dx',  parent: 'CT' },
  { abbr: 'CTH',         definition: 'Chemotherapy',  definition_kr: '화학요법 (항암치료)',                                      type: 'tx' },
  { abbr: 'CU',          definition: 'Contact mucositis or contact mucosal ulceration',  definition_kr: '접촉성 점막염 / 궤양',   type: 'dx' },
  { abbr: 'CUS',         definition: 'Contact ulcerative stomatitis',  definition_kr: '접촉성 궤양성 구내염 (CUS)',                     type: 'dx' },

  // ── D ──────────────────────────────────────────────────────
  { abbr: 'D',           definition: 'Diastema',  definition_kr: '치간이개 (Diastema)',                                          type: 'dx' },
  { abbr: 'D/O',         definition: 'Open diastema',  definition_kr: '개방성 치간이개',                                     type: 'dx',  parent: 'D' },
  { abbr: 'D/ODY',       definition: 'Diastema odontoplasty (or widening)',  definition_kr: '치간이개 치아성형술',               type: 'tx',  parent: 'D' },
  { abbr: 'D/V',         definition: 'Valve diastema',  definition_kr: '판막 치간이개',                                    type: 'dx',  parent: 'D' },
  { abbr: 'DC',          definition: 'Diagnostic cast',  definition_kr: '진단용 모델 (Cast)',                                   type: 'dx' },
  { abbr: 'DC/D',        definition: 'Die',  definition_kr: '다이 (Die)',                                               type: 'dx',  parent: 'DC' },
  { abbr: 'DC/SM',       definition: 'Stone model',  definition_kr: '석고 모델 (Stone model)',                                       type: 'dx',  parent: 'DC' },
  { abbr: 'DI',          definition: 'Discharge',  definition_kr: '분비물',                                         type: 'dx' },
  { abbr: 'DI/ND',       definition: 'Right nasal discharge',  definition_kr: '우측 콧물',                             type: 'dx',  parent: 'DI' },
  { abbr: 'DI/NS',       definition: 'Left nasal discharge',  definition_kr: '좌측 콧물',                              type: 'dx',  parent: 'DI' },
  { abbr: 'DI/NU',       definition: 'Bilateral nasal discharge',  definition_kr: '양측 콧물',                         type: 'dx',  parent: 'DI' },
  { abbr: 'DI/OD',       definition: 'Right ocular discharge',  definition_kr: '우측 눈물/분비물',                            type: 'dx',  parent: 'DI' },
  { abbr: 'DI/OS',       definition: 'Left ocular discharge',  definition_kr: '좌측 눈물/분비물',                             type: 'dx',  parent: 'DI' },
  { abbr: 'DI/OU',       definition: 'Bilateral ocular discharge',  definition_kr: '양측 눈물/분비물',                        type: 'dx',  parent: 'DI' },
  { abbr: 'DMO',         definition: 'Decreased mouth opening',  definition_kr: '개구장애 (입벌림 감소)',                           type: 'dx' },
  { abbr: 'DP',          definition: 'Defect preparation (prior to filling a dental defect)',  definition_kr: '결손부 형성', type: 'tx' },
  { abbr: 'DT',          definition: 'Deciduous tooth',  definition_kr: '유치',                                   type: 'anatomy' },
  { abbr: 'DT/P',        definition: 'Persistent deciduous tooth',  definition_kr: '잔존 유치',                        type: 'dx',  parent: 'DT',  generalComment: '영구치가 나왔는데도 빠지지 않고 남아있는 유치(젖니)입니다. 방치하면 치열이 틀어질 수 있습니다.' },
  { abbr: 'DTC',         definition: 'Dentigerous cyst',  definition_kr: '함치성 낭종 (Dentigerous cyst)',                                  type: 'dx',  generalComment: '매복된(잇몸 속에 묻힌) 치아 주위에 물주머니(낭종)가 생긴 상태입니다.' },
  { abbr: 'DTC/R',       definition: 'Dentigerous cyst removal',  definition_kr: '함치성 낭종 제거',                          type: 'tx',  parent: 'DTC',  generalComment: '잇몸 속 물주머니(낭종)를 외과적으로 제거하는 수술을 시행하였습니다.' },

  // ── E ──────────────────────────────────────────────────────
  { abbr: 'E',           definition: 'Enamel',  definition_kr: '법랑질 (Enamel)',                                            type: 'anatomy' },
  { abbr: 'E/D',         definition: 'Enamel defect',  definition_kr: '법랑질 결손',                                     type: 'dx',  parent: 'E',  generalComment: '치아의 가장 바깥층인 법랑질(에나멜)에 결손이 생긴 상태입니다.' },
  { abbr: 'E/H',         definition: 'Enamel hypoplasia',  definition_kr: '법랑질 형성부전',                                 type: 'dx',  parent: 'E',  generalComment: '치아 표면(법랑질)이 충분히 형성되지 않아 치아가 약하고 변색이 있을 수 있습니다.' },
  { abbr: 'E/HM',        definition: 'Enamel hypomineralization',  definition_kr: '법랑질 저석회화',                         type: 'dx',  parent: 'E' },
  { abbr: 'E/P',         definition: 'Enamel pearl',  definition_kr: '법랑질 진주',                                      type: 'dx',  parent: 'E' },
  { abbr: 'EM',          definition: 'Erythema multiforme',  definition_kr: '다형홍반',                               type: 'dx' },
  { abbr: 'ENO',         definition: 'Enophthalmos',  definition_kr: '안구함몰',                                      type: 'dx' },
  { abbr: 'EOG',         definition: 'Eosinophilic granuloma',  definition_kr: '호산구성 육아종',                            type: 'dx' },
  { abbr: 'EOG/L',       definition: 'Eosinophilic granuloma (lip)',  definition_kr: '호산구성 육아종 (입술)',                       type: 'dx',  parent: 'EOG' },
  { abbr: 'EOG/P',       definition: 'Eosinophilic granuloma (palate)',  definition_kr: '호산구성 육아종 (구개)',                    type: 'dx',  parent: 'EOG' },
  { abbr: 'EOG/T',       definition: 'Eosinophilic granuloma (tongue)',  definition_kr: '호산구성 육아종 (혀)',                    type: 'dx',  parent: 'EOG' },
  { abbr: 'ER',          definition: 'Erosion',  definition_kr: '미란 (Erosion)',                                           type: 'dx' },
  { abbr: 'ESP',         definition: 'Elongated soft palate',  definition_kr: '연구개 노장 (Elongated soft palate)',                             type: 'dx' },
  { abbr: 'ESP/R',       definition: 'Elongated soft palate reduction',  definition_kr: '연구개 노장 절제술',                   type: 'tx',  parent: 'ESP' },
  { abbr: 'EXO',         definition: 'Exophthalmos',  definition_kr: '안구돌출',                                      type: 'dx' },

  // ── F ──────────────────────────────────────────────────────
  { abbr: 'F',           definition: 'Flap',  definition_kr: '피판 (Flap)',                                              type: 'tx' },
  { abbr: 'F/AD',        definition: 'Advancement flap',  definition_kr: '전진 피판',                                  type: 'tx',  parent: 'F' },
  { abbr: 'F/AP',        definition: 'Apically positioned flap',  definition_kr: '근단변위 피판',                          type: 'tx',  parent: 'F' },
  { abbr: 'F/CO',        definition: 'Coronally positioned flap',  definition_kr: '치관변위 피판',                         type: 'tx',  parent: 'F' },
  { abbr: 'F/EN',        definition: 'Envelope flap',  definition_kr: '봉투형 피판',                                     type: 'tx',  parent: 'F' },
  { abbr: 'F/HI',        definition: 'Hinged (overlapping) flap',  definition_kr: '힌지형(중복) 피판',                         type: 'tx',  parent: 'F' },
  { abbr: 'F/IS',        definition: 'Island flap',  definition_kr: '아일랜드형 피판',                                       type: 'tx',  parent: 'F' },
  { abbr: 'F/LA',        definition: 'Laterally positioned flap',  definition_kr: '측방이동 피판',                         type: 'tx',  parent: 'F' },
  { abbr: 'F/RO',        definition: 'Rotation flap',  definition_kr: '회전 피판',                                     type: 'tx',  parent: 'F' },
  { abbr: 'F/TR',        definition: 'Transposition flap',  definition_kr: '이전(Transposition) 피판',                                type: 'tx',  parent: 'F' },
  { abbr: 'FB',          definition: 'Foreign body',  definition_kr: '이물질',                                      type: 'dx' },
  { abbr: 'FB/R',        definition: 'Foreign body removal',  definition_kr: '이물질 제거',                              type: 'tx',  parent: 'FB' },
  { abbr: 'FOD',         definition: 'Fibrous osteodystrophy',  definition_kr: '섬유성 골이영양증',                            type: 'dx' },
  { abbr: 'FOL',         definition: 'Folliculitis',  definition_kr: '모낭염',                                      type: 'dx' },
  { abbr: 'FRE',         definition: 'Frenuloplasty (frenulotomy, frenulectomy)',  definition_kr: '소대성형술 / 소대절제술',          type: 'tx' },
  { abbr: 'FT',          definition: 'Fiberotomy',  definition_kr: '섬유절단술',                                        type: 'tx' },
  { abbr: 'FX',          definition: 'Fracture (tooth or jaw)',  definition_kr: '골절 (치아 또는 턱)',                           type: 'dx',  generalComment: '치아 또는 턱뼈가 부러진(골절된) 상태입니다.' },
  { abbr: 'FX/R',        definition: 'Repair of jaw fracture',  definition_kr: '턱 골절 복원술',                            type: 'tx',  parent: 'FX',  generalComment: '부러진 턱뼈를 고정하고 회복시키는 수술을 시행하였습니다.' },
  { abbr: 'FX/R/EXF',    definition: 'External skeletal fixation',  definition_kr: '외부 골격 고정술',                        type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/IAS',    definition: 'Interarch splinting',  definition_kr: '악궁간 스플린트',                               type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/IDS',    definition: 'Interdental splinting',  definition_kr: '치아간 스플린트',                             type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/IQS',    definition: 'Interquadrant splinting',  definition_kr: '사분악간 스플린트',                           type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/MMF',    definition: 'Maxillomandibular fixation',  definition_kr: '상하악 고정술',                        type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/MZ',     definition: 'Muzzling',  definition_kr: '입마개 장착',                                          type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/PL',     definition: 'Bone plating',  definition_kr: '골 플레이트 고정식',                                      type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/WIR/C',  definition: 'Wire cerclage',  definition_kr: '철사 환상결찰 (Cerclage)',                                     type: 'tx',  parent: 'FX/R' },
  { abbr: 'FX/R/WIR/OS', definition: 'Intraosseous wiring',  definition_kr: '골내 철사고정술',                               type: 'tx',  parent: 'FX/R' },

  // ── G ──────────────────────────────────────────────────────
  { abbr: 'GC',          definition: 'Gingival curettage',  definition_kr: '치은 소파술',                                type: 'tx',  generalComment: '잇몸 속의 염증 조직을 긁어내어 치주 건강을 회복시키는 처치를 시행하였습니다.' },
  { abbr: 'GE',          definition: 'Gingival enlargement',  definition_kr: '치은 비대',                              type: 'dx',  generalComment: '잇몸 조직이 비정상적으로 부어오르거나 두꺼워진 상태입니다.' },
  { abbr: 'GF',          definition: 'Graft',  definition_kr: '이식재 (Graft)',                                             type: 'tx',  generalComment: '부족한 조직을 채우기 위해 다른 부위의 조직이나 인공 재료를 이식하는 수술을 시행하였습니다.' },
  { abbr: 'GF/B',        definition: 'Bone graft',  definition_kr: '골 이식',                                        type: 'tx',  parent: 'GF' },
  { abbr: 'GF/C',        definition: 'Cartilage graft',  definition_kr: '연골 이식',                                   type: 'tx',  parent: 'GF' },
  { abbr: 'GF/CT',       definition: 'Connective tissue graft',  definition_kr: '결합조직 이식',                           type: 'tx',  parent: 'GF' },
  { abbr: 'GF/F',        definition: 'Fat graft',  definition_kr: '지방 이식',                                         type: 'tx',  parent: 'GF' },
  { abbr: 'GF/G',        definition: 'Gingival graft',  definition_kr: '치은 이식',                                    type: 'tx',  parent: 'GF' },
  { abbr: 'GF/M',        definition: 'Mucosal graft',  definition_kr: '점막 이식',                                     type: 'tx',  parent: 'GF' },
  { abbr: 'GF/N',        definition: 'Nerve graft',  definition_kr: '신경 이식',                                       type: 'tx',  parent: 'GF' },
  { abbr: 'GF/S',        definition: 'Skin graft',  definition_kr: '피부 이식',                                        type: 'tx',  parent: 'GF' },
  { abbr: 'GF/V',        definition: 'Venous graft',  definition_kr: '정맥 이식',                                      type: 'tx',  parent: 'GF' },
  { abbr: 'GH',          definition: 'Gingival hyperplasia',  definition_kr: '치은 증식증',                              type: 'dx',  generalComment: '잇몸 조직이 과도하게 자라나 치아를 덮거나 음식 섭취를 방해할 수 있는 상태입니다.' },
  { abbr: 'GR',          definition: 'Gingival recession',  definition_kr: '치은 퇴축',                                type: 'dx',  generalComment: '잇몸이 내려앉아 치아 뿌리가 노출되어 있는 상태입니다. 차가운 음식에 민감해질 수 있습니다.' },
  { abbr: 'GTR',         definition: 'Guided tissue regeneration',  definition_kr: '조직 유도 재생술',                        type: 'tx',  generalComment: '손상된 잇몸 조직과 잇몸뼈가 다시 재생될 수 있도록 특수 막을 이용하는 수술을 시행하였습니다.' },
  { abbr: 'GV',          definition: 'Gingivectomy / gingivoplasty',  definition_kr: '치은 절제/성형술',                      type: 'tx',  generalComment: '과도하게 자라난 잇몸 조직을 잘라내어 구강 위생 환경을 개선하는 처치를 시행하였습니다.' },

  // ── H ──────────────────────────────────────────────────────
  { abbr: 'HC',          definition: 'Hypercementosis',  definition_kr: '백악질 비대증',                                   type: 'dx' },
  { abbr: 'HS',          definition: 'Hemisection',  definition_kr: '치아 반측절제술',                                       type: 'tx',  generalComment: '치아 뿌리가 두 개인 치아에서, 한쪽 뿌리와 치관을 절반으로 잘라 나쁜 쪽을 제거하는 수술입니다.' },
  { abbr: 'HYP',         definition: 'Hypodontia',  definition_kr: '부분 무치증 (Hypodontia)',                                        type: 'dx' },

  // ── I ──────────────────────────────────────────────────────
  { abbr: 'I1,2,3',      definition: 'Incisor',  definition_kr: '절치 (앞니)',                                           type: 'anatomy' },
  { abbr: 'IM',          definition: 'Detailed imprint of hard and/or soft tissues',  definition_kr: '임프레션 (인상채득)',      type: 'dx' },
  { abbr: 'IM/F',        definition: 'Full-mouth impression',  definition_kr: '전악 인상채득',                             type: 'dx',  parent: 'IM' },
  { abbr: 'IMP',         definition: 'Implant',  definition_kr: '임플란트',                                           type: 'tx' },
  { abbr: 'INF',         definition: 'Infundibulum',  definition_kr: '원뿔 (누두부)',                                      type: 'anatomy' },
  { abbr: 'IOF',         definition: 'Intraoral fistula',  definition_kr: '구강내 누공',                                 type: 'dx',  generalComment: '입 안에 비정상적인 통로(누공)가 생겨 고름이나 분비물이 나올 수 있는 상태입니다.' },
  { abbr: 'IOF/R',       definition: 'Intraoral fistula repair',  definition_kr: '구강내 누공 복원술',                          type: 'tx',  parent: 'IOF',  generalComment: '입 안에 생긴 비정상적인 통로(누공)를 막는 수술을 시행하였습니다.' },
  { abbr: 'IP',          definition: 'Inclined plane',  definition_kr: '경사면 장치 (Inclined plane)',                                    type: 'tx' },
  { abbr: 'IP/AC',       definition: 'Acrylic inclined plane',  definition_kr: '아크릴릭 경사면',                            type: 'tx',  parent: 'IP' },
  { abbr: 'IP/C',        definition: 'Composite inclined plane',  definition_kr: '컴포지트 경사면',                          type: 'tx',  parent: 'IP' },
  { abbr: 'IP/M',        definition: 'Metal (lab-produced) inclined plane',  definition_kr: '금속 경사면',               type: 'tx',  parent: 'IP' },
  { abbr: 'ITH',         definition: 'Immunotherapy',  definition_kr: '면역요법',                                     type: 'tx' },

  // ── L ──────────────────────────────────────────────────────
  { abbr: 'LAC',         definition: 'Laceration',  definition_kr: '열상 (찢김)',                                        type: 'dx' },
  { abbr: 'LAC/B',       definition: 'Laceration (cheek skin / buccal mucosa)',  definition_kr: '볼 열상',           type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/G',       definition: 'Laceration (gingiva / alveolar mucosa)',  definition_kr: '치은/점막 열상',            type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/L',       definition: 'Laceration (lip skin / labial mucosa)',  definition_kr: '입술 열상',             type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/O',       definition: 'Laceration (palatine tonsil / oropharyngeal mucosa)',  definition_kr: '구인두 열상', type: 'dx', parent: 'LAC' },
  { abbr: 'LAC/P',       definition: 'Laceration (palatal mucosa)',  definition_kr: '구개 열상',                       type: 'dx',  parent: 'LAC' },
  { abbr: 'LAC/R',       definition: 'Laceration repair',  definition_kr: '열상 봉합술',                                 type: 'tx',  parent: 'LAC' },
  { abbr: 'LAC/T',       definition: 'Laceration (lingual / sublingual mucosa)',  definition_kr: '혀/설하 열상',          type: 'dx',  parent: 'LAC' },
  { abbr: 'LE',          definition: 'Lupus erythematosus',  definition_kr: '홍반성 루푸스',                               type: 'dx' },
  { abbr: 'LIN',         definition: 'Tongue',  definition_kr: '혀',                                            type: 'anatomy' },
  { abbr: 'LIN/X',       definition: 'Tongue resection',  definition_kr: '혀 절제술',                                  type: 'tx',  parent: 'LIN' },
  { abbr: 'LIP',         definition: 'Lip / cheek',  definition_kr: '입술 / 뺨',                                       type: 'anatomy' },
  { abbr: 'LIP/A/R',     definition: 'Lip avulsion repair',  definition_kr: '입술 탈구(찢김) 복원',                               type: 'tx',  parent: 'LIP' },
  { abbr: 'LIP/X',       definition: 'Lip / cheek resection',  definition_kr: '입술/뺨 절제술',                             type: 'tx',  parent: 'LIP' },
  { abbr: 'LN',          definition: 'Lymph node (regional)',  definition_kr: '국소 림프절',                             type: 'anatomy' },
  { abbr: 'LN/E',        definition: 'Lymph node enlargement',  definition_kr: '림프절 비대',                            type: 'dx',  parent: 'LN' },
  { abbr: 'LN/X',        definition: 'Lymph node resection',  definition_kr: '림프절 절제술',                              type: 'tx',  parent: 'LN' },

  // ── M ──────────────────────────────────────────────────────
  { abbr: 'M1,2,3',      definition: 'Molar',  definition_kr: '구치 (어금니)',                                             type: 'anatomy' },
  { abbr: 'MAL',         definition: 'Malocclusion',  definition_kr: '부정교합',                                      type: 'dx',  generalComment: '위아래 치아가 제대로 맞물리지 않는 상태(부정교합)입니다. 음식 섭취나 구강 건강에 영향을 줄 수 있습니다.' },
  { abbr: 'MAL1',        definition: 'Class 1 malocclusion (neutroclusion)',  definition_kr: '1급 부정교합 (Neutroclusion)',              type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL1/BV',     definition: 'Buccoversion',  definition_kr: '협측 전위',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/DV',     definition: 'Distoversion',  definition_kr: '원심 전위',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/LABV',   definition: 'Labioversion',  definition_kr: '순측 전위',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/LV',     definition: 'Linguoversion',  definition_kr: '설측 전위',                                     type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/MV',     definition: 'Mesioversion',  definition_kr: '근심 전위',                                      type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL1/PV',     definition: 'Palatoversion',  definition_kr: '구개측 전위',                                     type: 'dx',  parent: 'MAL1' },
  { abbr: 'MAL2',        definition: 'Class 2 malocclusion (mandibular distoclusion)',  definition_kr: '2급 부정교합 (과개교합)',    type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL3',        definition: 'Class 3 malocclusion (mandibular mesioclusion)',  definition_kr: '3급 부정교합 (반대교합)',    type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL4',        definition: 'Class 4 malocclusion (asymmetrical skeletal)',  definition_kr: '4급 부정교합 (비대칭성)',      type: 'dx',  parent: 'MAL' },
  { abbr: 'MAL4/DV',     definition: 'Asymmetrical skeletal malocclusion (dorsoventral)',  definition_kr: '비대칭성 골격이상 (등배측)', type: 'dx',  parent: 'MAL4' },
  { abbr: 'MAL4/RC',     definition: 'Asymmetrical skeletal malocclusion (rostrocaudal)',  definition_kr: '비대칭성 골격이상 (두미측)', type: 'dx',  parent: 'MAL4' },
  { abbr: 'MAL4/STS',    definition: 'Asymmetrical skeletal malocclusion (side-to-side)',  definition_kr: '비대칭성 골격이상 (좌우측)', type: 'dx',  parent: 'MAL4' },
  { abbr: 'MAR',         definition: 'Marsupialization',  definition_kr: '조대술 (Marsupialization)',                                  type: 'tx' },
  { abbr: 'MET',         definition: 'Metastasis',  definition_kr: '전이 (Metastasis)',                                        type: 'dx' },
  { abbr: 'MET/D',       definition: 'Distant metastasis',  definition_kr: '원격 전이',                                type: 'dx',  parent: 'MET' },
  { abbr: 'MET/R',       definition: 'Regional metastasis',  definition_kr: '국소 전이',                               type: 'dx',  parent: 'MET' },
  { abbr: 'MMM',         definition: 'Masticatory muscle myositis',  definition_kr: '저작근염',                       type: 'dx' },
  { abbr: 'MN',          definition: 'Mandible / mandibular',  definition_kr: '하악 (아랫턱)',                             type: 'anatomy' },
  { abbr: 'MN/FX',       definition: 'Mandibular fracture',  definition_kr: '하악 골절',                               type: 'dx',  parent: 'MN' },
  { abbr: 'MRI',         definition: 'Magnetic resonance imaging',  definition_kr: '자기공명영상 (MRI)',                        type: 'dx' },
  { abbr: 'MX',          definition: 'Maxilla / maxillary',  definition_kr: '상악 (위턱)',                               type: 'anatomy' },
  { abbr: 'MX/FX',       definition: 'Maxillary fracture',  definition_kr: '상악 골절',                                type: 'dx',  parent: 'MX' },

  // ── N ──────────────────────────────────────────────────────
  { abbr: 'N',           definition: 'Nose / nasal / nasopharyngeal',  definition_kr: '코 / 비강 / 비인두',                     type: 'anatomy' },
  { abbr: 'N/EN',        definition: 'Rhinoscopy',  definition_kr: '비강내시경',                                        type: 'dx',  parent: 'N' },
  { abbr: 'N/LAV',       definition: 'Nasal lavage',  definition_kr: '비강 세척',                                      type: 'tx',  parent: 'N' },
  { abbr: 'N/NS',        definition: 'Naris stenosis',  definition_kr: '비공 협착',                                    type: 'dx',  parent: 'N' },
  { abbr: 'N/NS/R',      definition: 'Naroplasty',  definition_kr: '비공 성형술',                                        type: 'tx',  parent: 'N/NS' },
  { abbr: 'N/NPS',       definition: 'Nasopharyngeal stenosis',  definition_kr: '비인두 협착',                           type: 'dx',  parent: 'N' },
  { abbr: 'N/NPS/R',     definition: 'Nasopharyngeal stenosis repair',  definition_kr: '비인두 협착 복원술',                    type: 'tx',  parent: 'N/NPS' },
  { abbr: 'N/POL',       definition: 'Nasopharyngeal polyp',  definition_kr: '비인두 폴립',                              type: 'dx',  parent: 'N' },
  { abbr: 'N/SCC',       definition: 'Nasal SCC',  definition_kr: '비강 편평상피암',                                         type: 'dx',  parent: 'N' },

  // ── O ──────────────────────────────────────────────────────
  { abbr: 'OA',          definition: 'Orthodontic appliance',  definition_kr: '교정 장치',                             type: 'tx' },
  { abbr: 'OA/A',        definition: 'Orthodontic appliance adjustment',  definition_kr: '교정 장치 조절',                  type: 'tx',  parent: 'OA' },
  { abbr: 'OA/AR',       definition: 'Arch bar',  definition_kr: '아치 바',                                          type: 'tx',  parent: 'OA' },
  { abbr: 'OA/BKT',      definition: 'Bracket, button or hook',  definition_kr: '브라켓 / 버튼 / 훅',                           type: 'tx',  parent: 'OA' },
  { abbr: 'OA/CMB',      definition: 'Custom-made OA/BKT',  definition_kr: '맞춤형 교정 장치',                                type: 'tx',  parent: 'OA' },
  { abbr: 'OA/EC',       definition: 'Elastic chain, tube or thread',  definition_kr: '고무줄 / 튜브 / 실',                     type: 'tx',  parent: 'OA' },
  { abbr: 'OA/I',        definition: 'Orthodontic appliance installment',  definition_kr: '교정 장치 장착',                 type: 'tx',  parent: 'OA' },
  { abbr: 'OA/R',        definition: 'Orthodontic appliance removal',  definition_kr: '교정 장치 제거',                     type: 'tx',  parent: 'OA' },
  { abbr: 'OA/WIR',      definition: 'Orthodontic wire',  definition_kr: '교정용 와이어',                                  type: 'tx',  parent: 'OA' },
  { abbr: 'OAF',         definition: 'Oroantral fistula',  definition_kr: '구강상악동 누공',                                 type: 'dx',  generalComment: '입 안과 코의 빈 공간(부비동)이 비정상적으로 연결된 통로가 생긴 상태입니다. 음식물이 코로 넘어갈 수 있습니다.' },
  { abbr: 'OAF/R',       definition: 'Oroantral fistula repair',  definition_kr: '구강상악동 누공 복원술',                          type: 'tx',  parent: 'OAF',  generalComment: '입과 코 공간 사이의 비정상적인 통로를 막는 수술을 시행하였습니다.' },
  { abbr: 'OC',          definition: 'Orthodontic counseling',  definition_kr: '교정 상담',                            type: 'tx' },
  { abbr: 'ODY',         definition: 'Odontoplasty',  definition_kr: '치아 성형술',                                      type: 'tx' },
  { abbr: 'OFF',         definition: 'Orofacial fistula',  definition_kr: '구강안면 누공',                                 type: 'dx' },
  { abbr: 'OFF/R',       definition: 'Orofacial fistula repair',  definition_kr: '구강안면 누공 복원술',                          type: 'tx',  parent: 'OFF' },
  { abbr: 'OLI',         definition: 'Oligodontia',  definition_kr: '소수치아증',                                       type: 'dx' },
  { abbr: 'OM',          definition: 'Oral / maxillofacial mass',  definition_kr: '구강/안면 종괴',                         type: 'dx' },
  { abbr: 'OM/AA',       definition: 'Acanthomatous ameloblastoma',  definition_kr: '극세포성 사기질세포종',                       type: 'dx',  parent: 'OM' },
  { abbr: 'OM/AD',       definition: 'Adenoma',  definition_kr: '선종',                                           type: 'dx',  parent: 'OM' },
  { abbr: 'OM/ADC',      definition: 'Adenocarcinoma',  definition_kr: '선암종',                                    type: 'dx',  parent: 'OM' },
  { abbr: 'OM/APN',      definition: 'Anaplastic neoplasm',  definition_kr: '역형성 종양',                               type: 'dx',  parent: 'OM' },
  { abbr: 'OM/APO',      definition: 'Amyloid-producing odontogenic tumor',  definition_kr: '아밀로이드 생성 치성 종양',               type: 'dx',  parent: 'OM' },
  { abbr: 'OM/CE',       definition: 'Cementoma',  definition_kr: '백악질종',                                         type: 'dx',  parent: 'OM' },
  { abbr: 'OM/FIO',      definition: 'Feline inductive odontogenic tumor',  definition_kr: '고양이 유도성 치성 종양',                type: 'dx',  parent: 'OM' },
  { abbr: 'OM/FS',       definition: 'Fibrosarcoma',  definition_kr: '섬유육종',                                      type: 'dx',  parent: 'OM' },
  { abbr: 'OM/GCG',      definition: 'Giant cell granuloma',  definition_kr: '거대세포 육아종',                              type: 'dx',  parent: 'OM' },
  { abbr: 'OM/GCT',      definition: 'Granular cell tumor',  definition_kr: '과립세포 종양',                               type: 'dx',  parent: 'OM' },
  { abbr: 'OM/HS',       definition: 'Hemangiosarcoma',  definition_kr: '혈관육종',                                   type: 'dx',  parent: 'OM' },
  { abbr: 'OM/LI',       definition: 'Lipoma',  definition_kr: '지방종',                                            type: 'dx',  parent: 'OM' },
  { abbr: 'OM/LS',       definition: 'Lymphosarcoma',  definition_kr: '림프육종',                                     type: 'dx',  parent: 'OM' },
  { abbr: 'OM/MCT',      definition: 'Mast cell tumor',  definition_kr: '비만세포종',                                   type: 'dx',  parent: 'OM' },
  { abbr: 'OM/MM',       definition: 'Malignant melanoma',  definition_kr: '악성 흑색종',                                type: 'dx',  parent: 'OM' },
  { abbr: 'OM/MTB',      definition: 'Multilobular tumor of bone',  definition_kr: '다엽성 골종양',                        type: 'dx',  parent: 'OM' },
  { abbr: 'OM/OO',       definition: 'Osteoma',  definition_kr: '골종',                                           type: 'dx',  parent: 'OM' },
  { abbr: 'OM/OS',       definition: 'Osteosarcoma',  definition_kr: '골육종',                                      type: 'dx',  parent: 'OM' },
  { abbr: 'OM/PAP',      definition: 'Papilloma',  definition_kr: '유두종 (파필로마)',                                         type: 'dx',  parent: 'OM' },
  { abbr: 'OM/PCT',      definition: 'Plasma cell tumor',  definition_kr: '형질세포종',                                 type: 'dx',  parent: 'OM' },
  { abbr: 'OM/PNT',      definition: 'Peripheral nerve sheath tumor',  definition_kr: '말초신경초종양',                     type: 'dx',  parent: 'OM' },
  { abbr: 'OM/POF',      definition: 'Peripheral odontogenic fibroma',  definition_kr: '말초 치성 섬유종',                    type: 'dx',  parent: 'OM' },
  { abbr: 'OM/RBM',      definition: 'Rhabdomyosarcoma',  definition_kr: '횡문근육종',                                  type: 'dx',  parent: 'OM' },
  { abbr: 'OM/SCC',      definition: 'Squamous cell carcinoma',  definition_kr: '편평상피암종 (SCC)',                           type: 'dx',  parent: 'OM' },
  { abbr: 'OM/UDN',      definition: 'Undifferentiated neoplasm',  definition_kr: '미분화 종양',                         type: 'dx',  parent: 'OM' },
  { abbr: 'OMJL',        definition: 'Open-mouth jaw locking',  definition_kr: '개구성 하악 과두 잠김',                            type: 'dx' },
  { abbr: 'OMJL/R',      definition: 'Open-mouth jaw locking reduction',  definition_kr: '개구성 하악 과두 잠김 환원술',                  type: 'tx',  parent: 'OMJL' },
  { abbr: 'ONF',         definition: 'Oronasal fistula',  definition_kr: '구비루 (구강비강 누공)',                                  type: 'dx',  generalComment: '입과 코가 비정상적으로 연결된 상태입니다. 음식이나 물이 코로 넘어가거나 콧물이 나올 수 있습니다.' },
  { abbr: 'ONF/R',       definition: 'Oronasal fistula repair',  definition_kr: '구비루 복원술',                           type: 'tx',  parent: 'ONF',  generalComment: '입과 코가 연결된 비정상적인 통로를 막는 수술을 시행하였습니다.' },
  { abbr: 'OP',          definition: 'Operculectomy',  definition_kr: '치은판 절제술',                                     type: 'tx' },
  { abbr: 'OR',          definition: 'Orthodontic recheck',  definition_kr: '교정학적 재검진',                               type: 'tx' },
  { abbr: 'OS',          definition: 'Orthognathic surgery',  definition_kr: '악안면성형술',                              type: 'tx' },
  { abbr: 'OSN',         definition: 'Osteonecrosis',  definition_kr: '골괴사증',                                     type: 'dx' },
  { abbr: 'OSS',         definition: 'Osteosclerosis',  definition_kr: '골경화증',                                    type: 'dx' },
  { abbr: 'OST',         definition: 'Osteomyelitis',  definition_kr: '골수염',                                     type: 'dx' },

  // ── P ──────────────────────────────────────────────────────
  { abbr: 'PA',          definition: 'Periapical',  definition_kr: '치근단 (Periapical)',                                        type: 'anatomy' },
  { abbr: 'PA/A',        definition: 'Periapical abscess',  definition_kr: '치근단 농양',                                type: 'dx',  parent: 'PA',  generalComment: '치아 뿌리 끝에 고름(농양)이 고인 상태입니다. 심한 통증과 부기를 유발할 수 있습니다.' },
  { abbr: 'PA/C',        definition: 'Periapical cyst',  definition_kr: '치근단 낭종',                                   type: 'dx',  parent: 'PA',  generalComment: '치아 뿌리 끝에 물주머니(낭종)가 생긴 상태입니다.' },
  { abbr: 'PA/G',        definition: 'Periapical granuloma',  definition_kr: '치근단 육아종',                              type: 'dx',  parent: 'PA',  generalComment: '치아 뿌리 끝에 만성 염증으로 인한 염증 조직 덩어리가 생긴 상태입니다.' },
  { abbr: 'PA/P',        definition: 'Periapical pathology',  definition_kr: '치근단 병변',                              type: 'dx',  parent: 'PA',  generalComment: '치아 뿌리 끝 주변에 병적인 변화(병변)가 확인되었습니다.' },
  { abbr: 'PCB',         definition: 'Post-and-core build-up',  definition_kr: '포스트 앤 코어 수복',                            type: 'tx',  generalComment: '신경 치료 후 약해진 치아에 기둥(포스트)을 심고 그 위에 재료를 쌓아 치아를 복원하였습니다.' },
  { abbr: 'PCD',         definition: 'Direct pulp capping',  definition_kr: '직접 치수 복조술',                               type: 'tx',  generalComment: '치수(신경)가 노출된 경우 특수 재료로 덮어 치수를 보호하는 처치를 시행하였습니다.' },
  { abbr: 'PCI',         definition: 'Indirect pulp capping',  definition_kr: '간접 치수 복조술',                             type: 'tx',  generalComment: '치수(신경) 노출을 막기 위해 보호 재료를 간접적으로 적용하는 처치를 시행하였습니다.' },
  { abbr: 'PD',          definition: 'Periodontal disease',  definition_kr: '치주염 / 치주질환',                               type: 'dx',  generalComment: '잇몸과 치아를 지지하는 조골에 염증이 생긴 상태입니다. 치료하지 않으면 치아가 빠질 수 있습니다.' },
  { abbr: 'PD0',         definition: 'Clinically normal',  definition_kr: '정상 치주',                                 type: 'dx',  parent: 'PD',  generalComment: '잇몸 및 치주 상태가 정상입니다.' },
  { abbr: 'PD1',         definition: 'Gingivitis only (without attachment loss)',  definition_kr: '1기 치주질환 (치은염만 존재)',          type: 'dx',  parent: 'PD',  generalComment: '잇몸(치은)에만 염증이 있는 초기 단계입니다. 이 단계에서는 치료를 통해 완전 회복이 가능합니다.' },
  { abbr: 'PD2',         definition: 'Early periodontitis (<25% attachment loss)',  definition_kr: '2기 치주질환 (애착상실 25% 미만)',        type: 'dx',  parent: 'PD',  generalComment: '초기 치주염으로, 잇몸뼈가 25% 미만으로 손상된 상태입니다. 적극적인 치료와 관리가 필요합니다.' },
  { abbr: 'PD3',         definition: 'Moderate periodontitis (25–50% attachment loss)',  definition_kr: '3기 치주질환 (애착상실 25~50%)',   type: 'dx',  parent: 'PD',  generalComment: '중등도 치주염으로, 잇몸뼈가 25~50% 손상된 상태입니다. 전문적인 치료와 꾸준한 관리가 중요합니다.' },
  { abbr: 'PD4',         definition: 'Advanced periodontitis (>50% attachment loss)',  definition_kr: '4기 치주질환 (애착상실 50% 초과)',     type: 'dx',  parent: 'PD',  generalComment: '심한 치주염으로, 잇몸뼈가 50% 이상 손상된 상태입니다. 치아를 유지하기 어려울 수 있으며 발치가 필요할 수 있습니다.' },
  { abbr: 'PDE',         definition: 'Acquired palate defect',  definition_kr: '후천성 구개 결손',                            type: 'dx' },
  { abbr: 'PDE/R',       definition: 'Acquired palate defect repair',  definition_kr: '후천성 구개 결손 복원술',                     type: 'tx',  parent: 'PDE' },
  { abbr: 'PEC',         definition: 'Pericoronitis',  definition_kr: '치관주위염',                                     type: 'dx' },
  { abbr: 'PEO',         definition: 'Periostitis ossificans',  definition_kr: '화골성 골막염',                            type: 'dx' },
  { abbr: 'PH',          definition: 'Pulp horn (equines, du Toit system)',  definition_kr: '치수각',               type: 'anatomy' },
  { abbr: 'PH/D',        definition: 'Pulp horn defect',  definition_kr: '치수각 결손',                                  type: 'dx',  parent: 'PH' },
  { abbr: 'PHA',         definition: 'Pharynx',  definition_kr: '인두',                                           type: 'anatomy' },
  { abbr: 'PHA/IN',      definition: 'Pharyngitis',  definition_kr: '인두염',                                       type: 'dx',  parent: 'PHA' },
  { abbr: 'PM1-4',       definition: 'Premolar',  definition_kr: '소구치 (작은어금니)',                                          type: 'anatomy' },
  { abbr: 'POB',         definition: 'Palatal obturator',  definition_kr: '구개 폐쇄기',                                 type: 'tx' },
  { abbr: 'PRO',         definition: 'Professional dental cleaning (scaling, polishing, irrigation)',  definition_kr: '스케일링/연마 (전문 치과 치료)', type: 'tx',  generalComment: '전문 치과 기구를 이용하여 치아에 쌓인 치석과 플라그를 제거하고 치아를 연마하는 스케일링 시술을 하였습니다.' },
  { abbr: 'PTY',         definition: 'Ptyalism',  definition_kr: '유연증 (침흘림)',                                          type: 'dx' },
  { abbr: 'PU',          definition: 'Pulp',  definition_kr: '치수 (Pulp)',                                              type: 'anatomy' },
  { abbr: 'PU/M',        definition: 'Mineralization of pulp',  definition_kr: '치수 석회화',                            type: 'dx',  parent: 'PU' },
  { abbr: 'PU/S',        definition: 'Pulp stone',  definition_kr: '치수석 (치석)',                                        type: 'dx',  parent: 'PU' },
  { abbr: 'PV',          definition: 'Pemphigus vulgaris',  definition_kr: '심상성 건선 / 유천포창',                                type: 'dx' },
  { abbr: 'PYO',         definition: 'Pyogenic granuloma',  definition_kr: '화농성 육아종',                                type: 'dx' },

  // ── R ──────────────────────────────────────────────────────
  { abbr: 'R',           definition: 'Restoration (filling of a dental defect)',  definition_kr: '수복물 (레진 등)',          type: 'tx',  generalComment: '충치나 파절 등으로 손상된 치아를 특수 재료로 채워 복원하는 수복 치료를 시행하였습니다.' },
  { abbr: 'R/A',         definition: 'Filling made of amalgam',  definition_kr: '아말감 수복',                           type: 'tx',  parent: 'R',  generalComment: '손상된 치아를 아말감 재료로 채워 복원하였습니다.' },
  { abbr: 'R/C',         definition: 'Filling made of composite',  definition_kr: '복합레진 수복',                         type: 'tx',  parent: 'R',  generalComment: '치아색과 유사한 레진 재료로 손상된 치아를 채워 복원하였습니다.' },
  { abbr: 'R/CP',        definition: 'Filling made of compomer',  definition_kr: '컴포머 수복',                          type: 'tx',  parent: 'R',  generalComment: '컴포머 재료로 손상된 치아를 채워 복원하였습니다.' },
  { abbr: 'R/I',         definition: 'Filling made of glass ionomer',  definition_kr: 'GI (글라스 아이오노머) 수복',                     type: 'tx',  parent: 'R',  generalComment: '글라스 아이오노머 재료로 손상된 치아를 채워 복원하였습니다. 불소를 서서히 방출하는 효과가 있습니다.' },
  { abbr: 'RAD',         definition: 'Radiography',  definition_kr: '방사선 (X-ray)',                                       type: 'dx' },
  { abbr: 'RAD/SG',      definition: 'Sialography',  definition_kr: '타액선 조영술',                                       type: 'dx',  parent: 'RAD' },
  { abbr: 'RBA',         definition: 'Retrobulbar abscess',  definition_kr: '안구후 농양',                               type: 'dx' },
  { abbr: 'RCR',         definition: 'Retained crown-root or clinical crown-reserve crown',  definition_kr: '잔존 치관-치근', type: 'dx' },
  { abbr: 'RCT',         definition: 'Standard root canal therapy',  definition_kr: '일반 근관치료(신경치료)',                       type: 'tx',  generalComment: '치아 내부의 신경과 혈관(치수) 조직을 제거하고 깨끗이 소독하여 치아를 살리는 신경치료를 시행하였습니다.' },
  { abbr: 'RCT/S',       definition: 'Surgical root canal therapy',  definition_kr: '외과적 근관치료',                       type: 'tx',  parent: 'RCT',  generalComment: '일반 신경치료로 접근하기 어려운 경우, 잇몸을 절개하여 접근하는 수술적 신경치료를 시행하였습니다.' },
  { abbr: 'RO',          definition: 'Root',  definition_kr: '치근 (뿌리)',                                              type: 'anatomy' },
  { abbr: 'RO/AC',       definition: 'Anatomical root',  definition_kr: '해부학적 치근',                                   type: 'anatomy', parent: 'RO' },
  { abbr: 'RO/CR',       definition: 'Clinical root',  definition_kr: '임상적 치근',                                     type: 'anatomy', parent: 'RO' },
  { abbr: 'RO/X',        definition: 'Root resection / amputation',  definition_kr: '치근 절단수술',                       type: 'tx',  parent: 'RO' },
  { abbr: 'RP',          definition: 'Root planing',  definition_kr: '치근 활택술',                                      type: 'tx',  generalComment: '치아 뿌리 표면에 붙은 치석과 오염물질을 긁어내어 매끄럽게 만드는 치주 치료를 시행하였습니다.' },
  { abbr: 'RP/C',        definition: 'Closed root planing',  definition_kr: '폐쇄형 치근 활택술',                               type: 'tx',  parent: 'RP',  generalComment: '잇몸을 절개하지 않고 기구를 잇몸 안으로 넣어 치아 뿌리를 세정하는 치료를 시행하였습니다.' },
  { abbr: 'RP/O',        definition: 'Open root planing',  definition_kr: '개방형 치근 활택술',                                 type: 'tx',  parent: 'RP',  generalComment: '잇몸을 절개하여 치아 뿌리를 직접 눈으로 보면서 세정하는 치료를 시행하였습니다.' },
  { abbr: 'RPA',         definition: 'Retropharyngeal abscess',  definition_kr: '인두후 농양',                           type: 'dx' },
  { abbr: 'RR',          definition: 'Internal resorption',  definition_kr: '내부 흡수',                               type: 'dx',  generalComment: '치아 내부 조직이 스스로 녹아 없어지는 현상이 확인되었습니다.' },
  { abbr: 'RTH',         definition: 'Radiotherapy',  definition_kr: '방사선 요법',                                      type: 'tx' },
  { abbr: 'RTR',         definition: 'Retained root or reserve crown',  definition_kr: '잔존 치근',                    type: 'dx' },

  // ── S ──────────────────────────────────────────────────────
  { abbr: 'S',           definition: 'Surgery',  definition_kr: '수술 (Surgery)',                                           type: 'tx' },
  { abbr: 'S/M',         definition: 'Partial mandibulectomy',  definition_kr: '부분 하악절제술',                            type: 'tx',  parent: 'S' },
  { abbr: 'S/MB',        definition: 'Bilateral partial mandibulectomy',  definition_kr: '양측 부분 하악절제술',                  type: 'tx',  parent: 'S' },
  { abbr: 'S/MD',        definition: 'Dorsal marginal mandibulectomy',  definition_kr: '등쪽 변연 하악절제술',                    type: 'tx',  parent: 'S' },
  { abbr: 'S/MS',        definition: 'Segmental mandibulectomy',  definition_kr: '하악 분절절제술',                          type: 'tx',  parent: 'S' },
  { abbr: 'S/MT',        definition: 'Total mandibulectomy',  definition_kr: '전체 하악절제술',                              type: 'tx',  parent: 'S' },
  { abbr: 'S/P',         definition: 'Partial palatectomy',  definition_kr: '부분 구개절제술',                               type: 'tx',  parent: 'S' },
  { abbr: 'S/X',         definition: 'Partial maxillectomy',  definition_kr: '부분 상악절제술',                              type: 'tx',  parent: 'S' },
  { abbr: 'S/XB',        definition: 'Bilateral partial maxillectomy',  definition_kr: '양측 부분 상악절제술',                    type: 'tx',  parent: 'S' },
  { abbr: 'SCI',         definition: 'Scintigraphy',  definition_kr: '신티그래피 (섬광조영술)',                                      type: 'dx' },
  { abbr: 'SG',          definition: 'Salivary gland',  definition_kr: '타액선 (침샘)',                                    type: 'anatomy' },
  { abbr: 'SG/ADC',      definition: 'Salivary gland adenocarcinoma',  definition_kr: '타액선 선암종',                     type: 'dx',  parent: 'SG' },
  { abbr: 'SG/ADS',      definition: 'Sialadenosis',  definition_kr: '침샘증',                                      type: 'dx',  parent: 'SG' },
  { abbr: 'SG/IN',       definition: 'Sialadenitis',  definition_kr: '타액선염',                                      type: 'dx',  parent: 'SG' },
  { abbr: 'SG/MAR',      definition: 'Marsupialization',  definition_kr: '조대술 (침샘)',                                  type: 'tx',  parent: 'SG' },
  { abbr: 'SG/MUC/C',    definition: 'Cervical sialocele',  definition_kr: '경부 점액종',                                type: 'dx',  parent: 'SG' },
  { abbr: 'SG/MUC/P',    definition: 'Pharyngeal sialocele',  definition_kr: '인두 점액종',                              type: 'dx',  parent: 'SG' },
  { abbr: 'SG/MUC/S',    definition: 'Sublingual sialocele',  definition_kr: '설하 점액종',                              type: 'dx',  parent: 'SG' },
  { abbr: 'SG/NEC',      definition: 'Necrotizing sialometaplasia',  definition_kr: '괴사성 점액화생',                       type: 'dx',  parent: 'SG' },
  { abbr: 'SG/RC',       definition: 'Mucous retention cyst',  definition_kr: '점액 정체 낭종',                             type: 'dx',  parent: 'SG' },
  { abbr: 'SG/SI',       definition: 'Sialolith',  definition_kr: '타석증',                                         type: 'dx',  parent: 'SG' },
  { abbr: 'SG/X',        definition: 'Salivary gland resection',  definition_kr: '타액선 절제술',                          type: 'tx',  parent: 'SG' },
  { abbr: 'SHE',         definition: 'Shear mouth (equines)',  definition_kr: '쉬어 하악 (Shear mouth)',                             type: 'dx' },
  { abbr: 'SIN',         definition: 'Sinus',  definition_kr: '부비동 (Sinus)',                                             type: 'anatomy' },
  { abbr: 'SIN/CF',      definition: 'Conchofrontal sinus',  definition_kr: '전두동',                               type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/CF/F',    definition: 'Conchofrontal sinus flap',  definition_kr: '전두동 피판술',                          type: 'tx',  parent: 'SIN/CF' },
  { abbr: 'SIN/CMX',     definition: 'Caudal maxillary sinus',  definition_kr: '후방 상악동',                            type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/EN',      definition: 'Sinoscopy',  definition_kr: '부비동 내시경',                                         type: 'dx',  parent: 'SIN' },
  { abbr: 'SIN/F',       definition: 'Sinus flap',  definition_kr: '부비동 피판술',                                        type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/IN',      definition: 'Sinusitis',  definition_kr: '부비동염',                                         type: 'dx',  parent: 'SIN' },
  { abbr: 'SIN/LAV',     definition: 'Sinus lavage',  definition_kr: '부비동 세척',                                      type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/MX/F',    definition: 'Maxillary sinus flap',  definition_kr: '상악동 피판술',                              type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/RMX',     definition: 'Rostral maxillary sinus',  definition_kr: '전방 상악동',                           type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/SP',      definition: 'Sphenopalatine sinus',  definition_kr: '접형구개동',                              type: 'anatomy', parent: 'SIN' },
  { abbr: 'SIN/TRP',     definition: 'Sinus trephination',  definition_kr: '부비동 천공술',                                type: 'tx',  parent: 'SIN' },
  { abbr: 'SIN/VC',      definition: 'Ventral conchal sinus',  definition_kr: '배측 비갑개동',                             type: 'anatomy', parent: 'SIN' },
  { abbr: 'SR',          definition: 'Surgical repositioning',  definition_kr: '외과적 위치이동',                            type: 'tx' },
  { abbr: 'ST',          definition: 'Stomatitis',  definition_kr: '구내염 (Stomatitis)',                                        type: 'dx',  generalComment: '입 안 점막에 염증이 생긴 구내염이 확인되었습니다. 통증, 침 흘림, 식욕 감소 등의 증상이 나타날 수 있습니다.' },
  { abbr: 'ST/CS',       definition: 'Caudal stomatitis',  definition_kr: '만성 구내염 (Caudal stomatitis)',                                 type: 'dx',  parent: 'ST',  generalComment: '입 안 뒤쪽에 심한 만성 구내염이 있는 상태입니다. 고양이에게서 흔하며, 심한 통증으로 식사를 거부할 수 있습니다.' },
  { abbr: 'SYM',         definition: 'Mandibular symphysis',  definition_kr: '하악 결합',                              type: 'anatomy' },
  { abbr: 'SYM/R',       definition: 'Mandibular symphysis repair',  definition_kr: '하악 결합 복원술',                       type: 'tx',  parent: 'SYM' },
  { abbr: 'SYM/S',       definition: 'Mandibular symphysis separation',  definition_kr: '하악 결합 분리',                   type: 'dx',  parent: 'SYM' },

  // ── T ──────────────────────────────────────────────────────
  { abbr: 'T',           definition: 'Tooth',  definition_kr: '치아 (Tooth)',                                             type: 'anatomy' },
  { abbr: 'T/A',         definition: 'Avulsed tooth',  definition_kr: '탈구된 치아',                                     type: 'dx',  parent: 'T',  generalComment: '치아가 잇몸뼈로부터 완전히 빠져나온 상태입니다.' },
  { abbr: 'T/CCR',       definition: 'Concrescence',  definition_kr: '유착치',                                      type: 'dx',  parent: 'T',  generalComment: '두 개 이상의 치아 뿌리가 서로 합쳐져 붙어있는 상태입니다.' },
  { abbr: 'T/DEN',       definition: 'Dens invaginatus',  definition_kr: '치내치',                                  type: 'dx',  parent: 'T' },
  { abbr: 'T/DIL',       definition: 'Dilaceration',  definition_kr: '만곡치',                                      type: 'dx',  parent: 'T' },
  { abbr: 'T/E',         definition: 'Embedded tooth',  definition_kr: '매복치',                                    type: 'dx',  parent: 'T',  generalComment: '치아가 잇몸뼈 속에 묻혀 제대로 나오지 못한 상태(매복치)입니다.' },
  { abbr: 'T/EL',        definition: 'Tooth elongation',  definition_kr: '치아 과출',                                  type: 'dx',  parent: 'T' },
  { abbr: 'T/FDR',       definition: 'Fused roots',  definition_kr: '융합치근',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/FUS',       definition: 'Fusion',  definition_kr: '융합치',                                            type: 'dx',  parent: 'T' },
  { abbr: 'T/FX',        definition: 'Fractured tooth',  definition_kr: '치아 골절',                                   type: 'dx',  parent: 'T',  generalComment: '치아가 부러진(골절된) 상태입니다.' },
  { abbr: 'T/FX/EI',     definition: 'Enamel infraction',  definition_kr: '법랑질 균열',                                 type: 'dx',  parent: 'T/FX',  generalComment: '치아 표면(법랑질)에 눈에 보이지 않는 미세한 균열이 있는 상태입니다.' },
  { abbr: 'T/FX/EF',     definition: 'Enamel fracture',  definition_kr: '법랑질 골절',                                   type: 'dx',  parent: 'T/FX',  generalComment: '치아 표면(법랑질)이 부러진 상태이나 신경(치수)은 노출되지 않은 상태입니다.' },
  { abbr: 'T/FX/UCF',    definition: 'Uncomplicated crown fracture',  definition_kr: '비복합 치관골절',                      type: 'dx',  parent: 'T/FX',  generalComment: '치아 머리 부분이 부러졌으나 신경(치수)이 노출되지 않은 상태입니다.' },
  { abbr: 'T/FX/CCF',    definition: 'Complicated crown fracture',  definition_kr: '복합 치관골절',                        type: 'dx',  parent: 'T/FX',  generalComment: '치아 머리 부분이 부러지면서 내부 신경(치수)까지 노출된 상태입니다. 통증이 심하며 즉각적인 치료가 필요합니다.' },
  { abbr: 'T/FX/UCRF',   definition: 'Uncomplicated crown-root fracture',  definition_kr: '비복합 치관치근골절',                 type: 'dx',  parent: 'T/FX',  generalComment: '치아 머리와 뿌리 모두 골절되었으나 신경(치수)은 노출되지 않은 상태입니다.' },
  { abbr: 'T/FX/CCRF',   definition: 'Complicated crown-root fracture',  definition_kr: '복합 치관치근골절',                   type: 'dx',  parent: 'T/FX',  generalComment: '치아 머리와 뿌리 모두 골절되고 신경(치수)까지 노출된 심한 골절 상태입니다.' },
  { abbr: 'T/FX/RF',     definition: 'Root fracture',  definition_kr: '치근 골절',                                     type: 'dx',  parent: 'T/FX',  generalComment: '치아 뿌리 부분이 부러진 상태입니다.' },
  { abbr: 'T/GEM',       definition: 'Gemination',  definition_kr: '쌍생치',                                        type: 'dx',  parent: 'T' },
  { abbr: 'T/I',         definition: 'Impacted tooth',  definition_kr: '매복치',                                    type: 'dx',  parent: 'T' },
  { abbr: 'T/LUX',       definition: 'Luxated tooth',  definition_kr: '아탈구 치아',                                     type: 'dx',  parent: 'T' },
  { abbr: 'T/MAC',       definition: 'Macrodontia',  definition_kr: '거대치',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/MIC',       definition: 'Microdontia',  definition_kr: '왜소치',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/NE',        definition: 'Near pulp exposure',  definition_kr: '근접 치수 노출',                                type: 'dx',  parent: 'T',  generalComment: '치아 내부의 신경(치수)이 외부에 거의 노출될 정도로 치아가 많이 닳거나 손상된 상태입니다.' },
  { abbr: 'T/NV',        definition: 'Non-vital tooth',  definition_kr: '실활치 (비활성 치아)',                                   type: 'dx',  parent: 'T',  generalComment: '치아 내부의 신경과 혈관이 죽어있는 상태(신경이 죽은 치아)입니다. 색이 변하거나 감염이 올 수 있습니다.' },
  { abbr: 'T/PE',        definition: 'Pulp exposure',  definition_kr: '치수 노출',                                     type: 'dx',  parent: 'T',  generalComment: '치아 내부의 신경(치수)이 외부로 노출된 상태입니다. 심한 통증과 감염 위험이 있습니다.' },
  { abbr: 'T/RI',        definition: 'Tooth reimplantation (for an avulsed tooth)',  definition_kr: '치아 재식술',        type: 'tx',  parent: 'T' },
  { abbr: 'T/RP',        definition: 'Tooth repositioning (for a luxated tooth)',  definition_kr: '치아 재위치술',          type: 'tx',  parent: 'T' },
  { abbr: 'T/SN',        definition: 'Supernumerary tooth',  definition_kr: '과잉치',                               type: 'dx',  parent: 'T' },
  { abbr: 'T/SR',        definition: 'Supernumerary root',  definition_kr: '과잉치근',                                type: 'dx',  parent: 'T' },
  { abbr: 'T/TRA',       definition: 'Transposition',  definition_kr: '위치변위치',                                     type: 'dx',  parent: 'T' },
  { abbr: 'T/U',         definition: 'Unerupted tooth',  definition_kr: '미발정 치아',                                   type: 'dx',  parent: 'T' },
  { abbr: 'T/V',         definition: 'Vital tooth',  definition_kr: '생활치 (활성 치아)',                                       type: 'dx',  parent: 'T' },
  { abbr: 'T/XP',        definition: 'Partial tooth resection',  definition_kr: '부분 치아 절단술',                           type: 'tx',  parent: 'T' },
  { abbr: 'TMA',         definition: 'Trauma',  definition_kr: '외상 (Trauma)',                                            type: 'dx' },
  { abbr: 'TMA/B',       definition: 'Ballistic trauma',  definition_kr: '탄도 외상',                                  type: 'dx',  parent: 'TMA' },
  { abbr: 'TMA/BRN',     definition: 'Burn trauma',  definition_kr: '화상',                                       type: 'dx',  parent: 'TMA' },
  { abbr: 'TMA/E',       definition: 'Electric trauma',  definition_kr: '전기 외상',                                   type: 'dx',  parent: 'TMA' },
  { abbr: 'TMA/R',       definition: 'Trauma repair',  definition_kr: '외상 복원술',                                     type: 'tx',  parent: 'TMA' },
  { abbr: 'TMJ',         definition: 'Temporomandibular joint',  definition_kr: '측두하악관절 (TMJ)',                           type: 'anatomy' },
  { abbr: 'TMJ/A',       definition: 'TMJ ankylosis (true or false)',  definition_kr: 'TMJ 강직증',                      type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/A/R',     definition: 'TMJ ankylosis repair',  definition_kr: 'TMJ 강직증 복원술',                              type: 'tx',  parent: 'TMJ/A' },
  { abbr: 'TMJ/D',       definition: 'TMJ dysplasia',  definition_kr: 'TMJ 이상형성증',                                     type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/FX',      definition: 'TMJ fracture',  definition_kr: 'TMJ 골절',                                      type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/FX/R',    definition: 'TMJ fracture repair',  definition_kr: 'TMJ 골절 복원술',                               type: 'tx',  parent: 'TMJ/FX' },
  { abbr: 'TMJ/LUX',     definition: 'TMJ luxation',  definition_kr: 'TMJ 탈구',                                      type: 'dx',  parent: 'TMJ' },
  { abbr: 'TMJ/LUX/R',   definition: 'TMJ luxation reduction',  definition_kr: 'TMJ 탈구 복원술',                            type: 'tx',  parent: 'TMJ/LUX' },
  { abbr: 'TON',         definition: 'Palatine tonsil',  definition_kr: '구개 편도',                                   type: 'anatomy' },
  { abbr: 'TON/IN',      definition: 'Tonsillitis',  definition_kr: '편도염',                                       type: 'dx',  parent: 'TON' },
  { abbr: 'TON/X',       definition: 'Tonsillectomy',  definition_kr: '편도 절제술',                                     type: 'tx',  parent: 'TON' },
  { abbr: 'TP',          definition: 'Treatment plan',  definition_kr: '치료 계획',                                    type: 'tx',  generalComment: '앞으로 진행될 치료 계획을 수립하였습니다.' },
  { abbr: 'TR',          definition: 'Tooth resorption',  definition_kr: '치아 흡수(TR)',                                  type: 'dx',  generalComment: '치아 구조가 체내에서 스스로 녹아 없어지는 현상입니다. 특히 고양이에게 흔하며, 심한 통증을 유발합니다.' },
  { abbr: 'TRP',         definition: 'Trephination',  definition_kr: '천공술',                                      type: 'tx' },
  { abbr: 'TS',          definition: 'Trisection',  definition_kr: '삼분할술',                                        type: 'tx' },
  { abbr: 'TT',          definition: 'Temporal teratoma',  definition_kr: '측두 기형종',                                 type: 'dx' },

  // ── U ──────────────────────────────────────────────────────
  { abbr: 'US',          definition: 'Ultrasonography',  definition_kr: '초음파 (Ultrasonography)',                                   type: 'dx' },

  // ── V ──────────────────────────────────────────────────────
  { abbr: 'VPT',         definition: 'Vital pulp therapy',  definition_kr: '생활치수 치료 (VPT)',                                type: 'tx',  generalComment: '치아의 신경(치수)이 살아있는 상태를 유지하면서 치아를 치료하는 생활치수치료를 시행하였습니다. 치아를 최대한 살리는 치료 방법입니다.' },

  // ── X ──────────────────────────────────────────────────────
  { abbr: 'X',           definition: 'Closed extraction of a tooth (without sectioning)',  definition_kr: '단순 발치', type: 'tx',  generalComment: '치아를 절개 없이 단순하게 뽑는 발치를 시행하였습니다.' },
  { abbr: 'XS',          definition: 'Closed extraction of a tooth (with sectioning)',  definition_kr: '분할 발치',    type: 'tx',  generalComment: '치아를 여러 조각으로 분할하여 발치하는 시술을 시행하였습니다.' },
  { abbr: 'XS/ODY',      definition: 'Removal of interproximal crown tissue to facilitate transoral extraction',  definition_kr: '치관분할 접근 발치', type: 'tx', parent: 'XS',  generalComment: '발치를 쉽게 하기 위해 치아 머리 부분 사이의 조직을 먼저 제거한 후 발치하였습니다.' },
  { abbr: 'XSS',         definition: 'Open extraction of a tooth',  definition_kr: '외과적 발치',                        type: 'tx',  generalComment: '잇몸을 절개하고 잇몸뼈를 일부 제거하여 치아를 뽑는 외과적 발치를 시행하였습니다. 뿌리가 깊거나 복잡한 경우에 필요합니다.' },
  { abbr: 'XSS/APX/RPL', definition: 'Extraction after apicoectomy and repulsion',  definition_kr: '치근단절제 후 비관혈적발치',        type: 'tx',  parent: 'XSS',  generalComment: '치아 뿌리 끝을 제거한 후 발치를 시행하였습니다.' },
  { abbr: 'XSS/BUC',     definition: 'Transbuccal extraction after buccotomy',  definition_kr: '협부접근 외과적 발치',            type: 'tx',  parent: 'XSS',  generalComment: '볼 쪽을 통해 접근하는 방식으로 외과적 발치를 시행하였습니다.' },
  { abbr: 'XSS/BUC/ALV', definition: 'Transbuccal extraction after buccotomy and alveolectomy',  definition_kr: '협부절개 및 치조골삭제 발치', type: 'tx', parent: 'XSS/BUC',  generalComment: '볼 점막을 절개하고 치아를 싸고 있던 잇몸뼈를 일부 제거한 후 발치하였습니다.' },
  { abbr: 'XSS/COM',     definition: 'Transbuccal extraction after commissurotomy',  definition_kr: '구각절개 접근 외과적 발치',       type: 'tx',  parent: 'XSS',  generalComment: '입꼬리 부분을 절개하여 접근하는 방식으로 발치를 시행하였습니다.' },
  { abbr: 'XSS/COM/ALV', definition: 'Transbuccal extraction after commissurotomy and alveolectomy',  definition_kr: '구각절개 및 치조골삭제 발치', type: 'tx', parent: 'XSS/COM',  generalComment: '입꼬리 부분 절개 및 잇몸뼈 일부 제거 후 발치를 시행하였습니다.' },
  { abbr: 'XSS/MIB',     definition: 'Extraction via minimally invasive buccotomy',  definition_kr: '최소침습 협부 발치',       type: 'tx',  parent: 'XSS',  generalComment: '최소한의 절개만으로 볼 쪽을 통해 치아를 뽑는 최소 침습 발치 방법을 사용하였습니다.' },
  { abbr: 'XSS/RPL',     definition: 'Extraction after repulsion',  definition_kr: '반발법 발치',                        type: 'tx',  parent: 'XSS',  generalComment: '특수한 방법으로 치아를 밀어내어 발치하였습니다.' },

  // ── Z ──────────────────────────────────────────────────────
  { abbr: 'ZYG',         definition: 'Zygoma (zygomatic arch)',  definition_kr: '관골 (광대뼈)',                           type: 'anatomy' },
  { abbr: 'ZYG/X',       definition: 'Zygomectomy',  definition_kr: '관골 절제술',                                       type: 'tx',  parent: 'ZYG' },
];

// ── 유틸리티 함수 ─────────────────────────────────────────────

/** 타입별 필터 */
export function getByType(type: AvdcAbbrevType): AvdcAbbrev[] {
  return AVDC_ABBREVIATIONS.filter((a) => a.type === type);
}

/** 약어로 단일 검색 */
export function getByAbbr(abbr: string): AvdcAbbrev | undefined {
  return AVDC_ABBREVIATIONS.find(
    (a) => a.abbr.toLowerCase() === abbr.toLowerCase()
  );
}

/** 약어 또는 정의에서 텍스트 검색 */
export function searchAbbreviations(query: string): AvdcAbbrev[] {
  const q = query.toLowerCase();
  return AVDC_ABBREVIATIONS.filter(
    (a) =>
      a.abbr.toLowerCase().includes(q) ||
      a.definition.toLowerCase().includes(q) ||
      (a.definition_kr && a.definition_kr.includes(q))
  );
}

/** 상위 약어의 하위 항목 조회 */
export function getChildren(parentAbbr: string): AvdcAbbrev[] {
  return AVDC_ABBREVIATIONS.filter((a) => a.parent === parentAbbr);
}

/** 타입별 한글 레이블 */
export const TYPE_LABELS: Record<AvdcAbbrevType, string> = {
  anatomy: '해부 (Anatomy)',
  dx:      '진단 (Diagnosis)',
  tx:      '치료 (Treatment)',
};

/** 타입별 색상 (Tailwind 클래스) */
export const TYPE_COLORS: Record<AvdcAbbrevType, { bg: string; text: string; border: string }> = {
  anatomy: { bg: 'bg-gray-100',   text: 'text-gray-700',  border: 'border-gray-300'  },
  dx:      { bg: 'bg-blue-50',    text: 'text-blue-700',  border: 'border-blue-300'  },
  tx:      { bg: 'bg-red-50',     text: 'text-red-700',   border: 'border-red-300'   },
};
