import type { DentalTest } from './dentalTest_types';

// ============================================================
// DENTAL_TOOTH_TESTS
// 치아별(individual tooth) 검사 항목
// dental_chart_teeth 테이블에 저장
// ============================================================

export const DENTAL_TOOTH_TESTS: Record<string, DentalTest> = {

  // ── 치아 존재 여부 ─────────────────────────────────────────
  tooth_status: {
    testID:     'tooth_status',
    testName:   'Tooth Status',
    testNameKo: '치아 상태',
    testType:   'select',
    testInfo:   '해당 치아의 존재 여부 및 기본 상태. 선천적 결손, 미맹출, 유치 잔존, 기발치 등.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'present',    detail: 'Tooth present',          label: '존재' },
      { value: 'ANO',        detail: 'Missing tooth (ANO)',     label: '결손 (선천성-ANO)' },
      { value: 'extracted',  detail: 'Previously extracted',    label: '기발치' },
      { value: 'T/U',        detail: 'Unerupted tooth (T/U)',  label: '미맹출 (T/U)' },
      { value: 'T/I',        detail: 'Impacted tooth (T/I)',   label: '매복 (T/I)' },
      { value: 'DT/P',       detail: 'Persistent deciduous tooth (DT/P)', label: '유치 잔존 (DT/P)' },
    ],
    optComment: {
      present:    '치아 존재. 추가 평가 진행.',
      ANO:        '선천성 결손(ANO). 방사선으로 매복 여부 확인 필요.',
      extracted:  '기발치 확인. 치조 치유 상태 평가.',
      'T/U':      '미맹출(T/U). 방사선으로 위치 및 연관 낭종(DTC) 확인 필요.',
      'T/I':      '매복치(T/I). 방사선 평가 필수. 주변 구조물 영향 평가.',
      'DT/P':     '유치 잔존(DT/P). 영구치 맹출 방해 및 부정교합 유발. 발치 강력 권장.',
    },
    generalComment: {
      present:    '치아가 존재합니다.',
      ANO:        '이 위치에 치아가 없습니다. X-ray로 확인이 필요합니다.',
      extracted:  '이전에 발치된 치아입니다.',
      'T/U':      '이 치아는 아직 잇몸 밖으로 나오지 않았습니다. X-ray 확인이 필요합니다.',
      'T/I':      '이 치아는 잇몸 안에 묻혀 있습니다. X-ray 평가가 필요합니다.',
      'DT/P':     '빠져야 할 젖니가 아직 있습니다. 영구치 성장을 방해할 수 있어 발치가 필요합니다.',
    },
    urgency: {
      present:    'none',
      ANO:        'monitor',
      extracted:  'none',
      'T/U':      'recommended',
      'T/I':      'recommended',
      'DT/P':     'urgent',
    },
    suggestedTx: {
      present:    [],
      ANO:        ['RAD'],
      extracted:  [],
      'T/U':      ['RAD', 'DTC/R'],
      'T/I':      ['RAD', 'XSS'],
      'DT/P':     ['X', 'RAD'],
    },
    noteTags: ['tooth status', 'missing', 'unerupted', 'impacted', 'persistent deciduous'],
  },

  // ── 치주 질환 병기 (치아별) ────────────────────────────────
  periodontal_stage: {
    testID:     'periodontal_stage',
    testName:   'Periodontal Disease Stage',
    testNameKo: '치주 질환 병기',
    testType:   'select',
    testInfo:   'AVDC PD 분류. 치주낭 깊이, 치은 퇴축, 부착 소실, 방사선 골 소실을 종합하여 판정.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'PD0', detail: 'Clinically normal (PD0)',                             label: 'PD0 — 정상' },
      { value: 'PD1', detail: 'Gingivitis only, no attachment loss (PD1)',           label: 'PD1 — 치은염' },
      { value: 'PD2', detail: 'Early periodontitis, <25% attachment loss (PD2)',    label: 'PD2 — 초기 치주염' },
      { value: 'PD3', detail: 'Moderate periodontitis, 25–50% attachment loss (PD3)', label: 'PD3 — 중등도 치주염' },
      { value: 'PD4', detail: 'Advanced periodontitis, >50% attachment loss (PD4)', label: 'PD4 — 진행성 치주염' },
    ],
    optComment: {
      PD0: '정상(PD0). 이상 소견 없음.',
      PD1: '치은염(PD1). 부착 소실 없음. 스케일링으로 회복 가능.',
      PD2: '초기 치주염(PD2). 부착 소실 <25%. 치근 활택(RP) 및 재평가.',
      PD3: '중등도 치주염(PD3). 부착 소실 25~50%. 치주 수술 또는 발치 고려. 방사선 필수.',
      PD4: '진행성 치주염(PD4). 부착 소실 >50%. 대부분 발치 적응증. 전신 합병증 위험.',
    },
    generalComment: {
      PD0: '이 치아의 잇몸 상태는 건강합니다.',
      PD1: '잇몸에 염증이 있지만 치아 지지 구조는 아직 정상입니다.',
      PD2: '잇몸 뼈가 약간 손상되기 시작했습니다. 치료가 필요합니다.',
      PD3: '잇몸 뼈 손상이 상당합니다. 발치가 필요할 수 있습니다.',
      PD4: '이 치아의 지지 구조가 심하게 손상되어 발치가 필요한 상태입니다.',
    },
    urgency: {
      PD0: 'none',
      PD1: 'elective',
      PD2: 'recommended',
      PD3: 'urgent',
      PD4: 'urgent',
    },
    suggestedTx: {
      PD0: [],
      PD1: ['PRO'],
      PD2: ['PRO', 'GC', 'RP/C'],
      PD3: ['PRO', 'RP/O', 'GF/B', 'GTR'],
      PD4: ['XSS', 'ALV'],
    },
    noteTags: ['periodontal disease', 'PD', 'attachment loss', 'bone loss'],
  },

  // ── 치은염 (치아별) ────────────────────────────────────────
  gingivitis: {
    testID:     'gingivitis',
    testName:   'Gingivitis',
    testNameKo: '치은염',
    testType:   'select',
    testInfo:   '해당 치아 주변 치은의 염증 정도. 발적, 부종, 출혈 정도로 평가.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'GI0', detail: 'No gingivitis',       label: 'GI 0 (없음)' },
      { value: 'GI1', detail: 'Mild gingivitis',     label: 'GI 1 (경도)' },
      { value: 'GI2', detail: 'Moderate gingivitis', label: 'GI 2 (중등도)' },
      { value: 'GI3', detail: 'Severe gingivitis',   label: 'GI 3 (중증)' },
    ],
    optComment: {
      GI0: '치은 정상.',
      GI1: '경도 치은염(GI1). 경미한 발적 및 부종. 스케일링 권장.',
      GI2: '중등도 치은염(GI2). 발적, 부종, 탐침 출혈. 스케일링 및 치근 활택.',
      GI3: '중증 치은염(GI3). 자발 출혈, 심한 부종. 즉각 치료 및 치주 평가.',
    },
    generalComment: {
      GI0: '이 치아 주변 잇몸이 건강합니다.',
      GI1: '잇몸이 약간 붉고 부어 있습니다.',
      GI2: '잇몸 염증이 상당합니다. 치료가 필요합니다.',
      GI3: '잇몸 염증이 심합니다. 즉각적인 치료가 필요합니다.',
    },
    urgency: {
      GI0: 'none',
      GI1: 'elective',
      GI2: 'recommended',
      GI3: 'urgent',
    },
    suggestedTx: {
      GI0: [],
      GI1: ['PRO'],
      GI2: ['PRO', 'GC'],
      GI3: ['PRO', 'GC', 'RP'],
    },
    noteTags: ['gingivitis', 'gingival inflammation'],
  },

  // ── 치석 (치아별) ──────────────────────────────────────────
  calculus: {
    testID:     'calculus',
    testName:   'Calculus',
    testNameKo: '치석',
    testType:   'select',
    testInfo:   '해당 치아의 치석 정도. Grade 0~3. 협면(buccal), 설면(lingual) 구분 기록 권장.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'CI0', detail: 'No calculus (Grade 0)',       label: 'CI 0 (없음)' },
      { value: 'CI1', detail: 'Mild calculus (Grade 1)',     label: 'CI 1 (경도)' },
      { value: 'CI2', detail: 'Moderate calculus (Grade 2)', label: 'CI 2 (중등도)' },
      { value: 'CI3', detail: 'Severe calculus (Grade 3)',   label: 'CI 3 (중증)' },
    ],
    optComment: {
      CI0: '치석 없음.',
      CI1: '치석 CI 1. 치관 1/3 이하. 스케일링으로 제거.',
      CI2: '치석 CI 2. 치관 1/3~2/3 또는 치은연하 치석. 스케일링 및 치근 활택.',
      CI3: '치석 CI 3. 치관 2/3 이상 또는 치은연하 다량. 즉각 처치.',
    },
    generalComment: {
      CI0: '이 치아에 치석이 없습니다.',
      CI1: '이 치아에 약간의 치석이 있습니다.',
      CI2: '이 치아에 치석이 상당히 쌓여 있습니다.',
      CI3: '이 치아에 치석이 많이 쌓여 있습니다.',
    },
    urgency: {
      CI0: 'none',
      CI1: 'elective',
      CI2: 'recommended',
      CI3: 'urgent',
    },
    suggestedTx: {
      CI0: [],
      CI1: ['PRO'],
      CI2: ['PRO', 'RP/C'],
      CI3: ['PRO', 'RP/O'],
    },
    noteTags: ['calculus', 'scaling', 'tartar'],
  },

  // ── 치태 (치아별) ──────────────────────────────────────────
  plaque: {
    testID:     'plaque',
    testName:   'Plaque',
    testNameKo: '치태',
    testType:   'select',
    testInfo:   '해당 치아의 치태 정도. Modified Silness & Löe Index 0~3. 치은 1mm 이내 치태 측정.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'PI0', detail: 'No plaque (PI 0)',       label: 'PI 0 (없음)' },
      { value: 'PI1', detail: 'Mild plaque (PI 1)',     label: 'PI 1 (경도)' },
      { value: 'PI2', detail: 'Moderate plaque (PI 2)', label: 'PI 2 (중등도)' },
      { value: 'PI3', detail: 'Severe plaque (PI 3)',   label: 'PI 3 (중증)' },
    ],
    optComment: {
      PI0: '치태 없음.',
      PI1: '치태 PI 1. 치은연 부위 얇은 막. 스케일링 및 가정 관리 강화.',
      PI2: '치태 PI 2. 육안으로 확인 가능한 치태. 스케일링 및 양치질 교육.',
      PI3: '치태 PI 3. 치은, 치간 공극에 다량. 즉각 처치 및 집중 관리.',
    },
    generalComment: {
      PI0: '이 치아에 치태가 없습니다.',
      PI1: '이 치아에 약간의 치태가 있습니다. 양치질로 제거 가능합니다.',
      PI2: '이 치아에 치태가 눈해 띄게 있습니다. 스케일링과 꼼꼼한 양치질이 필요합니다.',
      PI3: '이 치아에 치태가 많습니다. 즉각적인 스케일링과 집중적인 구강 관리가 필요합니다.',
    },
    urgency: {
      PI0: 'none',
      PI1: 'elective',
      PI2: 'recommended',
      PI3: 'urgent',
    },
    suggestedTx: {
      PI0: [],
      PI1: ['PRO'],
      PI2: ['PRO'],
      PI3: ['PRO', 'GC'],
    },
    noteTags: ['plaque', 'plaque index', 'biofilm'],
  },

  // ── 치주낭 깊이 ─────────────────────────────────────────────
  probing_depth: {
    testID:     'probing_depth',
    testName:   'Probing Depth',
    testNameKo: '치주낭 깊이',
    testType:   'select',
    testInfo:   '치주낭 깊이(mm). 6포인트 측정 (MB, B, DB, ML, L, DL). 개 정상 <3mm, 고양이 정상 <1mm.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: '0',  detail: '0mm',  label: '0mm' },
      { value: '1',  detail: '1mm',  label: '1mm' },
      { value: '2',  detail: '2mm',  label: '2mm' },
      { value: '3',  detail: '3mm',  label: '3mm' },
      { value: '4',  detail: '4mm',  label: '4mm' },
      { value: '5',  detail: '5mm',  label: '5mm' },
      { value: '6',  detail: '6mm',  label: '6mm' },
      { value: '7',  detail: '7mm',  label: '7mm' },
      { value: '8',  detail: '8mm',  label: '8mm' },
      { value: '9',  detail: '9mm',  label: '9mm' },
      { value: '10', detail: '10mm+', label: '10mm+' },
    ],
    optComment: {
      '0':  '치주낭 깊이 0mm. 정상.',
      '1':  '치주낭 깊이 1mm. 개에서는 정상, 고양이에서는 경계/주의.',
      '2':  '치주낭 깊이 2mm. 개에서는 정상, 고양이에서는 깊은 치주낭 소견.',
      '3':  '치주낭 깊이 3mm. 개에서는 경계 소견, 집중 관리 필요.',
      '4':  '치주낭 깊이 4mm. 개의 중등도 치주염 지표.',
      '5':  '치주낭 깊이 5mm. 깊은 치주낭 소견. 치주 수술 또는 발치 고려.',
      '10': '치주낭 깊이 10mm 이상. 중증의 부착 소실.',
    },
    urgency: {
      '0':  'none',
      '1':  'none',
      '2':  'monitor',
      '3':  'recommended',
      '4':  'urgent',
      '5':  'urgent',
      '10': 'urgent',
    },
    noteTags: ['probing depth', 'pocket depth', 'periodontal pocket'],
  },

  // ── 치은 퇴축 ───────────────────────────────────────────────
  gingival_recession: {
    testID:     'gingival_recession',
    testName:   'Gingival Recession (GR)',
    testNameKo: '치은 퇴축',
    testType:   'select',
    testInfo:   '치은이 치근 방향으로 퇴축한 정도. 치근 노출 및 부착 소실(CAL) 증가.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none', detail: 'No recession (GR)',           label: '없음' },
      { value: 'GR1',  detail: 'Mild gingival recession',     label: 'GR 1 (<1mm)' },
      { value: 'GR2',  detail: 'Moderate gingival recession', label: 'GR 2 (1~3mm)' },
      { value: 'GR3',  detail: 'Severe gingival recession (GR)', label: 'GR 3 (>3mm)' },
    ],
    optComment: {
      none: '치은 퇴축 없음.',
      GR1:  '경도 치은 퇴축(<1mm). 치근 노출 소량. 치주 관리 강화.',
      GR2:  '중등도 치은 퇴축(1~3mm). 치근 과민 및 우식 위험. 치료 고려.',
      GR3:  '중증 치은 퇴축(>3mm). 치근 대량 노출. 이식술 또는 발치 고려.',
    },
    generalComment: {
      none: '잇몸이 정상 위치에 있습니다.',
      GR1:  '잇몸이 약간 내려앉아 치아 뿌리가 조금 보입니다.',
      GR2:  '잇몸이 상당히 내려앉아 치아 뿌리가 많이 노출되어 있습니다.',
      GR3:  '잇몸이 심하게 내려앉아 치아 뿌리가 많이 드러나 있습니다. 치료가 필요합니다.',
    },
    urgency: {
      none: 'none',
      GR1:  'monitor',
      GR2:  'recommended',
      GR3:  'urgent',
    },
    suggestedTx: {
      none:     [],
      mild:     ['PRO'],
      moderate: ['PRO', 'GF/CT'],
      severe:   ['PRO', 'GF/CT', 'XSS'],
    },
    noteTags: ['gingival recession', 'GR', 'root exposure'],
  },

  // ── 치아 동요도 ─────────────────────────────────────────────
  mobility: {
    testID:     'mobility',
    testName:   'Tooth Mobility',
    testNameKo: '치아 동요도',
    testType:   'select',
    testInfo:   'AVDC 기준. Grade 0~3. 수평 및 수직 동요도 평가.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'M0', detail: 'No mobility (M0)',                            label: 'M0 (없음)' },
      { value: 'M1', detail: 'Grade 1 mobility (M1) (<1mm horizontal)',     label: 'M1 (경도)' },
      { value: 'M2', detail: 'Grade 2 mobility (M2) (1–2mm horizontal)',    label: 'M2 (중등도)' },
      { value: 'M3', detail: 'Grade 3 mobility (M3) (>2mm horiz/vert)',     label: 'M3 (중증)' },
    ],
    optComment: {
      M0: '동요도 없음(M0). 정상.',
      M1: '동요도 M1. 경도. 치주 치료 후 재평가.',
      M2: '동요도 M2. 중등도. 심각한 치주 지지 소실. 발치 고려.',
      M3: '동요도 M3. 중증. 수직 동요 포함. 발치 적응증.',
    },
    generalComment: {
      M0: '이 치아는 흔들리지 않습니다.',
      M1: '이 치아가 약간 흔들립니다.',
      M2: '이 치아가 상당히 흔들립니다. 치료가 필요합니다.',
      M3: '이 치아가 심하게 흔들립니다. 발치가 필요할 수 있습니다.',
    },
    urgency: {
      M0: 'none',
      M1: 'recommended',
      M2: 'urgent',
      M3: 'urgent',
    },
    suggestedTx: {
      M0: [],
      M1: ['PRO', 'RP'],
      M2: ['XSS', 'RAD'],
      M3: ['XSS'],
    },
    noteTags: ['mobility', 'tooth mobility', 'loose tooth'],
  },

  // ── 치근 분기부 병변 ───────────────────────────────────────
  furcation: {
    testID:     'furcation',
    testName:   'Furcation Involvement',
    testNameKo: '치근 분기부 병변',
    testType:   'select',
    testInfo:   '다근치(상악 P4, 하악 M1 등)의 치근 분기부 노출 정도. Grade 0~3.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'F0', detail: 'No furcation involvement (F0)',              label: 'F0 (없음)' },
      { value: 'F1', detail: 'Furcation Grade 1 (F1) (probe <1/3 width)',  label: 'F1 (경도)' },
      { value: 'F2', detail: 'Furcation Grade 2 (F2) (probe 1/3–2/3)',     label: 'F2 (중등도)' },
      { value: 'F3', detail: 'Furcation Grade 3 (F3) (through-and-through)', label: 'F3 (중증/관통)' },
    ],
    optComment: {
      F0: '치근 분기부 정상(F0).',
      F1: '분기부 병변 F1. 탐침 1/3 미만 진입. 스케일링 및 치근 활택.',
      F2: '분기부 병변 F2. 탐침 1/3~2/3 진입. 발치 또는 치주 수술(GTR) 고려.',
      F3: '분기부 병변 F3. 탐침 관통. 발치 적응증.',
    },
    generalComment: {
      F0: '이 치아의 뿌리 사이 공간이 정상입니다.',
      F1: '치아 뿌리 사이에 약간의 병변이 있습니다.',
      F2: '치아 뿌리 사이 병변이 상당합니다. 치료가 필요합니다.',
      F3: '치아 뿌리 사이가 완전히 노출되었습니다. 발치가 필요할 수 있습니다.',
    },
    urgency: {
      F0: 'none',
      F1: 'recommended',
      F2: 'urgent',
      F3: 'urgent',
    },
    suggestedTx: {
      F0: [],
      F1: ['PRO', 'RP/C'],
      F2: ['RP/O', 'GTR', 'GF/B'],
      F3: ['XSS'],
    },
    noteTags: ['furcation', 'furcation involvement', 'multi-rooted'],
  },

  // ── 치아 파절 ──────────────────────────────────────────────
  tooth_fracture: {
    testID:     'tooth_fracture',
    testName:   'Tooth Fracture',
    testNameKo: '치아 파절',
    testType:   'select',
    testInfo:   'AVDC T/FX 분류. 치수 노출 여부가 치료 계획 결정의 핵심.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none',      detail: 'No fracture',                                     label: '없음' },
      { value: 'T/FX/EI',  detail: 'Enamel infraction (T/FX/EI)',                    label: '법랑질 균열 (T/FX/EI)' },
      { value: 'T/FX/EF',  detail: 'Enamel fracture (T/FX/EF)',                      label: '법랑질 파절 (T/FX/EF)' },
      { value: 'T/FX/UCF', detail: 'Uncomplicated crown fracture (T/FX/UCF)',        label: '비복잡 치관 파절 (T/FX/UCF)' },
      { value: 'T/FX/CCF', detail: 'Complicated crown fracture (T/FX/CCF)',          label: '복잡 치관 파절 (T/FX/CCF)' },
      { value: 'T/FX/UCRF', detail: 'Uncomplicated crown-root fracture (T/FX/UCRF)', label: '비복잡 치관-치근 파절 (T/FX/UCRF)' },
      { value: 'T/FX/CCRF', detail: 'Complicated crown-root fracture (T/FX/CCRF)',   label: '복잡 치관-치근 파절 (T/FX/CCRF)' },
      { value: 'T/FX/RF',  detail: 'Root fracture (T/FX/RF)',                        label: '치근 파절 (T/FX/RF)' },
    ],
    optComment: {
      none:       '파절 없음.',
      'T/FX/EI':  '법랑질 균열(T/FX/EI). 치수 비노출. 예후 양호. 수복 또는 경과 관찰.',
      'T/FX/EF':  '법랑질 파절(T/FX/EF). 치수 비노출. 예후 양호. 수복(R/C) 또는 Odontoplasty.',
      'T/FX/UCF': '비복잡 치관 파절(T/FX/UCF). 상아질 노출, 치수 비노출. 수복(R/C) 권장. 방사선 평가.',
      'T/FX/CCF': '복잡 치관 파절(T/FX/CCF). 치수 노출. VPT 또는 RCT 즉시 필요. 방사선 필수.',
      'T/FX/UCRF':'비복잡 치관-치근 파절(T/FX/UCRF). 치수 비노출. 수복 가능성 평가. 방사선 필수.',
      'T/FX/CCRF':'복잡 치관-치근 파절(T/FX/CCRF). 치수 노출, 치근 침범. RCT 또는 발치. 방사선 필수.',
      'T/FX/RF':  '치근 파절(T/FX/RF). 방사선 평가 필수. 대부분 발치 적응증.',
    },
    generalComment: {
      none:       '이 치아에 파절이 없습니다.',
      'T/FX/EI':  '치아 표면에 가는 균열이 있습니다. 대부분 통증은 없지만 정기 확인이 필요합니다.',
      'T/FX/EF':  '치아 겉면(법랑질)이 깨졌습니다. 신경은 노출되지 않았습니다. 수복 치료를 권장합니다.',
      'T/FX/UCF': '치아 안쪽까지 깨졌지만 신경은 노출되지 않았습니다. 시린 느낌이 있을 수 있으며 수복이 필요합니다.',
      'T/FX/CCF': '치아가 깨지면서 신경(치수)이 노출되었습니다. 통증이 있을 수 있으며 즉각적인 치료가 필요합니다.',
      'T/FX/UCRF':'치아 뿌리까지 파절이 진행되었으나 신경은 노출되지 않았습니다. 정밀 평가가 필요합니다.',
      'T/FX/CCRF':'치아가 뿌리까지 깨지면서 신경도 노출되었습니다. 발치가 필요할 수 있습니다.',
      'T/FX/RF':  '치아 뿌리가 파절되었습니다. 발치가 필요한 경우가 많습니다.',
    },
    urgency: {
      none:       'none',
      'T/FX/EI':  'monitor',
      'T/FX/EF':  'elective',
      'T/FX/UCF': 'recommended',
      'T/FX/CCF': 'urgent',
      'T/FX/UCRF':'recommended',
      'T/FX/CCRF':'urgent',
      'T/FX/RF':  'urgent',
    },
    suggestedTx: {
      none:       [],
      'T/FX/EI':  ['ODY'],
      'T/FX/EF':  ['R/C', 'ODY'],
      'T/FX/UCF': ['R/C', 'RAD'],
      'T/FX/CCF': ['VPT', 'RCT', 'RAD'],
      'T/FX/UCRF':['R/C', 'RCT', 'RAD'],
      'T/FX/CCRF':['RCT', 'XSS', 'RAD'],
      'T/FX/RF':  ['XSS', 'RAD'],
    },
    noteTags: ['fracture', 'tooth fracture', 'T/FX', 'pulp exposure'],
  },

  // ── 치수 노출 ──────────────────────────────────────────────
  pulp_exposure: {
    testID:     'pulp_exposure',
    testName:   'Pulp Exposure',
    testNameKo: '치수 노출',
    testType:   'select',
    testInfo:   '치수(신경) 노출 여부 및 형태. 치아 파절 또는 우식에 의한 노출.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none',   detail: 'No pulp exposure',                        label: '없음' },
      { value: 'T/NE',   detail: 'Near pulp exposure (T/NE)',               label: '치수 근접 노출 위험 (T/NE)' },
      { value: 'T/PE',   detail: 'Pulp exposure — vital tooth (T/PE T/V)', label: '치수 노출 — 생활 치수 (T/V)' },
      { value: 'T/PE/NV', detail: 'Pulp exposure — non-vital tooth (T/PE T/NV)', label: '치수 노출 — 비생활 치수 (T/NV)' },
    ],
    optComment: {
      none:     '치수 노출 없음.',
      'T/NE':   '치수 근접 노출 위험(T/NE). 상아질이 얇게 남아 있음. 간접 치수 복조(PCI) 또는 수복 고려.',
      'T/PE':   '생활 치수 노출(T/PE + T/V). 즉각 VPT 또는 RCT 필요. 감염 전 조기 처치가 예후에 결정적.',
      'T/PE/NV':'비생활 치수 노출(T/PE + T/NV). 치수 괴사 진행. 방사선으로 periapical pathology 확인. RCT 또는 발치.',
    },
    generalComment: {
      none:     '치아 신경이 노출되어 있지 않습니다.',
      'T/NE':   '치아 신경 가까이까지 파절 또는 마모가 진행되었습니다. 보호 처치가 필요합니다.',
      'T/PE':   '치아 신경이 노출되어 있습니다. 통증이 있을 수 있으며 즉각적인 치료가 필요합니다.',
      'T/PE/NV':'치아 신경이 이미 죽은 상태로 노출되어 있습니다. X-ray 확인 및 발치 또는 신경 치료가 필요합니다.',
    },
    urgency: {
      none:     'none',
      'T/NE':   'recommended',
      'T/PE':   'urgent',
      'T/PE/NV':'urgent',
    },
    suggestedTx: {
      none:     [],
      'T/NE':   ['PCI', 'R/C'],
      'T/PE':   ['VPT', 'RCT'],
      'T/PE/NV':['RCT', 'XSS', 'RAD'],
    },
    noteTags: ['pulp exposure', 'pulp', 'vital pulp', 'non-vital'],
  },

  // ── 우식 ───────────────────────────────────────────────────
  caries: {
    testID:     'caries',
    testName:   'Dental Caries',
    testNameKo: '치아 우식',
    testType:   'select',
    testInfo:   '치아 우식(CA). 개에서는 드물며 주로 교합면에 발생. 고양이에서는 FORL과 감별 필요.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none', detail: 'No caries',           label: '없음' },
      { value: 'CA1',  detail: 'Mild caries (CA)',     label: 'CA 1 (경도)' },
      { value: 'CA2',  detail: 'Moderate caries (CA)', label: 'CA 2 (중등도)' },
      { value: 'CA3',  detail: 'Severe caries (CA)',   label: 'CA 3 (중증)' },
    ],
    optComment: {
      none: '우식 없음.',
      CA1:  '경도 우식(CA). 법랑질 또는 상아질 표층. 수복(R/C, R/I) 가능. 방사선 평가.',
      CA2:  '중등도 우식(CA). 상아질 심층. 치수 근접 가능성. 수복 또는 VPT. 방사선 필수.',
      CA3:  '중증 우식(CA). 치수 침범 가능성 높음. RCT 또는 발치. 방사선 필수.',
    },
    generalComment: {
      none: '이 치아에 충치가 없습니다.',
      CA1:  '이 치아에 초기 충치가 있습니다. 치료로 치아를 보존할 수 있습니다.',
      CA2:  '충치가 상당히 진행되었습니다. 빠른 치료가 필요합니다.',
      CA3:  '충치가 심하게 진행되었습니다. 신경 치료 또는 발치가 필요할 수 있습니다.',
    },
    urgency: {
      none: 'none',
      CA1:  'recommended',
      CA2:  'urgent',
      CA3:  'urgent',
    },
    suggestedTx: {
      none: [],
      CA1:  ['R/C', 'R/I', 'RAD'],
      CA2:  ['PCI', 'R/C', 'VPT', 'RAD'],
      CA3:  ['RCT', 'XSS', 'RAD'],
    },
    noteTags: ['caries', 'CA', 'cavitation', 'dental decay'],
  },

  // ── 치아 흡수 (FORL / TR) ──────────────────────────────────
  // ── 치아 흡수 병기 (TR Stage) ─────────────────────────────
  resorption_stage: {
    testID:     'resorption_stage',
    testName:   'Tooth Resorption Stage',
    testNameKo: '치아 흡수 병기 (Stage)',
    testType:   'select',
    testInfo:   'AVDC TR 분류 — 조직 소실 깊이에 따른 병기(1~5).',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none', detail: 'No tooth resorption',                             label: '없음' },
      { value: 'TR1',  detail: 'Stage 1 — mild loss (cementum/enamel)',            label: 'Stage 1 — 경도' },
      { value: 'TR2',  detail: 'Stage 2 — moderate loss (into dentin)',            label: 'Stage 2 — 중등도' },
      { value: 'TR3',  detail: 'Stage 3 — deep loss (into pulp cavity)',           label: 'Stage 3 — 심부(치수노출)' },
      { value: 'TR4',  detail: 'Stage 4 — extensive loss (integrity lost)',        label: 'Stage 4 — 광범위' },
      { value: 'TR5',  detail: 'Stage 5 — remnants only (crown absent)',           label: 'Stage 5 — 치관소실/잔존' },
    ],
    optComment: {
      none: '치아 흡수 소견 없음.',
      TR1:  'Stage 1 치아 흡수. 치공조골 및 법랑질의 경미한 소실. 방사선 감시 권장.',
      TR2:  'Stage 2 치아 흡수. 상아질 침범, 치수 미노출. 통증 유발 가능. 치료 계획 수립 필요.',
      TR3:  'Stage 3 치아 흡수. 치수강 침범. 심한 통증 및 감염 위험. 대부분 발치 적응증.',
      TR4:  'Stage 4 치아 흡수. 치아의 구조적 무결성 상실. 즉각적인 발치 필요.',
      TR5:  'Stage 5 치아 흡수. 치관이 소실되고 치근만 잔존하거나 뼈로 대체됨. 임상 증상 없을 시 관찰 가능.',
    },
    generalComment: {
      none: '치아 흡수 소견이 발견되지 않았습니다.',
      TR1:  '치아 표면이 미세하게 녹기 시작했습니다. 정기적인 체크가 필요합니다.',
      TR2:  '치아 뿌리가 상아질까지 녹아들고 있습니다. 통증이 생길 수 있어 치료가 필요합니다.',
      TR3:  '치료 신경(치수)까지 흡수가 진행되었습니다. 매우 아플 수 있으며 발치가 필요합니다.',
      TR4:  '치아가 심하게 녹아 형체가 거의 남지 않았습니다. 즉시 발치해야 합니다.',
      TR5:  '이빨 윗부분(치관)이 이미 다 녹아 없어지고 뿌리만 남은 상태입니다.',
    },
    urgency: {
      none: 'none',
      TR1:  'monitor',
      TR2:  'recommended',
      TR3:  'urgent',
      TR4:  'urgent',
      TR5:  'monitor',
    },
    suggestedTx: {
      none: [],
      TR1:  ['RAD'],
      TR2:  ['XSS', 'RAD'],
      TR3:  ['XSS', 'RAD'],
      TR4:  ['XSS', 'RAD'],
      TR5:  ['RAD', 'monitor'],
    },
    noteTags: ['resorption', 'TR', 'stage', 'tooth resorption'],
  },

  // ── 치아 흡수 유형 (TR Type) ──────────────────────────────
  resorption_type: {
    testID:     'resorption_type',
    testName:   'Tooth Resorption Type',
    testNameKo: '치아 흡수 유형 (Type)',
    testType:   'select',
    testInfo:   'AVDC TR 분류 — 치주 소견 및 방사선 양상에 따른 구분(Type 1~3).',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none', detail: 'No tooth resorption',                             label: '없음' },
      { value: 'T1',   detail: 'Type 1 — PDL visible (inflammatory)',              label: 'Type 1 — 치주성' },
      { value: 'T2',   detail: 'Type 2 — PDL lost (replacement)',                  label: 'Type 2 — 대체성 (FORL)' },
      { value: 'T3',   detail: 'Type 3 — both features (T1 + T2)',                 label: 'Type 3 — 혼합성' },
    ],
    optComment: {
      none: '해당 없음.',
      T1:   'Type 1 흡수(염증성/치주성). 치주인대 공간 유지됨. 치주 질환과 연관성 높음. 완전 발치 원칙.',
      T2:   'Type 2 흡수(대체성/유착성). 치주인대 소실 및 골 대체. Crown amputation 고려 가능(흡수 상태에 따라).',
      T3:   'Type 3 흡수(혼합성). Type 1과 Type 2 양상이 혼재함. 부위별 맞춤형 발치 전략 필요.',
    },
    generalComment: {
      none: '해당 없음.',
      T1:   '염증에 의한 치아 흡수 형태입니다. 뿌리 전체를 제거하는 발치가 필요합니다.',
      T2:   '치아 뿌리가 뼈로 변해가는 형태입니다. 상태에 따라 치아 윗부분만 절단하는 특수 발치가 가능할 수 있습니다.',
      T3:   '두 가지 형태가 섞여 있어 정밀한 엑스레이 평가와 수술이 필요합니다.',
    },
    urgency: {
      none: 'none',
      T1:  'recommended',
      T2:  'recommended',
      T3:  'urgent',
    },
    suggestedTx: {
      none: [],
      T1:   ['XSS', 'RAD'],
      T2:   ['CR/A', 'XSS', 'RAD'],
      T3:   ['XSS', 'CR/A', 'RAD'],
    },
    noteTags: ['resorption type', 'T1', 'T2', 'T3', 'ankylosis'],
  },

  // ── 치아 마모/교모 ─────────────────────────────────────────
  wear: {
    testID:     'wear',
    testName:   'Tooth Wear (Attrition / Abrasion)',
    testNameKo: '치아 마모',
    testType:   'select',
    testInfo:   'AT(교모, attrition) = 치아끼리 마찰. AB(마모, abrasion) = 외부 물질에 의한 마모. 치수 노출 여부 평가 필수.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none', detail: 'No tooth wear',           label: '없음' },
      { value: 'AT1',  detail: 'Mild attrition (AT)',     label: 'AT 1 (경도)' },
      { value: 'AT3',  detail: 'Severe attrition (AT)',   label: 'AT 3 (중증)' },
      { value: 'AB1',  detail: 'Mild abrasion (AB)',      label: 'AB 1 (경도)' },
      { value: 'AB3',  detail: 'Severe abrasion (AB)',    label: 'AB 3 (중증)' },
    ],
    optComment: {
      none: '마모 없음.',
      AT1:  '경도 교모(AT1). 법랑질 광택 소실. 원인(부정교합 등) 평가.',
      AT3:  '중증 교모(AT3). 상아질 노출, 치수 근접 가능성. 치수 상태 평가 및 수복.',
      AB1:  '경도 마모(AB1). 원인(딱딱한 물체 씹기 등) 교육. 경과 관찰.',
      AB3:  '중증 마모(AB3). 상아질 또는 치수 노출 가능성. 수복 또는 VPT 고려.',
    },
    generalComment: {
      none: '이 치아에 마모가 없습니다.',
      AT1:  '이 치아가 다른 치아와 마찰로 약간 닳았습니다.',
      AT3:  '이 치아가 심하게 닳아 신경이 노출될 위험이 있습니다.',
      AB1:  '이 치아가 딱딱한 물건을 씹어서 약간 마모되었습니다.',
      AB3:  '이 치아가 심하게 마모되었습니다. 치료가 필요합니다.',
    },
    urgency: {
      none: 'none',
      AT1:  'monitor',
      AT3:  'recommended',
      AB1:  'monitor',
      AB3:  'recommended',
    },
    suggestedTx: {
      none:      [],
      AT_mild:   ['OC'],
      AT_severe: ['R/C', 'PCI', 'VPT'],
      AB_mild:   [],
      AB_severe: ['R/C', 'PCI', 'VPT'],
    },
    noteTags: ['attrition', 'abrasion', 'wear', 'AT', 'AB'],
  },

  // ── 유치 잔존 ──────────────────────────────────────────────
  persistent_deciduous: {
    testID:     'persistent_deciduous',
    testName:   'Persistent Deciduous Tooth',
    testNameKo: '유치 잔존',
    testType:   'select',
    testInfo:   'DT/P. 영구치 맹출 후에도 유치가 탈락하지 않은 상태. 부정교합 및 치주 문제 유발.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none',          detail: 'No persistent deciduous tooth',       label: '없음' },
      { value: 'DT/P_canine',  detail: 'Persistent deciduous canine (DT/P)',  label: '유치 견치 잔존 (DT/P)' },
      { value: 'DT/P_incisor', detail: 'Persistent deciduous incisor (DT/P)', label: '유치 절치 잔존 (DT/P)' },
      { value: 'DT/P_premolar', detail: 'Persistent deciduous premolar (DT/P)', label: '유치 전구치 잔존 (DT/P)' },
    ],
    optComment: {
      none:          '유치 잔존 없음.',
      'DT/P_canine': '유치 견치(canine) 잔존. 영구치와 겹쳐 부정교합 유발. 발치 필요.',
      'DT/P_incisor': '유치 절치(incisor) 잔존. 영구치와 겹쳐 부정교합 유발. 발치 필요.',
      'DT/P_premolar': '유치 전구치(premolar) 잔존. 영구치와 겹쳐 부정교합 유발. 발치 필요.',
    },
    generalComment: {
      none:          '유치 잔존이 없습니다.',
      'DT/P_canine': '유치 견치가 빠지지 않고 남아있습니다. 영구치와 겹쳐 부정교합을 일으킬 수 있습니다.',
      'DT/P_incisor': '유치 절치가 빠지지 않고 남아있습니다. 영구치와 겹쳐 부정교합을 일으킬 수 있습니다.',
      'DT/P_premolar': '유치 전구치가 빠지지 않고 남아있습니다. 영구치와 겹쳐 부정교합을 일으킬 수 있습니다.',
    },
    urgency: {
      none:          'none',
      'DT/P_canine': 'recommended',
      'DT/P_incisor': 'recommended',
      'DT/P_premolar': 'recommended',
    },
    suggestedTx: {
      none:          [],
      'DT/P_canine': ['XSS'],
      'DT/P_incisor': ['XSS'],
      'DT/P_premolar': ['XSS'],
    },
    noteTags: ['persistent_deciduous', 'DT/P', 'retained_deciduous'],
  },

  // ── 과잉치 ─────────────────────────────────────────────────
  supernumerary: {
    testID:     'supernumerary',
    testName:   'Supernumerary Tooth',
    testNameKo: '과잉치',
    testType:   'select',
    testInfo:   'T/SN. 정상 치아 수 외에 추가로 존재하는 치아. 과밀, 부정교합 유발.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none',  detail: 'No supernumerary tooth',             label: '없음' },
      { value: 'T/SN',  detail: 'Supernumerary tooth present (T/SN)', label: '과잉치 존재 (T/SN)' },
    ],
    optComment: {
      none:  '과잉치 없음.',
      'T/SN': '과잉치(T/SN) 존재. 치아 과밀, 인접치 흡수, 낭종 가능성. 방사선 평가 후 발치 여부 결정.',
    },
    generalComment: {
      none:  '과잉치가 없습니다.',
      'T/SN': '정상보다 치아가 하나 더 있습니다. 다른 치아에 영향을 줄 수 있어 평가가 필요합니다.',
    },
    urgency: {
      none:  'none',
      'T/SN': 'recommended',
    },
    suggestedTx: {
      none:  [],
      'T/SN': ['RAD', 'X', 'XSS'],
    },
    noteTags: ['supernumerary', 'T/SN', 'extra tooth'],
  },

  // ── 치아 착색 ──────────────────────────────────────────────
  staining: {
    testID:     'staining',
    testName:   'Tooth Discoloration / Staining',
    testNameKo: '치아 착색/변색',
    testType:   'select',
    testInfo:   '치아 변색. 외인성(extrinsic, 음식/치석)과 내인성(intrinsic, 치수 괴사/외상)으로 구분. 핑크 또는 회색 변색은 치수 이상 시사.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none',        detail: 'No discoloration',                         label: '정상' },
      { value: 'extrinsic',   detail: 'Extrinsic staining',                       label: '외인성 착색' },
      { value: 'pink',        detail: 'Pink discoloration (pulp hemorrhage)',      label: '핑크 변색 (치수 출혈)' },
      { value: 'gray',        detail: 'Gray/dark discoloration (pulp necrosis)',   label: '회색/암갈 변색 (치수 괴사)' },
      { value: 'tetracycline', detail: 'Intrinsic staining (tetracycline)',        label: '내인성 착색 (테트라사이클린)' },
    ],
    optComment: {
      none:        '착색 없음.',
      extrinsic:   '외인성 착색. 스케일링으로 제거 가능.',
      pink:        '핑크 변색 — 치수 출혈 시사. 생활 치수일 수 있으나 VPT 또는 RCT 평가 필요.',
      gray:        '회색/암갈 변색 — 치수 괴사 강력 시사. 방사선으로 periapical pathology 확인. RCT 또는 발치.',
      tetracycline: '내인성 착색(테트라사이클린). 치수 정상 가능. 미용적 수복 논의.',
    },
    generalComment: {
      none:        '이 치아의 색이 정상입니다.',
      extrinsic:   '치아 표면이 착색되어 있습니다. 스케일링으로 제거됩니다.',
      pink:        '이 치아가 분홍빛으로 변해 있습니다. 치아 내부 출혈이 있을 수 있어 검사가 필요합니다.',
      gray:        '이 치아가 회색으로 변해 신경이 죽었을 가능성이 있습니다. X-ray 및 치료가 필요합니다.',
      tetracycline: '항생제로 인한 내부 착색입니다. 치아 건강에는 큰 영향이 없을 수 있습니다.',
    },
    urgency: {
      none:        'none',
      extrinsic:   'elective',
      pink:        'recommended',
      gray:        'urgent',
      tetracycline: 'monitor',
    },
    suggestedTx: {
      none:        [],
      extrinsic:   ['PRO'],
      pink:        ['VPT', 'RCT', 'RAD'],
      gray:        ['RCT', 'XSS', 'RAD'],
      tetracycline: [],
    },
    noteTags: ['staining', 'discoloration', 'pink tooth', 'gray tooth', 'pulp necrosis'],
  },

  // ── 치근단 병소 ────────────────────────────────────────────
  periapical: {
    testID:     'periapical',
    testName:   'Periapical Pathology',
    testNameKo: '치근단 병소',
    testType:   'select',
    testInfo:   'PA 병소. 방사선으로 평가. 치근단 주위 골 소실, 농양, 낭종, 육아종.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'none',  detail: 'No periapical pathology',          label: '없음' },
      { value: 'PA/G',  detail: 'Periapical granuloma (PA/G)',      label: '치근단 육아종 (PA/G)' },
      { value: 'PA/A',  detail: 'Periapical abscess (PA/A)',        label: '치근단 농양 (PA/A)' },
      { value: 'PA/C',  detail: 'Periapical cyst (PA/C)',           label: '치근단 낭종 (PA/C)' },
      { value: 'PA/P',  detail: 'Periapical pathology (PA/P)',      label: '치근단 병소 (감별 불가, PA/P)' },
    ],
    optComment: {
      none:  '치근단 병소 없음.',
      'PA/G': '치근단 육아종(PA/G). 방사선으로 투과성 병소 확인. RCT 또는 발치.',
      'PA/A': '치근단 농양(PA/A). 통증, 부종, 누공 가능. 즉각적인 RCT 또는 발치. 항생제 병용 고려.',
      'PA/C': '치근단 낭종(PA/C). 점진적 성장. 방사선으로 골 파괴 범위 평가. RCT 또는 발치.',
      'PA/P': '치근단 병소(PA/P) 확인. 육아종/농양/낭종 감별 필요. RCT 또는 발치.',
    },
    generalComment: {
      none:  '이 치아 뿌리 끝에 이상이 없습니다.',
      'PA/G': '치아 뿌리 끝에 염증 덩어리가 있습니다. 치료가 필요합니다.',
      'PA/A': '치아 뿌리 끝에 고름이 찬 상태입니다. 통증이 심할 수 있으며 즉각적인 치료가 필요합니다.',
      'PA/C': '치아 뿌리 끝에 물혹이 있습니다. 점점 커질 수 있어 치료가 필요합니다.',
      'PA/P': '치아 뿌리 끝에 이상 소견이 있습니다. 정밀 검사가 필요합니다.',
    },
    urgency: {
      none:  'none',
      'PA/G': 'recommended',
      'PA/A': 'urgent',
      'PA/C': 'recommended',
      'PA/P': 'recommended',
    },
    suggestedTx: {
      none:  [],
      'PA/G': ['RCT', 'XSS', 'RAD'],
      'PA/A': ['RCT', 'XSS', 'RAD', 'AP/X'],
      'PA/C': ['RCT', 'DTC/R', 'XSS', 'RAD'],
      'PA/P': ['RCT', 'XSS', 'RAD'],
    },
    noteTags: ['periapical', 'PA', 'abscess', 'granuloma', 'cyst', 'apical'],
  },

  // ── 처치 내역 ──────────────────────────────────────────────
  treatment_done: {
    testID:     'treatment_done',
    testName:   'Treatment Performed',
    testNameKo: '시행된 치료',
    testType:   'multiselect',
    testInfo:   '해당 치아에 시행된 치료 내역. AVDC 약어로 기록.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'PRO',   detail: 'Professional dental cleaning (PRO)',         label: '스케일링/연마 (PRO)' },
      { value: 'X',     detail: 'Closed extraction (X)',                      label: '발치-단순 (X)' },
      { value: 'XS',    detail: 'Closed extraction with sectioning (XS)',     label: '발치-분할 (XS)' },
      { value: 'XSS',   detail: 'Open extraction (XSS)',                      label: '발치-외과 (XSS)' },
      { value: 'RCT',   detail: 'Root canal therapy (RCT)',                   label: '근관 치료 (RCT)' },
      { value: 'VPT',   detail: 'Vital pulp therapy (VPT)',                   label: '생활 치수 처치 (VPT)' },
      { value: 'R/C',   detail: 'Composite restoration (R/C)',                label: '복합 레진 수복 (R/C)' },
      { value: 'R/I',   detail: 'Glass ionomer restoration (R/I)',            label: '글라스 아이오노머 수복 (R/I)' },
      { value: 'CR/A',  detail: 'Crown amputation (CR/A)',                    label: '치관 절단 (CR/A)' },
      { value: 'ODY',   detail: 'Odontoplasty (ODY)',                         label: '치아 성형 (ODY)' },
      { value: 'GV',    detail: 'Gingivectomy/gingivoplasty (GV)',            label: '치은 절제/성형 (GV)' },
      { value: 'RP/C',  detail: 'Closed root planing (RP/C)',                 label: '치근 활택 — 비외과 (RP/C)' },
      { value: 'RP/O',  detail: 'Open root planing (RP/O)',                   label: '치근 활택 — 외과 (RP/O)' },
      { value: 'RAD',   detail: 'Dental radiograph (RAD)',                    label: '치과 방사선 (RAD)' },
      { value: 'B/I',   detail: 'Incisional biopsy (B/I)',                    label: '절개 생검 (B/I)' },
      { value: 'B/E',   detail: 'Excisional biopsy (B/E)',                    label: '절제 생검 (B/E)' },
    ],
    optComment:     {},
    generalComment: {},
    urgency:        {},
    suggestedTx:    {},
    noteTags: ['treatment', 'procedure', 'extraction', 'RCT', 'restoration'],
  },

  // ── 치료 계획 ──────────────────────────────────────────────
  treatment_plan: {
    testID:     'treatment_plan',
    testName:   'Treatment Plan',
    testNameKo: '치료 계획',
    testType:   'multiselect',
    testInfo:   '해당 치아의 향후 치료 계획. AVDC 약어로 기록.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'monitor',  detail: 'Monitor / recheck',                            label: '경과 관찰' },
      { value: 'PRO',      detail: 'Professional dental cleaning (PRO)',            label: '스케일링 (PRO)' },
      { value: 'X',        detail: 'Closed extraction (X)',                         label: '발치-단순 (X)' },
      { value: 'XS',       detail: 'Closed extraction with sectioning (XS)',        label: '발치-분할 (XS)' },
      { value: 'XSS',      detail: 'Open extraction (XSS)',                         label: '발치-외과 (XSS)' },
      { value: 'RCT',      detail: 'Root canal therapy (RCT)',                      label: '근관 치료 (RCT)' },
      { value: 'VPT',      detail: 'Vital pulp therapy (VPT)',                      label: '생활 치수 처치 (VPT)' },
      { value: 'R/C',      detail: 'Composite restoration (R/C)',                   label: '수복 — 레진 (R/C)' },
      { value: 'ODY',      detail: 'Odontoplasty (ODY)',                            label: '치아 성형 (ODY)' },
      { value: 'OA',       detail: 'Orthodontic appliance (OA)',                    label: '교정 장치 (OA)' },
      { value: 'RAD',      detail: 'Dental radiograph (RAD)',                       label: '치과 방사선 (RAD)' },
      { value: 'GTR',      detail: 'Guided tissue regeneration (GTR)',              label: '조직 유도 재생 (GTR)' },
      { value: 'CR/A',     detail: 'Crown amputation (CR/A)',                       label: '치관 절단 (CR/A)' },
    ],
    optComment:     {},
    generalComment: {},
    urgency:        {},
    suggestedTx:    {},
    noteTags: ['treatment plan', 'TP', 'plan'],
  },

  // ── 치료 우선순위 ──────────────────────────────────────────
  treatment_priority: {
    testID:     'treatment_priority',
    testName:   'Treatment Priority',
    testNameKo: '치료 우선순위',
    testType:   'select',
    testInfo:   '해당 치아의 치료 긴급도.',
    affectedSpecies: ['canine', 'feline'],
    options: [
      { value: 'urgent',      detail: 'Urgent — immediate treatment required',  label: '긴급 (Urgent)' },
      { value: 'recommended', detail: 'Recommended — treat at next visit',      label: '권장 (Recommended)' },
      { value: 'elective',    detail: 'Elective — when convenient',             label: '선택적 (Elective)' },
      { value: 'monitor',     detail: 'Monitor — observe and recheck',          label: '경과 관찰 (Monitor)' },
    ],
    optComment: {
      urgent:      '즉각적인 치료 필요. 지연 시 전신 건강에 영향 가능.',
      recommended: '다음 내원 시 치료 권장.',
      elective:    '선택적 치료. 증상 없으면 일정에 따라 시행.',
      monitor:     '경과 관찰. 다음 검진 시 재평가.',
    },
    generalComment: {
      urgent:      '이 치아는 빠른 치료가 필요합니다.',
      recommended: '다음 내원 시 이 치아 치료를 권장합니다.',
      elective:    '이 치아는 필요에 따라 선택적으로 치료할 수 있습니다.',
      monitor:     '이 치아는 지속적인 모니터링이 필요합니다.',
    },
    urgency:    {},
    suggestedTx:{},
    noteTags: ['priority', 'urgency', 'treatment priority'],
  },
};
