// // ============================================================
// // 타입 정의
// // ============================================================

// export type AnatomicGroup =
//   | 'LV'
//   | 'LA'
//   | 'AO'
//   | 'MV'
//   | 'TV'
//   | 'PA'
//   | 'RV'
//   | 'RA'
//   | 'Pericardium'
//   | 'Pleura'
//   | 'TDI'
//   | 'General';

// export type FunctionalGroup =
//   | 'MMVD_staging'
//   | 'LA_size'
//   | 'LA_pressure'
//   | 'LV_size'
//   | 'LV_systolic'
//   | 'LV_diastolic'
//   | 'MV_morphology'
//   | 'MV_regurgitation'
//   | 'AV_disease'
//   | 'TV_disease'
//   | 'PH_probability'
//   | 'PA_pressure'
//   | 'PA_flow'
//   | 'RV_function'
//   | 'Effusion'
//   | 'Hemodynamics'
//   | 'Cardiomegaly';

// // Functional Group 메타데이터 (Functional 탭 렌더링 순서 및 레이블)
// export const FUNCTIONAL_GROUP_META: Record<FunctionalGroup, {
//   label: string;
//   priority: number;
//   description: string;
// }> = {
//   MMVD_staging:     { label: 'MMVD Staging',          priority: 1,  description: 'MMVD 병기 평가 (MINE score, ACVIM)' },
//   LA_size:          { label: 'LA Size',                priority: 2,  description: '좌심방 크기' },
//   LA_pressure:      { label: 'LA Pressure',            priority: 3,  description: '좌심방압 상승 여부' },
//   LV_size:          { label: 'LV Size',                priority: 4,  description: '좌심실 크기 / Preload' },
//   LV_systolic:      { label: 'LV Systolic Function',   priority: 5,  description: '좌심실 수축 기능' },
//   LV_diastolic:     { label: 'LV Diastolic Function',  priority: 6,  description: '이완기능 장애 여부' },
//   MV_morphology:    { label: 'MV Morphology',          priority: 7,  description: '승모판 구조 이상' },
//   MV_regurgitation: { label: 'MV Regurgitation',       priority: 8,  description: 'MR 정도' },
//   AV_disease:       { label: 'AV Disease',             priority: 9,  description: '대동맥판 협착 / 역류' },
//   TV_disease:       { label: 'TV Disease',             priority: 10, description: '삼첨판 구조 및 역류' },
//   PH_probability:   { label: 'PH Probability',         priority: 11, description: '폐고혈압 가능성 종합' },
//   PA_pressure:      { label: 'PA Pressure',            priority: 12, description: '폐동맥압 추정' },
//   PA_flow:          { label: 'PA Flow Pattern',        priority: 13, description: 'PA 혈류 패턴 이상' },
//   RV_function:      { label: 'RV Function',            priority: 14, description: '우심실 기능 / 형태' },
//   Effusion:         { label: 'Effusion',               priority: 15, description: '심낭 / 흉강 삼출액' },
//   Hemodynamics:     { label: 'Hemodynamics',           priority: 16, description: '전신 활력징후' },
//   Cardiomegaly:     { label: 'Cardiomegaly',           priority: 17, description: '방사선상 심비대' },
// };

// // Anatomic Group 메타데이터
// export const ANATOMIC_GROUP_META: Record<AnatomicGroup, {
//   label: string;
//   priority: number;
// }> = {
//   General:     { label: 'General / PE',    priority: 1 },
//   LV:          { label: 'LV',             priority: 2 },
//   LA:          { label: 'LA',             priority: 3 },
//   MV:          { label: 'MV',             priority: 4 },
//   AO:          { label: 'AO / AV',        priority: 5 },
//   PA:          { label: 'PA / PV',        priority: 6 },
//   RV:          { label: 'RV / IVS',       priority: 7 },
//   RA:          { label: 'RA / CVC',       priority: 8 },
//   TV:          { label: 'TV',             priority: 9 },
//   TDI:         { label: 'TDI',            priority: 10 },
//   Pericardium: { label: 'Pericardium',    priority: 11 },
//   Pleura:      { label: 'Pleura',         priority: 12 },
// };


// // ============================================================
// // ECHO_TESTS
// // ============================================================

// export const ECHO_TESTS: Record<string, EchoTest> = {

//   // ============================================================
//   // PE 섹션 - 신체검사
//   // ============================================================
//   BW_kg: {
//     keywordID: 'BW_kg',
//     keywordName: 'BW (kg)',
//     section: 'PE',
//     group: 'PE',
//     testType: 'other',
//     unit: 'kg',
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics', 'MMVD_staging', 'LV_size'],
//   },
//   BP: {
//     keywordID: 'BP',
//     keywordName: 'Blood Pressure',
//     section: 'PE',
//     group: 'PE',
//     testType: 'range',
//     unit: 'mmHg',
//     thresholds: [80, 150],
//     optResult: ['hypotension', 'normal', 'hypertension'],
//     optComment: ['', '', ''],
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics'],
//   },
//   BT: {
//     keywordID: 'BT',
//     keywordName: 'Body Temp.',
//     section: 'PE',
//     group: 'PE',
//     testType: 'range',
//     unit: '°C',
//     thresholds: [38, 39.2],
//     optResult: ['hypothermia', 'normal', 'hyperthermia'],
//     optComment: ['', '', ''],
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics'],
//   },
//   HR: {
//     keywordID: 'HR',
//     keywordName: 'Heart Rate',
//     section: 'PE',
//     group: 'PE',
//     testType: 'range',
//     unit: 'bpm',
//     thresholds: [80, 160],
//     optResult: ['bradycardia', 'normal', 'tachycardia'],
//     optComment: ['', '', ''],
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics'],
//   },
//   RR: {
//     keywordID: 'RR',
//     keywordName: 'Respi. Rate',
//     section: 'PE',
//     group: 'PE',
//     testType: 'range',
//     unit: 'rr/min',
//     thresholds: [10, 30, 40, 60],
//     optResult: ['hypopnea', 'normal', 'tachypnea', 'tachypnea', 'tachypnea'],
//     optComment: ['', '', '', '', ''],
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics'],
//   },
//   HS: {
//     keywordID: 'HS',
//     keywordName: 'Heart Sound',
//     section: 'PE',
//     group: 'PE',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics'],
//   },
//   PE_comment: {
//     keywordID: 'PE_comment',
//     keywordName: 'P.E. comment',
//     section: 'PE',
//     group: 'PE',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: ['Hemodynamics'],
//   },

//   // ============================================================
//   // Radio 섹션 - 방사선
//   // ============================================================
//   VHS: {
//     keywordID: 'VHS',
//     keywordName: 'VHS',
//     section: 'Radio',
//     group: 'Thorax',
//     testType: 'range',
//     unit: '',
//     thresholds: [8.5, 11, 12, 13],
//     optResult: ['decrease', 'normal', 'mild increase', 'moderate increase', 'severe increase'],
//     optComment: ['microcardia', 'normal', 'mild cardiomegaly', 'moderate cardiomegaly', 'severe cardiomegaly'],
//     anatomic_group: 'General',
//     functional_groups: ['Cardiomegaly'],
//   },
//   VLAS: {
//     keywordID: 'VLAS',
//     keywordName: 'VLAS',
//     section: 'Radio',
//     group: 'Thorax',
//     testType: 'range',
//     unit: '',
//     thresholds: [3],
//     optResult: ['normal', 'increase'],
//     optComment: ['normal', 'LA cardiomegaly'],
//     anatomic_group: 'LA',
//     functional_groups: ['LA_size', 'Cardiomegaly'],
//   },
//   Radio_comment: {
//     keywordID: 'Radio_comment',
//     keywordName: 'Radiology comment',
//     section: 'Radio',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: ['Cardiomegaly'],
//   },

//   // ============================================================
//   // Bmode 섹션
//   // ============================================================
//   MV_leafletTipThickening: {
//     keywordID: 'MV_leafletTipThickening',
//     keywordName: 'MV Leaflet Tip Thickening',
//     section: 'Bmode',
//     group: 'MV',
//     testType: 'select',
//     options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
//     optResult: ['', 'normal', 'MV anterior leaflet tip thickening', 'MV posterior leaflet tip thickening', 'MV anterior & posterior leaflet tip thickening'],
//     optComment: ['', 'normal', 'MMVD', 'MMVD', 'MMVD'],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_morphology', 'MMVD_staging'],
//   },
//   MV_prolapse: {
//     keywordID: 'MV_prolapse',
//     keywordName: 'MV Prolapse',
//     section: 'Bmode',
//     group: 'MV',
//     testType: 'select',
//     options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
//     optResult: ['', 'normal', 'MV prolapse(anterior)', 'MV prolapse(posterior)', 'MV prolapse(anterior & posterior)'],
//     optComment: ['', 'normal', 'MMVD', 'MMVD', 'MMVD'],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_morphology', 'MMVD_staging'],
//   },
//   MV_flailmovement: {
//     keywordID: 'MV_flailmovement',
//     keywordName: 'MV Flail Movement',
//     section: 'Bmode',
//     group: 'MV',
//     testType: 'select',
//     options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
//     optResult: ['', 'normal', 'MV flail movement(anterior)', 'MV flail movement(posterior)', 'MV flail movement(anterior & posterior)'],
//     optComment: ['', 'normal', 'MMVD', 'MMVD', 'MMVD'],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_morphology', 'MMVD_staging'],
//   },
//   MV_SAM: {
//     keywordID: 'MV_SAM',
//     keywordName: 'Systolic Anterior Motion (SAM)',
//     section: 'Bmode',
//     group: 'MV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'none', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_morphology', 'LV_systolic'],
//   },
//   IVS_flattening: {
//     keywordID: 'IVS_flattening',
//     keywordName: 'IVS Flattening',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site1',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', 'RV enlargement'],
//     anatomic_group: 'RV',
//     functional_groups: ['RV_function', 'PH_probability'],
//   },
//   IVS_paradoxicalMV: {
//     keywordID: 'IVS_paradoxicalMV',
//     keywordName: 'IVS Paradoxical Movement',
//     section: 'Bmode',
//     group: 'IVS',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'RV',
//     functional_groups: ['RV_function'],
//   },
//   TV_leafletTipThickening: {
//     keywordID: 'TV_leafletTipThickening',
//     keywordName: 'TV Leaflet Tip Thickening',
//     section: 'Bmode',
//     group: 'TV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'TV leaflet tip thickening'],
//     optComment: ['', 'normal', 'TVI'],
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease'],
//   },
//   TV_prolapse: {
//     keywordID: 'TV_prolapse',
//     keywordName: 'TV Prolapse',
//     section: 'Bmode',
//     group: 'TV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'TV prolapse'],
//     optComment: ['', 'normal', 'TVI'],
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease'],
//   },
//   TV_flailmovement: {
//     keywordID: 'TV_flailmovement',
//     keywordName: 'TV Flail Movement',
//     section: 'Bmode',
//     group: 'TV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'TV flail movement'],
//     optComment: ['', 'normal', 'TVI'],
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease'],
//   },
//   AV_flattening: {
//     keywordID: 'AV_flattening',
//     keywordName: 'Aortic Valve Flattening',
//     section: 'Bmode',
//     group: 'AV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   AV_poststenoticdilation: {
//     keywordID: 'AV_poststenoticdilation',
//     keywordName: 'AV Post-stenotic Dilation',
//     section: 'Bmode',
//     group: 'AV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   LVOT_obstruction: {
//     keywordID: 'LVOT_obstruction',
//     keywordName: 'LVOT Obstruction',
//     section: 'Bmode',
//     group: 'LVOT',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['AV_disease', 'LV_systolic'],
//   },
//   PV_thickening: {
//     keywordID: 'PV_thickening',
//     keywordName: 'PV Thickening',
//     section: 'Bmode',
//     group: 'PV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   PV_changeOfdimension: {
//     keywordID: 'PV_changeOfdimension',
//     keywordName: 'PV Change of Dimension',
//     section: 'Bmode',
//     group: 'PV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow'],
//   },
//   PericardialEffusion: {
//     keywordID: 'PericardialEffusion',
//     keywordName: 'Pericardial Effusion',
//     section: 'Bmode',
//     group: 'Effusion',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'Pericardium',
//     functional_groups: ['Effusion'],
//   },
//   PericardialEffusion_vol: {
//     keywordID: 'PericardialEffusion_vol',
//     keywordName: 'Pericardial Effusion (vol.)',
//     section: 'Bmode',
//     group: 'Effusion',
//     testType: 'other',
//     unit: 'ml',
//     anatomic_group: 'Pericardium',
//     functional_groups: ['Effusion'],
//   },
//   PleuralEffusion: {
//     keywordID: 'PleuralEffusion',
//     keywordName: 'Pleural Effusion',
//     section: 'Bmode',
//     group: 'Effusion',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'Pleura',
//     functional_groups: ['Effusion'],
//   },
//   PleuralEffusion_vol: {
//     keywordID: 'PleuralEffusion_vol',
//     keywordName: 'Pleural Effusion (vol.)',
//     section: 'Bmode',
//     group: 'Effusion',
//     testType: 'other',
//     unit: 'mm',
//     anatomic_group: 'Pleura',
//     functional_groups: ['Effusion'],
//   },
//   VTI: {
//     keywordID: 'VTI',
//     keywordName: 'Systemic VTI',
//     section: 'Bmode',
//     group: 'LV',
//     testType: 'other',
//     unit: '',
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic'],
//   },
//   LVEIO: {
//     keywordID: 'LVEIO',
//     keywordName: 'LVEIO',
//     section: 'Bmode',
//     group: 'LV',
//     testType: 'calculated',
//     unit: '',
//     formula: 'LVEIO',
//     dependencies: ['MV_Ewave', 'VTI'],
//     thresholds: [13.26],
//     optResult: ['decrease', 'normal'],
//     optComment: ['CHF risk', 'normal'],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic', 'LA_pressure'],
//   },
//   Bmode_comment: {
//     keywordID: 'Bmode_comment',
//     keywordName: 'B-mode Comment',
//     section: 'Bmode',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: [],
//   },

//   // ============================================================
//   // Mmode 섹션
//   // ============================================================
//   VSd: {
//     keywordID: 'VSd',
//     keywordName: 'IVS-d',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_size'],
//   },
//   LVd: {
//     keywordID: 'LVd',
//     keywordName: 'LV-d',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_size', 'MMVD_staging'],
//   },
//   LVWd: {
//     keywordID: 'LVWd',
//     keywordName: 'LVW-d',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_size'],
//   },
//   VSs: {
//     keywordID: 'VSs',
//     keywordName: 'IVS-s',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic'],
//   },
//   LVs: {
//     keywordID: 'LVs',
//     keywordName: 'LV-s',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic'],
//   },
//   LVWs: {
//     keywordID: 'LVWs',
//     keywordName: 'LVW-s',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic'],
//   },
//   LVFS: {
//     keywordID: 'LVFS',
//     keywordName: 'FS',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'calculated',
//     unit: '%',
//     formula: 'LVFS',
//     dependencies: ['LVd', 'LVs'],
//     thresholds: [20, 28, 45, 55],
//     optResult: ['decrease', 'decrease', 'normal', 'increase', 'increase'],
//     optComment: ['severe myocardial systolic failure(suggestive)', '', 'normal', '', 'hyperdynamic LV function(would be consider)'],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic', 'MMVD_staging'],
//   },
//   EF: {
//     keywordID: 'EF',
//     keywordName: 'EF',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'range',
//     unit: '%',
//     thresholds: [40],
//     optResult: ['decrease', 'normal'],
//     optComment: ['LV contractility decrease', ''],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic'],
//   },
//   LVIDDN: {
//     keywordID: 'LVIDDN',
//     keywordName: 'LVIDDN',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'calculated',
//     unit: '',
//     formula: 'LVIDDN',
//     dependencies: ['LVd', 'BW_kg'],
//     thresholds: [1.7],
//     optResult: ['normal', 'increase'],
//     optComment: ['normal', 'increased LV preload (ACVIM B2?)'],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_size', 'MMVD_staging'],
//   },
//   ESV: {
//     keywordID: 'ESV',
//     keywordName: 'ESV',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'other',
//     unit: 'ml',
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic', 'LV_size'],
//   },
//   ESVI: {
//     keywordID: 'ESVI',
//     keywordName: 'Systolic Index (ESVI)',
//     section: 'Objective_Evaluation',
//     group: 'Mmode',
//     testType: 'calculated',
//     unit: 'ml/m²',
//     formula: 'ESVI',
//     dependencies: ['ESV', 'BW_kg'],
//     thresholds: [30, 70, 100],
//     optResult: ['normal', 'increase', 'increase', 'increase'],
//     optComment: ['normal myocardial function', 'mild myocardial failure', 'moderate myocardial failure', 'severe myocardial failure'],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_systolic'],
//   },
//   LAdMax: {
//     keywordID: 'LAdMax',
//     keywordName: 'LAd Max',
//     section: 'Objective_Evaluation',
//     group: 'LA FS',
//     testType: 'other',
//     unit: 'mm',
//     anatomic_group: 'LA',
//     functional_groups: ['LA_size'],
//   },
//   LAdMin: {
//     keywordID: 'LAdMin',
//     keywordName: 'LAd Min',
//     section: 'Objective_Evaluation',
//     group: 'LA FS',
//     testType: 'other',
//     unit: 'mm',
//     anatomic_group: 'LA',
//     functional_groups: ['LA_size'],
//   },
//   LAFS: {
//     keywordID: 'LAFS',
//     keywordName: 'LA FS',
//     section: 'Objective_Evaluation',
//     group: 'LA FS',
//     testType: 'calculated',
//     unit: '%',
//     formula: 'LAFS',
//     dependencies: ['LAdMax', 'LAdMin'],
//     thresholds: [19, 30],
//     optResult: ['decrease', 'decrease', 'normal'],
//     optComment: ['CHF risk', 'increased LA pressure', 'normal'],
//     anatomic_group: 'LA',
//     functional_groups: ['LA_size', 'LA_pressure'],
//   },
//   LA: {
//     keywordID: 'LA',
//     keywordName: 'LA',
//     section: 'Objective_Evaluation',
//     group: 'LA',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['decreased LA dia.', 'normal', 'LA remodelling'],
//     anatomic_group: 'LA',
//     functional_groups: ['LA_size', 'MMVD_staging'],
//   },
//   AO: {
//     keywordID: 'AO',
//     keywordName: 'AO',
//     section: 'Objective_Evaluation',
//     group: 'AO',
//     testType: 'mmode_range',
//     unit: 'mm',
//     refTable: 'mmoderef_dog',
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['decreased AO diameter', 'normal', 'increased AO diameter'],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   PA: {
//     keywordID: 'PA',
//     keywordName: 'PA',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'range',
//     unit: 'mm',
//     thresholds: [],
//     optResult: [],
//     optComment: [],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   LAAOratio: {
//     keywordID: 'LAAOratio',
//     keywordName: 'LA:AO Ratio',
//     section: 'Objective_Evaluation',
//     group: 'LA',
//     testType: 'calculated',
//     unit: '',
//     formula: 'LAAOratio',
//     dependencies: ['LA', 'AO'],
//     thresholds: [0.8, 1.3, 1.6, 2.0],
//     optResult: ['decrease', 'normal', 'mild increase', 'moderate increase', 'marked increase'],
//     optComment: ['', 'normal', 'LA vol. mild increase', 'LA vol. moderate increase (ACVIM >B2)', 'LA vol. severe increase'],
//     anatomic_group: 'LA',
//     functional_groups: ['LA_size', 'MMVD_staging', 'Cardiomegaly'],
//   },
//   PAAO: {
//     keywordID: 'PAAO',
//     keywordName: 'PA/AO',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'calculated',
//     unit: '',
//     formula: 'PAAO',
//     dependencies: ['PA', 'AO'],
//     thresholds: [1],
//     optResult: ['normal', 'increase'],
//     optComment: ['normal', 'PA dia. increase'],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },

//   // ============================================================
//   // ColorDoppler 섹션
//   // ============================================================
//   MV_turbulentJet: {
//     keywordID: 'MV_turbulentJet',
//     keywordName: 'MV Turbulent Jet',
//     section: 'ColorDoppler',
//     group: 'MV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', 'MV regurgitation'],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_regurgitation', 'MMVD_staging'],
//   },
//   MV_turbulentJetRange: {
//     keywordID: 'MV_turbulentJetRange',
//     keywordName: 'MV Turbulent Jet Range',
//     section: 'ColorDoppler',
//     group: 'MV',
//     testType: 'range',
//     unit: '%',
//     thresholds: [10, 30, 70],
//     optResult: ['normal', 'Mild', 'Moderate', 'Severe'],
//     optComment: ['', 'mild MV regurgitation', 'moderate MV regurgitation', 'severe MV regurgitation'],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_regurgitation', 'MMVD_staging'],
//   },
//   TV_turbulentJet: {
//     keywordID: 'TV_turbulentJet',
//     keywordName: 'TV Turbulent Jet',
//     section: 'ColorDoppler',
//     group: 'TV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', 'TV regurgitation'],
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease'],
//   },
//   TV_turbulentJetRange: {
//     keywordID: 'TV_turbulentJetRange',
//     keywordName: 'TV Turbulent Jet Range',
//     section: 'ColorDoppler',
//     group: 'TV',
//     testType: 'range',
//     unit: '%',
//     thresholds: [10, 30, 70],
//     optResult: ['normal', 'Mild', 'Moderate', 'Severe'],
//     optComment: ['', 'mild TV regurgitation', 'moderate TV regurgitation', 'severe TV regurgitation'],
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease'],
//   },
//   AV_turbulentJet: {
//     keywordID: 'AV_turbulentJet',
//     keywordName: 'AV Turbulent Jet',
//     section: 'ColorDoppler',
//     group: 'AV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   PV_turbulentJet: {
//     keywordID: 'PV_turbulentJet',
//     keywordName: 'PV Turbulent Jet',
//     section: 'ColorDoppler',
//     group: 'PV',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'normal', 'abnormal'],
//     optComment: ['', '', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow'],
//   },
//   CD_comment: {
//     keywordID: 'CD_comment',
//     keywordName: 'Color Doppler Comment',
//     section: 'ColorDoppler',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: [],
//   },

//   // ============================================================
//   // SpectralDoppler 섹션
//   // ============================================================
//   MV_Ewave: {
//     keywordID: 'MV_Ewave',
//     keywordName: 'MV E Wave',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'range',
//     unit: 'm/s',
//     thresholds: [1.08, 1.25],
//     optResult: ['normal', 'mild increase', 'increase'],
//     optComment: ['normal', 'monitoring', 'increased LA pressure'],
//     anatomic_group: 'MV',
//     functional_groups: ['LA_pressure', 'LV_diastolic', 'MV_regurgitation', 'MMVD_staging'],
//   },
//   MV_Awave: {
//     keywordID: 'MV_Awave',
//     keywordName: 'MV A Wave',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'MV',
//     functional_groups: ['LV_diastolic'],
//   },
//   MV_EAratio: {
//     keywordID: 'MV_EAratio',
//     keywordName: 'MV E:A Ratio',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'calculated',
//     unit: '',
//     formula: 'MV_EAratio',
//     dependencies: ['MV_Ewave', 'MV_Awave'],
//     thresholds: [1, 1.85],
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['diastolic dysfunction', 'normal', 'CHF suspect'],
//     anatomic_group: 'MV',
//     functional_groups: ['LV_diastolic', 'LA_pressure'],
//   },
//   IVRT: {
//     keywordID: 'IVRT',
//     keywordName: 'IVRT',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'range',
//     unit: 'ms',
//     thresholds: [50, 70],
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['LAP increase, CHF risk', 'normal', 'impaired relaxation susp.'],
//     anatomic_group: 'LV',
//     functional_groups: ['LA_pressure', 'LV_diastolic'],
//   },
//   EIVRT: {
//     keywordID: 'EIVRT',
//     keywordName: 'E/IVRT',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'calculated',
//     unit: '',
//     formula: 'EIVRT',
//     dependencies: ['MV_Ewave', 'IVRT'],
//     thresholds: [2.2],
//     optResult: ['normal', 'increase'],
//     optComment: ['normal', 'increased LA pressure, CHF risk'],
//     anatomic_group: 'LV',
//     functional_groups: ['LA_pressure', 'LV_diastolic'],
//   },
//   DT: {
//     keywordID: 'DT',
//     keywordName: 'Deceleration Time (DT)',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'range',
//     unit: 'ms',
//     thresholds: [80, 100],
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['increased LA pressure', 'normal', ''],
//     anatomic_group: 'MV',
//     functional_groups: ['LA_pressure', 'LV_diastolic'],
//   },
//   MR: {
//     keywordID: 'MR',
//     keywordName: 'MV Regurgitation',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'select',
//     options: ['', 'none', 'mild', 'moderate', 'severe'],
//     optResult: ['', 'normal', 'mild MR', 'moderate MR', 'severe MR'],
//     optComment: ['', '', 'mild MR', 'moderate MR', 'severe MR'],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_regurgitation', 'MMVD_staging'],
//   },
//   MR_vel: {
//     keywordID: 'MR_vel',
//     keywordName: 'MR Velocity',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'MV',
//     functional_groups: ['MV_regurgitation'],
//   },
//   MRPG: {
//     keywordID: 'MRPG',
//     keywordName: 'MR PG',
//     section: 'SpectralDoppler',
//     group: 'MV',
//     testType: 'calculated',
//     unit: 'mmHg',
//     formula: 'PG',
//     dependencies: ['MR_vel'],
//     thresholds: [],
//     optResult: [],
//     optComment: [],
//     anatomic_group: 'MV',
//     functional_groups: ['MV_regurgitation'],
//   },
//   TV_Ewave: {
//     keywordID: 'TV_Ewave',
//     keywordName: 'TV E Wave',
//     section: 'SpectralDoppler',
//     group: 'TV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease', 'RV_function'],
//   },
//   TR: {
//     keywordID: 'TR',
//     keywordName: 'TR Regurgitation',
//     section: 'SpectralDoppler',
//     group: 'TV',
//     testType: 'select',
//     options: ['', 'none', 'mild', 'moderate', 'severe'],
//     optResult: ['', 'normal', 'mild TR', 'moderate TR', 'severe TR'],
//     optComment: ['', '', 'mild TR', 'moderate TR', 'severe TR'],
//     anatomic_group: 'TV',
//     functional_groups: ['TV_disease', 'PA_pressure', 'PH_probability'],
//   },
//   TR_vel: {
//     keywordID: 'TR_vel',
//     keywordName: 'TR Velocity',
//     section: 'SpectralDoppler',
//     group: 'TV',
//     testType: 'range',
//     unit: 'm/s',
//     thresholds: [3],
//     optResult: ['normal', 'increase'],
//     optComment: ['', 'increased PA pressure?'],
//     anatomic_group: 'TV',
//     functional_groups: ['PA_pressure', 'PH_probability', 'TV_disease'],
//   },
//   TRPG: {
//     keywordID: 'TRPG',
//     keywordName: 'TR PG',
//     section: 'SpectralDoppler',
//     group: 'TV',
//     testType: 'calculated',
//     unit: 'mmHg',
//     formula: 'PG',
//     dependencies: ['TR_vel'],
//     thresholds: [],
//     optResult: [],
//     optComment: [],
//     anatomic_group: 'TV',
//     functional_groups: ['PA_pressure', 'PH_probability'],
//   },
//   PA_velocity: {
//     keywordID: 'PA_velocity',
//     keywordName: 'PA Velocity',
//     section: 'SpectralDoppler',
//     group: 'PA',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow'],
//   },
//   PR: {
//     keywordID: 'PR',
//     keywordName: 'PA Regurgitation',
//     section: 'SpectralDoppler',
//     group: 'PA',
//     testType: 'select',
//     options: ['', 'none', 'mild', 'moderate', 'severe'],
//     optResult: ['', 'normal', 'mild PR', 'moderate PR', 'severe PR'],
//     optComment: ['', '', 'mild PR', 'moderate PR', 'severe PR'],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   PR_vel: {
//     keywordID: 'PR_vel',
//     keywordName: 'PR Velocity',
//     section: 'SpectralDoppler',
//     group: 'PA',
//     testType: 'range',
//     unit: 'm/s',
//     thresholds: [2.5],
//     optResult: ['normal', 'increase'],
//     optComment: ['', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_pressure', 'PA_flow', 'PH_probability'],
//   },
//   PRPG: {
//     keywordID: 'PRPG',
//     keywordName: 'PR PG',
//     section: 'SpectralDoppler',
//     group: 'PA',
//     testType: 'calculated',
//     unit: 'mmHg',
//     formula: 'PG',
//     dependencies: ['PR_vel'],
//     thresholds: [],
//     optResult: [],
//     optComment: [],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_pressure'],
//   },
//   AV_velocity: {
//     keywordID: 'AV_velocity',
//     keywordName: 'AV Velocity',
//     section: 'SpectralDoppler',
//     group: 'AV',
//     testType: 'range',
//     unit: 'm/s',
//     thresholds: [1.5, 2.2, 3.5, 4.5],
//     optResult: ['decrease', 'normal', 'mild increase', 'moderate increase', 'severe increase'],
//     optComment: ['Systolic Dysfunction? hypovolemic?', 'normal', 'SAS?', 'SAS susp.', 'SAS susp.'],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease', 'LV_systolic'],
//   },
//   AR: {
//     keywordID: 'AR',
//     keywordName: 'AR Regurgitation',
//     section: 'SpectralDoppler',
//     group: 'AV',
//     testType: 'select',
//     options: ['', 'none', 'mild', 'moderate', 'severe'],
//     optResult: ['', 'normal', 'mild AR', 'moderate AR', 'severe AR'],
//     optComment: ['', '', 'mild AR', 'moderate AR', 'severe AR'],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   AR_vel: {
//     keywordID: 'AR_vel',
//     keywordName: 'AR Velocity',
//     section: 'SpectralDoppler',
//     group: 'AV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   ARPG: {
//     keywordID: 'ARPG',
//     keywordName: 'AR PG',
//     section: 'SpectralDoppler',
//     group: 'AV',
//     testType: 'calculated',
//     unit: 'mmHg',
//     formula: 'PG',
//     dependencies: ['AR_vel'],
//     thresholds: [],
//     optResult: [],
//     optComment: [],
//     anatomic_group: 'AO',
//     functional_groups: ['AV_disease'],
//   },
//   CVCcollapse: {
//     keywordID: 'CVCcollapse',
//     keywordName: 'CVC collapse',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'select',
//     options: ['', '<20%', '20-50%', '>50%'],
//     optResult: ['', 'RA pressure < 5mmHg', 'RA pressure 10mmHg', 'RA pressure > 15mmHg'],
//     optComment: ['', '', '', ''],
//     anatomic_group: 'RA',
//     functional_groups: ['PA_pressure', 'PH_probability', 'RV_function'],
//   },
//   RApressure: {
//     keywordID: 'RApressure',
//     keywordName: 'RA pressure',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'calculated',
//     unit: 'mmHg',
//     formula: 'RApressure',
//     dependencies: ['CVCcollapse'],
//     thresholds: [6, 15],
//     optResult: ['decrease or normal', 'mild ~ moderate increase', 'marked increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'RA',
//     functional_groups: ['PA_pressure', 'PH_probability'],
//   },
//   PApressure: {
//     keywordID: 'PApressure',
//     keywordName: 'PA pressure',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'calculated',
//     unit: 'mmHg',
//     formula: 'PApressure',
//     dependencies: ['RApressure', 'TRPG'],
//     thresholds: [25, 50, 76],
//     optResult: ['normal', 'mild increase', 'moderate increase', 'marked increase'],
//     optComment: ['normal', 'PH grade(Mild)', 'PH grade(Moderate)', 'PH grade(Severe)'],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_pressure', 'PH_probability'],
//   },
//   AT: {
//     keywordID: 'AT',
//     keywordName: 'AT',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'range',
//     unit: '',
//     thresholds: [58],
//     optResult: ['decrease', 'normal'],
//     optComment: ['', 'normal'],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   ET: {
//     keywordID: 'ET',
//     keywordName: 'ET',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'range',
//     unit: '',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow'],
//   },
//   ATET: {
//     keywordID: 'ATET',
//     keywordName: 'AT/ET',
//     section: 'Pulmonary_Hypertension',
//     group: 'Pulmonary_Hypertension',
//     testType: 'calculated',
//     unit: '',
//     formula: 'ATET',
//     dependencies: ['AT', 'ET'],
//     thresholds: [0.3, 0.5],
//     optResult: ['decrease', 'normal', 'increase'],
//     optComment: ['', '', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   SD_comment: {
//     keywordID: 'SD_comment',
//     keywordName: 'Spectral Doppler Comment',
//     section: 'SpectralDoppler',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: [],
//   },
//   PH_comment: {
//     keywordID: 'PH_comment',
//     keywordName: 'PH Comment',
//     section: 'SpectralDoppler',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: ['PH_probability'],
//   },

//   // ============================================================
//   // TDI 섹션
//   // ============================================================
//   Sm: {
//     keywordID: 'Sm',
//     keywordName: 'TDI Sm',
//     section: 'TDI',
//     group: 'MV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'TDI',
//     functional_groups: ['LV_systolic'],
//   },
//   Em: {
//     keywordID: 'Em',
//     keywordName: 'TDI Em',
//     section: 'TDI',
//     group: 'MV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'TDI',
//     functional_groups: ['LV_diastolic', 'LA_pressure'],
//   },
//   Am: {
//     keywordID: 'Am',
//     keywordName: 'TDI Am',
//     section: 'TDI',
//     group: 'MV',
//     testType: 'other',
//     unit: 'm/s',
//     anatomic_group: 'TDI',
//     functional_groups: ['LV_diastolic'],
//   },
//   EmAm: {
//     keywordID: 'EmAm',
//     keywordName: 'Em/Am',
//     section: 'TDI',
//     group: 'MV',
//     testType: 'calculated',
//     unit: '',
//     formula: 'EmAm',
//     dependencies: ['Em', 'Am'],
//     thresholds: [1],
//     optResult: ['normal', 'increase'],
//     optComment: ['normal', 'Impaired Relaxation'],
//     anatomic_group: 'TDI',
//     functional_groups: ['LV_diastolic'],
//   },
//   EEm: {
//     keywordID: 'EEm',
//     keywordName: 'E/Em',
//     section: 'TDI',
//     group: 'MV',
//     testType: 'calculated',
//     unit: '',
//     formula: 'EEm',
//     dependencies: ['MV_Ewave', 'Em'],
//     thresholds: [6, 9, 12],
//     optResult: ['normal', 'increase', 'increase', 'increase'],
//     optComment: ['normal', 'increased LA pressure(??)', 'increased LA pressure(>20mmHg)', 'CHF risk'],
//     anatomic_group: 'TDI',
//     functional_groups: ['LA_pressure', 'LV_diastolic'],
//   },
//   TDI_comment: {
//     keywordID: 'TDI_comment',
//     keywordName: 'TDI Comment',
//     section: 'TDI',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: [],
//   },
//   Last_comment: {
//     keywordID: 'Last_comment',
//     keywordName: 'General Review',
//     section: 'TDI',
//     group: 'Comment',
//     testType: 'textcomment',
//     anatomic_group: 'General',
//     functional_groups: [],
//   },

//   // ============================================================
//   // PH Possibility 섹션
//   // ============================================================
//   SystolicNotch: {
//     keywordID: 'SystolicNotch',
//     keywordName: 'Systolic Notching',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'none', 'yes'],
//     optComment: ['', '', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   RPAmax: {
//     keywordID: 'RPAmax',
//     keywordName: 'RPA max',
//     section: 'Pulmonary_Hypertension',
//     group: 'RPADi',
//     testType: 'range',
//     unit: 'mm',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow'],
//   },
//   RPAmin: {
//     keywordID: 'RPAmin',
//     keywordName: 'RPA min',
//     section: 'Pulmonary_Hypertension',
//     group: 'RPADi',
//     testType: 'range',
//     unit: 'mm',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow'],
//   },
//   RPADi: {
//     keywordID: 'RPADi',
//     keywordName: 'RPADi',
//     section: 'Pulmonary_Hypertension',
//     group: 'RPADi',
//     testType: 'calculated',
//     unit: '%',
//     formula: 'RPADi',
//     dependencies: ['RPAmax', 'RPAmin'],
//     thresholds: [30],
//     optResult: ['decrease', 'normal'],
//     optComment: ['', ''],
//     anatomic_group: 'PA',
//     functional_groups: ['PA_flow', 'PH_probability'],
//   },
//   MINE_LAAO: {
//     keywordID: 'MINE_LAAO',
//     keywordName: 'MINE_SCORE LA/AO ratio',
//     section: 'MINE_SCORE',
//     group: 'MINE_SCORE',
//     testType: 'calculated',
//     unit: '',
//     formula: 'MINE_LAAO',
//     dependencies: ['LAAOratio'],
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'LA',
//     functional_groups: ['MMVD_staging'],
//   },
//   MINE_LVIDDN: {
//     keywordID: 'MINE_LVIDDN',
//     keywordName: 'MINE_SCORE LVIDDN',
//     section: 'MINE_SCORE',
//     group: 'MINE_SCORE',
//     testType: 'calculated',
//     unit: '',
//     formula: 'MINE_LVIDDN',
//     dependencies: ['LVIDDN'],
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'LV',
//     functional_groups: ['MMVD_staging'],
//   },
//   MINE_FS: {
//     keywordID: 'MINE_FS',
//     keywordName: 'MINE_SCORE FS',
//     section: 'MINE_SCORE',
//     group: 'MINE_SCORE',
//     testType: 'calculated',
//     unit: '',
//     formula: 'MINE_FS',
//     dependencies: ['LVFS'],
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'LV',
//     functional_groups: ['MMVD_staging'],
//   },
//   MINE_Ewave: {
//     keywordID: 'MINE_Ewave',
//     keywordName: 'MINE_SCORE Ewave',
//     section: 'MINE_SCORE',
//     group: 'MINE_SCORE',
//     testType: 'calculated',
//     unit: '',
//     formula: 'MINE_Ewave',
//     dependencies: ['MV_Ewave'],
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     anatomic_group: 'MV',
//     functional_groups: ['MMVD_staging'],
//   },
//   MINE_score: {
//     keywordID: 'MINE_score',
//     keywordName: 'MINE_SCORE',
//     section: 'MINE_SCORE',
//     group: 'MINE_SCORE',
//     testType: 'calculated',
//     unit: '',
//     formula: 'MINE_score',
//     dependencies: ['MINE_LAAO', 'MINE_LVIDDN', 'MINE_FS', 'MINE_Ewave'],
//     thresholds: [4, 6, 8, 13],
//     optResult: ['Normal', 'Mild', 'Moderate', 'Severe', 'Late stage'],
//     optComment: ['', '', '', '', ''],
//     anatomic_group: 'General',
//     functional_groups: ['MMVD_staging'],
//   },
//   decreasedSizeOfLV: {
//     keywordID: 'decreasedSizeOfLV',
//     keywordName: 'Decreased size of LV',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site1',
//     testType: 'calculated_string',
//     unit: '',
//     thresholds: [''],
//     optResult: [''],
//     optComment: [''],
//     formula: 'decreasedSizeOfLV',
//     dependencies: ['LVd', 'BW_kg'],
//     anatomic_group: 'LV',
//     functional_groups: ['LV_size', 'PH_probability'],
//   },
//   RVhypertrophy: {
//     keywordID: 'RVhypertrophy',
//     keywordName: 'RV hypertrophy',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site1',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'none', 'yes'],
//     optComment: ['', '', ''],
//     anatomic_group: 'RV',
//     functional_groups: ['RV_function', 'PH_probability'],
//   },
//   RVsystolicDysfunction: {
//     keywordID: 'RVsystolicDysfunction',
//     keywordName: 'RV systolic dysfunction',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site1',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'none', 'yes'],
//     optComment: ['', '', ''],
//     anatomic_group: 'RV',
//     functional_groups: ['RV_function', 'PH_probability'],
//   },
//   RAenlargement: {
//     keywordID: 'RAenlargement',
//     keywordName: 'RA enlargement',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site3',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'none', 'yes'],
//     optComment: ['', '', ''],
//     anatomic_group: 'RA',
//     functional_groups: ['RV_function', 'PH_probability'],
//   },
//   CVCenlargement: {
//     keywordID: 'CVCenlargement',
//     keywordName: 'CVC enlargement',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site3',
//     testType: 'select',
//     options: ['', 'none', 'yes'],
//     optResult: ['', 'none', 'yes'],
//     optComment: ['', '', ''],
//     anatomic_group: 'RA',
//     functional_groups: ['RV_function', 'PH_probability'],
//   },
//   anatomic_PAAO: {
//     keywordID: 'anatomic_PAAO',
//     keywordName: 'Pulmonary artery enlargement',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'calculated_string',
//     unit: '',
//     thresholds: [''],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_PAAO',
//     dependencies: ['PAAO'],
//     anatomic_group: 'PA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_PR_vel: {
//     keywordID: 'anatomic_PR_vel',
//     keywordName: 'PR velocity > 2.5',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'calculated_string',
//     unit: '',
//     thresholds: [''],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_PR_vel',
//     dependencies: ['PR_vel'],
//     anatomic_group: 'PA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_RPADi: {
//     keywordID: 'anatomic_RPADi',
//     keywordName: 'RPADi < 30%',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'calculated_string',
//     unit: '',
//     thresholds: [''],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_RPADi',
//     dependencies: ['RPADi'],
//     anatomic_group: 'PA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_AT: {
//     keywordID: 'anatomic_AT',
//     keywordName: 'AT < 52',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'calculated_string',
//     unit: '',
//     thresholds: [''],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_AT',
//     dependencies: ['AT'],
//     anatomic_group: 'PA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_ATET: {
//     keywordID: 'anatomic_ATET',
//     keywordName: 'AT/ET < 0.3',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'calculated_string',
//     unit: '',
//     thresholds: [''],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_ATET',
//     dependencies: ['ATET'],
//     anatomic_group: 'PA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_number1: {
//     keywordID: 'anatomic_number1',
//     keywordName: 'Number of anatomic sites1',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site1',
//     testType: 'calculated',
//     unit: '',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_number1',
//     dependencies: ['IVS_flattening', 'decreasedSizeOfLV', 'RVhypertrophy', 'RVsysolicDysfunction'],
//     anatomic_group: 'RV',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_number2: {
//     keywordID: 'anatomic_number2',
//     keywordName: 'Number of anatomic sites2',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site2',
//     testType: 'calculated',
//     unit: '',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_number2',
//     dependencies: ['anatomic_PAAO', 'anatomic_PR_vel', 'anatomic_RPADi', 'anatomic_AT', 'anatomic_ATET', 'SystolicNotch'],
//     anatomic_group: 'PA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_number3: {
//     keywordID: 'anatomic_number3',
//     keywordName: 'Number of anatomic sites3',
//     section: 'PosibilityOfPH',
//     group: 'Anatomic site3',
//     testType: 'calculated',
//     unit: '',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_number3',
//     dependencies: ['RAenlargement', 'CVCenlargement'],
//     anatomic_group: 'RA',
//     functional_groups: ['PH_probability'],
//   },
//   anatomic_number: {
//     keywordID: 'anatomic_number',
//     keywordName: 'Number of anatomic sites',
//     section: 'PosibilityOfPH',
//     group: 'PosibilityOfPH',
//     testType: 'calculated',
//     unit: '',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     formula: 'anatomic_numbertotal',
//     dependencies: ['anatomic_number1', 'anatomic_number2', 'anatomic_number3'],
//     anatomic_group: 'General',
//     functional_groups: ['PH_probability'],
//   },
//   PHprob: {
//     keywordID: 'PHprob',
//     keywordName: 'Probability of PH',
//     section: 'PosibilityOfPH',
//     group: 'PosibilityOfPH',
//     testType: 'calculated',
//     unit: '',
//     thresholds: [],
//     optResult: [''],
//     optComment: [''],
//     formula: 'PHprob',
//     dependencies: ['anatomic_number', 'TR_vel'],
//     anatomic_group: 'General',
//     functional_groups: ['PH_probability'],
//   },
//   ACVIM: {
//     keywordID: 'ACVIM_stage',
//     keywordName: 'ACVIM stage',
//     section: 'ACVIM',
//     group: 'ACVIM',
//     testType: 'select',
//     options: ['', 'A', 'B1', 'B2', 'C', 'D'],
//     optResult: ['', '', '', '', '', ''],
//     optComment: ['', '', '', '', '', ''],
//     anatomic_group: 'General',
//     functional_groups: ['MMVD_staging'],
//   },
// };