import type { EchoTest } from "@/types/echocardio/echocardio-type";

export const ECHO_TESTS_FELINE: Record<string, EchoTest> = {
  // ---- PE ----
  BW_kg: {
    keywordID: 'BW_kg',
    keywordName: 'BW (kg)',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'other',
    unit: 'kg',
    anatomic_groups: ['General'],
    testinfo: "체중은 M-mode 정상 참고치 산출(allometric scaling: Y = a × BW^b)의 기준값으로 사용됩니다. 고양이는 체중에 따라 심장 크기가 달라지므로 반드시 정확한 측정이 필요합니다.",
    functional_groups: ['Physical_Exam', 'LV_size'],
  },
  BP: {
    keywordID: 'BP',
    keywordName: 'Blood Pressure',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'mmHg',
    testref: '80~160',
    thresholds: [80, 160],
    optResult: ['hypotension', 'normal', 'hypertension'],
    optComment: ['전신 저혈압 의심. 쇼크, 심부전, 약물 등 원인 평가 필요', '', '전신 고혈압. 고양이에서 신장질환, 갑상선기능항진증, 부신피질기능항진증 등 원인 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "수축기 혈압 기준. 고양이 정상 160mmHg 미만(white coat 효과 고려). 160mmHg 초과 시 고혈압. 고양이에서 고혈압은 신장질환, 갑상선기능항진증의 이차 합병증으로 흔하며 HCM과 감별 필요.",
    functional_groups: ['Physical_Exam'],
  },
  BT: {
    keywordID: 'BT',
    keywordName: 'Body Temp.',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: '°C',
    testref: '38~39.2',
    thresholds: [38, 39.2],
    optResult: ['hypothermia', 'normal', 'hyperthermia'],
    optComment: ['저체온증. 고양이에서 쇼크, CHF 말기, 패혈증 시 흔함. 예후 불량 신호', '', '발열. 감염, 염증성 질환 등 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "고양이 정상 체온 38.0~39.2°C. 저체온은 고양이 CHF의 불량한 예후 지표로 특히 중요. 심박출량 감소 및 말초 순환 부전을 반영.",
    functional_groups: ['Physical_Exam'],
  },
  HR: {
    keywordID: 'HR',
    keywordName: 'Heart Rate',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'bpm',
    testref: '140~220',
    thresholds: [140, 220],
    optResult: ['bradycardia', 'normal', 'tachycardia'],
    optComment: ['서맥. 고양이에서 방실차단, 미주신경 항진, 말기 심부전, 저체온 등 평가 필요', '', '빈맥. 스트레스(white coat), 통증, HCM, 갑상선기능항진증, 빈혈 등 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "고양이 정상 심박수는 140~220bpm. 고양이는 스트레스(white coat effect)로 병원 내 빈맥이 흔하므로 해석 시 주의. HCM에서 빈맥은 심근 산소 요구량 증가 및 충전 시간 단축으로 예후 악화.",
    functional_groups: ['Physical_Exam'],
  },
  RR: {
    keywordID: 'RR',
    keywordName: 'Respi. Rate',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'rr/min',
    testref: '20~30',
    thresholds: [10, 30, 40, 60],
    optResult: ['hypopnea', 'normal', 'tachypnea', 'tachypnea', 'tachypnea'],
    optComment: ['호흡 감소. 진정, 마취, 신경계 이상 평가 필요', '', '경도 빈호흡. 스트레스, 통증, 폐부종 초기 가능성', '중등도 빈호흡. 폐부종, 흉수, 기흉 등 평가 필요', '심한 빈호흡. CHF 폐부종, 흉수 응급 처치 필요'],
    anatomic_groups: ['General'],
    testinfo: "고양이 정상 호흡수 20~30회/분. 고양이는 안정 시 40회/분 초과 시 CHF로 인한 폐부종 또는 흉수의 중요한 경고 신호. 고양이 CHF의 초기 증상 중 하나.",
    functional_groups: ['Physical_Exam'],
  },
  HS: {
    keywordID: 'HS',
    keywordName: 'Heart Sound',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "심음 청진 소견. 고양이에서 심잡음은 HCM 환자의 약 50%에서 청진되지 않으므로 심잡음 부재가 HCM을 배제하지 않음. Gallop rhythm(S3, S4)은 심부전의 중요한 소견. SAM 동반 시 동적 LVOT 폐쇄 시사.",
    functional_groups: ['Physical_Exam'],
  },
  PE_comment: {
    keywordID: 'PE_comment',
    keywordName: 'P.E. comment',
    species: ['feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "신체검사 전반에 대한 추가 소견 기록란.",
    functional_groups: ['Physical_Exam'],
  },

  // ---- Radio ----
  Radio_comment: {
    keywordID: 'Radio_comment',
    keywordName: 'Radiology comment',
    species: ['feline'],
    sections: ['Radio'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "흉부 방사선 소견 기록란. 고양이에서 폐부종(간질성~폐포성 음영), 흉강 삼출(양측성이 흔함), 심장 크기(VHS), 기관 변위 등을 기록. 고양이 CHF에서 흉수가 폐부종보다 흔함.",
    functional_groups: ['Cardiomegaly'],
  },

  // ---- Bmode: MV ----
  MV_SAM: {
    keywordID: 'MV_SAM',
    keywordName: 'Systolic Anterior Motion (SAM)',
    species: ['feline'],
    sections: ['Bmode', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'SAM present'],
    optComment: ['', '', '동적 LVOT 폐쇄 시사. HCM에서 흔함. LVOT 혈류 속도 측정 필요. 예후 불량 인자'],
    anatomic_groups: ['MV'],
    testinfo: "수축기 전방 운동(SAM). 고양이 HCM에서 매우 중요한 소견. 승모판 전엽이 수축기에 LVOT를 막아 동적 폐쇄 유발. SAM 존재 시 LVOT 혈류 속도 측정 필수. MR을 동반하는 경우가 많음.",
    functional_groups: ['MV_morphology', 'LV_systolic', 'HCM_evaluation'],
  },
  MV_leafletTipThickening: {
    keywordID: 'MV_leafletTipThickening',
    keywordName: 'MV Leaflet Tip Thickening',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV anterior leaflet tip thickening',
      'MV posterior leaflet tip thickening',
      'MV anterior & posterior leaflet tip thickening',
    ],
    optComment: ['', '', '승모판 변성 시사', '승모판 변성 시사', '승모판 변성 시사'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 첨단부 비후. 고양이에서 개의 MMVD처럼 흔하지 않으나 노령묘에서 관찰 가능. 전엽/후엽/양엽 구분하여 기록.",
    functional_groups: ['MV_morphology'],
  },
  MV_prolapse: {
    keywordID: 'MV_prolapse',
    keywordName: 'MV Prolapse',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV prolapse(anterior)',
      'MV prolapse(posterior)',
      'MV prolapse(anterior & posterior)',
    ],
    optComment: ['', '', 'MR 동반 가능성 평가 필요', 'MR 동반 가능성 평가 필요', 'MR 동반 가능성 평가 필요'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 탈출증. 수축기에 승모판 첨판이 좌심방 방향으로 이탈. 고양이에서 HCM 관련 MR과 감별 필요.",
    functional_groups: ['MV_morphology'],
  },
  MV_flailmovement: {
    keywordID: 'MV_flailmovement',
    keywordName: 'MV Flail Movement',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV flail movement(anterior)',
      'MV flail movement(posterior)',
      'MV flail movement(anterior & posterior)',
    ],
    optComment: ['', '', '건삭 파열 시사. 중증 MR 가능성 높음', '건삭 파열 시사. 중증 MR 가능성 높음', '건삭 파열 시사. 중증 MR 가능성 높음'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 도리깨 운동. 건삭 파열로 첨판이 좌심방으로 완전히 이탈. 고양이에서 드물지만 중증 MR 동반.",
    functional_groups: ['MV_morphology'],
  },

  // ---- Bmode: IVS ----
  IVS_flattening: {
    keywordID: 'IVS_flattening',
    keywordName: 'IVS Flattening',
    species: ['feline'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['IVS'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'IVS flattening present'],
    optComment: ['', '', 'RV 압력/용적 과부하 시사. 폐고혈압 또는 RV enlargement 평가 필요'],
    anatomic_groups: ['RV'],
    testinfo: "심실중격 편평화. RV 압력 또는 용적 과부하 시 단축상에서 IVS가 편평해지거나 역전. 고양이 폐고혈압의 중요한 해부학적 지표.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  IVS_paradoxicalMV: {
    keywordID: 'IVS_paradoxicalMV',
    keywordName: 'IVS Paradoxical Movement',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['IVS'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'paradoxical IVS motion present'],
    optComment: ['', '', 'RV 용적 과부하 또는 전기전도 이상 시사'],
    anatomic_groups: ['RV'],
    testinfo: "심실중격 역설적 운동. 정상적으로 수축기에 LV 방향으로 움직여야 할 IVS가 반대 방향으로 움직이는 현상. RV 용적 과부하, LBBB, 심낭압전 시 관찰.",
    functional_groups: ['RV_function'],
  },

  // ---- Bmode: TV ----
  TV_leafletTipThickening: {
    keywordID: 'TV_leafletTipThickening',
    keywordName: 'TV Leaflet Tip Thickening',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV leaflet tip thickening'],
    optComment: ['', '', 'TVI 시사. TR 동반 여부 확인 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 첨단부 비후. 삼첨판 이형성증(TVI) 시 관찰. TR 동반 여부 및 PA 압력 평가 필요.",
    functional_groups: ['TV_disease'],
  },
  TV_prolapse: {
    keywordID: 'TV_prolapse',
    keywordName: 'TV Prolapse',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV prolapse'],
    optComment: ['', '', 'TVI 시사. TR 중증도 평가 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 탈출증. TVI 또는 이차성 변성 시 관찰. TR velocity로 PA 압력 추정 필요.",
    functional_groups: ['TV_disease'],
  },
  TV_flailmovement: {
    keywordID: 'TV_flailmovement',
    keywordName: 'TV Flail Movement',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV flail movement'],
    optComment: ['', '', '건삭 파열 시사. 중증 TR 가능성 높음'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 도리깨 운동. 건삭 파열로 삼첨판 첨판이 우심방으로 완전히 이탈. 중증 TR 동반 가능성 높음.",
    functional_groups: ['TV_disease'],
  },

  // ---- Bmode: RV ----
  RVhypertrophy: {
    keywordID: 'RVhypertrophy',
    keywordName: 'RV hypertrophy',
    species: ['feline'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['RV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'RV hypertrophy present'],
    optComment: ['', '', '만성 RV 압력 과부하 시사. 폐고혈압, PS 등 원인 평가 필요'],
    anatomic_groups: ['RV'],
    testinfo: "우심실 비대. 만성 압력 과부하(폐고혈압, PS 등)로 인한 우심실 벽 비후. 폐고혈압의 중요한 해부학적 증거.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  RVsystolicDysfunction: {
    keywordID: 'RVsystolicDysfunction',
    keywordName: 'RV systolic dysfunction',
    species: ['feline'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['RV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'RV systolic dysfunction present'],
    optComment: ['', '', '우심실 수축 기능 저하. 폐고혈압 진행 또는 RV 심근병증 평가 필요'],
    anatomic_groups: ['RV'],
    testinfo: "우심실 수축 기능 저하. RV 운동 감소로 평가. 폐고혈압 진행 또는 우심 심근병증 시 관찰.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  RAenlargement: {
    keywordID: 'RAenlargement',
    keywordName: 'RA enlargement',
    species: ['feline'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['RA'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'RA enlargement present'],
    optComment: ['', '', '우심방 압력/용적 증가 시사. TR 또는 폐고혈압 평가 필요'],
    anatomic_groups: ['RA'],
    testinfo: "우심방 확장. TR, 폐고혈압, 우심 심부전 등으로 인한 우심방 압력/용적 증가 시 관찰. 폐고혈압의 해부학적 증거.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  CVCenlargement: {
    keywordID: 'CVCenlargement',
    keywordName: 'CVC enlargement',
    species: ['feline'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['CVC'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'CVC enlargement present'],
    optComment: ['', '', '전신 정맥압 상승 시사. 우심부전, 폐고혈압, 심낭압전 등 평가 필요'],
    anatomic_groups: ['RA'],
    testinfo: "후대정맥(CVC) 확장. 우심방 압력 증가로 인한 정맥 울혈의 지표. CVCcollapse와 함께 평가.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },

  // ---- Bmode: AV ----
  AV_flattening: {
    keywordID: 'AV_flattening',
    keywordName: 'Aortic Valve Flattening',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'AV leaflet flattening present'],
    optComment: ['', '', 'LVOTO 또는 대동맥판 협착 시사. AV velocity 측정 필요'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 첨판 편평화. 대동맥판 협착 또는 LVOT 폐쇄(SAM 포함) 시 수축 중기에 관찰. 고양이 HCM에서 SAM에 의한 동적 LVOTO와 함께 나타날 수 있음.",
    functional_groups: ['AV_disease'],
  },
  AV_poststenoticdilation: {
    keywordID: 'AV_poststenoticdilation',
    keywordName: 'AV Post-stenotic Dilation',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'post-stenotic aortic dilation present'],
    optComment: ['', '', '대동맥 협착의 이차적 변화 시사'],
    anatomic_groups: ['AO'],
    testinfo: "협착 후 대동맥 확장. 대동맥판 협착으로 인한 고속 혈류가 협착 후방 대동맥 벽에 충격을 주어 확장을 일으킴.",
    functional_groups: ['AV_disease'],
  },
  LVOT_obstruction: {
    keywordID: 'LVOT_obstruction',
    keywordName: 'LVOT Obstruction',
    species: ['feline'],
    sections: ['Bmode', 'HCM_Evaluation'],
    groups: ['LVOT'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'LVOT obstruction present'],
    optComment: ['', '', 'HCM 관련 동적 LVOTO(SAM) 또는 고정성 협착 시사. AV velocity 및 PG 측정 필요'],
    anatomic_groups: ['LV'],
    testinfo: "좌심실 유출로 폐쇄. 고양이에서 HCM 관련 SAM에 의한 동적 폐쇄가 가장 흔함. AV velocity 가속 및 turbulence 동반. 도플러로 압력차 측정 필요.",
    functional_groups: ['AV_disease', 'LV_systolic', 'HCM_evaluation'],
  },

  // ---- Bmode: PV ----
  PV_thickening: {
    keywordID: 'PV_thickening',
    keywordName: 'PV Thickening',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'PV thickening present'],
    optComment: ['', '', 'PS 또는 폐동맥판 이형성 시사. PA velocity 측정 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 비후. PS 또는 판막 이형성 시 관찰. 판막 비후와 함께 개방 제한, 협착 후 PA 확장 동반 가능.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PV_changeOfdimension: {
    keywordID: 'PV_changeOfdimension',
    keywordName: 'PV Change of Dimension',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'PV dimension change present'],
    optComment: ['', '', '폐동맥판 개방 또는 폐쇄 이상 시사. 협착 또는 역류 평가 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 크기 변화 이상. 수축기/이완기 판막 크기 변화의 비정상적 패턴. PS 또는 PA 고혈압에서 관찰.",
    functional_groups: ['PA_flow'],
  },

  // ---- Bmode: Effusion ----
  PericardialEffusion: {
    keywordID: 'PericardialEffusion',
    keywordName: 'Pericardial Effusion',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'pericardial effusion present'],
    optComment: ['', '', '심낭 삼출. 고양이에서 종양, 심낭염, FIP 등 원인 평가. 심낭압전 여부 확인'],
    anatomic_groups: ['Pericardium'],
    testinfo: "심낭 삼출. 고양이에서 원인으로 종양(림프종, 중피종), FIP, 심낭염 등. 개보다 심낭압전 빈도는 낮으나 대량 삼출 시 RV/RA 허탈 여부 확인 필요.",
    functional_groups: ['Effusion'],
  },
  PericardialEffusion_vol: {
    keywordID: 'PericardialEffusion_vol',
    keywordName: 'Pericardial Effusion (vol.)',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'other',
    unit: 'ml',
    anatomic_groups: ['Pericardium'],
    testinfo: "심낭 삼출량(ml). 고양이는 개보다 심장이 작으므로 소량의 삼출도 임상적으로 유의할 수 있음. RA/RV diastolic collapse 동반 시 응급 심낭천자 고려.",
    functional_groups: ['Effusion'],
  },
  PleuralEffusion: {
    keywordID: 'PleuralEffusion',
    keywordName: 'Pleural Effusion',
    species: ['feline'],
    sections: ['Bmode','HCM_Evaluation'],
    groups: ['Effusion'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'pleural effusion present'],
    optComment: ['', '', '흉강 삼출. 고양이 CHF에서 폐부종보다 흉수가 더 흔함. 흉수천자로 호흡 증상 즉각 완화 가능'],
    anatomic_groups: ['Pleura'],
    testinfo: "흉강 삼출. 고양이 CHF에서 폐부종보다 흉수(양측성)가 더 흔한 증상. 빈호흡과 함께 나타나며 CHF의 중요한 징후. 방사선과 병행 평가 권장.",
    functional_groups: ['Effusion', 'HCM_evaluation'],
  },
  PleuralEffusion_vol: {
    keywordID: 'PleuralEffusion_vol',
    keywordName: 'Pleural Effusion (vol.)',
    species: ['feline'],
    sections: ['Bmode','HCM_Evaluation'],
    groups: ['Effusion'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['Pleura'],
    testinfo: "흉강 삼출 깊이(mm). 고양이에서 10mm 초과 시 임상적으로 유의미한 삼출. 고양이 CHF에서 흉수 배출 후 호흡 증상이 극적으로 개선되는 경우가 많음.",
    functional_groups: ['Effusion', 'HCM_evaluation'],
  },
  Bmode_comment: {
    keywordID: 'Bmode_comment',
    keywordName: 'B-mode Comment',
    species: ['feline'],
    sections: ['Bmode'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "B-mode 초음파 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- Mmode: 공통 계산 ----
  LVFS: {
    keywordID: 'LVFS',
    keywordName: 'FS',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'calculated',
    unit: '%',
    testref: '28~55',
    formula: 'LVFS',
    dependencies: ['LVd', 'LVs'],
    thresholds: [28, 55],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 수축 기능 저하. DCM 또는 HCM 말기 시사. 원인 평가 필요', '정상 LV 수축 기능', '과역동성 LV 기능. HCM 초기, 탈수, 빈혈, 교감신경 항진 등 평가'],
    anatomic_groups: ['LV'],
    testinfo: "좌심실 단축 분율(Fractional Shortening). FS = (LVd - LVs) / LVd × 100(%). 고양이 정상 28~55%. 고양이 HCM에서 FS는 정상~증가 소견이 흔하며, 감소는 HCM 말기 또는 DCM 시사.",
    functional_groups: ['LV_systolic', 'HCM_evaluation'],
  },
  EF: {
    keywordID: 'EF',
    keywordName: 'EF',
    species: ['feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'range',
    unit: '%',
    testref: '50~75',
    thresholds: [50, 75],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 수축 기능 저하. HCM 말기 또는 DCM 평가 필요', '정상 LV 수축 기능', '과역동성 LV 기능. HCM 초기, 탈수, 빈혈 등 평가'],
    anatomic_groups: ['LV'],
    testinfo: "박출 분율(Ejection Fraction). 고양이 정상 50~75%. 고양이 HCM에서 EF는 정상~증가가 일반적. 감소 시 HCM 말기(burn-out HCM) 또는 DCM 감별 필요.",
    functional_groups: ['LV_systolic'],
  },
  ESV: {
    keywordID: 'ESV',
    keywordName: 'ESV',
    species: ['feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'other',
    unit: 'ml',
    anatomic_groups: ['LV'],
    testinfo: "수축 말기 용적(End-Systolic Volume). EF 계산에 사용. Teichholz 공식으로 산출. 증가 시 LV 수축 기능 저하 시사.",
    functional_groups: ['LV_systolic', 'LV_size'],
  },
  LAdMax: {
    keywordID: 'LAdMax',
    keywordName: 'LAd Max',
    species: ['feline'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['LA'],
    testinfo: "좌심방 최대 직경. 이완기 말기(승모판 개방 직전) 측정. LA FS 계산에 사용.",
    functional_groups: ['LA_size'],
  },
  LAdMin: {
    keywordID: 'LAdMin',
    keywordName: 'LAd Min',
    species: ['feline'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['LA'],
    testinfo: "좌심방 최소 직경. 수축기 말기(승모판 폐쇄 직전) 측정. LA FS 계산에 사용.",
    functional_groups: ['LA_size'],
  },
  LAFS: {
    keywordID: 'LAFS',
    keywordName: 'LA FS',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['LA FS'],
    testType: 'calculated',
    unit: '%',
    testref: '19~30',
    formula: 'LAFS',
    dependencies: ['LAdMax', 'LAdMin'],
    thresholds: [19, 30],
    optResult: ['decrease', 'decrease', 'normal'],
    optComment: ['CHF 위험 증가. LA 기능 심각한 저하 시사', '좌심방압 증가 시사. 모니터링 강화 필요', '정상'],
    anatomic_groups: ['LA'],
    testinfo: "좌심방 단축 분율(LA Fractional Shortening). FS = (LAdMax - LAdMin) / LAdMax × 100. 고양이에서도 개와 동일한 기준 적용. 19% 미만: CHF 위험, 19~30%: LA 압력 증가 가능성, 30% 이상: 정상.",
    functional_groups: ['LA_size', 'LA_pressure', 'HCM_evaluation'],
  },

  // ---- ColorDoppler ----
  MV_turbulentJet: {
    keywordID: 'MV_turbulentJet',
    keywordName: 'MV Turbulent Jet',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'MV regurgitation jet present'],
    optComment: ['', '', 'MR 존재. 역류 범위(%) 측정으로 중증도 평가 필요. HCM에서 SAM 관련 MR 흔함'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 turbulent jet. 고양이 HCM에서 SAM에 의한 동적 MR이 흔함. 역류 면적/LA 면적 비율로 중증도 평가.",
    functional_groups: ['MV_regurgitation'],
  },
  MV_turbulentJetRange: {
    keywordID: 'MV_turbulentJetRange',
    keywordName: 'MV Turbulent Jet Range',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: '%',
    testref: '<10',
    thresholds: [10, 30, 70],
    optResult: ['normal/trivial', 'mild MR', 'moderate MR', 'severe MR'],
    optComment: ['생리적 역류 또는 없음', '경도 MR. 정기 모니터링 필요', '중등도 MR. LA 크기 변화 추적 필요', '중증 MR. LA 확장, CHF 위험. 치료 고려'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 면적 비율(%). 10% 미만 trivial, 10~30% 경도, 30~70% 중등도, 70% 초과 중증. 고양이 HCM에서 SAM 관련 MR은 동적이므로 심박수 조절 후 재평가 권장.",
    functional_groups: ['MV_regurgitation'],
  },
  TV_turbulentJet: {
    keywordID: 'TV_turbulentJet',
    keywordName: 'TV Turbulent Jet',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV regurgitation jet present'],
    optComment: ['', '', 'TR 존재. TR vel로 PA 압력 추정 가능'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 turbulent jet. TR velocity로 폐동맥압 추정 가능. 스펙트럼 도플러 측정 필수.",
    functional_groups: ['TV_disease'],
  },
  TV_turbulentJetRange: {
    keywordID: 'TV_turbulentJetRange',
    keywordName: 'TV Turbulent Jet Range',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['TV'],
    testType: 'range',
    unit: '%',
    testref: '<10',
    thresholds: [10, 30, 70],
    optResult: ['normal/trivial', 'mild TR', 'moderate TR', 'severe TR'],
    optComment: ['생리적 역류 또는 없음', '경도 TR. TR vel로 PA 압력 추정 권장', '중등도 TR. RA 확장 평가 필요', '중증 TR. RA/RV 확장, 우심부전 가능성'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 면적 비율(%). 10% 미만 trivial, 10~30% 경도, 30~70% 중등도, 70% 초과 중증. TR 존재 시 TR velocity로 PA 압력 추정 필수.",
    functional_groups: ['TV_disease'],
  },
  AV_turbulentJet: {
    keywordID: 'AV_turbulentJet',
    keywordName: 'AV Turbulent Jet',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'AV turbulent jet present'],
    optComment: ['', '', 'LVOTO(SAM) 또는 대동맥판 협착, AR 시사. AV velocity 측정 필요'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 turbulent jet. 고양이 HCM에서 SAM에 의한 동적 LVOTO로 인한 LVOT turbulence가 흔함. AV velocity와 SAM 유무 병행 평가.",
    functional_groups: ['AV_disease'],
  },
  PV_turbulentJet: {
    keywordID: 'PV_turbulentJet',
    keywordName: 'PV Turbulent Jet',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'PV turbulent jet present'],
    optComment: ['', '', 'PS 또는 PR 시사. PA velocity 및 PR vel 측정 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 turbulent jet. PS 또는 PR로 인한 난류 혈류. PA velocity와 PR vel 측정으로 병변 구분 및 중증도 평가.",
    functional_groups: ['PA_flow'],
  },
  CD_comment: {
    keywordID: 'CD_comment',
    keywordName: 'Color Doppler Comment',
    species: ['feline'],
    sections: ['ColorDoppler'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "컬러 도플러 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- SpectralDoppler: MV ----
  MV_Ewave: {
    keywordID: 'MV_Ewave',
    keywordName: 'MV E Wave',
    species: ['feline'],
    sections: ['SpectralDoppler', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'range',
    unit: 'm/s',
    testref: '<0.8',
    thresholds: [0.8, 1.0],
    optResult: ['normal', 'mild increase', 'increase'],
    optComment: ['정상 LA 압력', 'LA 압력 경도 상승 가능성. 모니터링 강화 필요', 'LA 압력 상승 시사. E/A ratio, IVRT, DT 병행 평가'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 E파. 고양이 정상 <0.8m/s (개보다 낮음). 0.8m/s 이상 시 LA 압력 상승 가능성. 고양이 HCM에서 E wave 증가는 LA 압력 상승을 반영. E/A ratio, IVRT, DT와 병행 평가.",
    functional_groups: ['LA_pressure', 'LV_diastolic', 'MV_regurgitation', 'HCM_evaluation'],
  },
  MV_Awave: {
    keywordID: 'MV_Awave',
    keywordName: 'MV A Wave',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['MV'],
    testinfo: "승모판 A파. 심방 수축에 의한 능동적 혈류 유입 속도. E/A ratio 계산에 사용. 고양이 HCM에서 이완기 기능 장애 시 A파 증가 또는 E/A 역전 가능.",
    functional_groups: ['LV_diastolic'],
  },
  MV_EAratio: {
    keywordID: 'MV_EAratio',
    keywordName: 'MV E:A Ratio',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '1~2',
    formula: 'MV_EAratio',
    dependencies: ['MV_Ewave', 'MV_Awave'],
    thresholds: [1, 2],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['이완기 기능 장애(이완 지연 패턴) 시사', '정상 이완 패턴', 'LA 압력 상승, restrictive 패턴 시사. CHF 위험'],
    anatomic_groups: ['MV'],
    testinfo: "E/A 비율. 고양이 정상 1~2. 1 미만: 이완 지연(이완기 기능 장애), 1~2: 정상, 2 초과: LA 압력 상승(restrictive 패턴). TDI Em과 병행 평가.",
    functional_groups: ['LV_diastolic', 'LA_pressure'],
  },
  IVRT: {
    keywordID: 'IVRT',
    keywordName: 'IVRT',
    species: ['feline'],
    sections: ['SpectralDoppler', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'range',
    unit: 'ms',
    testref: '50~70',
    thresholds: [50, 70],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LA 압력 상승 시사. CHF 위험. E wave 상승 동반 여부 확인', '정상', '이완 지연(impaired relaxation) 시사. HCM 이완기 기능 장애 가능'],
    anatomic_groups: ['LV'],
    testinfo: "등용적 이완 시간. 고양이 정상 50~70ms. 50ms 미만: LA 압력 상승(CHF 위험), 70ms 초과: 이완 지연. 고양이 HCM에서 이완기 기능 장애의 중요한 지표. E/IVRT와 함께 평가.",
    functional_groups: ['LA_pressure', 'LV_diastolic', 'HCM_evaluation'],
  },
  EIVRT: {
    keywordID: 'EIVRT',
    keywordName: 'E/IVRT',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '<2.2',
    formula: 'EIVRT',
    dependencies: ['MV_Ewave', 'IVRT'],
    thresholds: [2.2],
    optResult: ['normal', 'increase'],
    optComment: ['정상 LA 압력', 'LA 압력 상승 시사. CHF 위험 증가. 임상 증상과 병행 평가'],
    anatomic_groups: ['LV'],
    testinfo: "E/IVRT 비율. MV E파(m/s) / IVRT(ms) × 1000. 2.2 초과 시 LA 압력 상승 및 CHF 위험 증가. 고양이 HCM에서 CHF 위험 평가에 활용.",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  DT: {
    keywordID: 'DT',
    keywordName: 'Deceleration Time (DT)',
    species: ['feline'],
    sections: ['SpectralDoppler', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'range',
    unit: 'ms',
    testref: '60~100',
    thresholds: [60, 100],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LA 압력 심각한 상승. restrictive 패턴. CHF 위험 높음', '정상', '이완 지연 가능성'],
    anatomic_groups: ['MV'],
    testinfo: "감속 시간(Deceleration Time). 고양이 정상 60~100ms. 60ms 미만: LA 압력 심각한 상승(restrictive 패턴, CHF 위험). HCM에서 DT 단축은 불량한 예후 지표.",
    functional_groups: ['LA_pressure', 'LV_diastolic', 'HCM_evaluation'],
  },
  MR: {
    keywordID: 'MR',
    keywordName: 'MV Regurgitation',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no MR', 'mild MR', 'moderate MR', 'severe MR'],
    optComment: ['', '정상', '경도 MR. 정기 모니터링', '중등도 MR. LA 크기 추적 필요', '중증 MR. CHF 위험. 치료 고려'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 중증도. 고양이에서 HCM 관련 SAM에 의한 동적 MR이 흔함. 동적 MR은 심박수 감소 시 개선될 수 있음. 컬러 도플러 jet 범위와 MR velocity 종합 평가.",
    functional_groups: ['MV_regurgitation'],
  },
  MR_vel: {
    keywordID: 'MR_vel',
    keywordName: 'MR Velocity',
    species: ['feline'],
    sections: ['SpectralDoppler', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 속도. 수축기 MR jet의 최고 속도. MR PG 계산에 사용(PG = 4V²). 고양이 정상 범위 4~6m/s. 속도 감소는 LV 수축 기능 저하 또는 LA 압력 상승 시사.",
    functional_groups: ['MV_regurgitation'],
  },
  MRPG: {
    keywordID: 'MRPG',
    keywordName: 'MR PG',
    species: ['feline'],
    sections: ['SpectralDoppler', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['MR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 압력차(MR PG). Bernoulli 공식(PG = 4V²)으로 계산. 수축기 LV-LA 압력차를 반영. 감소 시 LV 수축력 저하 또는 LA 압력 상승 시사.",
    functional_groups: ['MV_regurgitation','HCM_evaluation'],
  },

  // ---- SpectralDoppler: TV ----
  TV_Ewave: {
    keywordID: 'TV_Ewave',
    keywordName: 'TV E Wave',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 E파. 이완 초기 RV로 유입되는 혈류 속도. RV 이완 기능 및 RA 압력 평가에 활용.",
    functional_groups: ['TV_disease', 'RV_function'],
  },
  TR: {
    keywordID: 'TR',
    keywordName: 'TR Regurgitation',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no TR', 'mild TR', 'moderate TR', 'severe TR'],
    optComment: ['', '정상', '경도 TR. TR vel로 PA 압력 추정', '중등도 TR. RA 확장 평가 필요', '중증 TR. RA/RV 확장, 우심부전 가능성'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 중증도. TR velocity로 PA 압력 추정 가능(TRPG + RA pressure = 수축기 PA 압력). 고양이 폐고혈압 평가의 핵심 지표.",
    functional_groups: ['TV_disease', 'PA_pressure', 'Pulmonary_Hypertension'],
  },
  TR_vel: {
    keywordID: 'TR_vel',
    keywordName: 'TR Velocity',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'range',
    unit: 'm/s',
    testref: '<3.0',
    thresholds: [3],
    optResult: ['normal', 'increase'],
    optComment: ['정상 범위. PA 압력 정상 추정', 'PA 압력 상승 가능성 시사. TRPG + RApressure로 수축기 PA 압력 계산 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 최고 속도. 3.0m/s 초과 시 PA 압력 상승 의심. 수축기 PA 압력 = TRPG(4×TR_vel²) + RA 압력. 고양이 폐고혈압 선별의 핵심 지표.",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension', 'TV_disease'],
  },
  TRPG: {
    keywordID: 'TRPG',
    keywordName: 'TR PG',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['TR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 압력차(TR PG). Bernoulli 공식(PG = 4V²)으로 계산. RA 압력을 더하면 수축기 PA 압력 추정 가능(PA pressure = TRPG + RApressure).",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },

  // ---- SpectralDoppler: PA ----
  PA_velocity: {
    keywordID: 'PA_velocity',
    keywordName: 'PA Velocity',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['PA'],
    testinfo: "폐동맥 혈류 최고 속도. 정상 약 0.9~1.2m/s. 증가 시 PS 또는 폐혈류 증가 시사. AT/ET 비율 계산과 함께 폐고혈압 평가에 활용.",
    functional_groups: ['PA_flow'],
  },
  PR: {
    keywordID: 'PR',
    keywordName: 'PA Regurgitation',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no PR', 'mild PR', 'moderate PR', 'severe PR'],
    optComment: ['', '정상 또는 생리적 미량 역류', '경도 PR. PR vel로 이완기 PA 압력 추정', '중등도 PR. RV 용적 과부하 평가 필요', '중증 PR. RV 확장 가능성'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 역류 중증도. PR velocity로 이완기 PA 압력 추정 가능. 경도 PR은 생리적일 수 있으나 중등도 이상은 PA 고혈압 또는 RV 과부하 시사.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PR_vel: {
    keywordID: 'PR_vel',
    keywordName: 'PR Velocity',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'range',
    unit: 'm/s',
    testref: '<2.5',
    thresholds: [2.5],
    optResult: ['normal', 'increase'],
    optComment: ['이완기 PA 압력 정상 범위', '이완기 PA 압력 상승 시사. PRPG + RApressure로 이완기 PA 압력 추정'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 역류 최고 속도. 2.5m/s 초과 시 이완기 PA 압력 상승 시사. 이완기 PA 압력 = PRPG + RA 압력.",
    functional_groups: ['PA_pressure', 'PA_flow', 'Pulmonary_Hypertension'],
  },
  PRPG: {
    keywordID: 'PRPG',
    keywordName: 'PR PG',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['PR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 역류 압력차(PR PG). Bernoulli 공식(PG = 4V²)으로 계산. RA 압력을 더하면 이완기 PA 압력 추정 가능.",
    functional_groups: ['PA_pressure'],
  },

  // ---- SpectralDoppler: AV ----
  AV_velocity: {
    keywordID: 'AV_velocity',
    keywordName: 'AV Velocity',
    species: ['feline'],
    sections: ['SpectralDoppler', 'HCM_Evaluation'],
    groups: ['AV'],
    testType: 'range',
    unit: 'm/s',
    testref: '0.9~1.7',
    thresholds: [0.9, 1.7, 3.0, 4.5],
    optResult: ['decrease', 'normal', 'mild increase', 'moderate increase', 'severe increase'],
    optComment: [
      'LV 수축 기능 저하 또는 저혈량증 시사',
      '정상',
      '동적 LVOTO(SAM) 또는 경미한 대동맥 협착 가능성',
      'LVOTO 또는 대동맥 협착 의심. SAM 유무 확인',
      'LVOTO 또는 대동맥 협착 확진 수준. 즉각적 평가 필요',
    ],
    anatomic_groups: ['AO'],
    testinfo: "대동맥 혈류 최고 속도. 고양이 정상 0.9~1.7m/s. 증가 시 고양이 HCM 관련 SAM에 의한 동적 LVOTO가 가장 흔한 원인. 고정성 대동맥 협착과 감별 필요. Bernoulli 공식으로 압력차 계산.",
    functional_groups: ['AV_disease', 'LV_systolic', 'HCM_evaluation'],
  },
  AR: {
    keywordID: 'AR',
    keywordName: 'AR Regurgitation',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no AR', 'mild AR', 'moderate AR', 'severe AR'],
    optComment: ['', '정상', '경도 AR. 정기 모니터링', '중등도 AR. LV 확장 평가 필요', '중증 AR. LV 용적 과부하'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 역류 중증도. LV 용적 과부하 유발. AR vel로 이완기 대동맥-LV 압력차 추정.",
    functional_groups: ['AV_disease'],
  },
  AR_vel: {
    keywordID: 'AR_vel',
    keywordName: 'AR Velocity',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 역류 최고 속도. 이완기 대동맥-LV 압력차를 반영. AR PG 계산에 사용.",
    functional_groups: ['AV_disease'],
  },
  ARPG: {
    keywordID: 'ARPG',
    keywordName: 'AR PG',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['AR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 역류 압력차(AR PG). Bernoulli 공식(PG = 4V²)으로 계산. 이완기 대동맥-LV 압력차를 반영.",
    functional_groups: ['AV_disease'],
  },
  SD_comment: {
    keywordID: 'SD_comment',
    keywordName: 'Spectral Doppler Comment',
    species: ['feline'],
    sections: ['SpectralDoppler'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "스펙트럼 도플러 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- PH 공통 ----
  CVCcollapse: {
    keywordID: 'CVCcollapse',
    keywordName: 'CVC collapse',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'select',
    options: ['', '<20%', '20-50%', '>50%'],
    optResult: ['', 'RA pressure elevated (>15mmHg)', 'RA pressure 10mmHg', 'RA pressure < 5mmHg'],
    optComment: ['', 'RA 압력 심각한 상승. 우심부전 또는 폐고혈압 진행', 'RA 압력 중등도 상승', 'RA 압력 정상 또는 경도 상승'],
    anatomic_groups: ['RA'],
    testinfo: "후대정맥 허탈률. 흡기 시 CVC 직경 감소 비율로 RA 압력 간접 추정. 20% 미만: RA 압력 >15mmHg(높음), 20~50%: 약 10mmHg(중등도), 50% 초과: <5mmHg(정상).",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension', 'RV_function'],
  },
  RApressure: {
    keywordID: 'RApressure',
    keywordName: 'RA pressure',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: 'mmHg',
    testref: '<6',
    formula: 'RApressure',
    dependencies: ['CVCcollapse'],
    thresholds: [6, 15],
    optResult: ['normal', 'mild~moderate increase', 'marked increase'],
    optComment: ['정상 RA 압력', 'RA 압력 경도~중등도 상승. 우심부전 초기 또는 폐고혈압 시사', 'RA 압력 심각한 상승. 진행된 우심부전 또는 폐고혈압'],
    anatomic_groups: ['RA'],
    testinfo: "CVC 허탈률로 추정한 우심방 압력. 수축기 PA 압력 계산(PA pressure = TRPG + RApressure)의 핵심 변수. 6mmHg 미만 정상, 6~15mmHg 중등도 상승, 15mmHg 초과 심각한 상승.",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },
  PApressure: {
    keywordID: 'PApressure',
    keywordName: 'PA pressure',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: 'mmHg',
    testref: '<25',
    formula: 'PApressure',
    dependencies: ['RApressure', 'TRPG'],
    thresholds: [25, 50, 76],
    optResult: ['normal', 'mild PH', 'moderate PH', 'severe PH'],
    optComment: ['정상 PA 압력', '경도 폐고혈압(Grade I)', '중등도 폐고혈압(Grade II)', '중증 폐고혈압(Grade III). 적극적 치료 필요'],
    anatomic_groups: ['PA'],
    testinfo: "수축기 폐동맥압 추정값. 공식: PA pressure = TRPG + RA pressure. 25mmHg 미만 정상, 25~50mmHg 경도 PH, 50~76mmHg 중등도 PH, 76mmHg 초과 중증 PH.",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },
  PA: {
    keywordID: 'PA',
    keywordName: 'PA',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['PA'],
    testinfo: "주폐동맥 직경(mm). PA/AO ratio 계산에 사용. 단독 값보다 AO 직경과의 비율(PA/AO)로 평가.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PAAO: {
    keywordID: 'PAAO',
    keywordName: 'PA/AO',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: '',
    testref: '<1.0',
    formula: 'PAAO',
    dependencies: ['PA', 'AO'],
    thresholds: [1],
    optResult: ['normal', 'PA enlargement'],
    optComment: ['정상 PA 직경', 'PA 확장 시사. 폐고혈압 또는 폐혈류 증가 평가 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥/대동맥 직경 비율. 1.0 초과 시 PA 확장 시사. 폐고혈압의 해부학적 지표. 정상에서는 PA와 AO가 거의 동일한 직경.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  AT: {
    keywordID: 'AT',
    keywordName: 'AT',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'ms',
    testref: '≥58',
    thresholds: [58],
    optResult: ['decrease', 'normal'],
    optComment: ['PA 압력 상승 시사. AT/ET 비율 계산 필요', '정상 PA 압력 시사'],
    anatomic_groups: ['PA'],
    testinfo: "가속 시간(Acceleration Time). PA 혈류 시작부터 최고 속도까지의 시간. 58ms 미만 시 PA 압력 상승 시사. AT/ET 비율과 함께 폐고혈압 선별에 활용.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  ET: {
    keywordID: 'ET',
    keywordName: 'ET',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'ms',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "박출 시간(Ejection Time). PA 혈류 시작부터 끝까지의 시간. AT/ET 비율 계산에 사용. 단독으로는 임상적 의의 제한적.",
    functional_groups: ['PA_flow'],
  },
  ATET: {
    keywordID: 'ATET',
    keywordName: 'AT/ET',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: '',
    testref: '0.3~0.5',
    formula: 'ATET',
    dependencies: ['AT', 'ET'],
    thresholds: [0.3, 0.5],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['PA 압력 상승 시사. 폐고혈압 가능성 높음', '정상 PA 압력 범위', '정상 또는 폐혈류 감소 가능성'],
    anatomic_groups: ['PA'],
    testinfo: "AT/ET 비율. 0.3 미만: PA 압력 상승(폐고혈압 가능성 높음), 0.3~0.5: 정상 범위. Systolic notch 동반 시 폐고혈압 가능성 더욱 증가.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  SystolicNotch: {
    keywordID: 'SystolicNotch',
    keywordName: 'Systolic Notching',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension', 'PosibilityOfPH'],
    groups: ['PA'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'systolic notch present'],
    optComment: ['', '정상', 'PA 혈류의 수축기 중기 역전. 폐고혈압의 강력한 시사 소견'],
    anatomic_groups: ['PA'],
    testinfo: "PA 혈류의 수축기 노치. 수축기 중기에 혈류가 일시적으로 역전되거나 감소하는 패턴. 폐혈관 저항 증가(폐고혈압)의 강력한 지표.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  RPAmax: {
    keywordID: 'RPAmax',
    keywordName: 'RPA max',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 최대 직경(mm). 흡기 시 측정. RPADi 계산에 사용.",
    functional_groups: ['PA_flow'],
  },
  RPAmin: {
    keywordID: 'RPAmin',
    keywordName: 'RPA min',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 최소 직경(mm). 호기 시 측정. RPADi 계산에 사용.",
    functional_groups: ['PA_flow'],
  },
  RPADi: {
    keywordID: 'RPADi',
    keywordName: 'RPADi',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'calculated',
    unit: '%',
    testref: '≥30',
    formula: 'RPADi',
    dependencies: ['RPAmax', 'RPAmin'],
    thresholds: [30],
    optResult: ['decrease', 'normal'],
    optComment: ['폐혈관 순응도 감소 시사. 폐고혈압 가능성', '정상 폐혈관 순응도'],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 직경 변동지수(RPADi). RPADi = (RPAmax - RPAmin) / RPAmin × 100(%). 30% 미만: 폐혈관 순응도 감소(폐고혈압 시사). 폐고혈압의 해부학적 보조 지표.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },

  anatomic_PAAO: {
    keywordID: 'anatomic_PAAO',
    keywordName: 'Pulmonary artery enlargement',
    species: ['feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_PAAO',
    dependencies: ['PAAO'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_PR_vel: {
    keywordID: 'anatomic_PR_vel',
    keywordName: 'PR velocity > 2.5',
    species: ['feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_PR_vel',
    dependencies: ['PR_vel'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_RPADi: {
    keywordID: 'anatomic_RPADi',
    keywordName: 'RPADi < 30%',
    species: ['feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_RPADi',
    dependencies: ['RPADi'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_AT: {
    keywordID: 'anatomic_AT',
    keywordName: 'AT < 52',
    species: ['feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_AT',
    dependencies: ['AT'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_ATET: {
    keywordID: 'anatomic_ATET',
    keywordName: 'AT/ET < 0.3',
    species: ['feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_ATET',
    dependencies: ['ATET'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number1: {
    keywordID: 'anatomic_number1',
    keywordName: 'Number of anatomic sites1',
    species: ['feline'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number1',
    dependencies: ['IVS_flattening', 'decreasedSizeOfLV', 'RVhypertrophy', 'RVsystolicDysfunction'],
    anatomic_groups: ['RV'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number2: {
    keywordID: 'anatomic_number2',
    keywordName: 'Number of anatomic sites2',
    species: ['feline'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number2',
    dependencies: ['anatomic_PAAO', 'anatomic_PR_vel', 'anatomic_RPADi', 'anatomic_AT', 'anatomic_ATET', 'SystolicNotch'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number3: {
    keywordID: 'anatomic_number3',
    keywordName: 'Number of anatomic sites3',
    species: ['feline'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number3',
    dependencies: ['RAenlargement', 'CVCenlargement'],
    anatomic_groups: ['RA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number: {
    keywordID: 'anatomic_number',
    keywordName: 'Number of anatomic sites',
    species: ['feline'],
    sections: [],
    groups: ['PosibilityOfPH'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_numbertotal',
    dependencies: ['anatomic_number1', 'anatomic_number2', 'anatomic_number3'],
    anatomic_groups: ['General'],
    testinfo: "폐고혈압 시사 소견이 나타난 해부학적 위치(Ventricles, PA, RA/CVC)의 총 개수입니다.",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  PHprob: {
    keywordID: 'PHprob',
    keywordName: 'Probability of PH',
    species: ['feline'],
    sections: [],
    groups: ['PosibilityOfPH'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'PHprob',
    dependencies: ['anatomic_number', 'TR_vel'],
    anatomic_groups: ['General'],
    testinfo: "폐고혈압 확률(Low, Intermediate, High). TR 속도와 해부학적 소견 개수를 종합하여 산출합니다.",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  PH_comment: {
    keywordID: 'PH_comment',
    keywordName: 'PH Comment',
    species: ['feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "폐고혈압 관련 전반적 소견 및 추가 의견 기록란.",
    functional_groups: ['Pulmonary_Hypertension'],
  },

  // ---- TDI 공통 ----
  Sm: {
    keywordID: 'Sm',
    keywordName: 'TDI Sm',
    species: ['feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "조직 도플러(TDI) 수축기 Sm파. 승모판 환상부에서 측정한 수축기 조직 속도. LV 수축 기능의 민감한 지표. 고양이 HCM에서 Sm 감소는 LV 종축 수축 기능 저하를 시사.",
    functional_groups: ['LV_systolic'],
  },
  Em: {
    keywordID: 'Em',
    keywordName: 'TDI Em',
    species: ['feline'],
    sections: ['TDI', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "조직 도플러(TDI) 이완 초기 Em파. 승모판 환상부에서 측정한 이완기 초기 조직 속도. 고양이 HCM에서 이완 기능 저하 시 Em 감소. E/Em(EEm) 계산에 사용.",
    functional_groups: ['LV_diastolic', 'LA_pressure', 'HCM_evaluation'],
  },
  Am: {
    keywordID: 'Am',
    keywordName: 'TDI Am',
    species: ['feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "조직 도플러(TDI) 심방 수축기 Am파. 심방 수축기 조직 속도. Em/Am ratio 계산에 사용. 이완기 기능 장애 시 Am 상대적 증가.",
    functional_groups: ['LV_diastolic'],
  },
  EmAm: {
    keywordID: 'EmAm',
    keywordName: 'Em/Am',
    species: ['feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '<1',
    formula: 'EmAm',
    dependencies: ['Em', 'Am'],
    thresholds: [1],
    optResult: ['normal', 'increase'],
    optComment: ['정상 또는 이완 지연 패턴', '이완 지연(Impaired Relaxation) 시사. HCM 이완기 기능 장애 가능성'],
    anatomic_groups: ['TDI'],
    testinfo: "TDI Em/Am 비율. 1 초과 시 이완 지연(impaired relaxation) 시사. 고양이 HCM에서 이완 기능 평가의 중요한 지표.",
    functional_groups: ['LV_diastolic'],
  },
  EEm: {
    keywordID: 'EEm',
    keywordName: 'E/Em',
    species: ['feline'],
    sections: ['TDI', 'HCM_Evaluation'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '<6',
    formula: 'EEm',
    dependencies: ['MV_Ewave', 'Em'],
    thresholds: [6, 9, 12],
    optResult: ['normal', 'mild increase', 'moderate increase', 'marked increase'],
    optComment: [
      '정상 LA 압력',
      'LA 압력 경도 상승 가능성. 다른 이완 지표와 병행 평가',
      'LA 압력 상승 시사(>20mmHg). CHF 위험',
      'LA 압력 심각한 상승. CHF 위험 높음. 즉각적 평가 필요',
    ],
    anatomic_groups: ['TDI'],
    testinfo: "E/Em 비율. 고양이 LA 충전압 추정에 활용. 6 미만 정상, 6~9 경도 상승, 9~12 중등도 상승(LA 압력 >20mmHg), 12 초과 심각한 상승. 고양이 HCM에서 CHF 위험 예측에 중요.",
    functional_groups: ['LA_pressure', 'LV_diastolic', 'HCM_evaluation'],
  },
  TDI_comment: {
    keywordID: 'TDI_comment',
    keywordName: 'TDI Comment',
    species: ['feline'],
    sections: ['TDI'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "TDI 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },
  
  ACVIM_Feline: {
    keywordID: 'ACVIM_Feline',
    keywordName: 'ACVIM Stage (Feline)',
    species: ['feline'],
    sections: ['General_Review'],
    groups: ['ACVIM'],
    testType: 'select',
    options: ['', 'A', 'B1', 'B2', 'C', 'D'],
    optResult: ['', 'Stage A', 'Stage B1', 'Stage B2', 'Stage C', 'Stage D'],
    optComment: [
      '',
      '심근병증 소인은 있으나 현재 심장 구조적 이상 없음. (예: 특정 품종 스크리닝)',
      '심근병증 진단됨. 심비대(LA 확장)가 없거나 경미함. 낮은 CHF/ATE 위험도.',
      '심근병증 + 중등도 이상의 심비대(LA/Ao > 1.5). CHF 또는 ATE 발생 고위험군.',
      '현재 또는 과거 CHF 증상(폐수종, 흉수) 또는 ATE(혈전증) 병력 존재.',
      '난치성 CHF. 표준 치료(Furosemide 등)에 반응이 불량한 말기 단계.',
    ],
    anatomic_groups: ['General'],
    testinfo: "고양이 ACVIM 심근병증(HCM 등) 병기. B2 기준: LA/Ao > 1.5 또는 LA max > 16mm. B2부터 Clopidogrel 등 항혈전 요법 고려. C단계부터 이뇨제 필수.",
    functional_groups: ['HCM_evaluation'],
  },
  // Last_comment: {
  //   keywordID: 'Last_comment',
  //   keywordName: 'General Review',
  //   species: ['feline'],
  //   sections: ['General_Review'],
  //   groups: ['Test Review'],
  //   testType: 'textcomment',
  //   anatomic_groups: ['General'],
  //   testinfo: "심장 초음파 전체 소견에 대한 종합 평가 및 임상 의견 기록란.",
  //   functional_groups: [],
  // },

  // ---- Radio (고양이 기준) ----
  VHS: {
    keywordID: 'VHS',
    keywordName: 'VHS',
    species: ['feline'],
    sections: ['Radio'],
    groups: ['Thorax'],
    testType: 'range',
    unit: '',
    testref: '7.5~9.3',
    thresholds: [7.5, 9.3],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['microcardia. 저혈량, 탈수 등 평가 필요', '정상 심장 크기', '심비대. HCM, DCM, 심낭 삼출 등 원인 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "척추 심장 점수(VHS). 고양이 정상 7.5~9.3. 9.3 초과 시 심비대 시사. 고양이에서 HCM 선별에 활용되나 민감도가 높지 않아 심초음파 검사가 필수. 흉수 동반 시 심장 크기 평가 제한.",
    functional_groups: ['Cardiomegaly'],
  },

  // ---- Mmode: 고양이 전용 (allometric formula) ----
  VSd: {
    keywordID: 'VSd',
    keywordName: 'IVS-d',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['IVS 두께 감소. 심근 위축 또는 저혈량 가능성', '정상', 'IVS 비후. HCM 진단 기준(≥6mm 또는 체중 보정값 초과) 평가 필요'],
    anatomic_groups: ['LV'],
    testinfo: "이완기 심실중격 두께. 고양이 체중 기반 allometric formula(Y = a x BW^b)로 정상 범위 계산. HCM 진단 기준: IVSd ≥6mm(일부 기준 5.5mm). 체중이 작거나 큰 고양이는 체중 보정값 기준 적용 권장.",
    functional_groups: ['LV_size', 'HCM_evaluation'],
  },
  LVd: {
    keywordID: 'LVd',
    keywordName: 'LV-d(LVIDd)',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 크기 감소. 저혈량, HCM 동반 LV 용적 감소 가능성', '정상', 'LV 확장. DCM 또는 용적 과부하 시사'],
    anatomic_groups: ['LV'],
    testinfo: "이완기 좌심실 내경(LVIDd). 고양이 체중 기반 allometric formula로 정상 범위 계산. HCM에서 LVIDd는 정상~감소 소견이 흔함. 감소 시 HCM으로 인한 LV 내강 협소화 시사.",
    functional_groups: ['LV_size', 'HCM_evaluation'],
  },
  LVWd: {
    keywordID: 'LVWd',
    keywordName: 'LVW-d(LVPWd)',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LVW 두께 감소. 심근 위축 가능성', '정상', 'LVW 비후. HCM 진단 기준(≥6mm) 평가 필요. IVSd와 함께 평가'],
    anatomic_groups: ['LV'],
    testinfo: "이완기 좌심실 후벽 두께(LVPWd). 고양이 체중 기반 allometric formula로 정상 범위 계산. 고양이에서 IVSd가 LVPWd보다 일반적으로 약간 두꺼움(IVSd > LVPWd). HCM 진단: LVPWd ≥6mm(일부 ≥5.5mm).",
    functional_groups: ['LV_size', 'HCM_evaluation'],
  },
  VSs: {
    keywordID: 'VSs',
    keywordName: 'IVS-s',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['IVS 수축기 두께화 감소. 수축 기능 저하 가능성', '정상', ''],
    anatomic_groups: ['LV'],
    testinfo: "수축기 심실중격 두께. 체중 기반 allometric formula로 정상 범위 계산. FS 계산 및 수축 기능 평가에 활용.",
    functional_groups: ['LV_size'],
  },
  LVs: {
    keywordID: 'LVs',
    keywordName: 'LV-s(LVIDs)',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 수축기 내경 감소. 과역동성 또는 HCM으로 인한 내강 협소화', '정상', '수축기 내경 증가. 수축 기능 저하(DCM 또는 HCM 말기) 시사'],
    anatomic_groups: ['LV'],
    testinfo: "수축기 좌심실 내경(LVIDs). FS 계산의 핵심 변수. 고양이 HCM에서 LVIDs는 정상~감소가 흔하며, 증가는 HCM 말기(burn-out) 또는 DCM을 시사.",
    functional_groups: ['LV_size', 'LV_systolic', 'HCM_evaluation'],
  },
  LVWs: {
    keywordID: 'LVWs',
    keywordName: 'LVW-s(LVPWs)',
    species: ['feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 후벽 수축기 두께화 감소. 수축 기능 저하 가능성', '정상', ''],
    anatomic_groups: ['LV'],
    testinfo: "수축기 좌심실 후벽 두께(LVPWs). 체중 기반 allometric formula로 정상 범위 계산. LVW 두께화율 평가에 활용.",
    functional_groups: ['LV_size'],
  },
  AO: {
    keywordID: 'AO',
    keywordName: 'AO',
    species: ['feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['AO 직경 감소. 저혈량 또는 심박출량 감소 가능성', '정상', 'AO 확장. 고혈압 또는 LVOTO 후 확장 가능성'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥 직경(mm). 체중 기반 allometric formula로 정상 범위 계산. LA/AO ratio 계산에 사용. 고양이에서 LA/AO >1.5 시 LA 확장 시사.",
    functional_groups: ['LA_size'],
  },
  LA: {
    keywordID: 'LA',
    keywordName: 'LA',
    species: ['feline'],
    sections: ['Objective_Evaluation','HCM_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_formula',
    unit: 'mm',
    refFormula: 'mmoderef_cat',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LA 직경 감소. 저혈량 가능성', '정상', 'LA 확장. HCM 진행, MR, LV 이완 기능 저하 시사. LA/AO ratio로 확인 필요'],
    anatomic_groups: ['LA'],
    testinfo: "좌심방 직경(mm). 체중 기반 allometric formula로 정상 범위 계산. 고양이에서 LA 확장(>16mm 또는 LA/AO >1.5)은 HCM 진행의 중요한 지표이며 CHF 위험 증가와 관련. LA/AO ratio와 병행 평가.",
    functional_groups: ['LA_size', 'HCM_evaluation'],
  },
  LAAOratio: {
    keywordID: 'LAAOratio',
    keywordName: 'LA:AO Ratio',
    species: ['feline'],
    sections: ['Objective_Evaluation', 'HCM_Evaluation'],
    groups: ['LA'],
    testType: 'calculated',
    unit: '',
    testref: '<1.5',
    formula: 'LAAOratio',
    dependencies: ['LA', 'AO'],
    thresholds: [1.5, 1.7],
    optResult: ['normal', 'mild increase', 'marked increase'],
    optComment: [
      '정상 LA 크기. CHF 위험 낮음',
      'LA 경도 확장. CHF 위험 증가. 6개월 이내 재검 권장',
      'LA 심각한 확장. CHF 위험 높음. 치료 및 집중 모니터링 필요',
    ],
    anatomic_groups: ['LA'],
    testinfo: "좌심방/대동맥 직경 비율(LA:AO ratio). 고양이 정상 <1.5. 고양이 HCM에서 가장 중요한 CHF 위험 예측 지표. 1.5~1.7: LA 경도 확장(CHF 위험 증가), 1.7 초과: LA 심각한 확장(CHF 위험 높음, 항혈전 치료 고려). 개의 기준(1.3)보다 높은 값을 사용하므로 혼동 주의.",
    functional_groups: ['LA_size', 'LA_pressure', 'HCM_evaluation'],
  },
};
