import type { EchoTest } from "@/types/echocardio/echocardio-type";

export const ECHO_TESTS_FELINE: Record<string, EchoTest> = {
  // ---- PE ----
  BW_kg: {
    keywordID: 'BW_kg',
    keywordName: 'BW (kg)',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'other',
    unit: 'kg',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics', 'LV_size'],
  },
  BP: {
    keywordID: 'BP',
    keywordName: 'Blood Pressure',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'mmHg',
    thresholds: [80, 150],
    optResult: ['hypotension', 'normal', 'hypertension'],
    optComment: ['', '', ''],
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics'],
  },
  BT: {
    keywordID: 'BT',
    keywordName: 'Body Temp.',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: '°C',
    thresholds: [38, 39.2],
    optResult: ['hypothermia', 'normal', 'hyperthermia'],
    optComment: ['', '', ''],
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics'],
  },
  HR: {
    keywordID: 'HR',
    keywordName: 'Heart Rate',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'bpm',
    testref: '80~160',
    thresholds: [80, 160],
    optResult: ['bradycardia', 'normal', 'tachycardia'],
    optComment: ['', '', ''],
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics'],
  },
  RR: {
    keywordID: 'RR',
    keywordName: 'Respi. Rate',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'rr/min',
    testref: '10~30',
    thresholds: [10, 30, 40, 60],
    optResult: ['hypopnea', 'normal', 'tachypnea', 'tachypnea', 'tachypnea'],
    optComment: ['', '', '', '', ''],
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics'],
  },
  HS: {
    keywordID: 'HS',
    keywordName: 'Heart Sound',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics'],
  },
  PE_comment: {
    keywordID: 'PE_comment',
    keywordName: 'P.E. comment',
    species: ['canine', 'feline'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Hemodynamics'],
  },

  // ---- Radio ----
  Radio_comment: {
    keywordID: 'Radio_comment',
    keywordName: 'Radiology comment',
    species: ['canine', 'feline'],
    sections: ['Radio'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Cardiomegaly'],
  },

  // ---- Bmode: MV ----
  MV_SAM: {
    keywordID: 'MV_SAM',
    keywordName: 'Systolic Anterior Motion (SAM)',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'none', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_morphology', 'LV_systolic'],
  },
  MV_leafletTipThickening: {
    keywordID: 'MV_leafletTipThickening',
    keywordName: 'MV Leaflet Tip Thickening',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV anterior leaflet tip thickening',
      'MV posterior leaflet tip thickening',
      'MV anterior & posterior leaflet tip thickening',
    ],
    optComment: ['', 'normal', 'MVD', 'MVD', 'MVD'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_morphology'],
  },
  MV_prolapse: {
    keywordID: 'MV_prolapse',
    keywordName: 'MV Prolapse',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV prolapse(anterior)',
      'MV prolapse(posterior)',
      'MV prolapse(anterior & posterior)',
    ],
    optComment: ['', 'normal', 'MVD', 'MVD', 'MVD'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_morphology'],
  },
  MV_flailmovement: {
    keywordID: 'MV_flailmovement',
    keywordName: 'MV Flail Movement',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV flail movement(anterior)',
      'MV flail movement(posterior)',
      'MV flail movement(anterior & posterior)',
    ],
    optComment: ['', 'normal', 'MVD', 'MVD', 'MVD'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_morphology'],
  },
  
  

  // ---- Bmode: IVS ----
  IVS_flattening: {
    keywordID: 'IVS_flattening',
    keywordName: 'IVS Flattening',
    species: ['canine', 'feline'],
    sections: ['Bmode','PosibilityOfPH'],
    groups: ['IVS'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', 'RV enlargement'],
    anatomic_groups: ['RV'],
    testinfo: "",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  IVS_paradoxicalMV: {
    keywordID: 'IVS_paradoxicalMV',
    keywordName: 'IVS Paradoxical Movement',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['IVS'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['RV'],
    testinfo: "",
    functional_groups: ['RV_function'],
  },

  // ---- Bmode: TV ----
  TV_leafletTipThickening: {
    keywordID: 'TV_leafletTipThickening',
    keywordName: 'TV Leaflet Tip Thickening',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV leaflet tip thickening'],
    optComment: ['', 'normal', 'TVI'],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease'],
  },
  TV_prolapse: {
    keywordID: 'TV_prolapse',
    keywordName: 'TV Prolapse',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV prolapse'],
    optComment: ['', 'normal', 'TVI'],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease'],
  },
  TV_flailmovement: {
    keywordID: 'TV_flailmovement',
    keywordName: 'TV Flail Movement',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV flail movement'],
    optComment: ['', 'normal', 'TVI'],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease'],
  },
  //---- Bmode : RV ----
  RVhypertrophy: {
    keywordID: 'RVhypertrophy',
    keywordName: 'RV hypertrophy',
    species: ['canine', 'feline'],
    sections: ['Bmode','PosibilityOfPH'],
    groups: ['RV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'none', 'yes'],
    optComment: ['', '', ''],
    anatomic_groups: ['RV'],
    testinfo: "",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  RVsystolicDysfunction: {
    keywordID: 'RVsystolicDysfunction',
    keywordName: 'RV systolic dysfunction',
    species: ['canine', 'feline'],
    sections: ['Bmode','PosibilityOfPH'],
    groups: ['RV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'none', 'yes'],
    optComment: ['', '', ''],
    anatomic_groups: ['RV'],
    testinfo: "",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
RAenlargement: {
    keywordID: 'RAenlargement',
    keywordName: 'RA enlargement',
    species: ['canine', 'feline'],
    sections: ['Bmode','PosibilityOfPH'],
    groups: ['RA'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'none', 'yes'],
    optComment: ['', '', ''],
    anatomic_groups: ['RA'],
    testinfo: "",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  CVCenlargement: {
    keywordID: 'CVCenlargement',
    keywordName: 'CVC enlargement',
    species: ['canine', 'feline'],
    sections: ['Bmode','PosibilityOfPH'],
    groups: ['CVC'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'none', 'yes'],
    optComment: ['', '', ''],
    anatomic_groups: ['RA'],
    testinfo: "",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  
  // ---- Bmode: AV ----
  AV_flattening: {
    keywordID: 'AV_flattening',
    keywordName: 'Aortic Valve Flattening',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease'],
  },
  AV_poststenoticdilation: {
    keywordID: 'AV_poststenoticdilation',
    keywordName: 'AV Post-stenotic Dilation',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease'],
  },
  LVOT_obstruction: {
    keywordID: 'LVOT_obstruction',
    keywordName: 'LVOT Obstruction',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['LVOT'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['AV_disease', 'LV_systolic'],
  },

  // ---- Bmode: PV ----
  PV_thickening: {
    keywordID: 'PV_thickening',
    keywordName: 'PV Thickening',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PV_changeOfdimension: {
    keywordID: 'PV_changeOfdimension',
    keywordName: 'PV Change of Dimension',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow'],
  },

  // ---- Bmode: Effusion ----
  PericardialEffusion: {
    keywordID: 'PericardialEffusion',
    keywordName: 'Pericardial Effusion',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['Pericardium'],
    testinfo: "",
    functional_groups: ['Effusion'],
  },
  PericardialEffusion_vol: {
    keywordID: 'PericardialEffusion_vol',
    keywordName: 'Pericardial Effusion (vol.)',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'other',
    unit: 'ml',
    anatomic_groups: ['Pericardium'],
    testinfo: "",
    functional_groups: ['Effusion'],
  },
  PleuralEffusion: {
    keywordID: 'PleuralEffusion',
    keywordName: 'Pleural Effusion',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['Pleura'],
    testinfo: "",
    functional_groups: ['Effusion'],
  },
  PleuralEffusion_vol: {
    keywordID: 'PleuralEffusion_vol',
    keywordName: 'Pleural Effusion (vol.)',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['Pleura'],
    testinfo: "",
    functional_groups: ['Effusion'],
  },
  Bmode_comment: {
    keywordID: 'Bmode_comment',
    keywordName: 'B-mode Comment',
    species: ['canine', 'feline'],
    sections: ['Bmode'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: [],
  },

  // ---- Mmode: 공통 계산 ----
  LVFS: {
    // threshold/optComment는 종별로 다름 → 각 종 파일에서 override
    keywordID: 'LVFS',
    keywordName: 'FS',
    species: ['canine', 'feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'calculated',
    unit: '%',
    testref: '28~45',
    formula: 'LVFS',
    dependencies: ['LVd', 'LVs'],
    thresholds: [], // 종별 파일에서 정의
    optResult: [],
    optComment: [],
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['LV_systolic'],
  },
  EF: {
    keywordID: 'EF',
    keywordName: 'EF',
    species: ['canine', 'feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'range',
    unit: '%',
    testref: '40~100',
    thresholds: [40],
    optResult: ['decrease', 'normal'],
    optComment: ['LV contractility decrease', ''],
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['LV_systolic'],
  },
  ESV: {
    keywordID: 'ESV',
    keywordName: 'ESV',
    species: ['canine', 'feline'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'other',
    unit: 'ml',
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['LV_systolic', 'LV_size'],
  },
  LAdMax: {
    keywordID: 'LAdMax',
    keywordName: 'LAd Max',
    species: ['canine', 'feline'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['LA'],
    testinfo: "",
    functional_groups: ['LA_size'],
  },
  LAdMin: {
    keywordID: 'LAdMin',
    keywordName: 'LAd Min',
    species: ['canine', 'feline'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['LA'],
    testinfo: "",
    functional_groups: ['LA_size'],
  },
  LAFS: {
    keywordID: 'LAFS',
    keywordName: 'LA FS',
    species: ['canine', 'feline'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'calculated',
    unit: '%',
    testref: '19~30',
    formula: 'LAFS',
    dependencies: ['LAdMax', 'LAdMin'],
    thresholds: [19, 30],
    optResult: ['decrease', 'decrease', 'normal'],
    optComment: ['CHF risk', 'increased LA pressure', 'normal'],
    anatomic_groups: ['LA'],
    testinfo: "",
    functional_groups: ['LA_size', 'LA_pressure'],
  },

  // ---- ColorDoppler ----
  MV_turbulentJet: {
    keywordID: 'MV_turbulentJet',
    keywordName: 'MV Turbulent Jet',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', 'MV regurgitation'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_regurgitation'],
  },
  MV_turbulentJetRange: {
    keywordID: 'MV_turbulentJetRange',
    keywordName: 'MV Turbulent Jet Range',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: '%',
    thresholds: [10, 30, 70],
    optResult: ['normal', 'Mild', 'Moderate', 'Severe'],
    optComment: [
      '',
      'mild MV regurgitation',
      'moderate MV regurgitation',
      'severe MV regurgitation',
    ],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_regurgitation'],
  },
  TV_turbulentJet: {
    keywordID: 'TV_turbulentJet',
    keywordName: 'TV Turbulent Jet',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', 'TV regurgitation'],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease'],
  },
  TV_turbulentJetRange: {
    keywordID: 'TV_turbulentJetRange',
    keywordName: 'TV Turbulent Jet Range',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['TV'],
    testType: 'range',
    unit: '%',
    thresholds: [10, 30, 70],
    optResult: ['normal', 'Mild', 'Moderate', 'Severe'],
    optComment: [
      '',
      'mild TV regurgitation',
      'moderate TV regurgitation',
      'severe TV regurgitation',
    ],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease'],
  },
  AV_turbulentJet: {
    keywordID: 'AV_turbulentJet',
    keywordName: 'AV Turbulent Jet',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease'],
  },
  PV_turbulentJet: {
    keywordID: 'PV_turbulentJet',
    keywordName: 'PV Turbulent Jet',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'abnormal'],
    optComment: ['', '', ''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow'],
  },
  CD_comment: {
    keywordID: 'CD_comment',
    keywordName: 'Color Doppler Comment',
    species: ['canine', 'feline'],
    sections: ['ColorDoppler'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: [],
  },

  // ---- SpectralDoppler: MV ----
  MV_Ewave: {
    keywordID: 'MV_Ewave',
    keywordName: 'MV E Wave',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: 'm/s',
    testref: '0~1.08',
    thresholds: [1.08, 1.25],
    optResult: ['normal', 'mild increase', 'increase'],
    optComment: ['normal', 'monitoring', 'increased LA pressure'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['LA_pressure', 'LV_diastolic', 'MV_regurgitation'],
  },
  MV_Awave: {
    keywordID: 'MV_Awave',
    keywordName: 'MV A Wave',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['LV_diastolic'],
  },
  MV_EAratio: {
    keywordID: 'MV_EAratio',
    keywordName: 'MV E:A Ratio',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '1~1.85',
    formula: 'MV_EAratio',
    dependencies: ['MV_Ewave', 'MV_Awave'],
    thresholds: [1, 1.85],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['diastolic dysfunction', 'normal', 'CHF suspect'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['LV_diastolic', 'LA_pressure'],
  },
  IVRT: {
    keywordID: 'IVRT',
    keywordName: 'IVRT',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: 'ms',
    testref: '50~70',
    thresholds: [50, 70],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LAP increase, CHF risk', 'normal', 'impaired relaxation susp.'],
    anatomic_groups: ['LV'],
    testinfo: "ㅁ나이ㅓㅣㅁㄹ너ㅣ",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  EIVRT: {
    keywordID: 'EIVRT',
    keywordName: 'E/IVRT',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '0~2.2',
    formula: 'EIVRT',
    dependencies: ['MV_Ewave', 'IVRT'],
    thresholds: [2.2],
    optResult: ['normal', 'increase'],
    optComment: ['normal', 'increased LA pressure, CHF risk'],
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  DT: {
    keywordID: 'DT',
    keywordName: 'Deceleration Time (DT)',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: 'ms',
    testref: '80~100',
    thresholds: [80, 100],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['increased LA pressure', 'normal', ''],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  MR: {
    keywordID: 'MR',
    keywordName: 'MV Regurgitation',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'normal', 'mild MR', 'moderate MR', 'severe MR'],
    optComment: ['', '', 'mild MR', 'moderate MR', 'severe MR'],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_regurgitation'],
  },
  MR_vel: {
    keywordID: 'MR_vel',
    keywordName: 'MR Velocity',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_regurgitation'],
  },
  MRPG: {
    keywordID: 'MRPG',
    keywordName: 'MR PG',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['MR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MV_regurgitation'],
  },

  // ---- SpectralDoppler: TV ----
  TV_Ewave: {
    keywordID: 'TV_Ewave',
    keywordName: 'TV E Wave',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease', 'RV_function'],
  },
  TR: {
    keywordID: 'TR',
    keywordName: 'TR Regurgitation',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'normal', 'mild TR', 'moderate TR', 'severe TR'],
    optComment: ['', '', 'mild TR', 'moderate TR', 'severe TR'],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['TV_disease', 'PA_pressure', 'Pulmonary_Hypertension'],
  },
  TR_vel: {
    keywordID: 'TR_vel',
    keywordName: 'TR Velocity',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'range',
    unit: 'm/s',
    testref: '0~3',
    thresholds: [3],
    optResult: ['normal', 'increase'],
    optComment: ['', 'increased PA pressure?'],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension', 'TV_disease'],
  },
  TRPG: {
    keywordID: 'TRPG',
    keywordName: 'TR PG',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['TR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['TV'],
    testinfo: "",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },

  // ---- SpectralDoppler: PA ----
  PA_velocity: {
    keywordID: 'PA_velocity',
    keywordName: 'PA Velocity',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow'],
  },
  PR: {
    keywordID: 'PR',
    keywordName: 'PA Regurgitation',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'normal', 'mild PR', 'moderate PR', 'severe PR'],
    optComment: ['', '', 'mild PR', 'moderate PR', 'severe PR'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PR_vel: {
    keywordID: 'PR_vel',
    keywordName: 'PR Velocity',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'range',
    unit: 'm/s',
    thresholds: [2.5],
    optResult: ['normal', 'increase'],
    optComment: ['', ''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_pressure', 'PA_flow', 'Pulmonary_Hypertension'],
  },
  PRPG: {
    keywordID: 'PRPG',
    keywordName: 'PR PG',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['PR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_pressure'],
  },

  // ---- SpectralDoppler: AV ----
  AV_velocity: {
    keywordID: 'AV_velocity',
    keywordName: 'AV Velocity',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'range',
    unit: 'm/s',
    testref: '1.5~2.2',
    thresholds: [1.5, 2.2, 3.5, 4.5],
    optResult: [
      'decrease',
      'normal',
      'mild increase',
      'moderate increase',
      'severe increase',
    ],
    optComment: [
      'Systolic Dysfunction? hypovolemic?',
      'normal',
      'SAS?',
      'SAS susp.',
      'SAS susp.',
    ],
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease', 'LV_systolic'],
  },
  AR: {
    keywordID: 'AR',
    keywordName: 'AR Regurgitation',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'normal', 'mild AR', 'moderate AR', 'severe AR'],
    optComment: ['', '', 'mild AR', 'moderate AR', 'severe AR'],
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease'],
  },
  AR_vel: {
    keywordID: 'AR_vel',
    keywordName: 'AR Velocity',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease'],
  },
  ARPG: {
    keywordID: 'ARPG',
    keywordName: 'AR PG',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['AR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['AO'],
    testinfo: "",
    functional_groups: ['AV_disease'],
  },
  SD_comment: {
    keywordID: 'SD_comment',
    keywordName: 'Spectral Doppler Comment',
    species: ['canine', 'feline'],
    sections: ['SpectralDoppler'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: [],
  },

  // ---- PH 공통 ----
  CVCcollapse: {
    keywordID: 'CVCcollapse',
    keywordName: 'CVC collapse',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'select',
    options: ['', '<20%', '20-50%', '>50%'],
    optResult: [
      '',
      'RA pressure < 5mmHg',
      'RA pressure 10mmHg',
      'RA pressure > 15mmHg',
    ],
    optComment: ['', '', '', ''],
    anatomic_groups: ['RA'],
    testinfo: "",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension', 'RV_function'],
  },
  RApressure: {
    keywordID: 'RApressure',
    keywordName: 'RA pressure',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'RApressure',
    dependencies: ['CVCcollapse'],
    thresholds: [6, 15],
    optResult: [
      'decrease or normal',
      'mild ~ moderate increase',
      'marked increase',
    ],
    optComment: ['', '', ''],
    anatomic_groups: ['RA'],
    testinfo: "",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },
  PApressure: {
    keywordID: 'PApressure',
    keywordName: 'PA pressure',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: 'mmHg',
    testref: '0~25',
    formula: 'PApressure',
    dependencies: ['RApressure', 'TRPG'],
    thresholds: [25, 50, 76],
    optResult: [
      'normal',
      'mild increase',
      'moderate increase',
      'marked increase',
    ],
    optComment: [
      'normal',
      'PH grade(Mild)',
      'PH grade(Moderate)',
      'PH grade(Severe)',
    ],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },
  PA: {
    keywordID: 'PA',
    keywordName: 'PA',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PAAO: {
    keywordID: 'PAAO',
    keywordName: 'PA/AO',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: '',
    testref: '0~1',
    formula: 'PAAO',
    dependencies: ['PA', 'AO'],
    thresholds: [1],
    optResult: ['normal', 'increase'],
    optComment: ['normal', 'PA dia. increase'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  AT: {
    keywordID: 'AT',
    keywordName: 'AT',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: '',
    testref: '58~',
    thresholds: [58],
    optResult: ['decrease', 'normal'],
    optComment: ['', 'normal'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  ET: {
    keywordID: 'ET',
    keywordName: 'ET',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow'],
  },
  ATET: {
    keywordID: 'ATET',
    keywordName: 'AT/ET',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: '',
    testref: '0.3~0.5',
    formula: 'ATET',
    dependencies: ['AT', 'ET'],
    thresholds: [0.3, 0.5],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['', '', ''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  SystolicNotch: {
    keywordID: 'SystolicNotch',
    keywordName: 'Systolic Notching',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension','PosibilityOfPH'],
    groups: ['PA'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'none', 'yes'],
    optComment: ['', '', ''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  RPAmax: {
    keywordID: 'RPAmax',
    keywordName: 'RPA max',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow'],
  },
  RPAmin: {
    keywordID: 'RPAmin',
    keywordName: 'RPA min',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['PA_flow'],
  },
  RPADi: {
    keywordID: 'RPADi',
    keywordName: 'RPADi',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'calculated',
    unit: '%',
    testref: '>30',
    formula: 'RPADi',
    dependencies: ['RPAmax', 'RPAmin'],
    thresholds: [30],
    optResult: ['decrease', 'normal'],
    optComment: ['', ''],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 직경 변동지수(RPADi). 30% 미만 시 폐혈관 순응도 감소 및 폐고혈압 가능성 시사.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  
  anatomic_PAAO: {
    keywordID: 'anatomic_PAAO',
    keywordName: 'Pulmonary artery enlargement',
    species: ['canine', 'feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_PAAO',
    dependencies: ['PAAO'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_PR_vel: {
    keywordID: 'anatomic_PR_vel',
    keywordName: 'PR velocity > 2.5',
    species: ['canine', 'feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_PR_vel',
    dependencies: ['PR_vel'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_RPADi: {
    keywordID: 'anatomic_RPADi',
    keywordName: 'RPADi < 30%',
    species: ['canine', 'feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_RPADi',
    dependencies: ['RPADi'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_AT: {
    keywordID: 'anatomic_AT',
    keywordName: 'AT < 52',
    species: ['canine', 'feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_AT',
    dependencies: ['AT'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_ATET: {
    keywordID: 'anatomic_ATET',
    keywordName: 'AT/ET < 0.3',
    species: ['canine', 'feline'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_ATET',
    dependencies: ['ATET'],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number1: {
    keywordID: 'anatomic_number1',
    keywordName: 'Number of anatomic sites1',
    species: ['canine', 'feline'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number1',
    dependencies: [
      'IVS_flattening',
      'decreasedSizeOfLV',
      'RVhypertrophy',
      'RVsystolicDysfunction',
    ],
    anatomic_groups: ['RV'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number2: {
    keywordID: 'anatomic_number2',
    keywordName: 'Number of anatomic sites2',
    species: ['canine', 'feline'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number2',
    dependencies: [
      'anatomic_PAAO',
      'anatomic_PR_vel',
      'anatomic_RPADi',
      'anatomic_AT',
      'anatomic_ATET',
      'SystolicNotch',
    ],
    anatomic_groups: ['PA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number3: {
    keywordID: 'anatomic_number3',
    keywordName: 'Number of anatomic sites3',
    species: ['canine', 'feline'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number3',
    dependencies: ['RAenlargement', 'CVCenlargement'],
    anatomic_groups: ['RA'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_number: {
    keywordID: 'anatomic_number',
    keywordName: 'Number of anatomic sites',
    species: ['canine', 'feline'],
    sections: [],
    groups: ['PosibilityOfPH'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_numbertotal',
    dependencies: ['anatomic_number1', 'anatomic_number2', 'anatomic_number3'],
    anatomic_groups: ['General'],
    testinfo: "폐고혈압 시사 소견이 나타난 해부학적 위치(Ventricles, PA, RA/CVC)의 총 개수입니다.",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  PHprob: {
    keywordID: 'PHprob',
    keywordName: 'Probability of PH',
    species: ['canine', 'feline'],
    sections: [],
    groups: ['PosibilityOfPH'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'PHprob',
    dependencies: ['anatomic_number', 'TR_vel'],
    anatomic_groups: ['General'],
    testinfo: "폐고혈압 확률(Low, Intermediate, High). TR 속도와 해부학적 소견 개수를 종합하여 산출합니다.",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  PH_comment: {
    keywordID: 'PH_comment',
    keywordName: 'PH Comment',
    species: ['canine', 'feline'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['Pulmonary_Hypertension'],
  },

  // ---- TDI 공통 ----
  Sm: {
    keywordID: 'Sm',
    keywordName: 'TDI Sm',
    species: ['canine', 'feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "",
    functional_groups: ['LV_systolic'],
  },
  Em: {
    keywordID: 'Em',
    keywordName: 'TDI Em',
    species: ['canine', 'feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "",
    functional_groups: ['LV_diastolic', 'LA_pressure'],
  },
  Am: {
    keywordID: 'Am',
    keywordName: 'TDI Am',
    species: ['canine', 'feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "",
    functional_groups: ['LV_diastolic'],
  },
  EmAm: {
    keywordID: 'EmAm',
    keywordName: 'Em/Am',
    species: ['canine', 'feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    formula: 'EmAm',
    dependencies: ['Em', 'Am'],
    thresholds: [1],
    optResult: ['normal', 'increase'],
    optComment: ['normal', 'Impaired Relaxation'],
    anatomic_groups: ['TDI'],
    testinfo: "",
    functional_groups: ['LV_diastolic'],
  },
  EEm: {
    keywordID: 'EEm',
    keywordName: 'E/Em',
    species: ['canine', 'feline'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '0~6',
    formula: 'EEm',
    dependencies: ['MV_Ewave', 'Em'],
    thresholds: [6, 9, 12],
    optResult: ['normal', 'increase', 'increase', 'increase'],
    optComment: [
      'normal',
      'increased LA pressure(??)',
      'increased LA pressure(>20mmHg)',
      'CHF risk',
    ],
    anatomic_groups: ['TDI'],
    testinfo: "",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  TDI_comment: {
    keywordID: 'TDI_comment',
    keywordName: 'TDI Comment',
    species: ['canine', 'feline'],
    sections: ['TDI'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: [],
  },
  Last_comment: {
    keywordID: 'Last_comment',
    keywordName: 'General Review',
    species: ['canine', 'feline'],
    sections: ['General_Review'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: [],
  },

  // ---- Radio (고양이 기준) ----
  VHS: {
    keywordID: "VHS",
    keywordName: "VHS",
    species: ["feline"],
    sections: ["Radio"],
    groups: ["Thorax"],
    testType: "range",
    unit: "",
    testref: "7.5~9.3",
    thresholds: [7.5, 9.3],
    optResult: ["decrease", "normal", "increase"],
    optComment: ["microcardia", "normal", "cardiomegaly"],
    anatomic_groups: ["General"],
    testinfo: "",
    functional_groups: ["Cardiomegaly"],
  },
  VSd: {
    keywordID: "VSd",
    keywordName: "IVS-d",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["", "", "hypertrophy"],
    anatomic_groups: ["LV"],
    testinfo: "",
    functional_groups: ["LV_size"],
  },
  LVd: {
    keywordID: "LVd",
    keywordName: "LV-d(LVIDd)",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["hypovolemic", "", "eccentric hypertrophy"],
    anatomic_groups: ["LV"],
    testinfo: "",
    functional_groups: ["LV_size"],
  },
  LVWd: {
    keywordID: "LVWd",
    keywordName: "LVW-d(LVPWd)",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["", "", "hypertrophy"],
    anatomic_groups: ["LV"],
    testinfo: "",
    functional_groups: ["LV_size"],
  },
  VSs: {
    keywordID: "VSs",
    keywordName: "IVS-s",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["", "", ""],
    anatomic_groups: ["LV"],
    testinfo: "",
    functional_groups: ["LV_size"],
  },
  LVs: {
    keywordID: "LVs",
    keywordName: "LV-s(LVIDs)",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["hyperdynamic", "", "systolic dysfunction"],
    anatomic_groups: ["LV"],
    testinfo: "",
    functional_groups: ["LV_size", "LV_systolic"],
  },
  LVWs: {
    keywordID: "LVWs",
    keywordName: "LVW-s(LVPWs)",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["", "", ""],
    anatomic_groups: ["LV"],
    testinfo: "",
    functional_groups: ["LV_size"],
  },
  AO: {
    keywordID: "AO",
    keywordName: "AO",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["", "", "AO dilation"],
    anatomic_groups: ["AO"],
    testinfo: "",
    functional_groups: ["LA_size"],
  },
  LA: {
    keywordID: "LA",
    keywordName: "LA",
    species: ["feline"],
    sections: ["Objective_Evaluation"],
    groups: ["Mmode"],
    testType: "mmode_formula",
    unit: "mm",
    refFormula: "mmoderef_cat",
    optResult: ["decrease", "normal", "increase"],
    optComment: ["", "", "LA enlargement"],
    anatomic_groups: ["LA"],
    testinfo: "",
    functional_groups: ["LA_size"],
  },

};
