import type { EchoTest } from "@/types/echocardio/echocardio-type";

export const ECHO_TESTS_CANINE: Record<string, EchoTest> = {
  // ---- PE ----
  BW_kg: {
    keywordID: 'BW_kg',
    keywordName: 'BW (kg)',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'other',
    unit: 'kg',
    anatomic_groups: ['General'],
    testinfo: "체중은 M-mode 정상 참고치 산출 및 LVIDDN, ESVI 계산의 기준값으로 사용됩니다.",
    functional_groups: ['Hemodynamics', 'LV_size'],
  },
  BP: {
    keywordID: 'BP',
    keywordName: 'Blood Pressure',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'mmHg',
    testref: '80~150',
    thresholds: [80, 150],
    optResult: ['hypotension', 'normal', 'hypertension'],
    optComment: ['전신 저혈압 의심. 쇼크, 심부전, 약물 등 원인 평가 필요', '', '전신 고혈압. 신장질환, 부신피질기능항진증 등 원인 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "수축기 혈압 기준. 80mmHg 미만은 저혈압, 150mmHg 초과는 고혈압으로 분류. 고혈압은 이차성 장기 손상(망막, 신장, 심장) 위험 증가.",
    functional_groups: ['Hemodynamics'],
  },
  BT: {
    keywordID: 'BT',
    keywordName: 'Body Temp.',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: '°C',
    testref: '38~39.2',
    thresholds: [38, 39.2],
    optResult: ['hypothermia', 'normal', 'hyperthermia'],
    optComment: ['저체온증. 쇼크, 패혈증, 마취 후 회복 지연 등 평가 필요', '', '발열. 감염, 염증, 열사병 등 원인 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "개의 정상 체온은 38.0~39.2°C. 저체온은 심박출량 감소 및 심부정맥 위험을 높이며, 발열은 심박수 증가와 심근 산소 요구량 증가를 초래할 수 있음.",
    functional_groups: ['Hemodynamics'],
  },
  HR: {
    keywordID: 'HR',
    keywordName: 'Heart Rate',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'bpm',
    testref: '80~160',
    thresholds: [80, 160],
    optResult: ['bradycardia', 'normal', 'tachycardia'],
    optComment: ['서맥. 방실차단, 미주신경 항진, 약물 등 원인 평가 필요', '', '빈맥. 통증, 흥분, 빈혈, 심부전, 부정맥 등 원인 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "개의 정상 심박수는 80~160bpm (소형견은 더 높을 수 있음). 서맥은 심박출량 감소를 유발하며, 빈맥은 심근 충전 시간 단축으로 심박출량을 저하시킬 수 있음.",
    functional_groups: ['Hemodynamics'],
  },
  RR: {
    keywordID: 'RR',
    keywordName: 'Respi. Rate',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'range',
    unit: 'rr/min',
    testref: '10~30',
    thresholds: [10, 30, 40, 60],
    optResult: ['hypopnea', 'normal', 'tachypnea', 'tachypnea', 'tachypnea'],
    optComment: ['호흡 감소. 진정, 마취, 신경계 이상 평가 필요', '', '경도 빈호흡. 스트레스, 통증, 경도 폐부종 등 평가 필요', '중등도 빈호흡. 폐부종, 흉수, 기흉 등 평가 필요', '심한 빈호흡. 응급 처치 필요. 폐부종, CHF 등 평가 필요'],
    anatomic_groups: ['General'],
    testinfo: "개의 정상 호흡수는 10~30회/분. 빈호흡(특히 안정 시 30회 초과)은 CHF로 인한 폐부종의 초기 징후일 수 있으며, ACVIM 지침에서 중요한 모니터링 지표.",
    functional_groups: ['Hemodynamics'],
  },
  HS: {
    keywordID: 'HS',
    keywordName: 'Heart Sound',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "심음 청진 소견. 심잡음(murmur)의 유무, 위치, 강도(grade 1~6), 특성을 기록. 좌측 심첨부(LV apex) 수축기 잡음은 MR, 우측 기저부 수축기 잡음은 PS/TR, 좌측 기저부 수축기 잡음은 SAS/PS를 시사.",
    functional_groups: ['Hemodynamics'],
  },
  PE_comment: {
    keywordID: 'PE_comment',
    keywordName: 'P.E. comment',
    species: ['canine'],
    sections: ['PE'],
    groups: ['PE'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "신체검사 전반에 대한 추가 소견 기록란.",
    functional_groups: ['Hemodynamics'],
  },

  

  // ---- Bmode: MV ----
  MV_SAM: {
    keywordID: 'MV_SAM',
    keywordName: 'Systolic Anterior Motion (SAM)',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'SAM present'],
    optComment: ['', '', 'LVOTO 가능성. 수축기 시 승모판 전엽이 LVOT를 막아 동적 폐쇄 유발 가능'],
    anatomic_groups: ['MV'],
    testinfo: "수축기 전방 운동(SAM). 승모판 전엽이 수축기에 LVOT 방향으로 움직이는 현상. 비후성 심근병증(HCM), 동적 LVOT 폐쇄 시 관찰. 존재 시 LVOT 혈류 속도 측정 필요.",
    functional_groups: ['MV_morphology', 'LV_systolic'],
  },
  MV_leafletTipThickening: {
    keywordID: 'MV_leafletTipThickening',
    keywordName: 'MV Leaflet Tip Thickening',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV anterior leaflet tip thickening',
      'MV posterior leaflet tip thickening',
      'MV anterior & posterior leaflet tip thickening',
    ],
    optComment: ['', '', 'MMVD 초기 변화 시사', 'MMVD 초기 변화 시사', 'MMVD 변화 시사'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 첨단부 비후. MMVD(점액종성 승모판 질환)의 초기 형태학적 변화로, 판막 첨단부의 nodule 또는 비후를 관찰. 전엽/후엽/양엽 구분하여 기록.",
    functional_groups: ['MV_morphology'],
  },
  MV_prolapse: {
    keywordID: 'MV_prolapse',
    keywordName: 'MV Prolapse',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV prolapse(anterior)',
      'MV prolapse(posterior)',
      'MV prolapse(anterior & posterior)',
    ],
    optComment: ['', '', 'MR 동반 가능성 평가 필요', 'MR 동반 가능성 평가 필요', 'MR 동반 가능성 평가 필요'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 탈출증. 수축기에 승모판 첨판이 좌심방 방향으로 이탈하는 현상. MMVD의 진행 소견. 탈출된 첨판 방향과 동반 역류 정도를 평가.",
    functional_groups: ['MV_morphology'],
  },
  MV_flailmovement: {
    keywordID: 'MV_flailmovement',
    keywordName: 'MV Flail Movement',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'anterior', 'posterior', 'anterior & posterior'],
    optResult: [
      '',
      'normal',
      'MV flail movement(anterior)',
      'MV flail movement(posterior)',
      'MV flail movement(anterior & posterior)',
    ],
    optComment: ['', '', '건삭 파열 시사. 중증 MR 가능성 높음', '건삭 파열 시사. 중증 MR 가능성 높음', '건삭 파열 시사. 중증 MR 가능성 높음'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 도리깨 운동. 건삭(chordae tendineae) 파열로 첨판이 좌심방으로 완전히 이탈하는 현상. MMVD 말기 또는 외상성 손상 시 관찰. 대부분 중증 MR 동반.",
    functional_groups: ['MV_morphology'],
  },

  // ---- Bmode: IVS ----
  IVS_flattening: {
    keywordID: 'IVS_flattening',
    keywordName: 'IVS Flattening',
    species: ['canine'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['IVS'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'IVS flattening present'],
    optComment: ['', '', 'RV 압력/용적 과부하 시사. 폐고혈압 또는 RV enlargement 평가 필요'],
    anatomic_groups: ['RV'],
    testinfo: "심실중격 편평화. 우심실 압력 또는 용적 과부하 시 단축상에서 IVS가 편평해지거나 역전되는 소견. 폐고혈압의 중요한 해부학적 지표.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  IVS_paradoxicalMV: {
    keywordID: 'IVS_paradoxicalMV',
    keywordName: 'IVS Paradoxical Movement',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['IVS'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'paradoxical IVS motion present'],
    optComment: ['', '', 'RV 용적 과부하 또는 전기전도 이상 시사'],
    anatomic_groups: ['RV'],
    testinfo: "심실중격 역설적 운동. 정상적으로 수축기에 LV 방향으로 움직여야 할 IVS가 반대 방향으로 움직이는 현상. RV 용적 과부하, 좌각차단(LBBB), 심낭압전 시 관찰.",
    functional_groups: ['RV_function'],
  },

  // ---- Bmode: TV ----
  TV_leafletTipThickening: {
    keywordID: 'TV_leafletTipThickening',
    keywordName: 'TV Leaflet Tip Thickening',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV leaflet tip thickening'],
    optComment: ['', '', 'TVI(삼첨판 이형성증) 시사'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 첨단부 비후. 삼첨판 이형성증(TVI)의 형태학적 변화. 비후 시 TR 동반 여부 확인 필요.",
    functional_groups: ['TV_disease'],
  },
  TV_prolapse: {
    keywordID: 'TV_prolapse',
    keywordName: 'TV Prolapse',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV prolapse'],
    optComment: ['', '', 'TVI 시사. TR 중증도 평가 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 탈출증. 수축기에 삼첨판 첨판이 우심방 방향으로 이탈하는 현상. TVI 또는 MMVD의 동반 병변으로 나타날 수 있음.",
    functional_groups: ['TV_disease'],
  },
  TV_flailmovement: {
    keywordID: 'TV_flailmovement',
    keywordName: 'TV Flail Movement',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV flail movement'],
    optComment: ['', '', '건삭 파열 시사. 중증 TR 가능성 높음'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 도리깨 운동. 건삭 파열로 삼첨판 첨판이 우심방으로 완전히 이탈. 중증 TR 동반 가능성 높음.",
    functional_groups: ['TV_disease'],
  },

  // ---- Bmode: RV ----
  RVhypertrophy: {
    keywordID: 'RVhypertrophy',
    keywordName: 'RV hypertrophy',
    species: ['canine'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['RV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'RV hypertrophy present'],
    optComment: ['', '', '만성 RV 압력 과부하 시사. 폐고혈압, PS 등 원인 평가 필요'],
    anatomic_groups: ['RV'],
    testinfo: "우심실 비대. 만성 압력 과부하(폐고혈압, 폐동맥 협착 등)로 인한 우심실 벽 비후. 폐고혈압의 중요한 해부학적 증거.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  RVsystolicDysfunction: {
    keywordID: 'RVsystolicDysfunction',
    keywordName: 'RV systolic dysfunction',
    species: ['canine'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['RV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'RV systolic dysfunction present'],
    optComment: ['', '', '우심실 수축 기능 저하. 폐고혈압 진행 또는 RV 심근병증 평가 필요'],
    anatomic_groups: ['RV'],
    testinfo: "우심실 수축 기능 저하. 우심실 운동 감소, TAPSE 저하 등으로 평가. 폐고혈압 진행 또는 우심 심근병증 시 관찰.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  RAenlargement: {
    keywordID: 'RAenlargement',
    keywordName: 'RA enlargement',
    species: ['canine'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['RA'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'RA enlargement present'],
    optComment: ['', '', '우심방 압력/용적 증가 시사. TR 또는 폐고혈압 평가 필요'],
    anatomic_groups: ['RA'],
    testinfo: "우심방 확장. TR, 폐고혈압, 우심 심부전 등으로 인한 우심방 압력/용적 증가 시 관찰. 폐고혈압의 해부학적 증거 중 하나.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },
  CVCenlargement: {
    keywordID: 'CVCenlargement',
    keywordName: 'CVC enlargement',
    species: ['canine'],
    sections: ['Bmode', 'PosibilityOfPH'],
    groups: ['CVC'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'CVC enlargement present'],
    optComment: ['', '', '전신 정맥압 상승 시사. 우심부전, 폐고혈압, 심낭압전 등 평가 필요'],
    anatomic_groups: ['RA'],
    testinfo: "후대정맥(CVC) 확장. 우심방 압력 증가로 인한 정맥 울혈의 지표. 직경 증가 및 호흡에 따른 허탈 감소(CVCcollapse 참조) 시 우심부전 또는 폐고혈압을 시사.",
    functional_groups: ['RV_function', 'Pulmonary_Hypertension'],
  },

  // ---- Bmode: AV ----
  AV_flattening: {
    keywordID: 'AV_flattening',
    keywordName: 'Aortic Valve Flattening',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'AV leaflet flattening present'],
    optComment: ['', '', 'LVOTO 또는 대동맥판 협착 시사. AV 혈류 속도 측정 필요'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 첨판 편평화. 대동맥판 협착(SAS) 또는 LVOT 폐쇄 시 수축 중기에 판막이 부분 폐쇄되는 현상. 스펙트럼 도플러로 혈류 속도 확인 필요.",
    functional_groups: ['AV_disease'],
  },
  AV_poststenoticdilation: {
    keywordID: 'AV_poststenoticdilation',
    keywordName: 'AV Post-stenotic Dilation',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'post-stenotic aortic dilation present'],
    optComment: ['', '', 'SAS 또는 대동맥판 협착의 이차적 변화 시사'],
    anatomic_groups: ['AO'],
    testinfo: "협착 후 대동맥 확장. SAS나 대동맥판 협착으로 인한 고속 혈류가 협착 후방의 대동맥 벽에 충격을 주어 확장을 일으킴. SAS의 중요한 이차 소견.",
    functional_groups: ['AV_disease'],
  },
  LVOT_obstruction: {
    keywordID: 'LVOT_obstruction',
    keywordName: 'LVOT Obstruction',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['LVOT'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'LVOT obstruction present'],
    optComment: ['', '', 'SAS 또는 동적 LVOT 폐쇄 시사. AV velocity 및 PG 측정 필요'],
    anatomic_groups: ['LV'],
    testinfo: "좌심실 유출로 폐쇄. 고정성(SAS - 판막하 섬유성 융기) 또는 동적(SAM) 폐쇄로 구분. AV 혈류 가속 및 turbulence 동반. 도플러로 압력차 측정 필요.",
    functional_groups: ['AV_disease', 'LV_systolic'],
  },

  // ---- Bmode: PV ----
  PV_thickening: {
    keywordID: 'PV_thickening',
    keywordName: 'PV Thickening',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'PV thickening present'],
    optComment: ['', '', '폐동맥판 협착(PS) 또는 이형성 시사. PA velocity 측정 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 비후. 폐동맥판 협착(PS) 또는 판막 이형성 시 관찰. 판막 비후와 함께 개방 제한, 협착 후 폐동맥 확장을 동반할 수 있음.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PV_changeOfdimension: {
    keywordID: 'PV_changeOfdimension',
    keywordName: 'PV Change of Dimension',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'PV dimension change present'],
    optComment: ['', '', '폐동맥판 개방 또는 폐쇄 이상 시사. 협착 또는 역류 평가 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 크기 변화 이상. 수축기/이완기 판막 크기 변화의 비정상적 패턴. PS 또는 폐동맥 고혈압에서 관찰될 수 있음.",
    functional_groups: ['PA_flow'],
  },

  // ---- Bmode: Effusion ----
  PericardialEffusion: {
    keywordID: 'PericardialEffusion',
    keywordName: 'Pericardial Effusion',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'pericardial effusion present'],
    optComment: ['', '', '심낭 삼출. 용량 측정 및 심낭압전(cardiac tamponade) 여부 평가 필요'],
    anatomic_groups: ['Pericardium'],
    testinfo: "심낭 삼출. 심낭 내 액체 저류. 원인으로 심장 종양(혈관육종 등), 심낭염, 특발성 등. 대량 삼출 시 심낭압전 위험. 용량(ml) 측정 및 우심방/우심실 허탈 여부 확인 필요.",
    functional_groups: ['Effusion'],
  },
  PericardialEffusion_vol: {
    keywordID: 'PericardialEffusion_vol',
    keywordName: 'Pericardial Effusion (vol.)',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'other',
    unit: 'ml',
    anatomic_groups: ['Pericardium'],
    testinfo: "심낭 삼출량(ml). 소량: <100ml, 중등량: 100~500ml, 대량: >500ml. 용량과 속도가 심낭압전 발생 여부를 결정. 우심방/우심실 diastolic collapse 동반 시 응급 심낭천자 고려.",
    functional_groups: ['Effusion'],
  },
  PleuralEffusion: {
    keywordID: 'PleuralEffusion',
    keywordName: 'Pleural Effusion',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'pleural effusion present'],
    optComment: ['', '', '흉강 삼출. 심부전, 종양, 염증성 원인 평가 필요. 호흡 곤란 동반 시 흉수천자 고려'],
    anatomic_groups: ['Pleura'],
    testinfo: "흉강 삼출. 흉막강 내 액체 저류. 좌심부전으로 인한 폐부종과 함께 또는 독립적으로 발생. CHF의 중요한 징후 중 하나. 방사선과 병행 평가 권장.",
    functional_groups: ['Effusion'],
  },
  PleuralEffusion_vol: {
    keywordID: 'PleuralEffusion_vol',
    keywordName: 'Pleural Effusion (vol.)',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['Effusion'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['Pleura'],
    testinfo: "흉강 삼출 깊이(mm). 흉막강에서 측정한 액체 깊이로 중증도를 간접 평가. 깊이 10mm 초과 시 임상적으로 유의미한 삼출로 간주.",
    functional_groups: ['Effusion'],
  },
  Bmode_comment: {
    keywordID: 'Bmode_comment',
    keywordName: 'B-mode Comment',
    species: ['canine'],
    sections: ['Bmode'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "B-mode 초음파 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- Mmode: 공통 ----
  EF: {
    keywordID: 'EF',
    keywordName: 'EF',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'range',
    unit: '%',
    testref: '40~70',
    thresholds: [40, 70],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 수축 기능 저하. DCM 또는 수축기 심부전 평가 필요', '', '과역동성 LV 기능. 탈수, 빈혈, 교감신경 항진 등 평가 필요'],
    anatomic_groups: ['LV'],
    testinfo: "박출 분율(Ejection Fraction). LV 수축 기능의 전반적 지표. Teichholz 공식으로 산출 (EF = (EDV-ESV)/EDV × 100). 40% 미만은 심한 수축 기능 저하를 의미.",
    functional_groups: ['LV_systolic'],
  },
  ESV: {
    keywordID: 'ESV',
    keywordName: 'ESV',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'other',
    unit: 'ml',
    anatomic_groups: ['LV'],
    testinfo: "수축 말기 용적(End-Systolic Volume). ESVI 계산에 사용. 증가 시 LV 수축 기능 저하 시사. Teichholz 공식으로 산출.",
    functional_groups: ['LV_systolic', 'LV_size'],
  },
  LAdMax: {
    keywordID: 'LAdMax',
    keywordName: 'LAd Max',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['LA'],
    testinfo: "좌심방 최대 직경. 이완기 말기(승모판 개방 직전)에 측정한 좌심방 최대 크기. LA FS 계산에 사용.",
    functional_groups: ['LA_size'],
  },
  LAdMin: {
    keywordID: 'LAdMin',
    keywordName: 'LAd Min',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'other',
    unit: 'mm',
    anatomic_groups: ['LA'],
    testinfo: "좌심방 최소 직경. 수축기 말기(승모판 폐쇄 직전)에 측정한 좌심방 최소 크기. LA FS 계산에 사용.",
    functional_groups: ['LA_size'],
  },
  LAFS: {
    keywordID: 'LAFS',
    keywordName: 'LA FS',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['LA FS'],
    testType: 'calculated',
    unit: '%',
    testref: '19~30',
    formula: 'LAFS',
    dependencies: ['LAdMax', 'LAdMin'],
    thresholds: [19, 30],
    optResult: ['decrease', 'decrease', 'normal'],
    optComment: ['CHF 위험 증가. LA 기능 심각한 저하 시사', '좌심방압 증가 시사. 모니터링 강화 필요', '정상'],
    anatomic_groups: ['LA'],
    testinfo: "좌심방 단축 분율(Left Atrial Fractional Shortening). LA 수축 기능 지표. FS = (LAdMax - LAdMin) / LAdMax × 100. 19% 미만은 CHF 위험, 19~30%는 LA 압력 증가, 30% 이상은 정상.",
    functional_groups: ['LA_size', 'LA_pressure'],
  },

  // ---- ColorDoppler ----
  MV_turbulentJet: {
    keywordID: 'MV_turbulentJet',
    keywordName: 'MV Turbulent Jet',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'MV regurgitation jet present'],
    optComment: ['', '', 'MR 존재. 역류 범위(%) 측정으로 중증도 평가 필요'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 turbulent jet. 수축기에 좌심방으로 역류하는 고속 난류 혈류. 존재 시 역류 면적/좌심방 면적 비율로 중증도 평가.",
    functional_groups: ['MV_regurgitation'],
  },
  MV_turbulentJetRange: {
    keywordID: 'MV_turbulentJetRange',
    keywordName: 'MV Turbulent Jet Range',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: '%',
    testref: '<10',
    thresholds: [10, 30, 70],
    optResult: ['normal/trivial', 'mild MR', 'moderate MR', 'severe MR'],
    optComment: ['생리적 역류 또는 없음', '경도 MR. 정기 모니터링 필요', '중등도 MR. 주기적 심초음파 평가 필요', '중증 MR. 좌심방/좌심실 확장 동반 여부 확인. 치료 고려'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 면적 비율. 컬러 도플러에서 역류 jet 면적 / 좌심방 면적 × 100(%). 10% 미만 trivial/없음, 10~30% 경도, 30~70% 중등도, 70% 초과 중증.",
    functional_groups: ['MV_regurgitation'],
  },
  TV_turbulentJet: {
    keywordID: 'TV_turbulentJet',
    keywordName: 'TV Turbulent Jet',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'TV regurgitation jet present'],
    optComment: ['', '', 'TR 존재. 역류 범위(%) 측정으로 중증도 평가 필요. TR vel 측정으로 PA 압력 추정 가능'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 turbulent jet. 수축기에 우심방으로 역류하는 고속 난류 혈류. TR velocity로 폐동맥압 추정 가능하므로 스펙트럼 도플러 측정 필수.",
    functional_groups: ['TV_disease'],
  },
  TV_turbulentJetRange: {
    keywordID: 'TV_turbulentJetRange',
    keywordName: 'TV Turbulent Jet Range',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['TV'],
    testType: 'range',
    unit: '%',
    testref: '<10',
    thresholds: [10, 30, 70],
    optResult: ['normal/trivial', 'mild TR', 'moderate TR', 'severe TR'],
    optComment: ['생리적 역류 또는 없음', '경도 TR. TR vel로 PA 압력 추정 권장', '중등도 TR. RA 확장 동반 여부 확인', '중증 TR. RA 확장, 우심부전 증상 평가 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 면적 비율(%). 10% 미만 trivial, 10~30% 경도, 30~70% 중등도, 70% 초과 중증. TR 존재 시 TR velocity로 PA 압력 추정 필수.",
    functional_groups: ['TV_disease'],
  },
  AV_turbulentJet: {
    keywordID: 'AV_turbulentJet',
    keywordName: 'AV Turbulent Jet',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'AV turbulent jet present'],
    optComment: ['', '', 'SAS, 대동맥판 협착 또는 AR 시사. AV velocity 및 AR vel 측정 필요'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 turbulent jet. 수축기 LVOT/AV 협착(SAS) 또는 이완기 AR로 인한 난류 혈류. AV velocity(m/s)와 AR vel 측정으로 병변 구분 및 중증도 평가.",
    functional_groups: ['AV_disease'],
  },
  PV_turbulentJet: {
    keywordID: 'PV_turbulentJet',
    keywordName: 'PV Turbulent Jet',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['PV'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'PV turbulent jet present'],
    optComment: ['', '', 'PS 또는 PR 시사. PA velocity 및 PR vel 측정 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 turbulent jet. 수축기 PS 또는 이완기 PR로 인한 난류 혈류. PA velocity와 PR vel 측정으로 병변 구분 및 중증도 평가.",
    functional_groups: ['PA_flow'],
  },
  CD_comment: {
    keywordID: 'CD_comment',
    keywordName: 'Color Doppler Comment',
    species: ['canine'],
    sections: ['ColorDoppler'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "컬러 도플러 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- SpectralDoppler: MV ----
  MV_Ewave: {
    keywordID: 'MV_Ewave',
    keywordName: 'MV E Wave',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: 'm/s',
    testref: '<1.08',
    thresholds: [1.08, 1.25],
    optResult: ['normal', 'mild increase', 'increase'],
    optComment: ['정상 LA 압력', 'LA 압력 경도 상승 시사. 모니터링 강화 필요', 'LA 압력 상승 시사. CHF 위험 증가. E/A ratio, IVRT, DT 병행 평가'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 E파. 이완 초기 LV 이완으로 인한 수동적 혈류 유입 속도. 1.08m/s 미만 정상, 1.08~1.25m/s 경도 증가(LA 압력 상승 시사), 1.25m/s 초과 LA 압력 증가. E/A ratio, IVRT, DT와 함께 이완 기능 평가에 활용.",
    functional_groups: ['LA_pressure', 'LV_diastolic', 'MV_regurgitation'],
  },
  MV_Awave: {
    keywordID: 'MV_Awave',
    keywordName: 'MV A Wave',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['MV'],
    testinfo: "승모판 A파. 심방 수축에 의한 능동적 혈류 유입 속도. E/A ratio 계산에 사용. 이완기 기능 장애 시 A파 증가(E/A<1). 심방세동 시 A파 소실.",
    functional_groups: ['LV_diastolic'],
  },
  MV_EAratio: {
    keywordID: 'MV_EAratio',
    keywordName: 'MV E:A Ratio',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '1~1.85',
    formula: 'MV_EAratio',
    dependencies: ['MV_Ewave', 'MV_Awave'],
    thresholds: [1, 1.85],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['이완기 기능 장애(이완 지연 패턴) 시사. IVRT 증가 동반 여부 확인', '정상 이완 패턴', 'LA 압력 상승, pseudo-normal 또는 restrictive 패턴 시사. CHF 의심'],
    anatomic_groups: ['MV'],
    testinfo: "E/A 비율. E파/A파 속도 비율로 LV 이완 기능 평가. 1 미만: 이완 지연 패턴(이완기 기능 장애 1단계), 1~1.85: 정상, 1.85 초과: LA 압력 상승(pseudo-normal 또는 restrictive 패턴). TDI Em과 병행 평가.",
    functional_groups: ['LV_diastolic', 'LA_pressure'],
  },
  IVRT: {
    keywordID: 'IVRT',
    keywordName: 'IVRT',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: 'ms',
    testref: '50~70',
    thresholds: [50, 70],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LA 압력 상승 시사. CHF 위험. E wave 상승 동반 여부 확인', '정상', '이완 지연(impaired relaxation) 시사. 이완기 기능 장애 1단계 가능성'],
    anatomic_groups: ['LV'],
    testinfo: "등용적 이완 시간(Isovolumic Relaxation Time). 대동맥판 폐쇄부터 승모판 개방까지의 시간. 50ms 미만: LA 압력 상승(CHF 위험), 50~70ms: 정상, 70ms 초과: 이완 지연(이완기 기능 장애). E/IVRT와 함께 활용.",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  EIVRT: {
    keywordID: 'EIVRT',
    keywordName: 'E/IVRT',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '<2.2',
    formula: 'EIVRT',
    dependencies: ['MV_Ewave', 'IVRT'],
    thresholds: [2.2],
    optResult: ['normal', 'increase'],
    optComment: ['정상 LA 압력', 'LA 압력 상승 시사. CHF 위험 증가. 임상 증상과 병행 평가'],
    anatomic_groups: ['LV'],
    testinfo: "E/IVRT 비율. MV E파 속도(m/s) / IVRT(ms) × 1000. 2.2 초과 시 LA 압력 상승 및 CHF 위험 증가를 시사. IVRT만으로는 pseudo-normal 패턴을 구분하기 어려울 때 보조 지표로 활용.",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  DT: {
    keywordID: 'DT',
    keywordName: 'Deceleration Time (DT)',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'range',
    unit: 'ms',
    testref: '80~100',
    thresholds: [80, 100],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LA 압력 상승 시사. restrictive 패턴 가능성. CHF 위험', '정상', '이완 지연 가능성. 임상적 의의는 다른 이완 지표와 함께 평가'],
    anatomic_groups: ['MV'],
    testinfo: "감속 시간(Deceleration Time). E파 최고점에서 기저선까지 감속하는 시간. 80ms 미만: LA 압력 심각한 상승(restrictive 패턴, CHF 위험), 80~100ms: 정상, 100ms 초과: 이완 지연 가능성.",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  MR: {
    keywordID: 'MR',
    keywordName: 'MV Regurgitation',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no MR', 'mild MR', 'moderate MR', 'severe MR'],
    optComment: ['', '정상', '경도 MR. 정기 모니터링 필요', '중등도 MR. LA/LV 확장 동반 여부 평가. 6개월 간격 심초음파 권장', '중증 MR. LA/LV 확장, LA 압력 상승 동반. 치료 및 집중 모니터링 필요'],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 중증도의 종합 평가. 컬러 도플러 jet 범위, MR velocity, MR PG, LA/LV 크기를 종합하여 분류. ACVIM 병기 결정에 중요한 인자.",
    functional_groups: ['MV_regurgitation'],
  },
  MR_vel: {
    keywordID: 'MR_vel',
    keywordName: 'MR Velocity',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 속도. 수축기 MR jet의 최고 속도. MR PG 계산에 사용(Bernoulli 공식: PG = 4V²). 통상 4~6m/s. 속도 감소는 LV 수축 기능 저하 또는 LA 압력 상승을 시사.",
    functional_groups: ['MV_regurgitation'],
  },
  MRPG: {
    keywordID: 'MRPG',
    keywordName: 'MR PG',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['MV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['MR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['MV'],
    testinfo: "승모판 역류 압력차(MR Pressure Gradient). Bernoulli 공식(PG = 4V²)으로 계산. 수축기 LV-LA 압력차를 반영. 정상은 80~120mmHg 수준. 감소 시 LV 수축력 저하 또는 LA 압력 상승 시사.",
    functional_groups: ['MV_regurgitation'],
  },

  // ---- SpectralDoppler: TV ----
  TV_Ewave: {
    keywordID: 'TV_Ewave',
    keywordName: 'TV E Wave',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 E파. 이완 초기 RV로 유입되는 혈류 속도. RV 이완 기능 및 RA 압력 평가에 활용. 증가 시 RA 압력 상승 또는 TR 중증도 증가 시사.",
    functional_groups: ['TV_disease', 'RV_function'],
  },
  TR: {
    keywordID: 'TR',
    keywordName: 'TR Regurgitation',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no TR', 'mild TR', 'moderate TR', 'severe TR'],
    optComment: ['', '정상', '경도 TR. TR vel로 PA 압력 추정', '중등도 TR. RA 확장 평가 및 PA 압력 추정', '중증 TR. RA/RV 확장, 우심부전 증상 평가. 폐고혈압 원인 평가 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 중증도. TR velocity로 PA 압력 추정 가능(TRPG + RA pressure = 수축기 PA 압력). TVI, 폐고혈압 등 원인 평가 필요.",
    functional_groups: ['TV_disease', 'PA_pressure', 'Pulmonary_Hypertension'],
  },
  TR_vel: {
    keywordID: 'TR_vel',
    keywordName: 'TR Velocity',
    species: ['canine'],
    sections: ['SpectralDoppler','PosibilityOfPH'],
    groups: ['TV'],
    testType: 'range',
    unit: 'm/s',
    testref: '<3.0',
    thresholds: [3],
    optResult: ['normal', 'increase'],
    optComment: ['정상 범위. PA 압력 정상 추정', 'PA 압력 상승 가능성 시사. TRPG + RApressure로 수축기 PA 압력 계산 필요'],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 최고 속도. 3.0m/s 초과 시 PA 압력 상승 의심. 수축기 PA 압력 = TRPG(4×TR_vel²) + RA 압력. 폐고혈압 선별 검사의 핵심 지표.",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension', 'TV_disease'],
  },
  TRPG: {
    keywordID: 'TRPG',
    keywordName: 'TR PG',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['TV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['TR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['TV'],
    testinfo: "삼첨판 역류 압력차(TR Pressure Gradient). Bernoulli 공식(PG = 4V²)으로 계산. RV-RA 수축기 압력차를 반영. RA 압력을 더하면 수축기 PA 압력 추정 가능(PA pressure = TRPG + RApressure).",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },

  // ---- SpectralDoppler: PA ----
  PA_velocity: {
    keywordID: 'PA_velocity',
    keywordName: 'PA Velocity',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['PA'],
    testinfo: "폐동맥 혈류 최고 속도. 정상은 약 0.9~1.2m/s. 증가 시 PS 또는 폐혈류 증가 시사. AT/ET 비율 계산과 함께 폐고혈압 평가에 활용.",
    functional_groups: ['PA_flow'],
  },
  PR: {
    keywordID: 'PR',
    keywordName: 'PA Regurgitation',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no PR', 'mild PR', 'moderate PR', 'severe PR'],
    optComment: ['', '정상 또는 생리적 미량 역류', '경도 PR. PR vel로 이완기 PA 압력 추정', '중등도 PR. RV 용적 과부하 평가 필요', '중증 PR. RV 확장, 우심부전 가능성. 폐고혈압 원인 평가'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 역류 중증도. PR velocity로 이완기 PA 압력 추정 가능. 경도 PR은 생리적일 수 있으나, 중등도 이상은 RV 용적 과부하 및 폐동맥 고혈압 시 관찰.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PR_vel: {
    keywordID: 'PR_vel',
    keywordName: 'PR Velocity',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'range',
    unit: 'm/s',
    testref: '<2.5',
    thresholds: [2.5],
    optResult: ['normal', 'increase'],
    optComment: ['이완기 PA 압력 정상 범위', '이완기 PA 압력 상승 시사. PRPG + RApressure로 이완기 PA 압력 추정'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 역류 최고 속도. 이완기 PA-RV 압력차를 반영. 2.5m/s 초과 시 이완기 PA 압력 상승 시사(PH 가능성). 이완기 PA 압력 = PRPG + RA 압력.",
    functional_groups: ['PA_pressure', 'PA_flow', 'Pulmonary_Hypertension'],
  },
  PRPG: {
    keywordID: 'PRPG',
    keywordName: 'PR PG',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['PA'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['PR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥판 역류 압력차(PR Pressure Gradient). Bernoulli 공식(PG = 4V²)으로 계산. 이완기 PA-RV 압력차를 반영. RA 압력을 더하면 이완기 PA 압력 추정 가능.",
    functional_groups: ['PA_pressure'],
  },

  // ---- SpectralDoppler: AV ----
  AV_velocity: {
    keywordID: 'AV_velocity',
    keywordName: 'AV Velocity',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'range',
    unit: 'm/s',
    testref: '1.5~2.2',
    thresholds: [1.5, 2.2, 3.5, 4.5],
    optResult: ['decrease', 'normal', 'mild increase', 'moderate increase', 'severe increase'],
    optComment: [
      'LV 수축 기능 저하 또는 저혈량증 시사. LVFS, EF 확인 필요',
      '정상',
      'SAS 의심. 반복 측정 및 정밀 평가 권장',
      'SAS 의심. PG 계산 및 임상 증상 평가',
      'SAS 확진 수준. PG >80mmHg. 심각한 LVOT 폐쇄 시사',
    ],
    anatomic_groups: ['AO'],
    testinfo: "대동맥 혈류 최고 속도. 정상 1.5~2.2m/s. 감소 시 LV 수축 기능 저하 또는 저혈량 시사. 증가 시 SAS(판막하 대동맥 협착) 의심. Bernoulli 공식으로 압력차 계산: PG = 4V².",
    functional_groups: ['AV_disease', 'LV_systolic'],
  },
  AR: {
    keywordID: 'AR',
    keywordName: 'AR Regurgitation',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'select',
    options: ['', 'none', 'mild', 'moderate', 'severe'],
    optResult: ['', 'no AR', 'mild AR', 'moderate AR', 'severe AR'],
    optComment: ['', '정상', '경도 AR. 정기 모니터링', '중등도 AR. LV 확장 평가 필요', '중증 AR. LV 용적 과부하, 확장. 치료 고려'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 역류 중증도. SAS, IE(감염성 심내막염) 또는 대동맥판 변성 시 발생. LV 용적 과부하 유발. AR vel로 이완기 대동맥-LV 압력차 추정.",
    functional_groups: ['AV_disease'],
  },
  AR_vel: {
    keywordID: 'AR_vel',
    keywordName: 'AR Velocity',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 역류 최고 속도. 이완기 대동맥-LV 압력차를 반영. AR PG 계산에 사용. 속도 감소 시 이완기 LV 압력 상승(이완 기능 저하) 또는 대동맥 이완기 혈압 감소 시사.",
    functional_groups: ['AV_disease'],
  },
  ARPG: {
    keywordID: 'ARPG',
    keywordName: 'AR PG',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['AV'],
    testType: 'calculated',
    unit: 'mmHg',
    formula: 'PG',
    dependencies: ['AR_vel'],
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['AO'],
    testinfo: "대동맥판 역류 압력차(AR Pressure Gradient). Bernoulli 공식(PG = 4V²)으로 계산. 이완기 대동맥-LV 압력차를 반영.",
    functional_groups: ['AV_disease'],
  },
  SD_comment: {
    keywordID: 'SD_comment',
    keywordName: 'Spectral Doppler Comment',
    species: ['canine'],
    sections: ['SpectralDoppler'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "스펙트럼 도플러 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- PH 공통 ----
  CVCcollapse: {
    keywordID: 'CVCcollapse',
    keywordName: 'CVC collapse',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'select',
    options: ['', '<20%', '20-50%', '>50%'],
    optResult: ['', 'RA pressure elevated (>15mmHg)', 'RA pressure 10mmHg', 'RA pressure < 5mmHg'],
    optComment: ['', 'RA 압력 심각한 상승. 우심부전 또는 폐고혈압 진행', 'RA 압력 중등도 상승', 'RA 압력 정상 또는 경도 상승'],
    anatomic_groups: ['RA'],
    testinfo: "후대정맥 허탈률. 흡기 시 CVC 직경 감소 비율로 RA 압력을 간접 추정. 20% 미만: RA 압력 >15mmHg(높음), 20~50%: RA 압력 약 10mmHg(중등도), 50% 초과: RA 압력 <5mmHg(정상).",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension', 'RV_function'],
  },
  RApressure: {
    keywordID: 'RApressure',
    keywordName: 'RA pressure',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: 'mmHg',
    testref: '<6',
    formula: 'RApressure',
    dependencies: ['CVCcollapse'],
    thresholds: [6, 15],
    optResult: ['normal', 'mild~moderate increase', 'marked increase'],
    optComment: ['정상 RA 압력', 'RA 압력 경도~중등도 상승. 우심부전 초기 또는 폐고혈압 시사', 'RA 압력 심각한 상승. 진행된 우심부전 또는 폐고혈압'],
    anatomic_groups: ['RA'],
    testinfo: "CVC 허탈률로 추정한 우심방 압력. 수축기 PA 압력 계산(PA pressure = TRPG + RApressure)의 핵심 변수. 6mmHg 미만 정상, 6~15mmHg 중등도 상승, 15mmHg 초과 심각한 상승.",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },
  PApressure: {
    keywordID: 'PApressure',
    keywordName: 'PA pressure',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: 'mmHg',
    testref: '<25',
    formula: 'PApressure',
    dependencies: ['RApressure', 'TRPG'],
    thresholds: [25, 50, 76],
    optResult: ['normal', 'mild PH', 'moderate PH', 'severe PH'],
    optComment: ['정상 PA 압력', '경도 폐고혈압(Grade I)', '중등도 폐고혈압(Grade II)', '중증 폐고혈압(Grade III). 적극적 치료 필요'],
    anatomic_groups: ['PA'],
    testinfo: "수축기 폐동맥압 추정값. 공식: PA pressure = TRPG + RA pressure. 25mmHg 미만 정상, 25~50mmHg 경도 PH, 50~76mmHg 중등도 PH, 76mmHg 초과 중증 PH.",
    functional_groups: ['PA_pressure', 'Pulmonary_Hypertension'],
  },
  PA: {
    keywordID: 'PA',
    keywordName: 'PA',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [],
    optComment: [],
    anatomic_groups: ['PA'],
    testinfo: "주폐동맥 직경(mm). PA/AO ratio 계산에 사용. 단독 값보다 AO 직경과의 비율(PA/AO)로 평가.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  PAAO: {
    keywordID: 'PAAO',
    keywordName: 'PA/AO',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: '',
    testref: '<1.0',
    formula: 'PAAO',
    dependencies: ['PA', 'AO'],
    thresholds: [1],
    optResult: ['normal', 'PA enlargement'],
    optComment: ['정상 PA 직경', 'PA 확장 시사. 폐고혈압 또는 폐혈류 증가 평가 필요'],
    anatomic_groups: ['PA'],
    testinfo: "폐동맥/대동맥 직경 비율. 1.0 초과 시 PA 확장 시사. 폐고혈압의 해부학적 지표 중 하나. 정상에서는 PA와 AO가 거의 동일한 직경을 가짐.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  AT: {
    keywordID: 'AT',
    keywordName: 'AT',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'ms',
    testref: '≥58',
    thresholds: [58],
    optResult: ['decrease', 'normal'],
    optComment: ['PA 압력 상승 시사. AT/ET 비율 계산 필요', '정상 PA 압력 시사'],
    anatomic_groups: ['PA'],
    testinfo: "가속 시간(Acceleration Time). PA 혈류 시작부터 최고 속도까지의 시간. 58ms 미만 시 PA 압력 상승 시사. AT/ET 비율과 함께 폐고혈압 선별에 활용.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  ET: {
    keywordID: 'ET',
    keywordName: 'ET',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'range',
    unit: 'ms',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "박출 시간(Ejection Time). PA 혈류 시작부터 끝까지의 시간. AT/ET 비율 계산에 사용. 단독으로는 임상적 의의가 제한적.",
    functional_groups: ['PA_flow'],
  },
  ATET: {
    keywordID: 'ATET',
    keywordName: 'AT/ET',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Pulmonary_Hypertension'],
    testType: 'calculated',
    unit: '',
    testref: '0.3~0.5',
    formula: 'ATET',
    dependencies: ['AT', 'ET'],
    thresholds: [0.3, 0.5],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['PA 압력 상승 시사. 폐고혈압 가능성 높음', '정상 PA 압력 범위', '정상 또는 폐혈류 감소 가능성'],
    anatomic_groups: ['PA'],
    testinfo: "AT/ET 비율. 0.3 미만: PA 압력 상승(폐고혈압 가능성 높음), 0.3~0.5: 정상 범위. 폐고혈압의 해부학적 보조 지표. Systolic notch 동반 시 폐고혈압 가능성 더욱 증가.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  SystolicNotch: {
    keywordID: 'SystolicNotch',
    keywordName: 'Systolic Notching',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension', 'PosibilityOfPH'],
    groups: ['PA'],
    testType: 'select',
    options: ['', 'none', 'yes'],
    optResult: ['', 'normal', 'systolic notch present'],
    optComment: ['', '정상', 'PA 혈류의 수축기 중기 역전. 폐고혈압의 강력한 시사 소견'],
    anatomic_groups: ['PA'],
    testinfo: "PA 혈류의 수축기 노치. PA 스펙트럼 도플러에서 수축기 중기에 혈류가 일시적으로 역전되거나 감소하는 패턴. 폐혈관 저항 증가(폐고혈압)의 강력한 지표.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
  RPAmax: {
    keywordID: 'RPAmax',
    keywordName: 'RPA max',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 최대 직경(mm). 흡기 시 측정. RPADi 계산에 사용. 단독 값보다 RPADi(직경 변동지수)로 평가.",
    functional_groups: ['PA_flow'],
  },
  RPAmin: {
    keywordID: 'RPAmin',
    keywordName: 'RPA min',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'range',
    unit: 'mm',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 최소 직경(mm). 호기 시 측정. RPADi 계산에 사용.",
    functional_groups: ['PA_flow'],
  },
  RPADi: {
    keywordID: 'RPADi',
    keywordName: 'RPADi',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['RPADi'],
    testType: 'calculated',
    unit: '%',
    testref: '≥30',
    formula: 'RPADi',
    dependencies: ['RPAmax', 'RPAmin'],
    thresholds: [30],
    optResult: ['decrease', 'normal'],
    optComment: ['폐혈관 순응도 감소 시사. 폐고혈압 가능성', '정상 폐혈관 순응도'],
    anatomic_groups: ['PA'],
    testinfo: "우폐동맥 직경 변동지수(RPA Distensibility Index). RPADi = (RPAmax - RPAmin) / RPAmin × 100(%). 30% 미만: 폐혈관 순응도 감소(폐고혈압 시사). 폐고혈압의 해부학적 보조 지표.",
    functional_groups: ['PA_flow', 'Pulmonary_Hypertension'],
  },
PH_comment: {
    keywordID: 'PH_comment',
    keywordName: 'PH Comment',
    species: ['canine'],
    sections: ['Pulmonary_Hypertension'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "폐고혈압 관련 전반적 소견 및 추가 의견 기록란.",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  anatomic_PAAO: {
    keywordID: 'anatomic_PAAO',
    keywordName: 'Pulmonary artery enlargement',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_PAAO',
    dependencies: ['PAAO'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_PR_vel: {
    keywordID: 'anatomic_PR_vel',
    keywordName: 'PR velocity > 2.5',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_PR_vel',
    dependencies: ['PR_vel'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_RPADi: {
    keywordID: 'anatomic_RPADi',
    keywordName: 'RPADi < 30%',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_RPADi',
    dependencies: ['RPADi'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_AT: {
    keywordID: 'anatomic_AT',
    keywordName: 'AT < 52',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_AT',
    dependencies: ['AT'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_ATET: {
    keywordID: 'anatomic_ATET',
    keywordName: 'AT/ET < 0.3',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Anatomic site'],
    testType: 'calculated_string',
    unit: '',
    thresholds: [''],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_ATET',
    dependencies: ['ATET'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_number1: {
    keywordID: 'anatomic_number1',
    keywordName: 'Number of anatomic sites1',
    species: ['canine'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number1',
    dependencies: ['IVS_flattening', 'decreasedSizeOfLV', 'RVhypertrophy', 'RVsystolicDysfunction'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_number2: {
    keywordID: 'anatomic_number2',
    keywordName: 'Number of anatomic sites2',
    species: ['canine'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number2',
    dependencies: ['anatomic_PAAO', 'anatomic_PR_vel', 'anatomic_RPADi', 'anatomic_AT', 'anatomic_ATET', 'SystolicNotch'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_number3: {
    keywordID: 'anatomic_number3',
    keywordName: 'Number of anatomic sites3',
    species: ['canine'],
    sections: [],
    groups: ['Anatomic site'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_number3',
    dependencies: ['RAenlargement', 'CVCenlargement'],
    anatomic_groups: [],
    testinfo: "",
    functional_groups: [],
  },
  anatomic_number: {
    keywordID: 'anatomic_number',
    keywordName: 'Number of anatomic sites',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Result'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'anatomic_numbertotal',
    dependencies: ['anatomic_number1', 'anatomic_number2', 'anatomic_number3'],
    anatomic_groups: [],
    testinfo: "폐고혈압 시사 소견이 나타난 해부학적 위치(Ventricles, PA, RA/CVC)의 총 개수입니다. ACVIM 가이드라인에 따른 PH 확률 결정의 핵심 지표입니다.",
    functional_groups: [],
  },
  PHprob: {
    keywordID: 'PHprob',
    keywordName: 'Probability of PH',
    species: ['canine'],
    sections: ['PosibilityOfPH'],
    groups: ['Result'],
    testType: 'calculated',
    unit: '',
    thresholds: [],
    optResult: [''],
    optComment: [''],
    formula: 'PHprob',
    dependencies: ['anatomic_number', 'TR_vel'],
    anatomic_groups: ['General'],
    testinfo: "ACVIM 가이드라인에 따른 폐고혈압 확률(Low, Intermediate, High)입니다. TR 속도와 해부학적 소견(anatomic sites) 개수를 종합하여 판정합니다.",
    functional_groups: ['Pulmonary_Hypertension'],
  },
  

  // ---- TDI 공통 ----
  
  Em: {
    keywordID: 'Em',
    keywordName: 'TDI Em',
    species: ['canine'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "조직 도플러(TDI) 이완 초기 Em파. 승모판 환상부에서 측정한 이완기 초기 조직 속도. LV 이완 기능 지표. 감소 시 이완 기능 저하 시사. E/Em(EEm) 계산에 사용.",
    functional_groups: ['LV_diastolic', 'LA_pressure'],
  },
  Am: {
    keywordID: 'Am',
    keywordName: 'TDI Am',
    species: ['canine'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "조직 도플러(TDI) 심방 수축기 Am파. 승모판 환상부에서 측정한 심방 수축기 조직 속도. Em/Am ratio 계산에 사용. 이완기 기능 장애 시 Am 상대적 증가.",
    functional_groups: ['LV_diastolic'],
  },
  Sm: {
    keywordID: 'Sm',
    keywordName: 'TDI Sm',
    species: ['canine'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'other',
    unit: 'm/s',
    anatomic_groups: ['TDI'],
    testinfo: "조직 도플러(TDI) 수축기 Sm파. 승모판 환상부에서 측정한 수축기 조직 속도. LV 수축 기능의 민감한 지표. 감소 시 LV 종축 수축 기능 저하 시사.",
    functional_groups: ['LV_systolic'],
  },
  EmAm: {
    keywordID: 'EmAm',
    keywordName: 'Em/Am',
    species: ['canine'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '<1',
    formula: 'EmAm',
    dependencies: ['Em', 'Am'],
    thresholds: [1],
    optResult: ['normal', 'increase'],
    optComment: ['정상 또는 이완 지연 패턴', '이완 지연(Impaired Relaxation) 시사. 이완기 기능 장애 가능성'],
    anatomic_groups: ['TDI'],
    testinfo: "TDI Em/Am 비율. 1 초과 시 이완 지연(impaired relaxation) 시사. MV E/A ratio와 병행하여 이완 기능 단계 평가에 활용.",
    functional_groups: ['LV_diastolic'],
  },
  EEm: {
    keywordID: 'EEm',
    keywordName: 'E/Em',
    species: ['canine'],
    sections: ['TDI'],
    groups: ['MV'],
    testType: 'calculated',
    unit: '',
    testref: '<6',
    formula: 'EEm',
    dependencies: ['MV_Ewave', 'Em'],
    thresholds: [6, 9, 12],
    optResult: ['normal', 'mild increase', 'moderate increase', 'marked increase'],
    optComment: [
      '정상 LA 압력',
      'LA 압력 경도 상승 가능성(??). 다른 이완 지표와 병행 평가',
      'LA 압력 상승 시사(>20mmHg). CHF 위험',
      'LA 압력 심각한 상승. CHF 위험 높음. 임상 증상 즉시 평가',
    ],
    anatomic_groups: ['TDI'],
    testinfo: "E/Em 비율(충전압 추정 지표). MV E파(m/s) / TDI Em(m/s). LA 충전압(filling pressure)을 반영하는 가장 신뢰성 있는 비침습적 지표. 6 미만 정상, 6~9 경도 상승, 9~12 중등도 상승(LA 압력 >20mmHg), 12 초과 심각한 상승.",
    functional_groups: ['LA_pressure', 'LV_diastolic'],
  },
  TDI_comment: {
    keywordID: 'TDI_comment',
    keywordName: 'TDI Comment',
    species: ['canine'],
    sections: ['TDI'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "TDI 전반에 대한 추가 소견 기록란.",
    functional_groups: [],
  },

  // ---- Radio: 개 전용 ----

 
  VHS: {
    keywordID: 'VHS',
    keywordName: 'VHS',
    species: ['canine'],
    sections: ['Radio'],
    groups: ['Thorax'],
    testType: 'range',
    unit: '',
    testref: '8.5~10.5',
    thresholds: [8.5, 11, 12, 13],
    optResult: ['decrease', 'normal', 'mild cardiomegaly', 'moderate cardiomegaly', 'severe cardiomegaly'],
    optComment: ['microcardia. 저혈량, 탈수 등 평가 필요', '정상 심장 크기', '경도 심비대. 6개월 이내 추적 검사 권장', '중등도 심비대. 심장 질환 원인 평가 및 치료 계획 수립', '중증 심비대. 즉각적인 원인 평가 및 치료 필요'],
    anatomic_groups: ['General'],
    testinfo: "척추 심장 점수(Vertebral Heart Score). 흉부 방사선에서 심장의 장축과 단축을 T4 기준 척추 수로 환산한 값. 개의 정상 범위 8.5~10.5 (품종에 따라 차이). 11 초과 시 심비대 시사.",
    functional_groups: ['Cardiomegaly'],
  },
  VLAS: {
    keywordID: 'VLAS',
    keywordName: 'VLAS',
    species: ['canine'],
    sections: ['Radio'],
    groups: ['Thorax'],
    testType: 'range',
    unit: '',
    testref: '≤3.0',
    thresholds: [3],
    optResult: ['normal', 'LA enlargement'],
    optComment: ['정상 좌심방 크기', 'LA 확장 시사. 심초음파로 LA 크기 및 LAAOratio 확인 권장'],
    anatomic_groups: ['LA'],
    testinfo: "척추 좌심방 크기(Vertebral Left Atrial Size). 측면 흉부 방사선에서 좌심방 크기를 척추 길이 단위로 측정. 3.0 초과 시 좌심방 확장 시사. MMVD B2 이상에서 증가.",
    functional_groups: ['LA_size', 'Cardiomegaly'],
  },
   Radio_comment: {
    keywordID: 'Radio_comment',
    keywordName: 'Radiology comment',
    species: ['canine'],
    sections: ['Radio'],
    groups: ['Comment'],
    testType: 'textcomment',
    anatomic_groups: ['General'],
    testinfo: "흉부 방사선 소견 기록란. 폐 음영(폐부종, 폐렴 등), 흉강 삼출, 기관 변위, 혈관 음영 변화 등을 기록.",
    functional_groups: ['Cardiomegaly'],
  },

  // ---- Mmode: 개 전용 (lookup table) ----
  VSd: {
    keywordID: 'VSd',
    keywordName: 'IVS-d',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['IVS 두께 감소. 심근 위축 또는 저혈량 가능성', '정상', '동심성 비대 시사. HCM, 고혈압, AS 등 원인 평가'],
    anatomic_groups: ['LV'],
    testinfo: "이완기 심실중격 두께(IVS diastole). 체중 기반 정상 참고치(mmoderef_dog)와 비교. 증가 시 동심성 비대(압력 과부하), 감소 시 심근 위축 또는 저혈량.",
    functional_groups: ['LV_size'],
  },
  LVd: {
    keywordID: 'LVd',
    keywordName: 'LV-d(LVIDd)',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 크기 감소. 저혈량, 탈수, 비후성 심근병증 시사', '정상', '이심성 비대 시사. MR, DCM, 용적 과부하 등 평가. LVIDDN으로 정규화 평가 권장'],
    anatomic_groups: ['LV'],
    testinfo: "이완기 좌심실 내경(LV Internal Diameter diastole). 체중 기반 정상 참고치와 비교. LVIDDN(정규화 지수)과 함께 평가. 증가는 LV 용적 과부하(MR, DCM 등) 시사.",
    functional_groups: ['LV_size'],
  },
  LVWd: {
    keywordID: 'LVWd',
    keywordName: 'LVW-d(LVPWd)',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 후벽 두께 감소. 심근 위축 또는 저혈량 가능성', '정상', '동심성 비대 시사. 고혈압, 압력 과부하 등 평가'],
    anatomic_groups: ['LV'],
    testinfo: "이완기 좌심실 후벽 두께(LV Posterior Wall diastole). 체중 기반 정상 참고치와 비교. IVS-d와 함께 심근 비대 또는 위축 평가에 활용.",
    functional_groups: ['LV_size'],
  },
  VSs: {
    keywordID: 'VSs',
    keywordName: 'IVS-s',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['IVS 수축기 두께화 감소. 수축 기능 저하 시사', '정상', '정상 범위 내 수축기 두께화 또는 과역동성'],
    anatomic_groups: ['LV'],
    testinfo: "수축기 심실중격 두께(IVS systole). 체중 기반 정상 참고치와 비교. FS 계산 및 수축 기능 평가에 활용.",
    functional_groups: ['LV_size'],
  },
  LVs: {
    keywordID: 'LVs',
    keywordName: 'LV-s(LVIDs)',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 수축기 내경 감소. 과역동성 또는 용적 감소', '정상', '수축기 내경 증가. 수축 기능 저하(DCM 등) 시사. FS 감소 동반 여부 확인'],
    anatomic_groups: ['LV'],
    testinfo: "수축기 좌심실 내경(LV Internal Diameter systole). FS 계산의 핵심 변수(FS = (LVd-LVs)/LVd × 100). 증가 시 LV 수축 기능 저하 시사.",
    functional_groups: ['LV_size', 'LV_systolic'],
  },
  LVWs: {
    keywordID: 'LVWs',
    keywordName: 'LVW-s(LVPWs)',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 후벽 수축기 두께화 감소. 수축 기능 저하 가능성', '정상', '정상 범위 내 또는 과역동성'],
    anatomic_groups: ['LV'],
    testinfo: "수축기 좌심실 후벽 두께(LV Posterior Wall systole). 체중 기반 정상 참고치와 비교. LVW 두께화율(thickening fraction) 평가에 활용.",
    functional_groups: ['LV_size'],
  },
  LVIDDN: {
    keywordID: 'LVIDDN',
    keywordName: 'LVIDDN',
    species: ['canine'],
    sections: ['Objective_Evaluation', 'MINE_SCORE'],
    groups: ['Mmode', 'MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    testref: '0~1.7',
    formula: 'LVIDDN',
    dependencies: ['LVd', 'BW_kg'],
    thresholds: [1.7],
    optResult: ['normal', 'increase'],
    optComment: ['normal', 'increased LV preload (ACVIM B2?)'],
    anatomic_groups: ['LV'],
    functional_groups: ['LV_size'],
    testinfo: "정규화된 좌심실 내경 지수(Normalized LVIDd). 체중 보정값. 1.7 이상일 경우 심비대(B2 단계) 가능성 시사.",
  },
  AO: {
    keywordID: 'AO',
    keywordName: 'AO',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['AO 직경 감소. 저혈량 또는 심박출량 감소 가능성', '정상', 'AO 확장. SAS 협착 후 확장 또는 전신 고혈압 가능성'],
    anatomic_groups: ['AO'],
    testinfo: "대동맥 직경(mm). 체중 기반 정상 참고치와 비교. LA/AO ratio 계산에 사용. SAS 협착 후 대동맥 확장, 전신 고혈압 등 평가.",
    functional_groups: ['LA_size'],
  },
  LA: {
    keywordID: 'LA',
    keywordName: 'LA',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'mmode_range',
    unit: 'mm',
    refTable: 'mmoderef_dog',
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LA 직경 감소. 저혈량 또는 폐쇄성 질환 가능성', '정상', 'LA 확장. MR, LV 이완 기능 저하, 심부전 시사. LAAOratio 확인 필요'],
    anatomic_groups: ['LA'],
    testinfo: "좌심방 직경(mm). 체중 기반 정상 참고치와 비교. LA/AO ratio 계산에 사용. MMVD에서 LA 크기 증가는 중요한 병기 결정 인자.",
    functional_groups: ['LA_size'],
  },
  LAAOratio: {
    keywordID: 'LAAOratio',
    keywordName: 'LA:AO ratio',
    species: ['canine'],
    sections: ['Objective_Evaluation', 'MINE_SCORE'],
    groups: ['Mmode', 'MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    testref: '1.0~1.6',
    formula: 'LAAOratio',
    dependencies: ['LA', 'AO'],
    thresholds: [0.8, 1.3, 1.6, 2.0],
    optResult: ['decrease', 'normal', 'mild increase', 'moderate increase', 'marked increase'],
    optComment: ['', 'normal', 'LA vol. mild increase', 'LA vol. moderate increase (ACVIM ≥B2)', 'LA vol. severe increase'],
    anatomic_groups: ['LA'],
    functional_groups: ['LA_size'],
    testinfo: "좌심방 내경과 대동맥 내경의 비율(LA:AO Ratio). 1.6 이상일 경우 심비대(B2 단계) 시사.",
  },
  LVFS: {
    keywordID: 'LVFS',
    keywordName: 'FS',
    species: ['canine'],
    sections: ['Objective_Evaluation'],
    groups: ['Mmode'],
    testType: 'calculated',
    unit: '%',
    testref: '25~45',
    formula: 'LVFS',
    dependencies: ['LVd', 'LVs'],
    thresholds: [25, 45],
    optResult: ['decrease', 'normal', 'increase'],
    optComment: ['LV 수축 기능 저하(DCM 등). 원인 평가 및 치료 계획 필요', '정상 LV 수축 기능', '과역동성 LV 기능. 탈수, 빈혈, 흥분, 교감신경 항진 등 평가'],
    anatomic_groups: ['LV'],
    testinfo: "좌심실 단축 분율(Fractional Shortening). FS = (LVd - LVs) / LVd × 100(%). 개의 정상 25~45%. 25% 미만: 수축 기능 저하, 45% 초과: 과역동성. M-mode로 측정.",
    functional_groups: ['LV_systolic'],
  },

  // ---- MINE Score (개 전용) ----
  MINE_LAAO: {
    keywordID: 'MINE_LAAO',
    keywordName: 'MINE_SCORE LA/AO ratio',
    species: ['canine'],
    sections: ['MINE_SCORE'],
    groups: ['MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    testref: '0.8~1.3',
    formula: 'MINE_LAAO',
    dependencies: ['LAAOratio'],
    thresholds: [1.3, 1.6],
    optResult: ['Grade 0', 'Grade 1', 'Grade 2'],
    optComment: ['', '', ''],
    anatomic_groups: ['LA'],
    testinfo: "",
    functional_groups: ['MMVD_staging'],
  },
  MINE_LVIDDN: {
    keywordID: 'MINE_LVIDDN',
    keywordName: 'MINE_SCORE LVIDDN',
    species: ['canine'],
    sections: ['MINE_SCORE'],
    groups: ['MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    testref: '0~1.7',
    formula: 'MINE_LVIDDN',
    dependencies: ['LVIDDN'],
    thresholds: [1.7],
    optResult: ['Grade 0', 'Grade 1'],
    optComment: ['', ''],
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['MMVD_staging'],
  },
  MINE_FS: {
    keywordID: 'MINE_FS',
    keywordName: 'MINE_SCORE FS',
    species: ['canine'],
    sections: ['MINE_SCORE'],
    groups: ['MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    testref: '25~45',
    formula: 'MINE_FS',
    dependencies: ['LVFS'],
    thresholds: [30],
    optResult: ['Grade 1', 'Grade 0'],
    optComment: ['', ''],
    anatomic_groups: ['LV'],
    testinfo: "",
    functional_groups: ['MMVD_staging'],
  },
  MINE_Ewave: {
    keywordID: 'MINE_Ewave',
    keywordName: 'MINE_SCORE E wave',
    species: ['canine'],
    sections: ['MINE_SCORE'],
    groups: ['MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    testref: '0~1.2',
    formula: 'MINE_Ewave',
    dependencies: ['MV_Ewave'],
    thresholds: [1.2],
    optResult: ['Grade 0', 'Grade 1'],
    optComment: ['', ''],
    anatomic_groups: ['MV'],
    testinfo: "",
    functional_groups: ['MMVD_staging'],
  },
  MINE_score: {
    keywordID: 'MINE_score',
    keywordName: 'MINE_SCORE Total',
    species: ['canine'],
    sections: ['MINE_SCORE'],
    groups: ['MINE_SCORE'],
    testType: 'calculated',
    unit: '',
    formula: 'MINE_score',
    dependencies: ['MINE_LAAO', 'MINE_LVIDDN', 'MINE_FS', 'MINE_Ewave'],
    thresholds: [1, 3],
    optResult: ['Low risk', 'Moderate risk', 'High risk'],
    optComment: ['', '', ''],
    anatomic_groups: ['General'],
    testinfo: "",
    functional_groups: ['MMVD_staging'],
  },

  // ---- ACVIM Staging (개 전용) ----
  ACVIM: {
    keywordID: 'ACVIM',
    keywordName: 'ACVIM Stage',
    species: ['canine'],
    sections: ['General_Review'],
    groups: ['ACVIM'],
    testType: 'select',
    options: ['', 'A', 'B1', 'B2', 'C', 'D'],
    optResult: ['', 'Stage A', 'Stage B1', 'Stage B2', 'Stage C', 'Stage D'],
    optComment: [
      '',
      '심장 질환 소인은 있으나 현재 구조적 이상 없음. 정기 검진 권장',
      '구조적 이상 존재하나 심비대 없음. 6~12개월 간격 심초음파 권장',
      '구조적 이상 + 심비대(LA/AO ≥1.6, LVIDDN ≥1.7). 약물 치료 시작 고려',
      '현재 또는 과거 CHF 증상. 적극적 치료 필요',
      '난치성 CHF. 표준 치료 반응 불량. 전문 치료 필요',
    ],
    anatomic_groups: ['General'],
    testinfo: "ACVIM(American College of Veterinary Internal Medicine) 심장 질환 병기. A~D로 분류. B2 기준: LA/AO ≥1.6 또는 LVIDDN ≥1.7(심비대 존재). B2부터 Pimobendan 치료 고려.",
    functional_groups: ['MMVD_staging'],
  },
  
  // Last_comment: {
  //   keywordID: 'Last_comment',
  //   keywordName: 'General Review',
  //   species: ['canine'],
  //   sections: ['General_Review'],
  //   groups: ['Test Review'],
  //   testType: 'textcomment',
  //   anatomic_groups: ['General'],
  //   testinfo: "심장 초음파 전체 소견에 대한 종합 평가 및 임상 의견 기록란.",
  //   functional_groups: [],
  // },
};
