import {
  Activity,
  BarChart4Icon,
  BuildingIcon,
  HeartPulseIcon,
  HomeIcon,
  ListChecksIcon,
  NotebookPen,
  PawPrintIcon,
  SyringeIcon,
  Folder,
} from 'lucide-react'

export const HOS_SIDEBAR_MENUS = [
  {
    name: '병원 홈',
    path: '',
    isReady: true,
    isVetOnly: false,
    icon: <HomeIcon />,
  },
  {
    name: '환자목록',
    path: 'patients',
    isReady: true,
    isVetOnly: false,
    icon: <PawPrintIcon />,
  },
  {
    name: '입원차트',
    path: 'icu',
    isReady: true,
    isVetOnly: false,
    icon: <SyringeIcon />,
  },
  {
    name: '모니터링',
    path: 'monitoring',
    isReady: true,
    isVetOnly: false,
    icon: <Activity />,
  },
  {
    name: '심초차트',
    path: 'echocardio',
    isReady: true,
    isVetOnly: true,
    icon: <HeartPulseIcon />,
  },
  {
    name: '진료노트',
    path: 'notes',
    isReady: true,
    isVetOnly: false,
    icon: <NotebookPen />,
  },
  {
    name: '컬렉션',
    path: 'collections',
    isReady: true,
    isVetOnly: false,
    icon: <Folder />,
  },
  {
    name: '벳툴',
    path: 'super',
    isReady: true,
    isVetOnly: true,
    icon: <BuildingIcon />,
  },
] as const
