import {
  Activity,
  BarChart4,
  Building,
  HeartPulse,
  Home,
  ListChecks,
  NotebookPen,
  PawPrint,
  Syringe,
  Folder,
} from 'lucide-react'

export const HOS_SIDEBAR_MENUS = [
  {
    name: '병원 홈',
    path: '',
    isReady: true,
    isVetOnly: false,
    icon: <Home />,
  },
  {
    name: '환자목록',
    path: 'patients',
    isReady: true,
    isVetOnly: false,
    icon: <PawPrint />,
  },
  {
    name: '입원차트',
    path: 'icu',
    isReady: true,
    isVetOnly: false,
    icon: <Syringe />,
  },
  {
    name: '모니터링',
    path: 'monitoring',
    isReady: true,
    isVetOnly: false,
    icon: <Activity />,
  },
  {
    name: '심초차트',
    path: 'echocardio',
    isReady: true,
    isVetOnly: true,
    icon: <HeartPulse />,
  },
  {
    name: '진료노트',
    path: 'notes',
    isReady: true,
    isVetOnly: false,
    icon: <NotebookPen />,
  },
  {
    name: '컬렉션',
    path: 'collections',
    isReady: true,
    isVetOnly: false,
    icon: <Folder />,
  },
  {
    name: '벳툴',
    path: 'super',
    isReady: true,
    isVetOnly: true,
    icon: <Building />,
  },
] as const
